### ISSUE TITLE
[Bug]: 七牛云 [error]:Upload failed

### ISSUE THREAD

**Issue by emmilia-hub** [Molunerfinn/PicGo#1003]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

配置一切无误，秘钥正确无空格。
![image](https://user-images.githubusercontent.com/75068978/199669600-ed40161b-b4a8-4fe3-ba0f-18eaee766434.png)
上传图片时报错：Upload failed at .....
请问是否是由于北美区域的问题？我的域名没备案，所以只能使用海外存储。

### 相关日志 | Logs

------Error Stack Begin------
Error: Upload failed
    at Object.Ve [as handle] (D:\picGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:27247)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\picGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17170)
    at async $e.start (D:\picGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15941)
    at async Tt.upload (D:\picGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70737)
    at async Object.upload (D:\picGo\resources\app.asar\background.js:2:653600)
    at async jn (D:\picGo\resources\app.asar\background.js:2:656249)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
不确定是什么原因，上传失败的时候，弹窗应该有写一些信息才对。这里应该是请求了七牛，但是接口没有返回 `key`，所以判断成了上传失败。
<img width="750" alt="image" src="https://user-images.githubusercontent.com/12621342/199671198-c3cd2a47-965c-42c5-8a10-71d383627405.png">

我这边七牛是正常的，无法复现问题

**Comment by Molunerfinn** [comment]
下个版本会补充一些错误信息到日志里

**Comment by emmilia-hub** [comment]
> 下个版本会补充一些错误信息到日志里

大佬，我尝试重新生成秘钥并使用，现在没问题了。应该是他新建用户的时候创建的秘钥有问题。

**Comment by Molunerfinn** [comment]
OK
