### ISSUE TITLE
[Bug]: 上传失败

### ISSUE THREAD

**Issue by 8ty** [Molunerfinn/PicGo#1005]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1beta8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

Unexpected token o in JSON at position 1SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)

一直显示这个，图床配置时正确的

### 相关日志 | Logs

Unexpected token o in JSON at position 1SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)

**Comment by Molunerfinn** [comment]
你什么图床啊？麻烦给详细点的信息 不然也没法帮你看

**Comment by 8ty** [comment]
> 你什么图床啊？麻烦给详细点的信息 不然也没法帮你看


不好意思不好意思 疏忽了

好像几乎是大部分的图床都显示这个
比如

![](https://i.postimg.cc/GhFmm4dv/image.png)

这几个都是，还有github图床也是

最近几次的日志
````````
------Error Stack Begin------
Error: image not found in clipboard
    at Tt.upload (D:\program\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70863)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.upload (D:\program\picgo\resources\app.asar\background.js:2:653600)
    at async D:\program\picgo\resources\app.asar\background.js:2:655433
    at async Bn (D:\program\picgo\resources\app.asar\background.js:2:655265)
-------Error Stack End------- 
2022-11-07 18:42:43 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at Tt.upload (D:\program\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70863)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.upload (D:\program\picgo\resources\app.asar\background.js:2:653600)
    at async D:\program\picgo\resources\app.asar\background.js:2:655433
    at async Bn (D:\program\picgo\resources\app.asar\background.js:2:655265)
-------Error Stack End------- 
2022-11-07 18:42:59 [PicGo INFO] Before transform 
2022-11-07 18:42:59 [PicGo INFO] beforeTransformPlugins: vika running 
2022-11-07 18:42:59 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-07 18:42:59 [PicGo INFO] Before upload 
2022-11-07 18:42:59 [PicGo INFO] beforeUploadPlugins: vika running 
2022-11-07 18:42:59 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-07 18:42:59 [PicGo INFO] Uploading... Current uploader is [superbed] 
2022-11-07 18:42:59 [PicGo INFO] afterUploadPlugins: vika running 
2022-11-07 18:42:59 [PicGo SUCCESS] 
 
2022-11-07 18:46:50 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-11-07 18:49:52 [PicGo INFO] Before transform 
2022-11-07 18:49:52 [PicGo INFO] beforeTransformPlugins: vika running 
2022-11-07 18:49:52 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-07 18:49:52 [PicGo INFO] Before upload 
2022-11-07 18:49:52 [PicGo INFO] beforeUploadPlugins: vika running 
2022-11-07 18:49:52 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-07 18:49:52 [PicGo INFO] Uploading... Current uploader is [superbed] 
2022-11-07 18:49:52 [PicGo INFO] afterUploadPlugins: vika running 
2022-11-07 18:49:52 [PicGo SUCCESS] 
 
2022-11-07 19:50:34 [PicGo INFO] Before transform 
2022-11-07 19:50:34 [PicGo INFO] beforeTransformPlugins: vika running 
2022-11-07 19:50:34 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-07 19:50:34 [PicGo INFO] Before upload 
2022-11-07 19:50:34 [PicGo INFO] beforeUploadPlugins: vika running 
2022-11-07 19:50:34 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-07 19:50:34 [PicGo INFO] Uploading... Current uploader is [superbed] 
2022-11-07 19:50:34 [PicGo INFO] afterUploadPlugins: vika running 
2022-11-07 19:50:34 [PicGo SUCCESS] 
 ```````````````

**Comment by Molunerfinn** [comment]
插件支持的图床请找插件相关方咨询。

另外上面的报错是说你剪贴板里没有图片，自然无法上传。剩下的我看你上传不是都成功了么
![image](https://user-images.githubusercontent.com/12621342/200309956-6fbaae9b-21ff-48e5-b018-af9b96a944fb.png)

**Comment by 8ty** [comment]
> 插件支持的图床请找插件相关方咨询。
> 
> 另外上面的报错是说你剪贴板里没有图片，自然无法上传。剩下的我看你上传不是都成功了么 ![image](https://user-images.githubusercontent.com/12621342/200309956-6fbaae9b-21ff-48e5-b018-af9b96a944fb.png)

那个剪贴板的我知道是错误（事实上，我的剪贴板里是有图片的，另外，他只是显示success，但是并没有链接）

**Comment by Molunerfinn** [comment]
我这边是正常的
<img width="590" alt="image" src="https://user-images.githubusercontent.com/12621342/200311794-f7449681-45c8-4b79-a6e2-851f7b99649c.png">

我看你有个afterUploadPlugins vika，我建议你删掉所有的插件再重启picgo试试，应该是插件的问题不是本体的问题。
![image](https://user-images.githubusercontent.com/12621342/200311936-5f5aa8a5-8f74-4c17-8ac7-f97f4de32790.png)
