### ISSUE TITLE
[Bug]: 不适配 MacOS 13 Ventura 

### ISSUE THREAD

**Issue by Jolsonz** [Molunerfinn/PicGo#1006]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0 release & v2.3.1-beta.8 

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

MAC系统升级到 MacOS 13 Ventura 后，无法上传图片。
picgo-core与picgo均不可。报错见日志。

根据日志找到下图文件猜测是未适配MacOS 13
<img width="761" alt="image" src="https://user-images.githubusercontent.com/28992832/200469982-b9aa830e-15d9-43a5-8313-028d15dff4ed.png">
系统版本
<img width="280" alt="image" src="https://user-images.githubusercontent.com/28992832/200470488-762b3c94-64df-4780-9d9c-afc63d2ba7ab.png">

### 相关日志 | Logs

[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: beforeUploadPlugins: rename-file running
[PicGo INFO]: Uploading... Current uploader is [githubPlus]
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[PicGo WARN]: failed
[PicGo ERROR]: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/xx/.picgo/node_modules/macos-release/index.js:27:26)
    at osName (/Users/xx/.picgo/node_modules/os-name/index.js:21:18)
    at getUserAgent (/Users/xx/.picgo/node_modules/universal-user-agent/dist-node/index.js:11:53)
    at parseOptions (/Users/xx/.picgo/node_modules/@octokit/rest/lib/parse-client-options.js:80:57)
    at new Octokit (/Users/xx/.picgo/node_modules/@octokit/rest/lib/constructor.js:23:31)
    at new DeprecatedOctokit (/Users/xx/.picgo/node_modules/@octokit/rest/index.js:29:10)
    at new Octo (/Users/xx/.picgo/node_modules/picgo-plugin-github-plus/dist/lib/octokit.js:30:24)
    at Object.getIns (/Users/xx/.picgo/node_modules/picgo-plugin-github-plus/dist/lib/octokit.js:159:11)
    at initOcto (/Users/xx/.picgo/node_modules/picgo-plugin-github-plus/dist/index.js:11:27)
    at Object.handle (/Users/xx/.picgo/node_modules/picgo-plugin-github-plus/dist/index.js:111:21)

**Comment by Molunerfinn** [comment]
堆栈信息是picgo-plugin-github-plus报出来的，不是picgo本体的错误，这个插件引用的包不支持macOS13，请去插件仓库提问。

**Comment by jzhang-gd** [comment]
```bash
picgo uninstall github-plus   

picgo install github-plus
```
更新插件就行了
