### ISSUE TITLE
[Bug]: Mac命令行上传失败

### ISSUE THREAD

**Issue by wisinfun** [Molunerfinn/PicGo#1009]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

/Applications/PicGo.app/Contents/MacOS/PicGo upload /Users/ym/Downloads/1.png

### 相关日志 | Logs

/Applications/PicGo.app/Contents/MacOS/PicGo upload /Users/ym/Downloads/1.png
on ready
startup true
[PicGo INFO]: [PicGo Server] is listening at 36677
[PicGo INFO]: cli -> uploading files from cli /Users/ym/Downloads/1.png
(node:8577) electron: NSVisualEffectMaterialUltraDark has been deprecated and removed as of macOS 10.15.
(Use `PicGo --trace-warnings ...` to show where the warning was created)
(node:8577) electron: NSVisualEffectMaterialUltraDark has been deprecated and removed as of macOS 10.15.
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: beforeUploadPlugins: renameFn running
[PicGo INFO]: Uploading... Current uploader is [gitlab-files-uploader]
[PicGo WARN]: failed
[PicGo ERROR]: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.handle (/Users/ym/Library/Application Support/picgo/node_modules/picgo-plugin-gitlab-files/dist/index.js:146:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17198)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
[PicGo ERROR]: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.handle (/Users/ym/Library/Application Support/picgo/node_modules/picgo-plugin-gitlab-files/dist/index.js:146:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17198)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
(node:8613) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
(Use `PicGo Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
(node:8614) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
(Use `PicGo Helper (Renderer) --trace-deprecation ...` to show where the warning was created)

**Comment by Molunerfinn** [comment]
插件上传问题 请去相关插件仓库提问
