### ISSUE TITLE
[Bug]: 最新版本，获取网络图片 TypeError: ctx.Request.request(...).on is not a function

### ISSUE THREAD

**Issue by systemctls** [Molunerfinn/PicGo#1020]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

https://img-blog.csdnimg.cn/20191218115416913.png

打开客户端，选择URL上传，会提示如下报错：参见相关日志。

就版本貌似没这个问题，今天刚升级发现的。

### 相关日志 | Logs

2022-11-20 17:36:52 [PicGo INFO] [PicGo Server] get the request {"list":["https://img-blog.csdnimg.cn/20191218115416913.png"]} 
2022-11-20 17:36:52 [PicGo INFO] [PicGo Server] upload files in list 
2022-11-20 17:36:52 [PicGo INFO] Before transform 
2022-11-20 17:36:52 [PicGo INFO] Transforming... Current transformer is [compress] 
2022-11-20 17:36:52 [PicGo INFO] 压缩:image2webp 
2022-11-20 17:36:52 [PicGo INFO] 图片地址:https://img-blog.csdnimg.cn/20191218115416913.png 
2022-11-20 17:36:52 [PicGo INFO] 图片信息:{"fileName":"20191218115416913.png","extname":".png"} 
2022-11-20 17:36:52 [PicGo INFO] Image2WebP 压缩开始 
2022-11-20 17:36:52 [PicGo INFO] 获取网络图片 
2022-11-20 17:36:52 [PicGo WARN] failed 
2022-11-20 17:36:52 [PicGo ERROR] 
------Error Stack Begin------
TypeError: ctx.Request.request(...).on is not a function
    at C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\utils.js:70:111
    at step (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\utils.js:52:23)
    at Object.next (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\utils.js:33:53)
    at C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\utils.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\utils.js:23:12)
    at fetchImage (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\utils.js:67:12)
    at Object.getImageBuffer (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\utils.js:85:16)
    at Object.Image2WebPCompress (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\compress\image2webp.js:24:20)
    at C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\index.js:27:41
-------Error Stack End------- 
2022-11-20 17:36:52 [PicGo ERROR]

**Comment by Molunerfinn** [comment]
请联系compress插件适配2.3.1新版picgo
