### ISSUE TITLE
[Bug]: 七牛云返回的链接没有http://，导致相册内图片显示不出来

### ISSUE THREAD

**Issue by hwnwdtx** [Molunerfinn/PicGo#1030]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

上传图片必现

### 相关日志 | Logs

rlwsz1fyl.bkt.clouddn.com/202211291251510.png
Failed to read /rlwsz1fyl.bkt.clouddn.com/202211291251510.png on picgo protocol Error: ENOENT, rlwsz1fyl.bkt.clouddn.com\202211291251510.png not found in D:\PicGo\resources\app.asar
    at createError (node:electron/js2c/asar_bundle:5:1243)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:5:7694)
    at e.readFile (node:electron/js2c/asar_bundle:5:8826)
    at Function.<anonymous> (D:\PicGo\resources\app.asar\background.js:2:599310) {
  code: 'ENOENT',
  errno: -2
}
Failed to read /rlwsz1fyl.bkt.clouddn.com/202211291251510.png on picgo protocol Error: ENOENT, rlwsz1fyl.bkt.clouddn.com\202211291251510.png not found in D:\PicGo\resources\app.asar
    at createError (node:electron/js2c/asar_bundle:5:1243)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:5:7694)
    at e.readFile (node:electron/js2c/asar_bundle:5:8826)
    at Function.<anonymous> (D:\PicGo\resources\app.asar\background.js:2:599310) {
  code: 'ENOENT',
  errno: -2
}
Failed to read /rlwsz1fyl.bkt.clouddn.com/202211291251510.png on picgo protocol Error: ENOENT, rlwsz1fyl.bkt.clouddn.com\202211291251510.png not found in D:\PicGo\resources\app.asar
    at createError (node:electron/js2c/asar_bundle:5:1243)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:5:7694)
    at e.readFile (node:electron/js2c/asar_bundle:5:8826)
    at Function.<anonymous> (D:\PicGo\resources\app.asar\background.js:2:599310) {
  code: 'ENOENT',
  errno: -2
}

**Comment by hwnwdtx** [comment]
已解决，是配置问题
