### ISSUE TITLE
[Bug]: 请问这个报错的如何处理，已尽力查看文档和搜索

### ISSUE THREAD

**Issue by JasonX2140** [Molunerfinn/PicGo#1035]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

V2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

过程：
1. 下载软件
2. 配置好阿里云后，上传文件图片可用，剪切板上传不可用
3. 卸载软件，重新下载安装
4. 配置好阿里云后，上传文件图片不可用，剪贴板上传不可用

### 相关日志 | Logs

------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17198)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
你提供的日志不够完整，看不出问题。

另外，第2步的时候，剪贴板上传不可用的日志是什么呢？第4步的应该是配置出了问题，但是第二步的情况应该是配置正确，但是剪贴板上传失败我不知道是什么报错。

**Comment by Molunerfinn** [comment]
picgo卸不卸载，其实没有影响。看了一下报错位置，应该依然是配置问题导致上传失败，检查一下你的配置，可以直接打开配置文件逐行查看。如果发现配置错误，要么直接在picgo的界面里配置，要么关闭picgo之后再手动修改配置文件。

![image](https://user-images.githubusercontent.com/12621342/205529724-f258716c-6f60-4750-9a09-afec11dc588f.png)

**Comment by Molunerfinn** [comment]
第2种剪贴板上传不可用的情况请再提供详细报错信息。

**Comment by Molunerfinn** [comment]
我还原了堆栈，发现你的报错使用的上传图床是sm.ms而不是aliyun

![image](https://user-images.githubusercontent.com/12621342/205530997-31056384-f101-420b-b761-c4935f2910fb.png)

报错日志里应该会有很详细的日志，提示你当前使用的上传图床是什么

![image](https://user-images.githubusercontent.com/12621342/205531056-687ed4ff-9f08-4bbb-a8fa-68494bc5e54d.png)

请先将阿里云指定为默认图床再试试吧。PicGo的图床上传都是经过测试的，麻烦出现上传问题的时候先找找自己的问题。

**Comment by Molunerfinn** [comment]
我复现你的报错，就是使用了smms的情况才会出现的：

```
2022-12-05 09:45:06 [PicGo INFO] Before transform 
2022-12-05 09:45:06 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-05 09:45:06 [PicGo INFO] Before upload 
2022-12-05 09:45:06 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-05 09:45:06 [PicGo INFO] Uploading... Current uploader is [smms] 
2022-12-05 09:45:27 [PicGo ERROR] {
  "method": "POST",
  "url": "https://sm.ms/api/v2/upload",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 8.7.198.46:443",
  "stack": "Error: connect ETIMEDOUT 8.7.198.46:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-12-05 09:45:27 [PicGo WARN] failed 
2022-12-05 09:45:27 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async Object.uploadWithBuildInClipboard (D:\Program Files\PicGo\resources\app.asar\background.js:2:653409)
    at async D:\Program Files\PicGo\resources\app.asar\background.js:2:655367
    at async Bn (D:\Program Files\PicGo\resources\app.asar\background.js:2:655267)
-------Error Stack End------- 
2022-12-05 09:45:27 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async Object.uploadWithBuildInClipboard (D:\Program Files\PicGo\resources\app.asar\background.js:2:653409)
    at async D:\Program Files\PicGo\resources\app.asar\background.js:2:655367
    at async Bn (D:\Program Files\PicGo\resources\app.asar\background.js:2:655267)
-------Error Stack End------- 
```
