### ISSUE TITLE
[Bug]: ubuntu下使用typora调用picgo上传失败

### ISSUE THREAD

**Issue by yangzexia** [Molunerfinn/PicGo#1037]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

typora配置如下：
![image](https://user-images.githubusercontent.com/37099022/206111519-61e470a3-cd23-4f57-ae78-8786d08f85e3.png)
可以在picgo中手动上传图片，在typora中设置上传服务为picgo(app)不能成功上传，显示的日志如下

### 相关日志 | Logs

2022-12-06 17:27:56 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-07 14:20:58 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-07 14:22:24 [PicGo INFO] [PicGo Server] get the request {"list":["/home/yzx/.config/Typora/typora-user-images/image-20221207142223949.png"]} 
2022-12-07 14:22:24 [PicGo INFO] [PicGo Server] upload files in list 
2022-12-07 14:22:26 [PicGo INFO] Before transform 
2022-12-07 14:22:26 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-07 14:22:26 [PicGo WARN] failed 
2022-12-07 14:22:26 [PicGo ERROR] 
------Error Stack Begin------
Error: read file /home/yzx/.config/Typora/typora-user-images/image-20221207142223949.png error
    at /snap/picgo/x1/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:38189
    at async Promise.all (index 0)
    at async Object.handle (/snap/picgo/x1/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:37138)
    at async $e.doTransform (/snap/picgo/x1/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:16679)
    at async $e.start (/snap/picgo/x1/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15916)
    at async Tt.upload (/snap/picgo/x1/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/snap/picgo/x1/resources/app.asar/background.js:2:653584)
    at async jn (/snap/picgo/x1/resources/app.asar/background.js:2:656251)
    at async /snap/picgo/x1/resources/app.asar/background.js:2:657340

**Comment by Molunerfinn** [comment]
你先确认一下这个文件存在么 `/home/yzx/.config/Typora/typora-user-images/image-20221207142223949.png`

**Comment by Molunerfinn** [comment]
如果你直接通过PicGo上传是正常的，那么这个问题你应该去问typora

**Comment by Molunerfinn** [comment]
参考
https://github.com/Molunerfinn/PicGo/issues/997
