### ISSUE TITLE
[Bug]: 更新2.3.1后，无法上传到七牛云

### ISSUE THREAD

**Issue by iamfeiyu** [Molunerfinn/PicGo#1044]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

刚更新完，配置七牛云相关参数后，截图后通过快捷键上传粘贴板图片，失败，拖拽图片到上传区域，失败。

相关配置如下：
![image](https://user-images.githubusercontent.com/25132486/208385473-27909a31-d796-4ce0-8f86-7875b82a13b9.png)

![image](https://user-images.githubusercontent.com/25132486/208385005-06eb21af-0936-40dc-876b-609b1f7bfe6d.png)

![image](https://user-images.githubusercontent.com/25132486/208384928-bdb0556d-9619-4021-97b0-303d802e1b0b.png)

### 相关日志 | Logs

2022-10-06 15:00:06 [PicGo INFO] [PicGo Server] is listening at 36677
2022-10-06 15:00:06 [PicGo INFO] Before transform
2022-10-06 15:00:06 [PicGo INFO] Transforming...
2022-10-06 15:00:06 [PicGo WARN] failed
2022-10-06 15:00:06 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:20:28
    at async Promise.all (index 0)
    at async Object.handle (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:11:5)
    at async Lifecycle.doTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:51:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:19:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2022-12-15 00:50:21 [PicGo INFO] [PicGo Server] is listening at 36677
2022-12-15 00:58:37 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-15 01:25:30 [PicGo INFO] Before transform 
2022-12-15 01:25:30 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-15 01:25:30 [PicGo INFO] Before upload 
2022-12-15 01:25:30 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-15 01:25:30 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-12-15 01:25:31 [PicGo WARN] failed 
2022-12-15 01:25:31 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEyNTMwLnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395733 seconds ago"
    }
  }
} 
2022-12-15 01:25:31 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEyNTMwLnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395733 seconds ago"
    }
  }
} 
2022-12-15 01:29:31 [PicGo INFO] Before transform 
2022-12-15 01:29:31 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-15 01:29:31 [PicGo INFO] Before upload 
2022-12-15 01:29:31 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-15 01:29:31 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-12-15 01:29:32 [PicGo WARN] failed 
2022-12-15 01:29:32 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEyOTMxLnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395733 seconds ago"
    }
  }
} 
2022-12-15 01:29:32 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEyOTMxLnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395733 seconds ago"
    }
  }
} 
2022-12-15 01:30:10 [PicGo INFO] Before transform 
2022-12-15 01:30:10 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-15 01:30:10 [PicGo INFO] Before upload 
2022-12-15 01:30:10 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-15 01:30:10 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-12-15 01:30:10 [PicGo WARN] failed 
2022-12-15 01:30:10 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEzMDA5LnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:30:10 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEzMDA5LnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:37:02 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71396)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:655435
    at async EventEmitter.Bn (C:\Program Files\PicGo\resources\app.asar\background.js:2:655267)
-------Error Stack End------- 
2022-12-15 01:38:13 [PicGo INFO] Before transform 
2022-12-15 01:38:13 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-15 01:38:13 [PicGo INFO] Before upload 
2022-12-15 01:38:13 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-15 01:38:13 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-12-15 01:38:13 [PicGo WARN] failed 
2022-12-15 01:38:13 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEzODYzMC5wbmc=",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:38:13 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDEzODYzMC5wbmc=",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:46:41 [PicGo INFO] Before transform 
2022-12-15 01:46:41 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-15 01:46:41 [PicGo INFO] Before upload 
2022-12-15 01:46:41 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-15 01:46:41 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-12-15 01:46:41 [PicGo WARN] failed 
2022-12-15 01:46:41 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDE0NjAyOS5wbmc=",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:46:41 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDE0NjAyOS5wbmc=",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:46:55 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-15 01:47:15 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-15 01:47:22 [PicGo INFO] [PicGo Server] shutdown 
2022-12-15 01:47:27 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-15 01:47:40 [PicGo INFO] Before transform 
2022-12-15 01:47:40 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-15 01:47:40 [PicGo INFO] Before upload 
2022-12-15 01:47:40 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-15 01:47:40 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-12-15 01:47:41 [PicGo WARN] failed 
2022-12-15 01:47:41 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDE0NzQ5NS5wbmc=",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:47:41 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nLzIwMjIxMjE1MDE0NzQ5NS5wbmc=",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:48:03 [PicGo INFO] Before transform 
2022-12-15 01:48:03 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-15 01:48:03 [PicGo INFO] Before upload 
2022-12-15 01:48:03 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-15 01:48:03 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-12-15 01:48:03 [PicGo WARN] failed 
2022-12-15 01:48:03 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nL0FybWEz6ZSu5L2N5pON5L2c5Zu-LnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
} 
2022-12-15 01:48:03 [PicGo ERROR] {
  "method": "POST",
  "url": "http://upload-z1.qiniup.com/putb64/-1/key/aW1nL0FybWEz6ZSu5L2N5pON5L2c5Zu-LnBuZw==",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "error": "token expired 395732 seconds ago"
    }
  }
}

**Comment by iamfeiyu** [comment]
补充：没有安装任何插件

**Comment by Molunerfinn** [comment]
日志里不是给得很明显了么，这个是你配置问题啊，401是身份鉴权不过，error里告诉了你为啥鉴权不过的原因啊，token过期了。

**Comment by Molunerfinn** [comment]
如果你提供的key你确认是正确的，请联系七牛的人看看这个报错对应的error要怎么解决。

**Comment by Molunerfinn** [comment]
如果你提供的key你确认是正确的，请联系七牛的人看看这个报错对应的error要怎么解决。

**Comment by iamfeiyu** [comment]
更新为新的密钥后，结果依旧，无法上传。在配置时，前一个密钥是正常使用状态，并没有过期。

**Comment by iamfeiyu** [comment]
我已向七牛云提交工单，正在等待反馈中

**Comment by JiapengLi** [comment]
七牛云报这个错误应该是系统时间没有对准。核对密钥正确的情况下，请尝试为系统对时。
