### ISSUE TITLE
[Bug]: typora+gitee上传测试时报错

### ISSUE THREAD

**Issue by mksasx** [Molunerfinn/PicGo#1047]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v 2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/35629227/209428486-fd4531ec-2a17-4781-bbab-74675f586441.png)

### 相关日志 | Logs

2022-12-24 16:46:13 [PicGo INFO] [PicGo Server] upload result  
2022-12-24 16:46:13 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2022-12-24 16:49:05 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\12631\\AppData\\Local\\Temp/typora-icon2.png","C:\\Users\\12631\\AppData\\Local\\Temp/typora-icon.png"]} 
2022-12-24 16:49:05 [PicGo INFO] [PicGo Server] upload files in list 
2022-12-24 16:49:05 [PicGo INFO] Before transform 
2022-12-24 16:49:05 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-24 16:49:05 [PicGo INFO] Before upload 
2022-12-24 16:49:05 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-24 16:49:05 [PicGo INFO] Uploading... Current uploader is [smms] 
2022-12-24 16:49:05 [PicGo ERROR] {
  "method": "POST",
  "url": "https://sm.ms/api/v2/upload",
  "statusCode": 0,
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-12-24 16:49:05 [PicGo WARN] failed 
2022-12-24 16:49:06 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2022-12-24 16:49:06 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2022-12-24 16:49:06 [PicGo INFO] [PicGo Server] upload result  
2022-12-24 16:49:06 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
首先，你没有把gitee图床设为你的默认图床，你只是配置了但是依然使用的是默认的 smms 图床：
![image](https://user-images.githubusercontent.com/12621342/209428733-a50e0b3a-0686-4ed4-b43a-615911777fe9.png)

其次，gitee图床是插件实现的，如果有问题请去插件仓库提问谢谢。日志麻烦自己稍微看看呀

**Comment by mksasx** [comment]
谢谢您~
