### ISSUE TITLE
[Bug]: 在Typora中验证图片上传选项时发生错误

### ISSUE THREAD

**Issue by cbpantianya** [Molunerfinn/PicGo#1048]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在Typora中将PicGo作为图片上传服务时，无法成功验证图片上传选项，显示以下内容
`{"success":false,"message":"upload error. see C:\\Users\\tiany\\AppData\\Roaming\\picgo\\picgo.log for more detail."}`
但是，我可以通过PicGo的GUI上传单张图片
相关的错误日志附在下方

### 相关日志 | Logs

2022-12-25 18:21:23 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\tiany\\AppData\\Local\\Temp/typora-icon2.png","C:\\Users\\tiany\\AppData\\Local\\Temp/typora-icon.png"]} 
2022-12-25 18:21:23 [PicGo INFO] [PicGo Server] upload files in list 
2022-12-25 18:21:23 [PicGo INFO] Before transform 
2022-12-25 18:21:23 [PicGo INFO] Transforming... Current transformer is [path] 
2022-12-25 18:21:23 [PicGo INFO] Before upload 
2022-12-25 18:21:23 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-12-25 18:21:23 [PicGo INFO] Uploading... Current uploader is [smms] 
2022-12-25 18:21:25 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18695)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2022-12-25 18:21:25 [PicGo WARN] failed 
2022-12-25 18:21:25 [PicGo ERROR] 
------Error Stack Begin------
Error: Error: [object Object]
    at Object.ve [as handle] (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2022-12-25 18:21:25 [PicGo ERROR] 
------Error Stack Begin------
Error: Error: [object Object]
    at Object.ve [as handle] (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2022-12-25 18:21:25 [PicGo INFO] [PicGo Server] upload result  
2022-12-25 18:21:25 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
smmms图床报错请自行查看此前deissue 更新日志解决。
