### ISSUE TITLE
[Bug]: TypeError: Cannot create property 'type' on string

### ISSUE THREAD

**Issue by 631068264** [Molunerfinn/PicGo#1053]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

使用pic-migrater 1.32 插件迁移图床后

Typora 上传图片失败
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/8144089/209946973-03f6ec8b-7600-4b95-993a-56ca5340c3e7.png">

后面重启PicGO 又正常了

### 相关日志 | Logs

2022-12-29 19:42:12 [PicGo INFO] [PicGo Server] upload result
2022-12-29 19:42:12 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑
2022-12-29 19:42:22 [PicGo INFO] [PicGo Server] get the request {"list":["\/Users\/wyx\/Library\/Application Support\/typora-user-images\/image-20221229194206221.png"]}
2022-12-29 19:42:22 [PicGo INFO] [PicGo Server] upload files in list
2022-12-29 19:42:22 [PicGo INFO] Before transform
2022-12-29 19:42:22 [PicGo INFO] Transforming... Current transformer is [base64]
2022-12-29 19:42:22 [PicGo INFO] Before upload
2022-12-29 19:42:22 [PicGo INFO] beforeUploadPlugins: renameFn running
2022-12-29 19:42:22 [PicGo INFO] Uploading... Current uploader is [github]
2022-12-29 19:42:22 [PicGo WARN] failed
2022-12-29 19:42:22 [PicGo ERROR]
------Error Stack Begin------
TypeError: Cannot create property 'type' on string '/Users/wyx/Library/Application Support/typora-user-images/image-20221229194206221.png'
    at $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17262)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
    at async /Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:657340
-------Error Stack End-------
2022-12-29 19:42:22 [PicGo ERROR]
------Error Stack Begin------
TypeError: Cannot create property 'type' on string '/Users/wyx/Library/Application Support/typora-user-images/image-20221229194206221.png'
    at $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17262)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
    at async /Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:657340
-------Error Stack End-------
2022-12-29 19:42:22 [PicGo INFO] [PicGo Server] upload result
2022-12-29 19:42:22 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
不知道你装了什么插件。请你把配置文件中的transformer从base64改为path。

**Comment by Molunerfinn** [comment]
迁移图片的时候有遇到报错么？

**Comment by 631068264** [comment]
配置文件路径在哪里，我一按xcode直接弹出来，最好定位到对应文件

迁移图片暂时没遇到报错，但是有的文件迁移不成功

**Comment by Molunerfinn** [comment]
> 配置文件路径在哪里，我一按xcode直接弹出来，最好定位到对应文件
> 
> 
> 
> 迁移图片暂时没遇到报错，但是有的文件迁移不成功

文档里有。跟日志文件同目录。不过你这情况不用看配置文件了 应该是插件的bug
