### ISSUE TITLE
[Bug]:  无法上传大文件

### ISSUE THREAD

**Issue by Littleor** [Molunerfinn/PicGo#1064]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

1. 配置好七牛云
2. 上传某个452MB的zip文件（或者其他大文件）
3. 报错

### 相关日志 | Logs

------Error Stack Begin------
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:642:37)
    at Buffer.toString (node:buffer:811:14)
    at Object.Ve [as handle] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:27146)
    at $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17221)
    at $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15980)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
-------Error Stack End------- 
2023-01-14 10:47:44 [PicGo ERROR]

**Comment by Molunerfinn** [comment]
PicGo 本来就不是用来传大文件的工具。
