### ISSUE TITLE
typora弹出重命名时没有文件格式的尾缀

### ISSUE THREAD

**Issue by Elliotoplit** [Molunerfinn/PicGo#1092]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在typora执行粘贴上传时，弹出的重命名显示框没有带有文件格式了
必须手动在尾部添加.jpg,不然会因为没有格式上传失败或者在图床里但是不会显示略缩图也不能使用
![image](https://user-images.githubusercontent.com/95361161/226168522-4e55799c-2747-46b3-a47a-26588664f8d9.png)

### 相关日志 | Logs

2023-03-19 17:54:11 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2023-03-19 17:57:39 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\豪大大\\AppData\\Local\\Temp/typora-icon2.png","C:\\Users\\豪大大\\AppData\\Local\\Temp/typora-icon.png"]} 
2023-03-19 17:57:39 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-19 17:57:39 [PicGo INFO] Before transform 
2023-03-19 17:57:39 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-19 17:57:40 [PicGo INFO] Before upload 
2023-03-19 17:57:40 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-19 17:58:30 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\豪大大\\AppData\\Local\\Temp/typora-icon2.png","C:\\Users\\豪大大\\AppData\\Local\\Temp/typora-icon.png"]} 
2023-03-19 17:58:30 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-19 17:58:30 [PicGo INFO] Before transform 
2023-03-19 17:58:30 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-19 17:58:30 [PicGo INFO] Before upload 
2023-03-19 17:58:30 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-19 17:58:36 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2023-03-19 17:58:37 [PicGo SUCCESS] 
https://bucketoelliot.oss-cn-chengdu.aliyuncs.com/img/typora-icon2.png.jpg
https://bucketoelliot.oss-cn-chengdu.aliyuncs.com/img/typora-icon.png.jpg 
2023-03-19 17:59:40 [PicGo INFO] detect second instance 
2023-03-19 17:59:45 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\豪大大\\AppData\\Local\\Temp/typora-icon2.png","C:\\Users\\豪大大\\AppData\\Local\\Temp/typora-icon.png"]} 
2023-03-19 17:59:45 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-19 17:59:45 [PicGo INFO] Before transform 
2023-03-19 17:59:45 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-19 17:59:45 [PicGo INFO] Before upload 
2023-03-19 17:59:45 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-19 17:59:48 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2023-03-19 17:59:48 [PicGo SUCCESS] 
https://bucketoelliot.oss-cn-chengdu.aliyuncs.com/img/typora-icon2.png.jpg
https://bucketoelliot.oss-cn-chengdu.aliyuncs.com/img/typora-icon.png.jpg 
2023-03-19 18:04:41 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2023-03-19 18:04:42 [PicGo SUCCESS] 
https://bucketoelliot.oss-cn-chengdu.aliyuncs.com/img/typora-icon2.png.jpg
https://bucketoelliot.oss-cn-chengdu.aliyuncs.com/img/typora-icon.png.jpg 
2023-03-19 18:05:52 [PicGo INFO] [PicGo Server] get the request {"list":["https://iknow-pic.cdn.bcebos.com/f7246b600c338744d84c10305c0fd9f9d62aa0f4"]} 
2023-03-19 18:05:52 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-19 18:05:52 [PicGo INFO] Before transform 
2023-03-19 18:05:52 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-19 18:05:53 [PicGo INFO] Before upload 
2023-03-19 18:05:53 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-19 18:07:48 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2023-03-19 18:07:48 [PicGo WARN] failed 
2023-03-19 18:07:48 [PicGo ERROR] 
------Error Stack Begin------
Error: No mime type found for file f7246b600c338744d84c10305c0fd9f9d62aa0f4
    at generateSignature (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\aliyun.js:14:15)
    at Object.handle (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\aliyun.js:44:35)
    at Lifecycle.doUpload (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:77)
    at Lifecycle.start (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:24)
    at async PicGo.upload (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\AppCenter\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\AppCenter\PicGo\resources\app.asar\background.js:36:31625)
    at async D:\AppCenter\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End------- 
2023-03-19 18:07:48 [PicGo ERROR] 
------Error Stack Begin------
Error: No mime type found for file f7246b600c338744d84c10305c0fd9f9d62aa0f4
    at generateSignature (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\aliyun.js:14:15)
    at Object.handle (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\aliyun.js:44:35)
    at Lifecycle.doUpload (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:77)
    at Lifecycle.start (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:24)
    at async PicGo.upload (D:\AppCenter\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\AppCenter\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\AppCenter\PicGo\resources\app.asar\background.js:36:31625)
    at async D:\AppCenter\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End------- 
2023-03-19 18:07:48 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2023-03-19 18:09:47 [PicGo INFO] [PicGo Server] get the request {"list":["https://iknow-pic.cdn.bcebos.com/f7246b600c338744d84c10305c0fd9f9d62aa0f4"]} 
2023-03-19 18:09:47 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-19 18:09:47 [PicGo INFO] Before transform 
2023-03-19 18:09:47 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-19 18:09:47 [PicGo INFO] Before upload 
2023-03-19 18:09:47 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-19 18:11:48 [PicGo INFO] detect second instance 
2023-03-19 18:11:52 [PicGo INFO] [PicGo Server] get the request {"list":["https://iknow-pic.cdn.bcebos.com/f7246b600c338744d84c10305c0fd9f9d62aa0f4"]} 
2023-03-19 18:11:52 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-19 18:11:52 [PicGo INFO] Before transform 
2023-03-19 18:11:52 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-19 18:11:52 [PicGo INFO] Before upload 
2023-03-19 18:11:52 [PicGo INFO] beforeUploadPlugins: renameFn running

**Comment by Molunerfinn** [comment]
那是因为你上传的图片url没有文件名后缀。

**Comment by Elliotoplit** [comment]
感谢~
