### ISSUE TITLE
[Bug]: 图片上传失败

### ISSUE THREAD

**Issue by konley** [Molunerfinn/PicGo#1096]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

没有安装任何插件，只使用SM.MS图床，上传一直失败。
直接网页访问sm.ms可以正常上传图片。

### 相关日志 | Logs

2023-03-29 23:19:08 [PicGo INFO] [PicGo Server] is listening at 36677 
2023-03-29 23:40:35 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292340973.png.1585364209'
-------Error Stack End------- 
2023-03-29 23:40:47 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292340272.png.3901808608'
-------Error Stack End------- 
2023-03-29 23:40:58 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292340615.png.3808454359'
-------Error Stack End------- 
2023-03-29 23:41:17 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292341690.png.3332609093'
-------Error Stack End------- 
2023-03-29 23:41:19 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292341979.png.3831616411'
-------Error Stack End------- 
2023-03-29 23:41:35 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292341622.png.230783688'
-------Error Stack End------- 
2023-03-29 23:42:10 [PicGo INFO] Before transform 
2023-03-29 23:42:10 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-29 23:42:10 [PicGo INFO] Before upload 
2023-03-29 23:42:10 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-29 23:42:10 [PicGo INFO] Uploading... Current uploader is [smms] 
2023-03-29 23:42:14 [PicGo ERROR] {
  "method": "POST",
  "url": "https://sm.ms/api/v2/upload",
  "statusCode": 0,
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-03-29 23:42:14 [PicGo WARN] failed 
2023-03-29 23:42:14 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
-------Error Stack End------- 
2023-03-29 23:42:14 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
-------Error Stack End------- 
2023-03-29 23:43:32 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\konle\\AppData\\Local\\Temp\\Typora\\typora-icon2.png","C:\\Users\\konle\\AppData\\Local\\Temp\\Typora\\typora-icon.png"]} 
2023-03-29 23:43:32 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-29 23:43:32 [PicGo INFO] Before transform 
2023-03-29 23:43:32 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-29 23:43:32 [PicGo INFO] Before upload 
2023-03-29 23:43:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-29 23:43:32 [PicGo INFO] Uploading... Current uploader is [smms] 
2023-03-29 23:43:53 [PicGo ERROR] {
  "method": "POST",
  "url": "https://sm.ms/api/v2/upload",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 93.46.8.90:443",
  "stack": "Error: connect ETIMEDOUT 93.46.8.90:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-03-29 23:43:53 [PicGo WARN] failed 
2023-03-29 23:43:53 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-03-29 23:43:53 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-03-29 23:43:53 [PicGo INFO] [PicGo Server] upload result  
2023-03-29 23:43:53 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2023-03-29 23:46:26 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\konle\\AppData\\Local\\Temp\\Typora\\typora-icon2.png","C:\\Users\\konle\\AppData\\Local\\Temp\\Typora\\typora-icon.png"]} 
2023-03-29 23:46:26 [PicGo INFO] [PicGo Server] upload files in list 
2023-03-29 23:46:26 [PicGo INFO] Before transform 
2023-03-29 23:46:26 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-29 23:46:26 [PicGo INFO] Before upload 
2023-03-29 23:46:26 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-29 23:46:26 [PicGo INFO] Uploading... Current uploader is [smms] 
2023-03-29 23:46:26 [PicGo ERROR] {
  "method": "POST",
  "url": "https://sm.ms/api/v2/upload",
  "statusCode": 0,
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-03-29 23:46:26 [PicGo WARN] failed 
2023-03-29 23:46:26 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-03-29 23:46:26 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-03-29 23:46:26 [PicGo INFO] [PicGo Server] upload result  
2023-03-29 23:46:26 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2023-03-29 23:54:01 [PicGo INFO] [PicGo Server] is listening at 36677 
2023-03-29 23:54:25 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292354518.png.2372460469'
-------Error Stack End------- 
2023-03-29 23:54:27 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292354652.png.1911831111'
-------Error Stack End------- 
2023-03-29 23:54:30 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292354413.png.3437627596'
-------Error Stack End------- 
2023-03-29 23:54:30 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'C:\Users\konle\AppData\Roaming\picgo\picgo-clipboard-images\202303292354702.png.2914087494'
-------Error Stack End------- 
2023-03-29 23:55:13 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71396)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:661590)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:663441
    at async Un (C:\Program Files\PicGo\resources\app.asar\background.js:2:663273)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
这个报错请参考以前的issue
