### ISSUE TITLE
[Bug]: 没有图片后缀的 URL 链接图片无法上传

### ISSUE THREAD

**Issue by 1912377458** [Molunerfinn/PicGo#1100]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

类似这种没有图片后缀的链接无法通过picgo上传，看日志提示不支持的文件类型
`https://doc.shiyanlou.com/courses/uid1723100-20211109-1636427844206`
<img width="686" alt="image" src="https://user-images.githubusercontent.com/73117213/230114488-f67653e0-e792-4753-9df4-8af3808c7ae1.png">

### 相关日志 | Logs

2023-04-05 22:27:54 [PicGo ERROR] 
------Error Stack Begin------
Error: 不支持的文件类型
    at Object.handle (/Users/xiangyu/Library/Application Support/picgo/node_modules/picgo-plugin-lankong/dist/index.js:197:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17198)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
这个是你的lankong插件的问题。
