### ISSUE TITLE
[Bug]: 上传失败

### ISSUE THREAD

**Issue by InfiCoda** [Molunerfinn/PicGo#1110]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0 beta.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

环境配置没问题，正确地填写了地址和token，但是上传失败，开加速器时报错如图一，不开加速器时报错如图二
![image](https://user-images.githubusercontent.com/110673535/232226832-bd44b135-babc-4615-85dc-ae27d01d944b.png)
![image](https://user-images.githubusercontent.com/110673535/232226840-77d73cc9-77be-444e-a453-710eeb73b997.png)

### 相关日志 | Logs

2023-04-15 16:04:51 [PicGo INFO] [PicGo Server] is listening at 36677 
2023-04-15 16:26:44 [PicGo INFO] detect second instance 
2023-04-15 16:33:25 [PicGo INFO] Before transform 
2023-04-15 16:33:25 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 16:33:25 [PicGo INFO] Before upload 
2023-04-15 16:33:25 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 16:33:25 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 16:33:35 [PicGo WARN] failed 
2023-04-15 16:33:35 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:33:35 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:33:37 [PicGo INFO] Before transform 
2023-04-15 16:33:37 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 16:33:37 [PicGo INFO] Before upload 
2023-04-15 16:33:37 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 16:33:37 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 16:33:37 [PicGo WARN] failed 
2023-04-15 16:33:37 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:33:37 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:33:45 [PicGo INFO] Before transform 
2023-04-15 16:33:45 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 16:33:45 [PicGo INFO] Before upload 
2023-04-15 16:33:45 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 16:33:45 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 16:33:55 [PicGo WARN] failed 
2023-04-15 16:33:55 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/arknights.jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:33:55 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/arknights.jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:34:02 [PicGo INFO] Before transform 
2023-04-15 16:34:02 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 16:34:03 [PicGo INFO] Before upload 
2023-04-15 16:34:03 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 16:34:03 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 16:34:08 [PicGo WARN] failed 
2023-04-15 16:34:08 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:34:08 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:34:14 [PicGo INFO] Before transform 
2023-04-15 16:34:14 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 16:34:14 [PicGo INFO] Before upload 
2023-04-15 16:34:14 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 16:34:14 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 16:34:16 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at Tt.upload (D:\Tools\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71396)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.upload (D:\Tools\PicGo\resources\app.asar\background.js:2:661590)
    at async D:\Tools\PicGo\resources\app.asar\background.js:2:663441
    at async Un (D:\Tools\PicGo\resources\app.asar\background.js:2:663273)
-------Error Stack End------- 
2023-04-15 16:34:24 [PicGo WARN] failed 
2023-04-15 16:34:24 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/arknights%20(2).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 16:34:24 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/arknights%20(2).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 17:12:38 [PicGo INFO] detect second instance 
2023-04-15 17:12:45 [PicGo INFO] Before transform 
2023-04-15 17:12:45 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 17:12:45 [PicGo INFO] Before upload 
2023-04-15 17:12:45 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 17:12:45 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 17:12:56 [PicGo WARN] failed 
2023-04-15 17:12:56 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo ENOTFOUND api.github.com",
  "stack": "Error: getaddrinfo ENOTFOUND api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 17:12:56 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo ENOTFOUND api.github.com",
  "stack": "Error: getaddrinfo ENOTFOUND api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 17:12:59 [PicGo INFO] Before transform 
2023-04-15 17:12:59 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 17:12:59 [PicGo INFO] Before upload 
2023-04-15 17:12:59 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 17:12:59 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 17:13:10 [PicGo WARN] failed 
2023-04-15 17:13:10 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo ENOTFOUND api.github.com",
  "stack": "Error: getaddrinfo ENOTFOUND api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 17:13:10 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo ENOTFOUND api.github.com",
  "stack": "Error: getaddrinfo ENOTFOUND api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 17:13:26 [PicGo INFO] [PicGo Server] shutdown 
2023-04-15 21:02:27 [PicGo INFO] [PicGo Server] is listening at 36677 
2023-04-15 21:02:57 [PicGo INFO] Before transform 
2023-04-15 21:02:57 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 21:02:58 [PicGo INFO] Before upload 
2023-04-15 21:02:58 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 21:02:58 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 21:02:58 [PicGo WARN] failed 
2023-04-15 21:02:58 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/arknights%20(3).jpg",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 21:02:58 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/arknights%20(3).jpg",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 21:11:03 [PicGo INFO] Before transform 
2023-04-15 21:11:03 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 21:11:03 [PicGo INFO] Before upload 
2023-04-15 21:11:03 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 21:11:03 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 21:11:03 [PicGo WARN] failed 
2023-04-15 21:11:03 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 21:11:03 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 21:23:17 [PicGo INFO] Before transform 
2023-04-15 21:23:17 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 21:23:17 [PicGo INFO] Before upload 
2023-04-15 21:23:17 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 21:23:17 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 21:23:17 [PicGo WARN] failed 
2023-04-15 21:23:17 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 21:23:17 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 21:23:24 [PicGo INFO] Before transform 
2023-04-15 21:23:24 [PicGo INFO] Transforming... Current transformer is [path] 
2023-04-15 21:23:24 [PicGo INFO] Before upload 
2023-04-15 21:23:24 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-04-15 21:23:24 [PicGo INFO] Uploading... Current uploader is [github] 
2023-04-15 21:23:34 [PicGo WARN] failed 
2023-04-15 21:23:34 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-04-15 21:23:34 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/InfiCoda/pic_bed/contents/img/1999(14).jpg",
  "statusCode": 0,
  "message": "getaddrinfo EAI_AGAIN api.github.com",
  "stack": "Error: getaddrinfo EAI_AGAIN api.github.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
这是你的网络问题，请自行搜索报错的关键词。

**Comment by InfiCoda** [comment]
感谢，都是我这垃圾校园网惹的祸
