### ISSUE TITLE
上传腾讯云COS失败

### ISSUE THREAD

**Issue by asa-world** [Molunerfinn/PicGo#1113]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

正常使用很长时间了，最近突然上传不了了，之前使用的是v2.3.1 beta4，报错为404，今天升级到2.3.1正式版，还是有报错。
在腾讯云cos的官网可以正常上传
希望大佬求解

### 相关日志 | Logs

------Error Stack Begin------
TypeError: req.end is not a function
    at C:\Users\asa\AppData\Roaming\picgo\node_modules\picgo-plugin-compress\dist\compress\tinypngweb.js:21:13
    at async Promise.all (index 0)
    at async $e.doTransform (D:\app\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:16679)
    at async $e.start (D:\app\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15916)
    at async Tt.upload (D:\app\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\app\picgo\resources\app.asar\background.js:2:653584)
    at async jn (D:\app\picgo\resources\app.asar\background.js:2:656251)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
这是你 picgo-plugin-compress 的报错。
