### ISSUE TITLE
[Bug]: Error: ENOENT: no such file or directory, open '‪E:/java_study/picgo/blog_upload.json'

### ISSUE THREAD

**Issue by Orangewl** [Molunerfinn/PicGo#1133]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Molunerfinn/PicGo/assets/54013096/c675b48a-aea4-4152-a770-8a844833e69b)

### 相关日志 | Logs

2023-05-28 09:38:27 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '‪E:/java_study/picgo/blog_upload.json'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at C:\Users\wang\AppData\Roaming\picgo\node_modules\picgo-plugin-sftp-uploader\dist\config.js:75:45
    at new Promise (<anonymous>)
    at Object.exports.getPcigoConfig (C:\Users\wang\AppData\Roaming\picgo\node_modules\picgo-plugin-sftp-uploader\dist\config.js:39:12)
    at Object.handle (C:\Users\wang\AppData\Roaming\picgo\node_modules\picgo-plugin-sftp-uploader\dist\index.js:15:43)
-------Error Stack End------- 
2023-05-28 09:38:27 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
这个报错是sftp plugin的报错，请去插件仓库反馈。
