### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SUFEHeisenberg** [Molunerfinn/PicGo#1138]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在Typora中配置PicGo图床时图片无法上传，远程仓库配置在了gitee上，用了gitee2.0.5和gitee-uploader1.12等几个插件都不行。日志中报错如下所示，期待回复和帮助！感激不尽！

### 相关日志 | Logs

- gitee 2.0.5插件报错如下：

  2023-06-14 18:44:17 [PicGo ERROR] 
  ------Error Stack Begin------
  Error: [object Object]
      at Object.ve [as handle] (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async $e.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
      at async $e.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
      at async Tt.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
      at async Object.upload (D:\PicGo\resources\app.asar\background.js:2:653584)
      at async jn (D:\PicGo\resources\app.asar\background.js:2:656251)
      at async D:\PicGo\resources\app.asar\background.js:2:657340
  -------Error Stack End------- 
  2023-06-14 18:44:17 [PicGo INFO] [PicGo Server] upload result  
  2023-06-14 18:44:17 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 

- gitee-uploader1.1.2日志报错如下：
  2023-06-14 18:38:19 [PicGo ERROR] 
  ------Error Stack Begin------
  TypeError: Cannot read properties of null (reading 'replace')
      at Object.getPath (C:\Users\Administrator.WIN-T57L97EEQAK\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\lib\helper.js:62:25)
      at new Octo (C:\Users\Administrator.WIN-T57L97EEQAK\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\lib\octokit.js:47:30)
      at Object.getIns (C:\Users\Administrator.WIN-T57L97EEQAK\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\lib\octokit.js:230:11)
      at initOcto (C:\Users\Administrator.WIN-T57L97EEQAK\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js:11:27)
      at Object.handle (C:\Users\Administrator.WIN-T57L97EEQAK\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js:110:21)
      at $e.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17221)
      at $e.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15980)
      at async Tt.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
      at async Object.upload (D:\PicGo\resources\app.asar\background.js:2:653584)
      at async jn (D:\PicGo\resources\app.asar\background.js:2:656251)
  -------Error Stack End------- 
  2023-06-14 18:38:19 [PicGo INFO] [PicGo Server] upload result  
  2023-06-14 18:38:19 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
请去插件仓库反馈，谢谢。

**Comment by SUFEHeisenberg** [comment]
> 请去插件仓库反馈，谢谢。

好的，感谢回复
