### ISSUE TITLE
[Feature]: github上的图片链接无法上传到其他图床

### ISSUE THREAD

**Issue by Sbwillbealier** [Molunerfinn/PicGo#1144]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

当我想将之前上传到github上的图片链接（使用了jsDelivr的CDN，去掉CDN也一样的），粘贴到picgo上面通过url上传到其他图床时会出现以下问题，请问有解决办法吗？
`------Error Stack Begin------
Error: request https://cdn.jsdelivr.net/gh/Sbwillbealier/cdn_img@blog-1.0/img/202306251106395.png timeout
    at D:\App\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:38189
    at async Promise.all (index 0)
    at async Object.handle (D:\App\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:37138)
    at async $e.doTransform (D:\App\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:16679)
    at async $e.start (D:\App\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15916)
    at async Tt.upload (D:\App\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\App\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\App\PicGo\resources\app.asar\background.js:2:656251)
-------Error Stack End------- `

![image](https://github.com/Molunerfinn/PicGo/assets/25285227/948a6bb6-bcac-4b84-827d-9783e77f451f)

**Comment by Molunerfinn** [comment]
这个是 jsdelivr CDN 发现是国内 IP 就会回源 github 本身原始链接导致的。这个跟 picgo 无关，跟你的网络有关系。

花钱不要用 github 当图床就能解决这个问题。
