### ISSUE TITLE
[Bug]: 支持win11吗？

### ISSUE THREAD

**Issue by 780886** [Molunerfinn/PicGo#1145]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

请问一下win11系统下载后打不开是什么原因呢

**Comment by Molunerfinn** [comment]
支持 在右下角任务栏。

**Comment by 780886** [comment]
上传图片报错，部分日志信息:
2023-07-05 17:39:26 [PicGo ERROR] {
  "method": "POST",
  "url": "https://sm.ms/api/v2/upload",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 46.82.174.69:443",
  "stack": "Error: connect ETIMEDOUT 46.82.174.69:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-07-05 17:39:26 [PicGo WARN] failed 
2023-07-05 17:39:26 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-07-05 17:39:26 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-07-05 17:39:26 [PicGo INFO] [PicGo Server] upload result  
2023-07-05 17:39:26 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
可以看一下具体是什么原因嘛？谢谢！

**Comment by Molunerfinn** [comment]
网络超时。 smms 的接口国内被封，域名可以换成 smms.app 试试。
