### ISSUE TITLE
上传图片显示连接超时，可是配置和网络并没有问题

### ISSUE THREAD

**Issue by jiechen257** [Molunerfinn/PicGo#1167]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

我用的 jsdelivr + github，在这之前一直用的好好的，最近一次上传是三五天前，这是报错截图：
<img width="1228" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/73946940/dff0e857-eb49-4f48-bffb-19ba0d34b08d">

### 相关日志 | Logs

------Error Stack Begin------
TypeError: Object has been destroyed
    at Object.b.send (node:electron/js2c/browser_init:161:2482)
    at Tt.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:659801)
    at Tt.emit (node:events:394:28)
    at $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:16056)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:661590)
    at async zn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:664240)
-------Error Stack End------- 
2023-08-20 18:29:49 [PicGo INFO] Before transform 
2023-08-20 18:29:49 [PicGo INFO] Transforming... Current transformer is [path] 
2023-08-20 18:29:49 [PicGo INFO] Before upload 
2023-08-20 18:29:49 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-08-20 18:29:49 [PicGo INFO] Uploading... Current uploader is [github] 
2023-08-20 18:31:04 [PicGo WARN] failed 
2023-08-20 18:31:04 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/jiechen257/gallery/contents/img/202308201829639.jpeg",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 20.205.243.168:443",
  "stack": "Error: connect ETIMEDOUT 20.205.243.168:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-08-20 18:31:04 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/jiechen257/gallery/contents/img/202308201829639.jpeg",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 20.205.243.168:443",
  "stack": "Error: connect ETIMEDOUT 20.205.243.168:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
你这个就是网络超时啊

**Comment by Molunerfinn** [comment]
能访问 github.com 并不代表 github api 能正常访问。 picgo 是通过 github api 上传的

**Comment by Molunerfinn** [comment]
配个代理吧

**Comment by jiechen257** [comment]
> 配个代理吧
我一直开着代理的，我youtube、twitter都在正常浏览

**Comment by jiechen257** [comment]
> 配个代理吧

我一直开着代理的，我youtube、twitter都在正常浏览

**Comment by Molunerfinn** [comment]
picgo  有内置代理配置，配那个

**Comment by jiechen257** [comment]
定位到了 是clashX的代理模式问题 谢谢大佬

**Comment by hyyxiaoluo** [comment]
> 定位到了 是clashX的代理模式问题 谢谢大佬

老哥，我跟你一样，咋解决的啊，我之前都可以的

**Comment by jiechen257** [comment]
> > 定位到了 是clashX的代理模式问题 谢谢大佬
> 
> 老哥，我跟你一样，咋解决的啊，我之前都可以的

你看下 ClashX 的【增强模式】是不是没打开，打开下就可以了，至于原理看我这篇博客：[ClashX的增强模式](https://becase.top/2023/08/19/ClashX%E7%9A%84%E5%A2%9E%E5%BC%BA%E6%A8%A1%E5%BC%8F)

**Comment by hyyxiaoluo** [comment]
> picgo 有内置代理配置，配那个

我现在配置了代理还是不行，我把给pigco配置的代理用到手机上，手机修改wifi的手动代理后都能正常访问外网，代理应该没问题吧，懵了

**Comment by cold-bin** [comment]
我也是这个问题。连api.github.com都ping不通，但是浏览器可以访问得到这个。后面我修改host解决了这个问题。应该是代理规则得问题。

**Comment by jiechen257** [comment]
> 我也是这个问题。连api.github.com都ping不通，但是浏览器可以访问得到这个。后面我修改host解决了这个问题。应该是代理的问题。浏览器可以走代理，并不是设置了系统代理所有的请求都会走代理。
> 
> 可以给picgo单独设置代理到正确端口，让picgo的请求一定要走代理才行： ![image](https://user-images.githubusercontent.com/85239590/262284934-2c52c5c9-3980-408a-9162-1bca2bb99010.png)

也可以设置全局代理的，看这篇文章最后那部分 [ClashX增强模式](https://becase.top/2023/08/19/ClashX%E7%9A%84%E5%A2%9E%E5%BC%BA%E6%A8%A1%E5%BC%8F)

**Comment by zzziv** [comment]
改下 hosts
https://blog.csdn.net/MJL1907101/article/details/132847772

**Comment by jiechen257** [comment]
> 改下 hosts https://blog.csdn.net/MJL1907101/article/details/132847772

感谢，不过问题已经解决了（vpn开启全局就好
