### ISSUE TITLE
[Feature]: 希望修改typora通过调用picgo server方式向smms上传的方式

### ISSUE THREAD

**Issue by DraceWang** [Molunerfinn/PicGo#1171]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

首先非常感谢作者的付出，picgo是非常好用的软件。

我在20年左右使用typora的时候有非常好用的直接调用picgo来上传图床并自动转为url来显示图片，这样可以非常便捷的写作。

 目前我在使用中遇到的困难是typora无法再像以前一样调用picgo的上传了，经过调查发现是smms被墙了的原因。而且picgo已经使用备用域名完成了对smms的支持 #676，但是typora的自动上传似乎并没有支持。
同时注意到 #676 问题中提及直接替换备用域名无法使用api，因此进行了尝试，发现如下方式可以上传成功：

![20230824122527.png](https://s2.loli.net/2023/08/24/RbqyL3JKMA9xSzY.png)

删除原有参数，改为`inajax=1`，同时在body中增加表单，key为 smfile 文件类型，值就是我们需要上传的图片。

我对picgo还不是非常了解，如果作者大大愿意修改自然是最好，我后期有时间的话也会尝试去修改这个。

**Comment by Molunerfinn** [comment]
picgo server 跟smms本身上传逻辑是解耦的。

**Comment by Molunerfinn** [comment]
理论上你配置了备用域名后，用 picgo 本身能正常上传的情况下，用 typora 调用也是能正常上传的，typora 调用 picgo server ，picgo server 再调 smms 的 uploader 上传，跟你直接用 picgo 上传是一样的。

不能上传的情况下，请提供日志看看具体的原因。

**Comment by DraceWang** [comment]
wow ，你大概是我在github上遇到回复最快的作者了。

很遗憾，我不清楚具体是什么原因，导致typora调用上传失败了，但在我这里确实发生了。

![](https://s2.loli.net/2023/08/24/BmVGvSIEiW4jswd.png)

![20230824142528.png](https://s2.loli.net/2023/08/24/MhJ8wgGvejQVioa.png)

log信息如下，log中上传了两次，第一次是使用typora调用picgo上传，第二次是直接使用picgo上传。

```
2023-08-24 14:25:14 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\wsdbo\\AppData\\Local\\Temp\\Typora\\typora-icon2.png","C:\\Users\\wsdbo\\AppData\\Local\\Temp\\Typora\\typora-icon.png"]} 
2023-08-24 14:25:14 [PicGo INFO] [PicGo Server] upload files in list 
2023-08-24 14:25:14 [PicGo INFO] Before transform 
2023-08-24 14:25:14 [PicGo INFO] Transforming... Current transformer is [path] 
2023-08-24 14:25:14 [PicGo INFO] Before upload 
2023-08-24 14:25:14 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-08-24 14:25:14 [PicGo INFO] Uploading... Current uploader is [smms] 
2023-08-24 14:25:16 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18695)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-08-24 14:25:16 [PicGo WARN] failed 
2023-08-24 14:25:16 [PicGo ERROR] 
------Error Stack Begin------
Error: Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-08-24 14:25:16 [PicGo ERROR] 
------Error Stack Begin------
Error: Error: [object Object]
    at Object.ve [as handle] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Program Files\PicGo\resources\app.asar\background.js:2:656251)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2023-08-24 14:25:16 [PicGo INFO] [PicGo Server] upload result  
2023-08-24 14:25:16 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2023-08-24 14:34:03 [PicGo INFO] Before transform 
2023-08-24 14:34:03 [PicGo INFO] Transforming... Current transformer is [path] 
2023-08-24 14:34:03 [PicGo INFO] Before upload 
2023-08-24 14:34:03 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-08-24 14:34:03 [PicGo INFO] Uploading... Current uploader is [smms] 
2023-08-24 14:34:05 [PicGo SUCCESS] 
https://s2.loli.net/2023/08/24/BmVGvSIEiW4jswd.png 
```
这个报错信息我翻了下以前的issue和 #1147 问题接近，但是我这边[picgo error]后面没有post请求的信息。

也不知道是不是我这边什么配置错误，如果可以，还烦请作者大大帮我指出。

谢谢

**Comment by Molunerfinn** [comment]
你用typora传的那两张图片已经被 smms 官方封禁。你传几张自己的图片就可以了

**Comment by DraceWang** [comment]
好的，非常感谢。如果可以可以在新版本中说明，毕竟是typora这个上传验证的功能对smms图床无效，也防止其他picgo用户再来叨扰作者大大。

**Comment by LiGeng2000** [comment]
2024-05-17 14:55:08 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\18335\\Documents\\Tencent Files\\mosaic\\nt_qq\\nt_data\\Pic\\2024-05\\Ori\\3b478da358dca38470d234802b167cb2.jpg"]} 
2024-05-17 14:55:08 [PicGo INFO] [PicGo Server] upload files in list 
2024-05-17 14:55:08 [PicGo INFO] Before transform 
2024-05-17 14:55:08 [PicGo INFO] Transforming... Current transformer is [path] 
2024-05-17 14:55:08 [PicGo INFO] Before upload 
2024-05-17 14:55:08 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-05-17 14:55:08 [PicGo INFO] Uploading... Current uploader is [smms] 
2024-05-17 14:55:13 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18695)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2024-05-17 14:55:13 [PicGo WARN] failed 
2024-05-17 14:55:13 [PicGo ERROR] 
------Error Stack Begin------
Error: Error: [object Object]
    at Object.ve [as handle] (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2024-05-17 14:55:13 [PicGo ERROR] 
------Error Stack Begin------
Error: Error: [object Object]
    at Object.ve [as handle] (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\ProgramFiles\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:656251)
    at async D:\ProgramFiles\PicGo\resources\app.asar\background.js:2:657340
-------Error Stack End------- 
2024-05-17 14:55:13 [PicGo INFO] [PicGo Server] upload result  
2024-05-17 14:55:13 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 


这是我传了一张自己的图片然后失败的log，找657340的时候找到了这篇，能问一下是什么问题嘛，谢谢！
