### ISSUE TITLE
[Bug]: 上传url图片失败

### ISSUE THREAD

**Issue by wincent98** [Molunerfinn/PicGo#1185]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

通过url上传失败, 图片可以正常访问, https://dubbo.apache.org/imgs/architecture.png

### 相关日志 | Logs

------Error Stack Begin------
Error: request https://dubbo.apache.org/imgs/architecture.png error, write EPROTO 1082983816:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:../../third_party/boringssl/src/ssl/tls_record.cc:594:SSL alert number 70

    at D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:38189
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.handle (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:37138)
    at async $e.doTransform (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:16679)
    at async $e.start (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15916)
    at async Tt.upload (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\Software\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (D:\Software\PicGo\resources\app.asar\background.js:2:656251)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
<img width="378" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/9b432622-44b4-4b41-955f-712472e03a35">
我通过 URL 上传这张图片是正常的。检查你的网络是否有设置什么代理之类的
