### ISSUE TITLE
macOS Mojave 下无法打开软件

### ISSUE THREAD

**Issue by 954630688** [Molunerfinn/PicGo#119]
## 问题类型

你好！新装的 macOS,无法打开软件。

## PicGo的相关信息

PicGo: 1.6.2
macOS: 10.14

## 问题重现

```
➜  ~ /Applications/PicGo.app/Contents/MacOS/PicGo ; exit;
2018-09-29 21:53:37.840 PicGo[727:25998] *** WARNING: Textured window <AtomNSWindow: 0x7fc385c87150> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
module.js:487
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Applications/PicGo.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/Applications/PicGo.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/Applications/PicGo.app/Contents/Resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:338:26)

[进程已完成]

```

## 功能请求

---

**Comment by 954630688** [comment]
不好意思，没有看上面状态栏哪里
