### ISSUE TITLE
[Bug]: 打不开Picgo,之前安装过nodejs然后那个盘被我用来干其他事了,看日志说是找不到nodejs那个路径，我也不知道怎么改。现在就是无法启动gui界面

### ISSUE THREAD

**Issue by Eviden0** [Molunerfinn/PicGo#1251]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo2.4.0-beta.7-x64

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

安装完打不开，任务管理器有进程但是任务栏就是没有图标！

### 相关日志 | Logs

2024-06-08 22:11:46 [PicGo ERROR] 
------Error Stack Begin------
Error: UNKNOWN: unknown error, stat 'E:\NodeJs\node_global'
    at statSync (node:fs:1536:3)
    at Object.e.statSync (node:electron/js2c/asar_bundle:5:4527)
    at Conf.loadUser (F:\Picgo\resources\app.asar\node_modules\npm-conf\lib\conf.js:162:21)
    at module.exports (F:\Picgo\resources\app.asar\node_modules\npm-conf\index.js:32:7)
    at Object.<anonymous> (F:\Picgo\resources\app.asar\node_modules\get-proxy\index.js:2:36)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
那你重新安装nodejs啊

**Comment by Eviden0** [comment]
肯定安装nodejs了，在另一个地方，但是它就是识别原路径然后就一直在那报错进不去

**Comment by Molunerfinn** [comment]
这种问题你应该去问 chatgpt

**Comment by Eviden0** [comment]
ok，搞好了，修改一下默认.npmrc文件指向的node路径即可。打扰了...
