### ISSUE TITLE
[Feature]: add support for images of `awebp` extension

### ISSUE THREAD

**Issue by leinad59** [Molunerfinn/PicGo#1254]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.6

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

I failed uploading `awebp` image from Juejin to Picgo, here is the log:

```
2024-06-19 11:20:19 [PicGo ERROR] 
------Error Stack Begin------
Error: No mime type found for file 9bf02376c1db4de0bb4ee3b1050ccef7~tplv-k3u1fbpfcp-zoom-in-crop-mark:1512:0:0:0.awebp
    at ut (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:34565)
    at Object.pt [as handle] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:35264)
    at je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19857)
    at je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18616)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74902)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:686906)
    at async hr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:689655)
-------Error Stack End-------
```

I'm wondering if we can support `awebp` images?

**Comment by Molunerfinn** [comment]
OK, I will take a look
