### ISSUE TITLE
[Bug]: 不能同步到chevereto的图床

### ISSUE THREAD

**Issue by Tony-2046** [Molunerfinn/PicGo#1257]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1和v2.4.0 beta7

### 系统信息 | System Information

Mac

### 其它的验证
1. 在使用picgo 之前，使用python 脚本已经可以正常将图片上传到chevereto。----- 验证了 url 和 API KEY 的正确性。
2. 原来的Cheveretor V3的版本，怀疑不正确。重新搭建了Chevereto V4 版本，出现故障类似。
3. 使用不同的chevereto 插件 chevereto 1.1.0  和 cheveretov4 1.4.0 ，出现故障类似。
4. 根据网上的排错方式，添加compress 方式，开关server 等都无效。

### 使用最新版本 v2.4.0 beta7 、chevereto 1.1.0 插件 和Cheveretor V4
-------Error Stack End------- 
2024-06-26 21:13:47 [PicGo INFO] Before transform 
2024-06-26 21:13:47 [PicGo INFO] Transforming... Current transformer is [compress] 
2024-06-26 21:13:47 [PicGo INFO] 压缩:image2webp 
2024-06-26 21:13:47 [PicGo INFO] 图片地址:/Desktop/春季研学3.jpg 
2024-06-26 21:13:47 [PicGo INFO] 图片信息:{"fileName":"春季研学3.jpg","extname":".jpg"} 
2024-06-26 21:13:47 [PicGo INFO] Image2WebP 压缩开始 
2024-06-26 21:13:47 [PicGo INFO] 获取本地图片 
2024-06-26 21:13:47 [PicGo INFO] 转换图片为WebP 
2024-06-26 21:13:48 [PicGo INFO] Image2WebP 压缩成功 
2024-06-26 21:13:48 [PicGo INFO] 图片信息:[{"fileName":"春季研学3.webp","extname":".webp","height":2268,"width":4032}] 
2024-06-26 21:13:48 [PicGo INFO] Before upload 
2024-06-26 21:13:48 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-06-26 21:13:48 [PicGo INFO] Uploading... Current uploader is [chevereto] 
2024-06-26 21:13:48 [PicGo WARN] failed 
2024-06-26 21:13:48 [PicGo ERROR] {
  "method": "POST",
  "url": "https://mysite.com::59021/api/1/upload/",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "No key provided",
        "code": 100
      },
      "status_txt": "Bad Request"
    }
  }
} 

### 使用版本 v2.4.0 beta7 、chevereto 1.1.0 插件 和 Cheveretor V3
与V4的类似，仅仅错误原因出现变化；

      "error": {
        "message": "Invalid API v1 key",
        "code": 100
      },
通过log文件中的错误信息，可以导出错误信息中的网页，发现是个人chevereto 的登录界面；发现是个人chevereto 的登录界面

### 使用版本 v2.4.0 beta7 、cheveretov4 1.4.0 插件 和 Cheveretor V4

Error: Request failed with status code 400
    at Object.handle (/Users/name/Library/Application Support/picgo/node_modules/picgo-plugin-cheveretov4/src/index.js:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74902)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690047)
-------Error Stack End-------

### 相关日志 | Logs

-------Error Stack End------- 
2024-06-26 21:01:12 [PicGo ERROR] 
------Error Stack Begin------
Error: Request failed with status code 400
    at Object.handle (/Users/na me/Library/Application Support/picgo/node_modules/picgo-plugin-cheveretov4/src/index.js:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:75256)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async /Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:689242
    at async dr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:689074)
-------Error Stack End------- 
2024-06-26 21:04:07 [PicGo INFO] Before transform 
2024-06-26 21:04:07 [PicGo INFO] Transforming... Current transformer is [compress] 
2024-06-26 21:04:07 [PicGo INFO] 压缩:image2webp 
2024-06-26 21:04:07 [PicGo INFO] 图片地址:/Users/name/Desktop/春季研学3.jpg 
2024-06-26 21:04:07 [PicGo INFO] 图片信息:{"fileName":"春季研学3.jpg","extname":".jpg"} 
2024-06-26 21:04:07 [PicGo INFO] Image2WebP 压缩开始 
2024-06-26 21:04:07 [PicGo INFO] 获取本地图片 
2024-06-26 21:04:07 [PicGo INFO] 转换图片为WebP 
2024-06-26 21:04:08 [PicGo INFO] Image2WebP 压缩成功 
2024-06-26 21:04:08 [PicGo INFO] 图片信息:[{"fileName":"春季研学3.webp","extname":".webp","height":2268,"width":4032}] 
2024-06-26 21:04:08 [PicGo INFO] Before upload 
2024-06-26 21:04:08 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-06-26 21:04:08 [PicGo INFO] Uploading... Current uploader is [cheveretov4] 
2024-06-26 21:04:08 [PicGo WARN] failed 
2024-06-26 21:04:08 [PicGo ERROR] 
------Error Stack Begin------
Error: Request failed with status code 400
    at Object.handle (/Users/name/Library/Application Support/picgo/node_modules/picgo-plugin-cheveretov4/src/index.js:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74902)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690047)
-------Error Stack End------- 
2024-06-26 21:04:08 [PicGo ERROR] 
------Error Stack Begin------
Error: Request failed with status code 400
    at Object.handle (/Users/name/Library/Application Support/picgo/node_modules/picgo-plugin-cheveretov4/src/index.js:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74902)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690047)
-------Error Stack End------- 
2024-06-26 21:13:21 [PicGo INFO] Before transform 
2024-06-26 21:13:21 [PicGo INFO] Transforming... Current transformer is [compress] 
2024-06-26 21:13:21 [PicGo INFO] 压缩:image2webp 
2024-06-26 21:13:21 [PicGo INFO] 图片地址:/Users/name/Desktop/春季研学3.jpg 
2024-06-26 21:13:21 [PicGo INFO] 图片信息:{"fileName":"春季研学3.jpg","extname":".jpg"} 
2024-06-26 21:13:21 [PicGo INFO] Image2WebP 压缩开始 
2024-06-26 21:13:21 [PicGo INFO] 获取本地图片 
2024-06-26 21:13:21 [PicGo INFO] 转换图片为WebP 
2024-06-26 21:13:23 [PicGo INFO] Image2WebP 压缩成功 
2024-06-26 21:13:23 [PicGo INFO] 图片信息:[{"fileName":"春季研学3.webp","extname":".webp","height":2268,"width":4032}] 
2024-06-26 21:13:23 [PicGo INFO] Before upload 
2024-06-26 21:13:23 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-06-26 21:13:23 [PicGo INFO] Uploading... Current uploader is [cheveretov4] 
2024-06-26 21:13:23 [PicGo WARN] failed 
2024-06-26 21:13:23 [PicGo ERROR] 
------Error Stack Begin------
Error: Request failed with status code 400
    at Object.handle (/Users/name/Library/Application Support/picgo/node_modules/picgo-plugin-cheveretov4/src/index.js:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74902)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690047)
-------Error Stack End------- 
2024-06-26 21:13:23 [PicGo ERROR] 
------Error Stack Begin------
Error: Request failed with status code 400
    at Object.handle (/Users/name/Library/Application Support/picgo/node_modules/picgo-plugin-cheveretov4/src/index.js:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74902)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690047)
-------Error Stack End------- 
2024-06-26 21:13:47 [PicGo INFO] Before transform 
2024-06-26 21:13:47 [PicGo INFO] Transforming... Current transformer is [compress] 
2024-06-26 21:13:47 [PicGo INFO] 压缩:image2webp 
2024-06-26 21:13:47 [PicGo INFO] 图片地址:/Users/name/Desktop/春季研学3.jpg 
2024-06-26 21:13:47 [PicGo INFO] 图片信息:{"fileName":"春季研学3.jpg","extname":".jpg"} 
2024-06-26 21:13:47 [PicGo INFO] Image2WebP 压缩开始 
2024-06-26 21:13:47 [PicGo INFO] 获取本地图片 
2024-06-26 21:13:47 [PicGo INFO] 转换图片为WebP 
2024-06-26 21:13:48 [PicGo INFO] Image2WebP 压缩成功 
2024-06-26 21:13:48 [PicGo INFO] 图片信息:[{"fileName":"春季研学3.webp","extname":".webp","height":2268,"width":4032}] 
2024-06-26 21:13:48 [PicGo INFO] Before upload 
2024-06-26 21:13:48 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-06-26 21:13:48 [PicGo INFO] Uploading... Current uploader is [chevereto] 
2024-06-26 21:13:48 [PicGo WARN] failed 
2024-06-26 21:13:48 [PicGo ERROR] {
  "method": "POST",
  "url": "https://mysite.com/api/1/upload/",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "No key provided",
        "code": 100
      },
      "status_txt": "Bad Request"
    }
  }
} 
2024-06-26 21:13:48 [PicGo ERROR] {
  "method": "POST",
  "url": "https://mysite.com/api/1/upload/",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "No key provided",
        "code": 100
      },
      "status_txt": "Bad Request"
    }
  }
} 
2024-06-26 21:15:24 [PicGo INFO] Before transform 
2024-06-26 21:15:24 [PicGo INFO] Transforming... Current transformer is [compress] 
2024-06-26 21:15:24 [PicGo INFO] 压缩:image2webp 
2024-06-26 21:15:24 [PicGo INFO] 图片地址:/Users/name/Desktop/春季研学3.jpg 
2024-06-26 21:15:24 [PicGo INFO] 图片信息:{"fileName":"春季研学3.jpg","extname":".jpg"} 
2024-06-26 21:15:24 [PicGo INFO] Image2WebP 压缩开始 
2024-06-26 21:15:24 [PicGo INFO] 获取本地图片 
2024-06-26 21:15:24 [PicGo INFO] 转换图片为WebP 
2024-06-26 21:15:25 [PicGo INFO] Image2WebP 压缩成功 
2024-06-26 21:15:25 [PicGo INFO] 图片信息:[{"fileName":"春季研学3.webp","extname":".webp","height":2268,"width":4032}] 
2024-06-26 21:15:25 [PicGo INFO] Before upload 
2024-06-26 21:15:25 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-06-26 21:15:25 [PicGo INFO] Uploading... Current uploader is [chevereto] 
2024-06-26 21:15:25 [PicGo WARN] failed 
2024-06-26 21:15:25 [PicGo ERROR] {
  "method": "POST",
  "url": "https://mysite.com/api/1/upload",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "No key provided",
        "code": 100
      },
      "status_txt": "Bad Request"
    }
  }
} 
2024-06-26 21:15:25 [PicGo ERROR] {
  "method": "POST",
  "url": "https://mysite.com/api/1/upload",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "No key provided",
        "code": 100
      },
      "status_txt": "Bad Request"
    }
  }
} 
2024-06-26 21:16:18 [PicGo INFO] Before transform 
2024-06-26 21:16:18 [PicGo INFO] Transforming... Current transformer is [compress] 
2024-06-26 21:16:18 [PicGo INFO] 压缩:image2webp 
2024-06-26 21:16:18 [PicGo INFO] 图片地址:/Users/name/Desktop/春季研学3.jpg 
2024-06-26 21:16:18 [PicGo INFO] 图片信息:{"fileName":"春季研学3.jpg","extname":".jpg"} 
2024-06-26 21:16:18 [PicGo INFO] Image2WebP 压缩开始 
2024-06-26 21:16:18 [PicGo INFO] 获取本地图片 
2024-06-26 21:16:18 [PicGo INFO] 转换图片为WebP 
2024-06-26 21:16:19 [PicGo INFO] Image2WebP 压缩成功 
2024-06-26 21:16:19 [PicGo INFO] 图片信息:[{"fileName":"春季研学3.webp","extname":".webp","height":2268,"width":4032}] 
2024-06-26 21:16:19 [PicGo INFO] Before upload 
2024-06-26 21:16:19 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-06-26 21:16:19 [PicGo INFO] Uploading... Current uploader is [chevereto] 
2024-06-26 21:16:20 [PicGo WARN] failed 
2024-06-26 21:16:20 [PicGo ERROR] {
  "method": "POST",
  "url": "https://mysite.com/api/1/upload",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "No key provided",
        "code": 100
      },
      "status_txt": "Bad Request"
    }
  }
} 
2024-06-26 21:16:20 [PicGo ERROR] {
  "method": "POST",
  "url": "https://mysite.com/api/1/upload",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "No key provided",
        "code": 100
      },
      "status_txt": "Bad Request"
    }
  }
}

**Comment by Molunerfinn** [comment]
插件相关的图床请去插件仓库反馈
