### ISSUE TITLE
[Bug]: 启动无反应，任务栏也没有

### ISSUE THREAD

**Issue by ToTryEveryThing** [Molunerfinn/PicGo#1264]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

- win11
- 启动无反应
- 任务栏会短暂存在，点击后消失，无反应
- 任务管理器中存在
-  这个时候会让我的浏览器和win11 操作特卡
- 卸载之后才有好转

![image](https://github.com/user-attachments/assets/eca0aaa8-60dc-42d2-bd89-7f6ea21ea8dc)

### 相关日志 | Logs

2024-07-16 16:01:58 [PicGo INFO] [PicGo Server] is listening at 36677 
2024-07-16 16:10:31 [PicGo INFO] [PicGo Server] is listening at 36677 

2024-07-16 14:49:15 [PicGo INFO] Before transform
2024-07-16 14:49:15 [PicGo INFO] Transforming...
2024-07-16 14:49:15 [PicGo INFO] Before upload
2024-07-16 14:49:15 [PicGo INFO] Uploading...
2024-07-16 14:49:15 [PicGo WARN] failed
2024-07-16 14:49:15 [PicGo ERROR] Error: Can't find smms config, please provide api token, see https://sm.ms/home/apitoken
------Error Stack Begin------
Error: Can't find smms config, please provide api token, see https://sm.ms/home/apitoken
    at Object.handle (C:\Users\84929\AppData\Roaming\Typora\picgo\win64\node_modules\picgo\dist\src\plugins\uploader\smms.js:26:15)
    at Lifecycle.doUpload (C:\Users\84929\AppData\Roaming\Typora\picgo\win64\node_modules\picgo\dist\src\core\Lifecycle.js:70:24)
    at Lifecycle.start (C:\Users\84929\AppData\Roaming\Typora\picgo\win64\node_modules\picgo\dist\src\core\Lifecycle.js:21:24)
    at async PicGo.upload (C:\Users\84929\AppData\Roaming\Typora\picgo\win64\node_modules\picgo\dist\src\core\PicGo.js:156:13)
    at async Command.<anonymous> (C:\Users\84929\AppData\Roaming\Typora\picgo\win64\node_modules\picgo\dist\src\plugins\commander\upload.js:29:13)
-------Error Stack End-------

**Comment by ToTryEveryThing** [comment]
还一个提示
![image](https://github.com/user-attachments/assets/bbeeee7d-41c0-46fd-957d-e833e4a78009)

**Comment by ToTryEveryThing** [comment]
我又尝试了 安装在C盘 这次可以正常运行了😂😂

**Comment by Molunerfinn** [comment]
你自己是否有自定义的配置文件路径，路径出错了，导致 picgo 无法起来

也有可能是权限不够，导致一直在启动之前读取配置文件读不到，然后就起不来。
