### ISSUE TITLE
[Bug]: 使用smms图床一直无法上传

### ISSUE THREAD

**Issue by zyh778** [Molunerfinn/PicGo#1282]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

一直无法上传图片，查阅日志发错误

### 相关日志 | Logs

-------Error Stack End------- 
2024-10-12 18:52:20 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (E:\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (E:\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (E:\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (E:\picgo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71624)
    at async Object.upload (E:\picgo\resources\app.asar\background.js:2:653584)
    at async E:\picgo\resources\app.asar\background.js:2:655435
    at async Bn (E:\picgo\resources\app.asar\background.js:2:655267)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
配了备用域名了吗？smms本体域名需要挂代理上传

**Comment by Molunerfinn** [comment]
配置界面看下smms的配置

**Comment by zyh778** [comment]
![image](https://github.com/user-attachments/assets/6758b814-0e9a-40e4-becb-e576ecd4a454)
zhe这里配置了，也不行，直接挂梯子也没用

**Comment by Molunerfinn** [comment]
日志给完整一点。有啥插件吗

**Comment by Molunerfinn** [comment]
直接挂梯子不一定可以。你可以尝试在picgo配置里配一下上传代理

**Comment by zyh778** [comment]
没有用什么插件，我先配置一下试试，谢谢

**Comment by zyh778** [comment]
你好，我刚刚安装了新的2.4.0的beta8版本后并进行了配置从而解决了问题，感谢帮助

**Comment by Molunerfinn** [comment]
ok
