### ISSUE TITLE
[求助]:  picgo amazon s3 uploader  插件安装成功，床列表里没有，刷新后又显示未安装状态！

### ISSUE THREAD

**Issue by tmdos** [Molunerfinn/PicGo#1285]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v24.0-beta

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

 picgo amazon s3 uploader  插件安装成功，图床列表里没有，刷新后又显示未安装状态！
![1](https://github.com/user-attachments/assets/67b267bd-2ea4-49c0-82b1-a2cf794739c3)
![2](https://github.com/user-attachments/assets/70d10b2e-64dd-4c7c-b7ff-40c5b0ebcf04)

### 相关日志 | Logs

-------Error Stack End------- 
2024-10-23 01:06:10 [PicGo INFO] [PicGo Server] shutdown 
2024-10-23 01:12:33 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module 'peek-readable'
Require stack:
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\ReadStreamTokenizer.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\core.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\index.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\file-type\index.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\utils.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\uploader.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\index.js
- D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js
- D:\Program Files\PicGo\resources\app.asar\index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js:4:25)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
-------Error Stack End------- 
2024-10-23 01:12:33 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] 
2024-10-23 01:12:33 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] successfully 
2024-10-23 01:17:20 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module 'peek-readable'
Require stack:
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\ReadStreamTokenizer.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\core.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\index.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\file-type\index.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\utils.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\uploader.js
- C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\index.js
- D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js
- D:\Program Files\PicGo\resources\app.asar\index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js:4:25)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
-------Error Stack End------- 
2024-10-23 01:17:20 [PicGo SUCCESS] 插件安装成功

**Comment by tmdos** [comment]
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js:4:25)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\ReadStreamTokenizer.js:4:29)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\core.js:4:31)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\index.js:5:14)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\file-type\index.js:2:17)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\utils.js:10:21)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\uploader.js:10:17)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\index.js:5:36)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Nt.getPlugin (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:43919)
    at Nt.registerPlugin (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:43042)
    at Nt.load (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:42716)
    at $t.init (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:73680)
    at new $t (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:72925)
    at D:\Program Files\PicGo\resources\app.asar\index.js:2:683957
    at D:\Program Files\PicGo\resources\app.asar\index.js:2:734774
    at Object.<anonymous> (D:\Program Files\PicGo\resources\app.asar\index.js:2:734778)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (node:electron/js2c/browser_init:193:3197)
    at Object../lib/browser/init.ts (node:electron/js2c/browser_init:193:3401)
    at __webpack_require__ (node:electron/js2c/browser_init:1:128)
    at node:electron/js2c/browser_init:1:1200
    at node:electron/js2c/browser_init:1:1267
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
-------Error Stack End------- 
2024-10-23 01:34:17 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] 
2024-10-23 01:34:17 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] successfully 
2024-10-23 01:36:02 [PicGo ERROR] 
------Error Stack Begin------
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Administrator\node_modules\peek-readable\lib\index.js from C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js not supported.
Instead change the require of index.js in C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js to a dynamic import() which is available in all CommonJS modules.
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js:4:25)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\ReadStreamTokenizer.js:4:29)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\core.js:4:31)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\index.js:5:14)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\file-type\index.js:2:17)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\utils.js:10:21)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\uploader.js:10:17)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\index.js:5:36)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Nt.getPlugin (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:43919)
    at Nt.registerPlugin (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:43042)
    at D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:55490
    at Array.forEach (<anonymous>)
    at Rt.install (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:55455)
    at async IpcMainImpl.<anonymous> (D:\Program Files\PicGo\resources\app.asar\index.js:2:710584)
-------Error Stack End------- 
2024-10-23 01:36:02 [PicGo SUCCESS] 插件安装成功

**Comment by Molunerfinn** [comment]
报错很明显了 这个模块不存在。所以picgo无法把这个插件运行起来。请去插件仓库反馈

**Comment by caibimiaokong** [comment]
我也遇到这个问题了

**Comment by caibimiaokong** [comment]
Piclist可正常使用

**Comment by MugenLee** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)
> 
> ### PicGo的版本 | PicGo Version
> v24.0-beta
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> picgo amazon s3 uploader 插件安装成功，图床列表里没有，刷新后又显示未安装状态！ ![1](https://private-user-images.githubusercontent.com/179437083/378953246-67b267bd-2ea4-49c0-82b1-a2cf794739c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4Mjc5MDcsIm5iZiI6MTczNTgyNzYwNywicGF0aCI6Ii8xNzk0MzcwODMvMzc4OTUzMjQ2LTY3YjI2N2JkLTJlYTQtNDljMC04MmIxLWEyY2Y3OTQ3MzljMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDIwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzRjYTcwZWZlMTIwNjczY2JlZjkzMzgzNWM0MjI0NTYxOTJiZTRlNzYwODllYWU0Mjk3YTFmMzNjZGM1OTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.80ND4wGqBvAI9Lb6BDSumPQvHlqeR_JEP-kmlmMBV4U) ![2](https://private-user-images.githubusercontent.com/179437083/378953277-70d10b2e-64dd-4c7c-b7ff-40c5b0ebcf04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4Mjc5MDcsIm5iZiI6MTczNTgyNzYwNywicGF0aCI6Ii8xNzk0MzcwODMvMzc4OTUzMjc3LTcwZDEwYjJlLTY0ZGQtNGM3Yy1iN2ZmLTQwYzViMGViY2YwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDIwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWQwODBmNTg1YTE2MWRlNjM4ZGFlYzQ4MmJkN2E1MWE2YjRmOThlYzBlYzM2YTA4OGM5MjBjOTY5M2NiODgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kxPGPOi2V2L65Nbslno774AD8kNf2DU4E9xTXVwFk1c)
> 
> ### 相关日志 | Logs
> -------Error Stack End------- 2024-10-23 01:06:10 [PicGo INFO] [PicGo Server] shutdown 2024-10-23 01:12:33 [PicGo ERROR] ------Error Stack Begin------ Error: Cannot find module 'peek-readable' Require stack:
> 
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\ReadStreamTokenizer.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\core.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\index.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\file-type\index.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\utils.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\uploader.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\index.js
> * D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js
> * D:\Program Files\PicGo\resources\app.asar\index.js
> * at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
>   at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
>   at Module._load (node:internal/modules/cjs/loader:785:27)
>   at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
>   at Module.require (node:internal/modules/cjs/loader:1012:19)
>   at require (node:internal/modules/cjs/helpers:94:18)
>   at Object. (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js:4:25)
>   at Module._compile (node:internal/modules/cjs/loader:1116:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
>   at Module.load (node:internal/modules/cjs/loader:988:32)
>   -------Error Stack End-------
>   2024-10-23 01:12:33 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P]
>   2024-10-23 01:12:33 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] successfully
>   2024-10-23 01:17:20 [PicGo ERROR]
>   ------Error Stack Begin------
>   Error: Cannot find module 'peek-readable'
>   Require stack:
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\ReadStreamTokenizer.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\core.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\index.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\file-type\index.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\utils.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\uploader.js
> * C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-s3\dist\index.js
> * D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js
> * D:\Program Files\PicGo\resources\app.asar\index.js
> * at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
>   at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
>   at Module._load (node:internal/modules/cjs/loader:785:27)
>   at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
>   at Module.require (node:internal/modules/cjs/loader:1012:19)
>   at require (node:internal/modules/cjs/helpers:94:18)
>   at Object. (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\strtok3\lib\AbstractTokenizer.js:4:25)
>   at Module._compile (node:internal/modules/cjs/loader:1116:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
>   at Module.load (node:internal/modules/cjs/loader:988:32)
>   -------Error Stack End-------
>   2024-10-23 01:17:20 [PicGo SUCCESS] 插件安装成功

我也遇到了这个问题，请问解决了么，是如何解决的呢？  T T

**Comment by castock79** [comment]
一样的问题，不知道怎么解决。尝试了好多个版本的Node.js都不行。
