### ISSUE TITLE
[Bug]: 莫名其妙的报错，代码实在是看不懂。

### ISSUE THREAD

**Issue by jinzhao-data** [Molunerfinn/PicGo#1290]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

在obsidian 报错，里面只显示了‘upload error’‘。看了以picgo的日志，查阅了google和chatgpt，都无法解决。

### 相关日志 | Logs

2024-11-17 18:04:03 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of null (reading 'startsWith')
    at se (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:2008)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:41422
    at Array.map (<anonymous>)
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:41329)
    at je.doTransform (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19338)
    at je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18563)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74893)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687298)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690047)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
错误日志给完整一点？另外你用的是什么图床？ 什么配置呢？

**Comment by jinzhao-data** [comment]
好像不是picgo的问题，
1. 单独使用picgo可以上传图片
2. obsidian中用微信截图到剪贴板， 然后 ctr v 是可以识别，并上传
唯独把本地图片拖到 obsidian编辑区，就会报错。

**Comment by Molunerfinn** [comment]
那请去obsidian反馈
