### ISSUE TITLE
[Bug]: upload error

### ISSUE THREAD

**Issue by jinzhao-data** [Molunerfinn/PicGo#1292]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

1. obsidian 拖拽上传
2. 
![image](https://github.com/user-attachments/assets/39e4c65c-ce55-4cca-92eb-e96ed595aba7)

3. 
![image](https://github.com/user-attachments/assets/bffd2379-3758-4254-a7cd-542484cfdac0)

### 相关日志 | Logs

2024-11-19 14:01:20 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of null (reading 'startsWith')
    at se (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:1964)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:37193
    at Array.map (<anonymous>)
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:37164)
    at $e.doTransform (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:16702)
    at $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15927)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
-------Error Stack End------- 
2024-11-19 14:01:20 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
参考前序 issue，请去ob反馈

**Comment by jinzhao-data** [comment]
picgo的权限问题，ob 1.74版本不给本地图片文件夹访问权限会有同样错误，给了权限就没问题。ob 1.77 在拖拽的过程中，picgo没有权限申请的对话了。

**Comment by Molunerfinn** [comment]
权限申请对话框不是 picgo 提供的功能 是系统级别的。如果你没有提供权限 那自然无法防问
