### ISSUE TITLE
[Bug]: Mac 配置正确上传失败

### ISSUE THREAD

**Issue by Rclurn** [Molunerfinn/PicGo#1298]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

无论如何上传都是失败

### 相关日志 | Logs

------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17198)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
同样的问题之前的issue出现过无数次 请自行查看。
