### ISSUE TITLE
PicGo2.1.2上传阿里云OSS失败

### ISSUE THREAD

**Issue by li-xiaojun** [Molunerfinn/PicGo#259]
## 问题类型
Bug：使用PicGo2.1.2版本，按照文档配置好的阿里云OSS，但是仍然上传失败，提示说请检查您的配置项是否正确。

## PicGo的相关信息
window平台，PicGo2.1.2

## 问题重现

![image](https://user-images.githubusercontent.com/4426715/57430629-deb0c900-7262-11e9-8eb7-d27e5ed50867.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/57430627-dd7f9c00-7262-11e9-9840-7eb4ae789292.png)
这一项填错了，好好看看文档吧。
同样的issue:https://github.com/Molunerfinn/PicGo/issues/254

**Comment by li-xiaojun** [comment]
@Molunerfinn 都试了，都不行
最开始就是：`oss-cn-beijing`但也不行，我就试试带域名，现在是2个都不行

**Comment by Molunerfinn** [comment]
@li-xiaojun 首先肯定不是 `oss-cn-beijing.aliyuncs.com` 其余的就打开你的配置文件，看看配置文件里具体项是否有多空格之类的错误。

我这边测试没问题- -，不是PicGo的问题，好好检查配置吧。PicGo的阿里云用户有很多，如果PicGo本身出问题了，那issue区早就炸锅了

**Comment by Molunerfinn** [comment]
以及你可以看看日志文件：
![image](https://user-images.githubusercontent.com/12621342/57432030-3bae7e00-7267-11e9-9a8a-d286e58a4106.png)
看看报了什么错

**Comment by li-xiaojun** [comment]
日志内容如下：
```
2019-05-09 14:35:25 [PicGo INFO] Before transform
2019-05-09 14:35:25 [PicGo INFO] Transforming...
2019-05-09 14:35:25 [PicGo INFO] Before upload
2019-05-09 14:35:25 [PicGo INFO] Uploading...
2019-05-09 14:35:25 [PicGo ERROR] StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  <Code>SignatureDoesNotMatch</Code>\n  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>\n  <RequestId>5CD3CA2DCF4DC17A372D2A22</RequestId>\n  <HostId>lxj-markdown-image.oss-cn-beijing.aliyuncs.com</HostId>\n  <OSSAccessKeyId>LTAIlG6Z2JZ2bUBL</OSSAccessKeyId>\n  <SignatureProvided>cjhIJF1/Z1g069JS/D0zYX7hRmY=</SignatureProvided>\n  <StringToSign>PUT\n\nimage/png\nThu, 09 May 2019 06:35:25 GMT\n/lxj-markdown-image/project_step1.png</StringToSign>\n  <StringToSignBytes>50 55 54 0A 0A 69 6D 61 67 65 2F 70 6E 67 0A 54 68 75 2C 20 30 39 20 4D 61 79 20 32 30 31 39 20 30 36 3A 33 35 3A 32 35 20 47 4D 54 0A 2F 6C 78 6A 2D 6D 61 72 6B 64 6F 77 6E 2D 69 6D 61 67 65 2F 70 72 6F 6A 65 63 74 5F 73 74 65 70 31 2E 70 6E 67 </StringToSignBytes>\n</Error>\n"
------Error Stack Begin------
StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  <Code>SignatureDoesNotMatch</Code>\n  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>\n  <RequestId>5CD3CA2DCF4DC17A372D2A22</RequestId>\n  <HostId>lxj-markdown-image.oss-cn-beijing.aliyuncs.com</HostId>\n  <OSSAccessKeyId>LTAIlG6Z2JZ2bUBL</OSSAccessKeyId>\n  <SignatureProvided>cjhIJF1/Z1g069JS/D0zYX7hRmY=</SignatureProvided>\n  <StringToSign>PUT\n\nimage/png\nThu, 09 May 2019 06:35:25 GMT\n/lxj-markdown-image/project_step1.png</StringToSign>\n  <StringToSignBytes>50 55 54 0A 0A 69 6D 61 67 65 2F 70 6E 67 0A 54 68 75 2C 20 30 39 20 4D 61 79 20 32 30 31 39 20 30 36 3A 33 35 3A 32 35 20 47 4D 54 0A 2F 6C 78 6A 2D 6D 61 72 6B 64 6F 77 6E 2D 69 6D 61 67 65 2F 70 72 6F 6A 65 63 74 5F 73 74 65 70 31 2E 70 6E 67 </StringToSignBytes>\n</Error>\n"
    at new StatusCodeError (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (E:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (E:\PicGo\resources\app.asar\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (E:\PicGo\resources\app.asar\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
-------Error Stack End-------

```

**Comment by Molunerfinn** [comment]
`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

所以好好检查一下你的KEYID和KEYSECRET吧

**Comment by li-xiaojun** [comment]
@Molunerfinn 
好了，阿里云的问题。

**Comment by Molunerfinn** [comment]
😄 OK

**Comment by Jaya0455** [comment]
今天碰到同样的问题，RAM访问控制里面生成的Accesskey一定要先复制到记事本。一开始没复制，直接cv到picgo里面，就报错了。
The request signature we calculated does not match the signature you provided. Check your key and signing method.
这个错误就说明id和secret有误。

**Comment by beyond24** [comment]
> 今天碰到同样的问题，RAM访问控制里面生成的Accesskey一定要先复制到记事本。一开始没复制，直接cv到picgo里面，就报错了。 The request signature we calculated does not match the signature you provided. Check your key and signing method. 这个错误就说明id和secret有误。

感谢，解决了！问题在于阿里云那个复制按钮，复制下来是两项信息，key+secret，单独复制后面的secret就可以了。
