### ISSUE TITLE
PicGo 开发计划

### ISSUE THREAD

**Issue by Molunerfinn** [Molunerfinn/PicGo#265]
开发计划一直可以在 [projects](https://github.com/Molunerfinn/PicGo/projects) 列表里找到。

本issue的目的主要是方便给大家看看 PicGo 未来版本的目标。另外由于本人还是在校生，所以更新版本的时间不定，有空就多写写新的Feature，没空的时候就会以修Bug为主，请谅解。

## 2.x 版本计划

> 计划列表只是暂时的，计划不分先后。下一个版本的计划科查看[projects](https://github.com/Molunerfinn/PicGo/projects)。

| TODO项                        | 说明                                                                                | 优先级 | 状态 |
| ------------------------------ | ------------------------------------------------------------------------------------- | ------ | ------ |
| 快捷键系统                | 完善快捷键系统，以及插件也能使用快捷键                             | ⭐️⭐️⭐️ | 未开始 |
| 图片列表与配置分离    | 配置项依旧使用JSON，历史记录图片将使用SQLite存储                   | ⭐️⭐️⭐️ | 未开始 |
| macOS剪贴板上传图片bug  | 由于屏幕颜色描述文件导致的上传剪贴板图片bug                       | ⭐️⭐️ | 已完成 |
| 配置项alias别名显示     | 插件配置项目前都是英文，通过alias选项能够显示中文（以后也可以实现i18n） | ⭐️⭐️ | 已完成 |
| 批量上传图片速度优化 | 改进现有批量上传图片逻辑                                                  | ⭐️⭐️ | 未开始 |
| 界面重构                   | 现有界面太Web化，将其重构成更像一个桌面应用                       | ⭐️⭐️ | 未开始 |
| i18n国际化                  | 国际化语言自适应配置                                                        | ⭐️⭐️ | 未开始 |
| Windows10 Fluent Design风格  | Windows10 窗体半透明效果，力求实现macOS版本的效果                    | ⭐️ | 未开始 |
| Typora支持                   | 期望Typora接入PicGo，相关[issue](https://github.com/typora/typora-issues/issues/2476) | ⭐️ | 未知 |
| 白色皮肤（甚至自定义皮肤） | 增加色彩、背景色可定制化                                                  | ⭐️ | 未开始 |
| guiApi增强，自定义窗口、页面等 | 增强guiApi，加入诸如进度条、自定义显示窗口或者页面等           | ⭐️ | 未开始 |

如果你也有一些好的想法，欢迎在本issue里提出。 **不过需要注意的是，如果你的想法能用插件实现，请去[插件讨论区](https://github.com/Molunerfinn/PicGo/issues/222)讨论。**

如果PicGo对你有帮助，欢迎点个star~如果觉得它很好用，也欢迎请我喝杯咖啡，赞助二维码在仓库的 [README](https://github.com/Molunerfinn/PicGo) 最下方以及PicGo主窗口的左下角~

**Comment by COCO5666** [comment]
路过图床感觉也不错，能否增加一下对路过图床的支持？

**Comment by Molunerfinn** [comment]
@COCO5666 
![image](https://user-images.githubusercontent.com/12621342/60657238-8fae9b00-9e83-11e9-8cf4-9271d695d76d.png)

**Comment by gogobody** [comment]
请问sm.ms图床能支持用户认证吗？新版v2api支持用户自主管理相册

**Comment by Molunerfinn** [comment]
@gogobody v2和v1的api调用差距明显，目前不考虑直接在本体里做支持。可以通过插件来支持。

**Comment by Jecvay** [comment]
图片列表能否直接从桶里面获取一份出来, 现在换台电脑就没了, 除非自己复制配置文件/数据库过去

**Comment by VincentChengzc** [comment]
建议picgo加入账户管理功能。上传的相册可以云同步。

**Comment by Molunerfinn** [comment]
@VincentChengzc 这块以后会以github私有仓库作为配置存储来实现，不过也是通过插件来实现。另外我是学生没有收入来源，自建服务器来做用户账号存储是不考虑的。谢谢

**Comment by Jecvay** [comment]
> @VincentChengzc 这块以后会以github私有仓库作为配置存储来实现，不过也是通过插件来实现。另外我是学生没有收入来源，自建服务器来做用户账号存储是不考虑的。谢谢

不用云同步啊, 从桶拿个列表出来, 保存到本地.

**Comment by Molunerfinn** [comment]
@Jecvay 有的图床是没有所谓的存储桶的概念的。

**Comment by VincentChengzc** [comment]
@Jecvay 其实从用户的角度来说是最好简便处理。是能有多简单就多简单处理。@Molunerfinn 其實要是從事開發行業我多多少少建议自己租个服务器vultr 等这些都可以很便宜入手

**Comment by objcoding** [comment]
希望支持gitee，毕竟免费的图床才是大众需求，github太慢了，经常图裂。脑壳疼

**Comment by Molunerfinn** [comment]
> 希望支持gitee，毕竟免费的图床才是大众需求，github太慢了，经常图裂。脑壳疼

首先：
![image](https://user-images.githubusercontent.com/12621342/71403647-51907800-266b-11ea-9cb7-9a1994b0ee35.png)

其次，已经有插件支持gitee图床。

https://github.com/zWingz/picgo-plugin-github-plus

https://github.com/lizhuangs/picgo-plugin-gitee-uploader

伸手党也不是这样吧？

**Comment by objcoding** [comment]
> > 希望支持gitee，毕竟免费的图床才是大众需求，github太慢了，经常图裂。脑壳疼
> 
> 首先：
> ![image](https://user-images.githubusercontent.com/12621342/71403647-51907800-266b-11ea-9cb7-9a1994b0ee35.png)
> 
> 其次，已经有插件支持gitee图床。
> 
> https://github.com/zWingz/picgo-plugin-github-plus
> 
> https://github.com/lizhuangs/picgo-plugin-gitee-uploader
> 
> 伸手党也不是这样吧？

你说得在理，但方式不对，你的话很难听，做开源不是这么回答用户方的。

**Comment by itgoyo** [comment]
> > > 希望支持 gitee，毕竟免费的图床才是大众需求，github 太慢了，经常图裂。脑壳疼
> > 
> > 
> > 首先：
> > ![image](https://user-images.githubusercontent.com/12621342/71403647-51907800-266b-11ea-9cb7-9a1994b0ee35.png)
> > 其次，已经有插件支持 gitee 图床。
> > https://github.com/zWingz/picgo-plugin-github-plus
> > https://github.com/lizhuangs/picgo-plugin-gitee-uploader
> > 伸手党也不是这样吧？
> 
> 你说得在理，但方式不对，你的话很难听，做开源不是这么回答用户方的。

不发表任何意见，但是有一点我要说的，每当我遇到什么问题点时候都会先把README好好看完，如果项目有wiki的我会把wiki认真看完，最后在issue里面搜索我出现问题点关键字看看有没有前人出现问题和我一样提出了类似的issue。如果都没有我会先把可能的原因分析一遍然后再问作者，项目是开源的，但是作者没有必要对任何人负责，只有你自己才能对自己负责。遇到问题不要马上就丢出来，问怎么怎么不行，怎么怎么没有这个功能，因为开源也要花精力的也要用时间去做。就比如刚刚我看到picgo2.2.0出现了快速截图上传的功能，但是我在快捷键里面找不到设置的地方，然后看到作者的图片里面有一个图片上出现了quick的字样，然后我自己去插件的地方搜了一下quick，果然出现了这个功能。碰巧路过多讲了几句，大家不要在意。

**Comment by Chichele** [comment]
我最近关注到一个CDN叫jsDeliver，它可以为github所有库的文件提供国内国外的CDN服务；换句话说只要你把文件传到github repo上，然后就能通过它的链接去访问cdn，例如：https://cdn.jsdelivr.net/gh/Chichele/trackerslist@master/README.md

我的想法是在PicGo的github图床上可以直接增加输出这个链接，这样可以更好满足“图床”这个概念。

**Comment by yf-9186** [comment]
> 
> 
> 我最近关注到一个CDN叫jsDeliver，它可以为github所有库的文件提供国内国外的CDN服务；换句话说只要你把文件传到github repo上，然后就能通过它的链接去访问cdn，例如：https://cdn.jsdelivr.net/gh/Chichele/trackerslist@master/README.md
> 
> 我的想法是在PicGo的github图床上可以直接增加输出这个链接，这样可以更好满足“图床”这个概念。

目前可以配置自定义域名，给你看下我的配置
![图片](https://user-images.githubusercontent.com/38492750/72228973-366bb500-35e6-11ea-86c1-159c5c94ba80.png)

**Comment by Chichele** [comment]
> > 我最近关注到一个CDN叫jsDeliver，它可以为github所有库的文件提供国内国外的CDN服务；换句话说只要你把文件传到github repo上，然后就能通过它的链接去访问cdn，例如：https://cdn.jsdelivr.net/gh/Chichele/trackerslist@master/README.md
> > 我的想法是在PicGo的github图床上可以直接增加输出这个链接，这样可以更好满足“图床”这个概念。
> 
> 目前可以配置自定义域名，给你看下我的配置
> ![图片](https://user-images.githubusercontent.com/38492750/72228973-366bb500-35e6-11ea-86c1-159c5c94ba80.png)

按你的描述，成功！感谢！
主要是我之前没理解这个“自定义域名”的用途。

**Comment by shadowfish07** [comment]
可以添加对linux服务器的支持吗？我想要用PicGo-Server做和网站融合的操作，但是发现linux安装不了....查了很多资料还是失败放弃了，好像现在的linux安装包不能用于没有图形界面的linux系统

**Comment by Molunerfinn** [comment]
> 可以添加对linux服务器的支持吗？我想要用PicGo-Server做和网站融合的操作，但是发现linux安装不了....查了很多资料还是失败放弃了，好像现在的linux安装包不能用于没有图形界面的linux系统

那你应该去用[PicGo-Core](https://github.com/PicGo/PicGo-Core)...，自己写一个web服务去调PicGo-Core的上传就行了。

**Comment by zcxzzz** [comment]
你好，我下载了2.2.2forwindows的exe，安装之前先去VirusTotal扫了一下，探测到了 Bkav HW32.Packed.这个是正常的吗

**Comment by Molunerfinn** [comment]
> 你好，我下载了2.2.2forwindows的exe，安装之前先去VirusTotal扫了一下，探测到了 Bkav HW32.Packed.这个是正常的吗

不知道这是啥东西，可能是electron-builder的构建产物，如果不放心可以自行构建

**Comment by schrodingercatss** [comment]
希望能增加一个同步功能，这样在不同设备下就能方便的切换使用了。

**Comment by Molunerfinn** [comment]
> 希望能增加一个同步功能，这样在不同设备下就能方便的切换使用了。

这个会通过插件实现。未来会提供官方的同步插件

**Comment by xiang578** [comment]
> > 希望能增加一个同步功能，这样在不同设备下就能方便的切换使用了。
> 
> 这个会通过插件实现。未来会提供官方的同步插件

十分期待同步插件

**Comment by FFRaycoder** [comment]
@Molunerfinn i18n国际化能否使用vue-i18n？

**Comment by Molunerfinn** [comment]
> @Molunerfinn i18n国际化能否使用vue-i18n？

PicGo这边已经有官方的[i18n](https://github.com/PicGo/i18n)插件了，只是还没进行开发。

**Comment by blackbox079** [comment]
imgur 图床能否设置cdn？

**Comment by dingmingyang** [comment]
希望相册的删除功能可以完善下，在提示确认提示是可以让用户勾选☑️是否删除图片服务器的源文件。像七牛也是支持删除资源接口调用的。

**Comment by ZonuyCode** [comment]
2020-10-30 15:34:09 [PicGo ERROR] StatusCodeError: 404 - {"message":"Branch master not found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Branch master not found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------
![image](https://user-images.githubusercontent.com/57613482/97676895-54020080-1acc-11eb-9e7c-342d7a890d17.png)
一直说上传失败，请问一下是哪里出问题了？要怎么修改？

**Comment by ZonuyCode** [comment]
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'D:\Program Files (x86)\PicGo\https:\cdn.jsdelivr.net\gh\ZonuyCode\myhexo\img\安装1.png'
-------Error Stack End-------
2020-10-30 20:14:32 [PicGo INFO] [PicGo Server] shutdown
2020-10-30 20:15:17 [PicGo INFO] [PicGo Server] is listening at 36677
2020-10-30 20:28:00 [PicGo INFO] [PicGo Server] shutdown
2020-10-30 20:31:24 [PicGo INFO] [PicGo Server] is listening at 36677
2020-10-30 20:32:10 [PicGo INFO] [PicGo Server] shutdown
2020-10-30 21:32:53 [PicGo INFO] [PicGo Server] is listening at 36677
出现这样的一个错误要怎么改？就是图片上传成功但看不到图片
![image](https://user-images.githubusercontent.com/57613482/97725872-a31a5680-1b09-11eb-825d-005590b0a199.png)

**Comment by hlgmup** [comment]
有帐号系统吗，能否给github 添加公共CDN

**Comment by Molunerfinn** [comment]
> 有帐号系统吗，能否给github 添加公共CDN

没有，picgo是纯本地应用。公共CDN自行就可以设置。

**Comment by arobot123** [comment]
软件很好用，点赞！

我的电脑是fedora x64的，也可跑，基本功能都是ok的。作为小白，不知道能支持设置图床吗？默认是sm.ms。另外，附上上传处理的打印信息，请确认是否需要优化，谢谢！

版本: PicGo-2.3.0-beta.5.AppImage
OS：Fedora x86_64

```text
% PicGo-2.3.0-beta.5.AppImage
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[PicGo INFO]: [PicGo Server] is listening at 36677
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: beforeUploadPlugins: renameFn running
[PicGo INFO]: Uploading... Current uploader is [smms]
[PicGo SUCCESS]: 
https://i.loli.net/2021/04/20/aZ7M35TFgz6Pr14.png
(node:18598) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webContents' of null
    at Nt (/tmp/.mount_PicGo-PIkG8v/resources/app.asar/background.js:16:36627)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:18598) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webContents' of null
    at Nt (/tmp/.mount_PicGo-PIkG8v/resources/app.asar/background.js:16:36627)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:18598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Molunerfinn** [comment]
> 软件很好用，点赞！
> 
> 
> 
> 我的电脑是fedora x64的，也可跑，基本功能都是ok的。作为小白，不知道能支持设置图床吗？默认是sm.ms。另外，附上上传处理的打印信息，请确认是否需要优化，谢谢！
> 
> 
> 
> 版本: PicGo-2.3.0-beta.5.AppImage
> 
> OS：Fedora x86_64
> 
> 
> 
> ```text
> 
> % PicGo-2.3.0-beta.5.AppImage
> 
> Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
> 
> [PicGo INFO]: [PicGo Server] is listening at 36677
> 
> [PicGo INFO]: Before transform
> 
> [PicGo INFO]: Transforming... Current transformer is [path]
> 
> [PicGo INFO]: Before upload
> 
> [PicGo INFO]: beforeUploadPlugins: renameFn running
> 
> [PicGo INFO]: Uploading... Current uploader is [smms]
> 
> [PicGo SUCCESS]: 
> 
> https://i.loli.net/2021/04/20/aZ7M35TFgz6Pr14.png
> 
> (node:18598) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webContents' of null
> 
>     at Nt (/tmp/.mount_PicGo-PIkG8v/resources/app.asar/background.js:16:36627)
> 
>     at processTicksAndRejections (internal/process/task_queues.js:89:5)
> 
> (node:18598) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webContents' of null
> 
>     at Nt (/tmp/.mount_PicGo-PIkG8v/resources/app.asar/background.js:16:36627)
> 
>     at processTicksAndRejections (internal/process/task_queues.js:89:5)
> 
> (node:18598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> 
> (node:18598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> 
> (node:18598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> (node:18598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> ```

当然支持...用之前先好好看文档吧

**Comment by lbr77** [comment]
建议增加Github图床的多仓库支持
https://github.com/jsdelivr/jsdelivr/pull/18247/files

![image](https://user-images.githubusercontent.com/53066066/116834587-5ff08b80-abf1-11eb-90cb-620e9882714d.png)

**Comment by xinatcg** [comment]
> > @Molunerfinn i18n国际化能否使用vue-i18n？
> 
> PicGo这边已经有官方的[i18n](https://github.com/PicGo/i18n)插件了，只是还没进行开发。

这个 i18n  有相关文档吗？如果有相关文档或者思路，我想帮忙做这个~ 打算在推荐给同事使用，但是需要英文~

**Comment by Molunerfinn** [comment]
> > > @Molunerfinn i18n国际化能否使用vue-i18n？
> > 
> > 
> > PicGo这边已经有官方的[i18n](https://github.com/PicGo/i18n)插件了，只是还没进行开发。
> 
> 这个 i18n 有相关文档吗？如果有相关文档或者思路，我想帮忙做这个~ 打算在推荐给同事使用，但是需要英文~

目前文档就是在 https://github.com/PicGo/i18n 首页的readme里，可以先本地跑一个试试。

如果有兴趣，可以先整理一份目前picgo软件中用到的中文列表，然后对应一份英文列表。

例如

```
// zh.js
{
  UPLOAD_SUCCESS: '上传成功',
  UPLOAD_FAIL: '上传失败',
  // ...
}

// en.js
{
  UPLOAD_SUCCESS: 'Upload success',
  UPLOAD_FAIL: 'Upload fail',
  // ...
}
```

非常欢迎贡献代码 @xinatcg

**Comment by xinatcg** [comment]
> > > > @Molunerfinn i18n国际化能否使用vue-i18n？
> > > 
> > > 
> > > PicGo这边已经有官方的[i18n](https://github.com/PicGo/i18n)插件了，只是还没进行开发。
> > 
> > 
> > 这个 i18n 有相关文档吗？如果有相关文档或者思路，我想帮忙做这个~ 打算在推荐给同事使用，但是需要英文~
> 
> 目前文档就是在 https://github.com/PicGo/i18n 首页的readme里，可以先本地跑一个试试。
> 
> 如果有兴趣，可以先整理一份目前picgo软件中用到的中文列表，然后对应一份英文列表。
> 
> 例如
> 
> ```js
> // zh.js
> {
>   UPLOAD_SUCCESS: '上传成功',
>   UPLOAD_FAIL: '上传失败',
>   // ...
> }
> 
> // en.js
> {
>   UPLOAD_SUCCESS: 'Upload success',
>   UPLOAD_FAIL: 'Upload fail',
>   // ...
> }
> ```
> 
> 非常欢迎贡献代码 @xinatcg

我看了一下 PicGo/i18n , 我看目前有两种使用方法： FileSyncAdapter and ObjectAdapter。如果是 FileSyncAdapter，我看 test 中使用创建的 json，并且是多级结构，比如：
{
  "user": {
    "name": "PicGo",
    "country": "China"
  },
  "report": {
    "singular": "only ${cnt} report",
    "plural": "${cnt} reports"
  }
}

**Comment by xjxxm** [comment]
可以支持私有相册吗？现在必须私有写公开读，在相册才能预览。想当成相册用，支持仅个人可见

**Comment by so1ve** [comment]
> 可以支持私有相册吗？现在必须私有写公开读，在相册才能预览。想当成相册用，支持仅个人可见

那估计就和Picgo没关系了 这个是图床的功能

**Comment by LonelyJupiter** [comment]
Molunerfinn您好，目前配合github使用PicGo非常好用，谢谢开发！提出以下两个建议请考虑：
1、相册界面，打开图片后希望可以滚轮放大。
2、希望可以自定义每张图片的注释，直接用commit message是不是就很好？如果能在相册界面显示注释那就更好了。

再次感谢！

**Comment by xihajun** [comment]
请问能不能指点一下默认文件名是在哪里修改呀，想要自己实现一个识别图片文字然后自动命名的feature，应该实现起来不会很难，不知道有没有可能指导一下具体可能需要修改的位置哈，谢谢这么好用的工具！

**Comment by Molunerfinn** [comment]
> 请问能不能指点一下默认文件名是在哪里修改呀，想要自己实现一个识别图片文字然后自动命名的feature，应该实现起来不会很难，不知道有没有可能指导一下具体可能需要修改的位置哈，谢谢这么好用的工具！

参考文档，可以自行开发插件，你的需求可以在beforeUploadPlugins里修改output的fileName：
https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/cli.html#beforeuploadplugins

**Comment by Betristor** [comment]
可以更改picgo在Mac上的菜单栏图标吗？黑色背景的时候会显得很难看。右数第二个。
![image](https://user-images.githubusercontent.com/55777837/160533718-af8fd639-e60a-4506-8f32-172c1200c110.png)
通体白色，黑色部分留空，应该可以适应不同的显示场景。绝大多数的图标都是这么设计的。

**Comment by leecobaby** [comment]
提个建议：

希望 PicGo 项目支持 文件上传不止一个远程存储，而是能一键上传到多个存储库，如腾讯cos,阿里oss,免费图床等。并建立数据库和哈希索引搜索。 这样做的好处是，一但一个储存节点出现意外无法访问（被薅空了），就可以批量的更改前缀域名或者无缝对接 FreeCDN 项目，来到达高可用，多备份的意图。

当然我有时间也会尝试辅助作者开发此块功能，就不知道作者是否会纳入计划了。

**Comment by Molunerfinn** [comment]
> 可以更改picgo在Mac上的菜单栏图标吗？黑色背景的时候会显得很难看。右数第二个。 ![image](https://user-images.githubusercontent.com/55777837/160533718-af8fd639-e60a-4506-8f32-172c1200c110.png) 通体白色，黑色部分留空，应该可以适应不同的显示场景。绝大多数的图标都是这么设计的。

beta5已经更新

**Comment by Molunerfinn** [comment]
> 提个建议：
> 
> 希望 PicGo 项目支持 文件上传不止一个远程存储，而是能一键上传到多个存储库，如腾讯cos,阿里oss,免费图床等。并建立数据库和哈希索引搜索。 这样做的好处是，一但一个储存节点出现意外无法访问（被薅空了），就可以批量的更改前缀域名或者无缝对接 FreeCDN 项目，来到达高可用，多备份的意图。
> 
> 当然我有时间也会尝试辅助作者开发此块功能，就不知道作者是否会纳入计划了。

有计划，详见https://github.com/Molunerfinn/PicGo/projects/9?query=is%3Aopen+sort%3Aupdated-desc
不过涉及底层核心逻辑的改造，需要我思考一下再搞

**Comment by longdoer** [comment]
能否增加一下对PicGo图床（https://www.picgo.net）的支持？

**Comment by Molunerfinn** [comment]
> 能否增加一下对PicGo图床（[https://www.picgo.net）的支持？](https://www.picgo.net%EF%BC%89%E7%9A%84%E6%94%AF%E6%8C%81%EF%BC%9F)

有插件支持。本体不会做对接。
<img width="788" alt="image" src="https://user-images.githubusercontent.com/12621342/191914592-231ceb36-a911-46d5-9fd1-72a076344ac5.png">

**Comment by longdoer** [comment]
> > > > 希望支持 gitee，毕竟免费的图床才是大众需求，github 太慢了，经常图裂。脑壳疼
> > > 
> > > 
> > > 首先：
> > > ![image](https://user-images.githubusercontent.com/12621342/71403647-51907800-266b-11ea-9cb7-9a1994b0ee35.png)
> > > 其次，已经有插件支持 gitee 图床。
> > > https://github.com/zWingz/picgo-plugin-github-plus
> > > https://github.com/lizhuangs/picgo-plugin-gitee-uploader
> > > 伸手党也不是这样吧？
> > 
> > 
> > 你说得在理，但方式不对，你的话很难听，做开源不是这么回答用户方的。
> 
> 不发表任何意见，但是有一点我要说的，每当我遇到什么问题点时候都会先把README好好看完，如果项目有wiki的我会把wiki认真看完，最后在issue里面搜索我出现问题点关键字看看有没有前人出现问题和我一样提出了类似的issue。如果都没有我会先把可能的原因分析一遍然后再问作者，项目是开源的，但是作者没有必要对任何人负责，只有你自己才能对自己负责。遇到问题不要马上就丢出来，问怎么怎么不行，怎么怎么没有这个功能，因为开源也要花精力的也要用时间去做。就比如刚刚我看到picgo2.2.0出现了快速截图上传的功能，但是我在快捷键里面找不到设置的地方，然后看到作者的图片里面有一个图片上出现了quick的字样，然后我自己去插件的地方搜了一下quick，果然出现了这个功能。碰巧路过多讲了几句，大家不要在意。

可考虑 https://www.picgo.net/

**Comment by velvetflame** [comment]
您好，请问能否添加多个文件夹/相册集的功能，目前所有上传的图片都在一个目录下，软件上也不便管理

**Comment by longdoer** [comment]
> 您好，请问能否添加多个文件夹/相册集的功能，目前所有上传的图片都在一个目录下，软件上也不便管理

Hi,您可以在https://www.picgo.net/ 登录后在右上角菜单选择相册即可创建相册。

**Comment by bevishe** [comment]
你好，请问能否添加一个相册同步云图床已有图片资源的功能？现有的图片只会显示当前设备上传的图片资源，能否开发一个同步的接口，选中之后可以定时同步我们oss上面的图片到相册，可以只显示缩略图和可以复制url即可，平时自己多设备用的比较多，可能需要该功能。同时感谢你们的开源，软件很好用 ！！ 👍👍👍

**Comment by CodeGetters** [comment]
用TS写会不会更爽🥰

**Comment by encorexin** [comment]
希望能够增加 flatpak 安装支持。

**Comment by Boris-code** [comment]
希望存储路径支持表达式、如可以用年月日作为路径的一部分

**Comment by wanwe** [comment]
> > 提个建议：
> 
> > 
> 
> > 希望 PicGo 项目支持 文件上传不止一个远程存储，而是能一键上传到多个存储库，如腾讯cos,阿里oss,免费图床等。并建立数据库和哈希索引搜索。 这样做的好处是，一但一个储存节点出现意外无法访问（被薅空了），就可以批量的更改前缀域名或者无缝对接 FreeCDN 项目，来到达高可用，多备份的意图。
> 
> > 
> 
> > 当然我有时间也会尝试辅助作者开发此块功能，就不知道作者是否会纳入计划了。
> 
> 
> 
> 有计划，详见https://github.com/Molunerfinn/PicGo/projects/9?query=is%3Aopen+sort%3Aupdated-desc
> 
> 不过涉及底层核心逻辑的改造，需要我思考一下再搞

请问这个完成了吗？beta里支持同一个图床多个配置文件，没看到同时上传到多个图床的功能呢

**Comment by iplane787** [comment]
希望能支持备份配置文件到webdav或s3

**Comment by Molunerfinn** [comment]
> 可否将picGo Server 剥离出来成一个单独的项目  ， 这样可以部署在公网的docker上 ，  可以有多个机器通过访问web-UI  或API接口  来上传图片     

你可以直接使用picgo-core 这个包，简单封装一下就能实现
