### ISSUE TITLE
github private repo, 上传报错

### ISSUE THREAD

**Issue by mrdulin** [Molunerfinn/PicGo#272]
## 问题类型

bug report

## PicGo的相关信息

Mac

## 问题重现

配置好github private repo, 上传png图片报错，日志如下：

```bash
2019-05-20 21:20:57 [PicGo INFO] Before transform
2019-05-20 21:20:57 [PicGo INFO] Transforming...
2019-05-20 21:20:57 [PicGo INFO] Before upload
2019-05-20 21:20:57 [PicGo INFO] Uploading...
2019-05-20 21:20:58 [PicGo ERROR] StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
-------Error Stack End-------
```

**Comment by mrdulin** [comment]
问题解决，需要设置仓库名：用户名/仓库名
