### ISSUE TITLE
macOS图片上传失败

### ISSUE THREAD

**Issue by tangyongshuang** [Molunerfinn/PicGo#274]
## 问题类型
选则github图床，剪切板或者是手动上传图片都显示失败

Bug Report
## PicGo的相关信息

macOS Mojave
## 问题重现
各种上传图片失败

**github配置如下：**
![image](https://user-images.githubusercontent.com/41354908/58322220-ec657180-7e52-11e9-97a9-88fce8963e81.png)

**日志信息如下：**
2019-05-24 18:31:47 [PicGo INFO] Before transform
2019-05-24 18:31:47 [PicGo INFO] Before upload
2019-05-24 18:31:47 [PicGo INFO] Uploading...
2019-05-24 18:31:53 [PicGo ERROR] StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#update-a-file"}
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#update-a-file"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
-------Error Stack End-------

## 功能请求

---

**Comment by Molunerfinn** [comment]
你配置错了，查查之前有人提过同样的issue，好好看看文档吧
