### ISSUE TITLE
编译运行失败

### ISSUE THREAD

**Issue by xuange306** [Molunerfinn/PicGo#297]
## 问题类型
  源码编译运行失败

## PicGo的相关信息
mac
node: v8.9.1
picGo: dev 分支源码
## 问题重现

> picgo@2.1.2 dev /Users/zhangzexuan/Documents/gitdoc_zzx/PicGo
> node .electron-vue/dev-runner.js

/Users/zhangzexuan/Documents/gitdoc_zzx/PicGo/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/Users/zhangzexuan/Documents/gitdoc_zzx/PicGo/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/Users/zhangzexuan/Documents/gitdoc_zzx/PicGo/node_modules/electron/index.js:18:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/zhangzexuan/Documents/gitdoc_zzx/PicGo/.electron-vue/dev-runner.js:4:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! picgo@2.1.2 dev: `node .electron-vue/dev-runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the picgo@2.1.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangzexuan/.npm/_logs/2019-06-25T04_44_59_646Z-debug.log

**Comment by Molunerfinn** [comment]
`export ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"`

你这个原因是electron没有下载安装好，请先调整electron源如上再安装运行一遍

**Comment by Molunerfinn** [comment]
请问问题解决了么？你这个是需要访问外网来下载electron的包的，不然无法调试运行

**Comment by Molunerfinn** [comment]
长期无反馈，issue先关了
