### ISSUE TITLE
Window10 RequestError sm.ms图床 上传图片失败

### ISSUE THREAD

**Issue by brakchen** [Molunerfinn/PicGo#302]
## 问题类型

Bug Report

## PicGo的相关信息
Windows 10
PicGo 2.1.2
仅图床 SM.MS
图片大小 4kb
Data.json
```json
{
  "uploaded": [],
  "picBed": {
    "current": "smms",
    "list": [
      {
        "name": "SM.MS图床",
        "type": "smms",
        "visible": true
      },
      {
        "name": "腾讯云COS",
        "type": "tcyun",
        "visible": false
      },
      {
        "name": "微博图床",
        "type": "weibo",
        "visible": false
      },
      {
        "name": "GitHub图床",
        "type": "github",
        "visible": false
      },
      {
        "name": "七牛图床",
        "type": "qiniu",
        "visible": false
      },
      {
        "name": "Imgur图床",
        "type": "imgur",
        "visible": false
      },
      {
        "name": "阿里云OSS",
        "type": "aliyun",
        "visible": false
      },
      {
        "name": "又拍云图床",
        "type": "upyun",
        "visible": false
      }
    ],
    "smms": true
  },
  "settings": {
    "shortKey": {
      "upload": "CommandOrControl+Shift+P"
    },
    "showUpdateTip": true,
    "autoStart": true,
    "rename": false,
    "autoRename": true,
    "uploadNotification": true
  },
  "needReload": false,
  "picgoPlugins": {}
}
```

## 问题重现
浏览了一圈issue好像没发现跟我一样的问题
问题出现在，上传图片的时候不管是剪切板还是直接拖拽图片都会出现一样的error，然后上传失败
```
2019-06-30 19:20:21 [PicGo INFO] Before transform
2019-06-30 19:20:21 [PicGo INFO] Transforming...
2019-06-30 19:20:21 [PicGo INFO] Before upload
2019-06-30 19:20:21 [PicGo INFO] Uploading...
2019-06-30 19:20:21 [PicGo ERROR] RequestError: Error: write EPROTO 3482118584:error:100003e8:SSL routines:OPENSSL_internal:SSLV3_ALERT_CLOSE_NOTIFY:../../third_party/boringssl/src/ssl/tls_record.cc:586:SSL alert number 0

------Error Stack Begin------
RequestError: Error: write EPROTO 3482118584:error:100003e8:SSL routines:OPENSSL_internal:SSLV3_ALERT_CLOSE_NOTIFY:../../third_party/boringssl/src/ssl/tls_record.cc:586:SSL alert number 0

    at new RequestError (D:\application\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\application\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\application\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\application\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (D:\application\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at onwriteError (_stream_writable.js:431:12)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
看上去是HTTPS的问题，应该是SM.MS那边的问题，

**Comment by brakchen** [comment]
应该不是sm.ms的问题，我用MacBook 上传了一下没什么问题：
macos mojave 10.14.5
picgo 2.1.2
图片大小 2kb
仅 sm,ms 图床

**Comment by Molunerfinn** [comment]
我这边的Windows的PicGo测试没问题，可能跟网络有关系，报错是跟HTTPS解析相关的，所以应该跟PicGo本身没啥关系才对

**Comment by brakchen** [comment]
应该跟openssl有关系，我明天测试了以后再来

**Comment by brakchen** [comment]
无法找到问题

**Comment by supbadboy** [comment]
上传失败是为什么    服务端出错，或者图片配置错误
