### ISSUE TITLE
剪切板图片上传提示上传失败，请检查配置和上传的文件

### ISSUE THREAD

**Issue by kollyQAQ** [Molunerfinn/PicGo#305]
问题类型
Bug Report

PicGo的相关信息
MacOS 10.14.5
版本:2.1.2

问题重现
点击选择文件上传没有问题，复制图片后点击剪切板图片上传后报错，提示请检查配置和上传的文件是否符合要求。

使用的是github图床

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/199
![Uploading image.png…]()

**Comment by wrwe3888** [comment]
我默认阿里云，设置检查了很多遍，没有错误，但是一直提示：请检查配置和上传的文件是否符合要求。请问这是怎么回事啊？用的是win10的2.2.2版本。

**Comment by wrwe3888** [comment]
同样的设置， mpic可以。

**Comment by Molunerfinn** [comment]
> 同样的设置， mpic可以。

很多时候你看看报错日志就知道为啥了- -

**Comment by wrwe3888** [comment]
不是特别懂啊，日志在附件里，能否帮忙看下？
















在 2020-07-12 22:46:37，"PiEgg" <notifications@github.com> 写道：

同样的设置， mpic可以。

很多时候你看看报错日志就知道为啥了- -

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
2020-07-12 19:52:14 [PicGo INFO] [PicGo Server] is listening at 36677 
2020-07-12 20:00:09 [PicGo INFO] Before transform 
2020-07-12 20:00:09 [PicGo INFO] Transforming... 
2020-07-12 20:00:09 [PicGo INFO] Before upload 
2020-07-12 20:00:09 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:00:09 [PicGo INFO] Uploading... 
2020-07-12 20:00:28 [PicGo WARN] failed 
2020-07-12 20:00:28 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
2020-07-12 20:00:43 [PicGo INFO] Before transform 
2020-07-12 20:00:43 [PicGo INFO] Transforming... 
2020-07-12 20:00:43 [PicGo INFO] Before upload 
2020-07-12 20:00:43 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:00:43 [PicGo INFO] Uploading... 
2020-07-12 20:00:48 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/jfPCDYpFM9uBW7e.png 
2020-07-12 20:03:46 [PicGo INFO] Before transform 
2020-07-12 20:03:46 [PicGo INFO] Transforming... 
2020-07-12 20:03:46 [PicGo INFO] Before upload 
2020-07-12 20:03:46 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:03:46 [PicGo INFO] Uploading... 
2020-07-12 20:03:49 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/JQo2FdxzvSlcBsZ.png 
2020-07-12 20:03:56 [PicGo INFO] Before transform 
2020-07-12 20:03:56 [PicGo INFO] Transforming... 
2020-07-12 20:03:56 [PicGo INFO] Before upload 
2020-07-12 20:03:56 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:03:56 [PicGo INFO] Uploading... 
2020-07-12 20:04:00 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/qdhiIo85SmTPwWN.png 
2020-07-12 20:04:31 [PicGo INFO] Before transform 
2020-07-12 20:04:31 [PicGo INFO] Transforming... 
2020-07-12 20:04:31 [PicGo INFO] Before upload 
2020-07-12 20:04:31 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:04:31 [PicGo INFO] Uploading... 
2020-07-12 20:04:35 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/jfPCDYpFM9uBW7e.png 
2020-07-12 20:05:42 [PicGo INFO] Before transform 
2020-07-12 20:05:42 [PicGo INFO] Transforming... 
2020-07-12 20:05:42 [PicGo INFO] Before upload 
2020-07-12 20:05:42 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:05:42 [PicGo INFO] Uploading... 
2020-07-12 20:05:45 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/JQo2FdxzvSlcBsZ.png 
2020-07-12 20:06:24 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:134:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2020-07-12 20:06:27 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:134:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2020-07-12 20:09:58 [PicGo INFO] Before transform 
2020-07-12 20:09:58 [PicGo INFO] Transforming... 
2020-07-12 20:09:58 [PicGo INFO] Before upload 
2020-07-12 20:09:58 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:09:58 [PicGo INFO] Uploading... 
2020-07-12 20:10:01 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/jfPCDYpFM9uBW7e.png 
2020-07-12 20:10:29 [PicGo INFO] Before transform 
2020-07-12 20:10:29 [PicGo INFO] Transforming... 
2020-07-12 20:10:29 [PicGo INFO] Before upload 
2020-07-12 20:10:29 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:10:29 [PicGo INFO] Uploading... 
2020-07-12 20:10:31 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/JQo2FdxzvSlcBsZ.png 
2020-07-12 20:13:11 [PicGo INFO] Before transform 
2020-07-12 20:13:11 [PicGo INFO] Transforming... 
2020-07-12 20:13:11 [PicGo INFO] Before upload 
2020-07-12 20:13:11 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:13:11 [PicGo INFO] Uploading... 
2020-07-12 20:13:14 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/jfPCDYpFM9uBW7e.png 
2020-07-12 20:19:04 [PicGo INFO] Before transform 
2020-07-12 20:19:04 [PicGo INFO] Transforming... 
2020-07-12 20:19:04 [PicGo INFO] Before upload 
2020-07-12 20:19:04 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:19:07 [PicGo INFO] Uploading... 
2020-07-12 20:19:11 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/jfPCDYpFM9uBW7e.png 
2020-07-12 20:20:11 [PicGo INFO] Before transform 
2020-07-12 20:20:11 [PicGo INFO] Transforming... 
2020-07-12 20:20:11 [PicGo INFO] Before upload 
2020-07-12 20:20:11 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 20:20:13 [PicGo INFO] Uploading... 
2020-07-12 20:20:24 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/jfPCDYpFM9uBW7e.png 
2020-07-12 21:22:48 [PicGo INFO] Before transform 
2020-07-12 21:22:48 [PicGo INFO] Transforming... 
2020-07-12 21:22:48 [PicGo INFO] Before upload 
2020-07-12 21:22:48 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 21:22:50 [PicGo INFO] Uploading... 
2020-07-12 21:22:53 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/VXDgwdfLxbyJpSH.png 
2020-07-12 21:27:04 [PicGo INFO] Before transform 
2020-07-12 21:27:04 [PicGo INFO] Transforming... 
2020-07-12 21:27:04 [PicGo INFO] Before upload 
2020-07-12 21:27:04 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 21:27:06 [PicGo INFO] Uploading... 
2020-07-12 21:27:09 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/gqAEu19kZjl2GLx.png 
2020-07-12 21:28:08 [PicGo INFO] Before transform 
2020-07-12 21:28:08 [PicGo INFO] Transforming... 
2020-07-12 21:28:08 [PicGo INFO] Before upload 
2020-07-12 21:28:08 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 21:28:08 [PicGo INFO] Uploading... 
2020-07-12 21:28:11 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/gqAEu19kZjl2GLx.png 
2020-07-12 21:28:53 [PicGo INFO] Before transform 
2020-07-12 21:28:53 [PicGo INFO] Transforming... 
2020-07-12 21:28:53 [PicGo INFO] Before upload 
2020-07-12 21:28:53 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-12 21:28:53 [PicGo INFO] Uploading... 
2020-07-12 21:28:58 [PicGo SUCCESS] 
https://i.loli.net/2020/07/12/gqAEu19kZjl2GLx.png 
2020-07-12 21:39:00 [PicGo INFO] [PicGo Server] shutdown 
2020-07-12 21:45:12 [PicGo INFO] [PicGo Server] is listening at 36677
2020-07-12 21:45:31 [PicGo INFO] Before transform
2020-07-12 21:45:31 [PicGo INFO] Transforming...
2020-07-12 21:45:31 [PicGo INFO] Before upload
2020-07-12 21:45:31 [PicGo INFO] Uploading...
2020-07-12 21:45:35 [PicGo WARN] failed
2020-07-12 21:45:35 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 21:46:05 [PicGo INFO] Before transform
2020-07-12 21:46:05 [PicGo INFO] Transforming...
2020-07-12 21:46:05 [PicGo INFO] Before upload
2020-07-12 21:46:05 [PicGo INFO] Uploading...
2020-07-12 21:46:05 [PicGo WARN] failed
2020-07-12 21:46:05 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 21:47:07 [PicGo INFO] Before transform
2020-07-12 21:47:07 [PicGo INFO] Transforming...
2020-07-12 21:47:07 [PicGo INFO] Before upload
2020-07-12 21:47:07 [PicGo INFO] Uploading...
2020-07-12 21:47:09 [PicGo WARN] failed
2020-07-12 21:47:09 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 21:48:53 [PicGo INFO] Before transform
2020-07-12 21:48:53 [PicGo INFO] Transforming...
2020-07-12 21:48:53 [PicGo INFO] Before upload
2020-07-12 21:48:53 [PicGo INFO] Uploading...
2020-07-12 21:48:54 [PicGo WARN] failed
2020-07-12 21:48:54 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 21:49:27 [PicGo INFO] Before transform
2020-07-12 21:49:27 [PicGo INFO] Transforming...
2020-07-12 21:49:27 [PicGo INFO] Before upload
2020-07-12 21:49:27 [PicGo INFO] Uploading...
2020-07-12 21:49:28 [PicGo WARN] failed
2020-07-12 21:49:28 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 21:58:42 [PicGo INFO] Before transform
2020-07-12 21:58:42 [PicGo INFO] Transforming...
2020-07-12 21:58:42 [PicGo INFO] Before upload
2020-07-12 21:58:42 [PicGo INFO] Uploading...
2020-07-12 21:59:03 [PicGo ERROR] RequestError: Error: connect ETIMEDOUT 104.26.0.124:443
------Error Stack Begin------
RequestError: Error: connect ETIMEDOUT 104.26.0.124:443
    at new RequestError (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
2020-07-12 21:59:03 [PicGo WARN] failed
2020-07-12 22:05:31 [PicGo INFO] Before transform
2020-07-12 22:05:31 [PicGo INFO] Transforming...
2020-07-12 22:05:31 [PicGo INFO] Before upload
2020-07-12 22:05:31 [PicGo INFO] Uploading...
2020-07-12 22:05:32 [PicGo WARN] failed
2020-07-12 22:05:32 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 22:12:20 [PicGo INFO] Before transform
2020-07-12 22:12:20 [PicGo INFO] Transforming...
2020-07-12 22:12:20 [PicGo INFO] Before upload
2020-07-12 22:12:20 [PicGo INFO] Uploading...
2020-07-12 22:12:20 [PicGo WARN] failed
2020-07-12 22:12:20 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 22:42:09 [PicGo INFO] Before transform
2020-07-12 22:42:09 [PicGo INFO] Transforming...
2020-07-12 22:42:09 [PicGo INFO] Before upload
2020-07-12 22:42:09 [PicGo INFO] Uploading...
2020-07-12 22:42:10 [PicGo WARN] failed
2020-07-12 22:42:10 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 22:47:14 [PicGo INFO] Before transform
2020-07-12 22:47:14 [PicGo INFO] Transforming...
2020-07-12 22:47:14 [PicGo INFO] Uploading...
2020-07-12 22:47:14 [PicGo INFO] Before upload
2020-07-12 22:47:15 [PicGo WARN] failed
2020-07-12 22:47:15 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-07-12 22:47:40 [PicGo INFO] Before transform
2020-07-12 22:47:40 [PicGo INFO] Transforming...
2020-07-12 22:47:40 [PicGo INFO] Before upload
2020-07-12 22:47:40 [PicGo INFO] Uploading...
2020-07-12 22:47:43 [PicGo WARN] failed
2020-07-12 22:47:43 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (C:\Users\pc\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
> 同样的设置， mpic可以。

请问你把阿里云设置成默认上传图床了吗？日志里全都是smms的，还有很多报错是你剪贴板里没有图片，当然报错啊

**Comment by wrwe3888** [comment]
确定是把阿里云oss设为默认了，我是把图片直接拖到上传框里的。这些基本操作，我确定是没有问题的。否则也不来问了。 我也很纳闷，我明明完全没有操作sm的任何事情，为什么它给我上传到sm了。













在 2020-07-13 08:00:14，"PiEgg" <notifications@github.com> 写道：

同样的设置， mpic可以。

请问你把阿里云设置成默认上传图床了吗？日志里全都是smms的，还有很多报错是你剪贴板里没有图片，当然报错啊

**Comment by Molunerfinn** [comment]
> 确定是把阿里云oss设为默认了，我是把图片直接拖到上传框里的。这些基本操作，我确定是没有问题的。否则也不来问了。 我也很纳闷，我明明完全没有操作sm的任何事情，为什么它给我上传到sm了。 在 2020-07-13 08:00:14，"PiEgg" <notifications@github.com> 写道： 同样的设置， mpic可以。 请问你把阿里云设置成默认上传图床了吗？日志里全都是smms的，还有很多报错是你剪贴板里没有图片，当然报错啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

先试试更新到最新的beta.3，然后先选一下其他图床作为默认图床，再选回阿里云，再上传看看，如果还是报错，给一下阿里云的报错信息

**Comment by wrwe3888** [comment]
我昨天先用的是beta，出问题后，想到可能是beta版有bug，就换回了2.2.2，还是出问题。所以联系你了。


刚才把默认换成sm，出现同样的错误：上传失败，请检查配置和上传的文件！


然后再换回默认的阿里云，一样的提示信息。


如何查看阿里云的报错信息呢？


picgo没有QQ群、微信群、电报之类的吗？













在 2020-07-13 16:15:33，"PiEgg" <notifications@github.com> 写道：

确定是把阿里云oss设为默认了，我是把图片直接拖到上传框里的。这些基本操作，我确定是没有问题的。否则也不来问了。 我也很纳闷，我明明完全没有操作sm的任何事情，为什么它给我上传到sm了。 在 2020-07-13 08:00:14，"PiEgg" notifications@github.com 写道： 同样的设置， mpic可以。 请问你把阿里云设置成默认上传图床了吗？日志里全都是smms的，还有很多报错是你剪贴板里没有图片，当然报错啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

先试试更新到最新的beta.3，然后先选一下其他图床作为默认图床，再选回阿里云，再上传看看，如果还是报错，给一下阿里云的报错信息

**Comment by Molunerfinn** [comment]
@wrwe3888 首页就给了联系方式：
![image](https://user-images.githubusercontent.com/12621342/87306997-74bd3f00-c54b-11ea-8a65-5d6ef55a615d.png)
先看看picgo的报错日志啊- -
https://gitter.im/picgo-all/PicGo?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/87307257-d2518b80-c54b-11ea-909a-20fe0cac72f8.png)

**Comment by wrwe3888** [comment]
我今天更新了2.3.0 beta.3 版，设置好了以阿里云为默认图床，参数反复核对都没有错。
然后试着上传了一张照片，还是上传失败，提示：请检查配置和上传的文件是否符合要求。
为避免混淆，我上传照片前把之前的日志都删了。以下是上传这张图片留下的日志。
我的chrome浏览器安装了一个【谷歌上网助手】插件（插件界面如下图），然后没有设置其它的代理。


我百度了不少内容，都不太懂原因。能否帮我看一下，我接下来应该如何操作？
十分感谢。


 -------------------------------------------------------------------------------------------------------
2020-07-21 02:29:25 [PicGo INFO] Before transform 
2020-07-21 02:29:25 [PicGo INFO] Transforming... 
2020-07-21 02:29:25 [PicGo INFO] Before upload 
2020-07-21 02:29:25 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-07-21 02:29:25 [PicGo INFO] Uploading... 
2020-07-21 02:29:46 [PicGo WARN] failed 
2020-07-21 02:29:46 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: connect ETIMEDOUT 104.26.1.124:443
    at new RequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 


 -------------------------------------------------------------------------------------------------------




 -------------------------------------------------------------------------------------------------------




在 2020-07-13 21:00:23，"PiEgg" <notifications@github.com> 写道：

**Comment by Molunerfinn** [comment]
@wrwe3888 检查一下你配置文件里的 `picBed.current` 以及 `picBed.uploader` 的配置均为 `aliyun`

**Comment by wrwe3888** [comment]
之前就试过啊，配置文件打不开。报错如下：


















在 2020-07-21 09:02:16，"PiEgg" <notifications@github.com> 写道：

@wrwe3888 检查一下你配置文件里的 picBed.current 以及 picBed.uploader 的配置均为 aliyun

**Comment by wrwe3888** [comment]
默认图床也设置好了啊。。




















在 2020-07-21 09:02:16，"PiEgg" <notifications@github.com> 写道：

@wrwe3888 检查一下你配置文件里的 picBed.current 以及 picBed.uploader 的配置均为 aliyun

**Comment by wrwe3888** [comment]
请问这个如何操作？










在 2020-07-21 09:04:12，"王" <wrwe3888@163.com> 写道：

之前就试过啊，配置文件打不开。报错如下：


















在 2020-07-21 09:02:16，"PiEgg" <notifications@github.com> 写道：

@wrwe3888 检查一下你配置文件里的 picBed.current 以及 picBed.uploader 的配置均为 aliyun

**Comment by wrwe3888** [comment]
人呢？可否指导一下？













在 2020-07-22 09:16:57，"王" <wrwe3888@163.com> 写道：







请问这个如何操作？










在 2020-07-21 09:04:12，"王" <wrwe3888@163.com> 写道：

之前就试过啊，配置文件打不开。报错如下：


















在 2020-07-21 09:02:16，"PiEgg" <notifications@github.com> 写道：

@wrwe3888 检查一下你配置文件里的 picBed.current 以及 picBed.uploader 的配置均为 aliyun
