### ISSUE TITLE
偶发性的上传图片失败现象

### ISSUE THREAD

**Issue by Zrincet** [Molunerfinn/PicGo#311]
## 问题类型
偶发性的图片上传错误现象

## PicGo的相关信息
Windows 10  
PicGo - 2.1.2

相关去敏配置
![image](https://user-images.githubusercontent.com/11169330/61722780-7bccc980-ad9d-11e9-861b-ef4e30dd3184.png)

## 问题重现
偶发性的突然无法通过剪贴板上传任何图片，上传的图片类型都是截图，具有连续性，所以应该不是由于图片的问题产生的无法上传现象产生
![image](https://user-images.githubusercontent.com/11169330/61722572-1e387d00-ad9d-11e9-8caa-56315f4f91f1.png)

以下为相关失败上传日志
2019-07-23 22:44:53 [PicGo INFO] Before transform
2019-07-23 22:44:53 [PicGo INFO] Transforming...
2019-07-23 22:44:53 [PicGo INFO] Before upload
2019-07-23 22:44:53 [PicGo ERROR] TypeError: Error processing argument at index 1, conversion failure from 323.5
------Error Stack Begin------
TypeError: Error processing argument at index 1, conversion failure from 323.5
    at S (E:\PicGo\resources\app.asar\dist\electron\main.js:1:56154)
    at t.<anonymous> (E:\PicGo\resources\app.asar\dist\electron\main.js:1:57309)
    at r (E:\PicGo\resources\app.asar\dist\electron\main.js:1:24237)
    at Generator._invoke (E:\PicGo\resources\app.asar\dist\electron\main.js:1:25294)
    at Generator.t.(anonymous function) [as next] (E:\PicGo\resources\app.asar\dist\electron\main.js:1:24416)
    at o (E:\PicGo\resources\app.asar\dist\electron\main.js:1:1455)
    at E:\PicGo\resources\app.asar\dist\electron\main.js:1:1597
    at new Promise (<anonymous>)
    at new e (E:\PicGo\resources\app.asar\dist\electron\main.js:1:3088)
    at E:\PicGo\resources\app.asar\dist\electron\main.js:1:1390
-------Error Stack End-------
重启应用后，故障解除
## 功能请求

---

**Comment by Molunerfinn** [comment]
看上去跟Electron本身有点关系：https://github.com/electron/electron/issues/7657
不过我目前暂时无法复现同样的问题，看错误日志也不太明确问题出在哪里。如果重启有效就先重启，这个问题可以留着之后知道怎么解决了我再解决。

**Comment by SHERlocked93** [comment]
+1 ，这两天我也频现 **剪切板图片上传** 功能失效的情况，但是拖拽上传图片是成功的

**Comment by Molunerfinn** [comment]
@SHERlocked93 可以提供剪贴板上传失效的log文件么？在设置里可以打开log文件

**Comment by SHERlocked93** [comment]
[log.txt](https://github.com/Molunerfinn/PicGo/files/3450172/log.txt)
这是文件，最后几次是拖拽上传，然后上传成功了的，之前是剪切板上传然后失败了的，你瞅瞅

**Comment by Molunerfinn** [comment]
@SHERlocked93 如果你是MAC用户，参考这个issue，已经解决了：https://github.com/Molunerfinn/PicGo/issues/199

**Comment by SHERlocked93** [comment]
> @SHERlocked93 如果你是MAC用户，参考这个issue，已经解决了：#199

还真是...换了语言就好了，这是啥原理 😅

**Comment by SHERlocked93** [comment]
你好，现在又报了另一个错误，同样是上传失败

```
-------Error Stack End-------
2019-08-04 19:42:28 [PicGo INFO] Before transform
2019-08-04 19:42:28 [PicGo INFO] Transforming...
2019-08-04 19:42:28 [PicGo INFO] Before upload
2019-08-04 19:42:28 [PicGo INFO] Uploading...
2019-08-04 19:42:29 [PicGo ERROR] Error
------Error Stack Begin------
Error
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/uploader/smms.js:42:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------
2019-08-04 19:45:28 [PicGo INFO] Before transform
2019-08-04 19:45:28 [PicGo INFO] Before upload
2019-08-04 19:45:28 [PicGo INFO] Uploading...
2019-08-04 19:45:30 [PicGo ERROR] Error
------Error Stack Begin------
Error
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/uploader/smms.js:42:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
这是smms那边报的错，不知道是什么

**Comment by SHERlocked93** [comment]
> 这是smms那边报的错，不知道是什么

尴尬了，怎么提交都不行，只能紧急用 Github 的图床救急 😅

**Comment by luferl** [comment]
我也是smms.js报错，stack如下：

2019-08-07 09:35:22 [PicGo INFO] Before upload
2019-08-07 09:35:22 [PicGo INFO] Uploading...
2019-08-07 09:35:32 [PicGo ERROR] Error
------Error Stack Begin------
Error
    at Object.handle (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\plugins\uploader\smms.js:42:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------


但是我再去smms手动上传，会提示 Image upload repeated limit.
所以我猜测图片已经上传成功，但是callback崩了，而且我现在也不能重新上传。。。

**Comment by Molunerfinn** [comment]
@luferl 你后面这个报错是smms报的，意思是你上传的图片已经触发他们的重复限制了。不是PicGo不让你传，也不是你上传成功，是smms那边的问题

**Comment by RobinOfSky** [comment]
求解这个是什么问题？
2019-09-17 18:46:11 [PicGo INFO] Before transform
2019-09-17 18:46:11 [PicGo INFO] Transforming...
2019-09-17 18:46:11 [PicGo INFO] Before upload
2019-09-17 18:46:11 [PicGo INFO] Uploading...
2019-09-17 18:46:11 [PicGo ERROR] RequestError: Error: connect EACCES 13.250.168.23:443
------Error Stack Begin------
RequestError: Error: connect EACCES 13.250.168.23:443
    at new RequestError (D:\picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (D:\picgo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
@RobinOfSky 你这个是网络连接失败，检查一下你的网络吧。

**Comment by RobinOfSky** [comment]
> @RobinOfSky你这个是网络连接失败，检查一下你的网络吧。
网络没问题的

**Comment by DingJunyao** [comment]
我也出现了同样的情况，只要开启上传前重命名，就会报错，与网络没有关系（看起来在上传之前就报错了；关闭这个选项后不会报错）。以下是日志里的相关信息：

```
2019-10-28 23:06:41 [PicGo INFO] Before transform
2019-10-28 23:06:41 [PicGo INFO] Transforming...
2019-10-28 23:06:41 [PicGo INFO] Before upload
2019-10-28 23:06:41 [PicGo ERROR] TypeError: Error processing argument at index 0, conversion failure from 832.5
------Error Stack Begin------
TypeError: Error processing argument at index 0, conversion failure from 832.5
    at S (C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:56154)
    at t.<anonymous> (C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:57309)
    at r (C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:24237)
    at Generator._invoke (C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:25294)
    at Generator.t.(anonymous function) [as next] (C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:24416)
    at o (C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:1455)
    at C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:1597
    at new Promise (<anonymous>)
    at new e (C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:3088)
    at C:\Program Files\PicGo\resources\app.asar\dist\electron\main.js:1:1390
-------Error Stack End-------
```

系统版本：Windows 10 专业版 1903

**Comment by Molunerfinn** [comment]
@DingJunyao 用的什么图床，这个我之后测试一下

**Comment by DingJunyao** [comment]
> @DingJunyao 用的什么图床，这个我之后测试一下

是OSS的图床。

**Comment by Numen-fan** [comment]
请问SMMS的Authorization在哪里啊？

**Comment by Molunerfinn** [comment]
> 请问SMMS的Authorization在哪里啊？

请先使用 smms-user 插件。在README里有说明。

**Comment by Numen-fan** [comment]
感谢回复，原来就是API Token，那我已经设置了，如图：




可是我上传为何还是失败啊？











------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PiEgg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月3日(星期一) 中午11:10
收件人:&nbsp;"Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;;
抄送:&nbsp;"范家佳"<1414340590@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Molunerfinn/PicGo] 偶发性的上传图片失败现象 (#311)



 
请问SMMS的Authorization在哪里啊？
  
请先使用 smms-user 插件。在README里有说明。

**Comment by Molunerfinn** [comment]
> 感谢回复，原来就是API Token，那我已经设置了，如图： 可是我上传为何还是失败啊？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"PiEgg"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月3日(星期一) 中午11:10 收件人:&nbsp;"Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;; 抄送:&nbsp;"范家佳"<1414340590@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Molunerfinn/PicGo] 偶发性的上传图片失败现象 (#311) 请问SMMS的Authorization在哪里啊？ 请先使用 smms-user 插件。在README里有说明。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

设置了之后需要将smms-user设置成默认上传图床才能使用。如果设置了依然不行，请去smms-user的插件仓库提issue。

**Comment by Numen-fan** [comment]
抱歉，我忘记了需要重启应用，已经解决，感激！


&nbsp; &nbsp; 祝生活如意。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "PiEgg"<notifications@github.com&gt;; 
发送时间: 2020年2月3日(星期一) 中午11:17
收件人: "Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;; 
抄送: "范家佳"<1414340590@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Molunerfinn/PicGo] 偶发性的上传图片失败现象 (#311)



 
感谢回复，原来就是API Token，那我已经设置了，如图： 可是我上传为何还是失败啊？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"PiEgg"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月3日(星期一) 中午11:10 收件人:&nbsp;"Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;; 抄送:&nbsp;"范家佳"<1414340590@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Molunerfinn/PicGo] 偶发性的上传图片失败现象 (#311) 请问SMMS的Authorization在哪里啊？ 请先使用 smms-user 插件。在README里有说明。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
设置了之后需要将smms-user设置成默认上传图床才能使用。如果设置了依然不行，请去smms-user的插件仓库提issue。

**Comment by Molunerfinn** [comment]
请问一下更新到PicGo最新版还会出现这个问题吗？如果没有的话就先关闭issue啦

**Comment by Numen-fan** [comment]
问题已解决了，可以关闭了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PiEgg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 下午4:19
收件人:&nbsp;"Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;;
抄送:&nbsp;"范家佳"<1414340590@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Molunerfinn/PicGo] 偶发性的上传图片失败现象 (#311)




请问一下更新到PicGo最新版还会出现这个问题吗？如果没有的话就先关闭issue啦

**Comment by 2006wzt** [comment]
您好，请问我上一秒还发送成功，突然这次就无法传输图片是怎么回事，日志如下：
![image](https://user-images.githubusercontent.com/74082571/200110885-4095efea-9dbe-4458-a4c0-bec333646d8b.png)
