### ISSUE TITLE
Github 图床一直上传失败  

### ISSUE THREAD

**Issue by wujunze** [Molunerfinn/PicGo#320]
token 都配置好了  Github 图床一直上传失败  

## PicGo的相关信息

Mac 平台

## 问题重现
```bash
2019-08-28 13:12:11 [PicGo INFO] Before transform
2019-08-28 13:12:11 [PicGo INFO] Before upload
2019-08-28 13:12:11 [PicGo INFO] Uploading...
2019-08-28 13:12:13 [PicGo ERROR] StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
-------Error Stack End-------

```

**Comment by wujunze** [comment]
fixed

**Comment by yuzhenpeng** [comment]
> fixed

问一下你是怎么解决的

**Comment by SnVuamll** [comment]
我也遇上这个问题了，请问和这个issue是一样吗？

```
2020-05-08 10:17:20 [PicGo INFO] Before transform
2020-05-08 10:17:20 [PicGo INFO] Transforming...
2020-05-08 10:17:20 [PicGo INFO] Before upload
2020-05-08 10:17:20 [PicGo INFO] Uploading...
2020-05-08 10:17:26 [PicGo WARN] failed
2020-05-08 10:17:26 [PicGo ERROR] StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
> 我也遇上这个问题了，请问和这个issue是一样吗？
> 
> ```
> 2020-05-08 10:17:20 [PicGo INFO] Before transform
> 2020-05-08 10:17:20 [PicGo INFO] Transforming...
> 2020-05-08 10:17:20 [PicGo INFO] Before upload
> 2020-05-08 10:17:20 [PicGo INFO] Uploading...
> 2020-05-08 10:17:26 [PicGo WARN] failed
> 2020-05-08 10:17:26 [PicGo ERROR] StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
> ------Error Stack Begin------
> StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
>     at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
>     at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
>     at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
>     at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
>     at Request.emit (events.js:200:13)
>     at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
>     at Request.emit (events.js:200:13)
>     at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
>     at Object.onceWrapper (events.js:288:20)
>     at IncomingMessage.emit (events.js:205:15)
> -------Error Stack End-------
> ```

你这个是没好好看文档，配置写错了
