### ISSUE TITLE
2.1.2版在Linux mint上无法上传图片问题

### ISSUE THREAD

**Issue by chrischen789** [Molunerfinn/PicGo#321]
## 问题类型

Bug Report

## PicGo的相关信息

picgo 2.1.2 Linux
系统是 Linux mint 19.1

## 问题重现

1.使用控制台对picgo-2.1.2-x86_64.AppImage进行授权
$ sudo chmod +x picgo-2.1.2-x86_64.AppImage

2.然后执行
$ ./picgo-2.1.2-x86_64.AppImage

3.配置好阿里云的oss，在mac上测试可用

![image](https://user-images.githubusercontent.com/16202163/64012002-6773ad80-cb4f-11e9-810d-763d62454fe3.png)

进行图片上传提示“上传失败  服务端出错，请重试”

4.检查日志文件，内容如下
```
2019-08-30 17:37:17 [PicGo INFO] Before transform
2019-08-30 17:37:17 [PicGo INFO] Transforming...
2019-08-30 17:37:17 [PicGo INFO] Before upload
2019-08-30 17:37:17 [PicGo INFO] Uploading...
2019-08-30 17:37:17 [PicGo ERROR] RequestError: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7777
------Error Stack Begin------
RequestError: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7777
    at new RequestError (/tmp/.mount_picgo-O7hXIm/resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/tmp/.mount_picgo-O7hXIm/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/tmp/.mount_picgo-O7hXIm/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/tmp/.mount_picgo-O7hXIm/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/tmp/.mount_picgo-O7hXIm/resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.onError (/tmp/.mount_picgo-O7hXIm/resources/app.asar/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
-------Error Stack End-------
```
仔细观察发现启动的时候也有错误
```
➜  bin ./picgo-2.1.2-x86_64.AppImage  

(picgo:4515): Gtk-WARNING **: 17:52:27.904: Theme parsing error: gtk.css:10777:44: Expected a valid selector
(node:4515) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:7777
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
(node:4515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4515) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

---

**Comment by chrischen789** [comment]
可能是我的打开方式不对，直接双击图标，选择yes，然后通过启动器打开可以正常使用
