### ISSUE TITLE
阿里云OSS报错 RequestError: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Nisekoi5** [Molunerfinn/PicGo#337]
## 问题类型
感觉像是Bug

## PicGo的相关信息
windows10 1903 
picgo 2.1.2

## 问题重现
OSS设置，我使用相同的设置用官方的OSSbrowse可以上传。
https://i.loli.net/2019/09/19/2ZGptcJAiTIsCvN.jpg
相关日志
```
2019-09-19 11:23:20 [PicGo INFO] Before transform
2019-09-19 11:23:20 [PicGo INFO] Transforming...
2019-09-19 11:23:20 [PicGo INFO] Before upload
2019-09-19 11:23:20 [PicGo INFO] Uploading...
2019-09-19 11:23:21 [PicGo ERROR] RequestError: Error: unable to verify the first certificate
------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
-------Error Stack End-------

```

## 功能请求

---

**Comment by Molunerfinn** [comment]
经测试没有问题。好好检查配置是否有问题，比如多了空格之类的。PicGo的OSS用户很多，如果真的是PicGo出问题，issue区早就炸了。

![image](https://user-images.githubusercontent.com/12621342/65219771-db202f00-daeb-11e9-8779-badb60086194.png)

**Comment by Nisekoi5** [comment]
找到原因了。好像只是单独我的OSS出问题了。上传控制台出现CORS。连OSS的网页端都上传不了了
明明设置了泛域名。发工单给工程师也搞不明白。不知道该咋解决

**Comment by UniqueDong** [comment]
我也遇到了，老哥找到问题了么
