### ISSUE TITLE
Github 图床上传文件失败

### ISSUE THREAD

**Issue by WymanY** [Molunerfinn/PicGo#338]
## 问题类型

Bug Report
## PicGo的相关信息
Pic版本2.1.2

Mac 10.14.4,
Xcode 10.3 正式版
## 问题重现

Github图传上传失败，提示请检查配置和上传的文件。

0. GitHub之前上传成功过，突然无法上传了，github的配置从未发生过变化
1. 单显示器
2. 尝试过切换英文，仍然不好使。
GIthub配置文件如下：
![image](https://user-images.githubusercontent.com/11940805/65365397-a75c1b00-dc4b-11e9-9f33-d1ae4df16319.png)

日志文件如下：
![image](https://user-images.githubusercontent.com/11940805/65365312-01101580-dc4b-11e9-99af-992afb25b56c.png)

---

**Comment by Molunerfinn** [comment]
报错是 `socket hang up`，说明你的网络有问题。

1. 检查代理配置
2. 检查网络访问

跟PicGo本身没有关系。

**Comment by WymanY** [comment]
> 报错是 `socket hang up`，说明你的网络有问题。
> 
> 1. 检查代理配置
> 2. 检查网络访问
> 
> 跟PicGo本身没有关系。

嗯好的，我再试试吧，主要是我github网页访问正常，可能是走命令行有问题，可能最近github被封的厉害，我试着排除一下区别。

**Comment by man2018** [comment]
@WymanY 你问题解决没

**Comment by man2018** [comment]
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
我跟你问题一样，全局翻墙也照样无法使用github的图床

**Comment by WymanY** [comment]
> ------Error Stack Begin------
> RequestError: Error: socket hang up
> at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
> at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
> at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
> at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
> at Request.emit (events.js:200:13)
> at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
> at ClientRequest.emit (events.js:200:13)
> at TLSSocket.socketOnEnd (_http_client.js:436:9)
> at TLSSocket.emit (events.js:205:15)
> at endReadableNT (_stream_readable.js:1154:12)
> -------Error Stack End-------
> 我跟你问题一样，全局翻墙也照样无法使用github的图床

我这边觉得github的访问有些问题，我这边改成gitee 托管了，很稳定，速度也很快，而且不用翻墙
