### ISSUE TITLE
上传失败，请检查图片格式

### ISSUE THREAD

**Issue by hdtopku** [Molunerfinn/PicGo#339]
使用的是smms图床，之前上传都正常，后来忘了压缩图片，上传了大概5个2M左右大小的图片就老是提示上传错误了。以下是一些错误日志，上传的是png图片。
```
2019-09-27 23:38:43 [PicGo INFO] Before transform
2019-09-27 23:38:43 [PicGo INFO] Transforming...
2019-09-27 23:38:43 [PicGo INFO] Before upload
2019-09-27 23:38:43 [PicGo INFO] Uploading...
2019-09-27 23:38:48 [PicGo ERROR] Error
------Error Stack Begin------
Error
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/uploader/smms.js:42:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
smms现在会进行重复检查。如果你上传了之前已经上传过的图片，会被smms拒收。
