### ISSUE TITLE
腾讯云COS接口似乎更新了，上传失败。

### ISSUE THREAD

**Issue by xwzy** [Molunerfinn/PicGo#351]
## 问题类型
Bug Report

## PicGo的相关信息
Mac和Windows，2.1.2。

## 问题重现
我的配置一直没有改过，之前一直可以上传，Mac和Win都没问题，一段时间没用了，今天突然全挂了，我确认检查了配置也没问题（和之前一样），看了一下这个项目[https://github.com/tencentyun/cos-js-sdk-v5](https://github.com/tencentyun/cos-js-sdk-v5)，似乎上个月有更新，开发者可以确认下是否有接口变动吗，感谢。
报错信息
```
2019-10-25 21:14:52 [PicGo INFO] Before transform
2019-10-25 21:14:52 [PicGo INFO] Transforming...
2019-10-25 21:14:52 [PicGo INFO] Before upload
2019-10-25 21:14:52 [PicGo ERROR] Error: Upload failed
------Error Stack Begin------
Error: Upload failed
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/uploader/tcyun.js:114:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------
```

## 功能请求

---

**Comment by icecrea** [comment]
@xwzy  请问下是哪里的控制权限有问题呀，我这边也有相同报错
