### ISSUE TITLE
TypeError: Cannot read property 'width' of null

### ISSUE THREAD

**Issue by qiujiafei123** [Molunerfinn/PicGo#363]
版本:
PicGo-2.1.2.dmg

遇到的问题: 
配置好七牛图床的各种参数，并设置为默认图床，然后去"上传区"上传提示:上传失败，请检查配置(其他方式上传也均提示此错误),  目前可以确认七牛配置无误(同样的参数配置使用另一台Ubuntu机器, picgo-2.1.2-x86_64.AppImage 可以成功上传至七牛云并在相册展示出来)

日志显示:
```
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at Promise.all.ctx.input.map (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/transformer/path.js:20:28)
-------Error Stack End-------
2019-12-02 11:50:47 [PicGo INFO] Before transform
2019-12-02 11:50:47 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at Promise.all.ctx.input.map (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/transformer/path.js:20:28)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
这个问题估计是上传的图片格式不支持，你上传的格式莫非是ICO？

**Comment by qiujiafei123** [comment]
hhh, 大意了 😆 ， 我上传的是一个pdf，刚用图片上传没问题， 很好用，感谢作者 👍
