### ISSUE TITLE
SMMS上传失败

### ISSUE THREAD

**Issue by yisany** [Molunerfinn/PicGo#380]
## 问题类型

2.2.0版本使用SMMS图床上传图片失败

## PicGo的相关信息

MacOS_10.14.6

## 问题重现

SMMS官方的api路径变了, 导致接口请求error

错误日志:
```
2020-01-06 22:37:56 [PicGo ERROR] Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
------Error Stack Begin------
Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/plugins/uploader/smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:70:9)
    at async Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:21:13)
    at async PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:145:21)
-------Error Stack End-------
```

---

**Comment by yisany** [comment]
在closed issue里面找到了, 建议放出来一段时间

**Comment by Molunerfinn** [comment]
> 在closed issue里面找到了, 建议放出来一段时间

OK，已经放到pin区

![image](https://user-images.githubusercontent.com/12621342/71825741-73f8ab80-30d7-11ea-9cf5-053622737098.png)

**Comment by pidada** [comment]
请问下大家怎么解决的呢
