### ISSUE TITLE
关于DNS影响上传的问题

### ISSUE THREAD

**Issue by wongFanx** [Molunerfinn/PicGo#401]
## 问题类型

Bug Report
## PicGo的相关信息

mac OS catalina 10.15
PicGo 2.2.2

## 问题重现

咨询一下为什么把 NDS 修改成 8.8.8.8 或者其他的. 就会出现上传失败的问题呢?

`
2020-01-28 20:23:37 [PicGo INFO] Before transform
2020-01-28 20:23:37 [PicGo INFO] Before upload
2020-01-28 20:23:38 [PicGo ERROR] HttpError: request to https://api.github.com/repos/wongFanx/Image-Hosting/contents/img/20200128202337.png failed, reason: Hostname/IP does not match certificate's altnames: Host: api.github.com. is not in the cert's altnames: DNS:*.c.docs.google.com, DNS:*.a1.googlevideo.com, DNS:*.c.2mdn.net, DNS:*.c.audiobooks.play.google.com, DNS:*.c.bigcache.googleapis.com, DNS:*.c.chat.google.com, DNS:*.c.doc-0-0-sj.sj.googleusercontent.com, DNS:*.c.drive.google.com, DNS:*.c.googlesyndication.com, DNS:*.c.googlevideo.com, DNS:*.c.inbox.google.com, DNS:*.c.lh3-da.googleusercontent.com, DNS:*.c.lh3-da.photos0.sandbox.google.com, DNS:*.c.lh3-db.googleusercontent.com, DNS:*.c.lh3-db.photos1.sandbox.google.com, DNS:*.c.lh3-dc.googleusercontent.com, DNS:*.c.lh3-dc.photos2.sandbox.google.com, DNS:*.c.lh3-dd.googleusercontent.com, DNS:*.c.lh3-dd.photos3.sandbox.google.com, DNS:*.c.lh3-de.googleusercontent.com, DNS:*.c.lh3-de.photos4.sandbox.google.com, DNS:*.c.lh3-df.googleusercontent.com, DNS:*.c.lh3-df.photos5.sandbox.google.com, DNS:*.c.lh3-dg.googleusercontent.com, DNS:*.c.lh3-dg.photos6.sandbox.google.com, DNS:*.c.lh3-dz.googleusercontent.com, DNS:*.c.lh3-dz.photos-autopush.sandbox.google.com, DNS:*.c.lh3.googleusercontent.com, DNS:*.c.lh3.photos.google.com, DNS:*.c.mail.google.com, DNS:*.c.offline.maps.google.com, DNS:*.c.pack.google.com, DNS:*.c.play.google.com, DNS:*.c.video.google.com, DNS:*.c.youtube.com, DNS:*.cache1.c.docs.google.com, DNS:*.cache1.c.play.google.com, DNS:*.cache1.c.video.google.com, DNS:*.cache1.c.youtube.com, DNS:*.cache2.c.docs.google.com, DNS:*.cache2.c.play.google.com, DNS:*.cache2.c.video.google.com, DNS:*.cache2.c.youtube.com, DNS:*.cache3.c.docs.google.com, DNS:*.cache3.c.play.google.com, DNS:*.cache3.c.video.google.com, DNS:*.cache3.c.youtube.com, DNS:*.cache4.c.docs.google.com, DNS:*.cache4.c.play.google.com, DNS:*.cache4.c.video.google.com, DNS:*.cache4.c.youtube.com, DNS:*.cache5.c.docs.google.com, DNS:*.cache5.c.play.google.com, DNS:*.cache5.c.video.google.com, DNS:*.cache5.c.youtube.com, DNS:*.cache6.c.docs.google.com, DNS:*.cache6.c.play.google.com, DNS:*.cache6.c.video.google.com, DNS:*.cache6.c.youtube.com, DNS:*.cache7.c.docs.google.com, DNS:*.cache7.c.play.google.com, DNS:*.cache7.c.video.google.com, DNS:*.cache7.c.youtube.com, DNS:*.cache8.c.docs.google.com, DNS:*.cache8.c.play.google.com, DNS:*.cache8.c.video.google.com, DNS:*.cache8.c.youtube.com, DNS:*.dai.googlevideo.com, DNS:*.gcpcdn.gvt1.com, DNS:*.googlevideo.com, DNS:*.googlezip.net, DNS:*.gvt1.com, DNS:*.offline-maps.gvt1.com, DNS:*.snap.gvt1.com, DNS:*.xn--ngstr-lra8j.com, DNS:xn--ngstr-lra8j.com
------Error Stack Begin------
HttpError: request to https://api.github.com/repos/wongFanx/Image-Hosting/contents/img/20200128202337.png failed, reason: Hostname/IP does not match certificate's altnames: Host: api.github.com. is not in the cert's altnames: DNS:*.c.docs.google.com, DNS:*.a1.googlevideo.com, DNS:*.c.2mdn.net, DNS:*.c.audiobooks.play.google.com, DNS:*.c.bigcache.googleapis.com, DNS:*.c.chat.google.com, DNS:*.c.doc-0-0-sj.sj.googleusercontent.com, DNS:*.c.drive.google.com, DNS:*.c.googlesyndication.com, DNS:*.c.googlevideo.com, DNS:*.c.inbox.google.com, DNS:*.c.lh3-da.googleusercontent.com, DNS:*.c.lh3-da.photos0.sandbox.google.com, DNS:*.c.lh3-db.googleusercontent.com, DNS:*.c.lh3-db.photos1.sandbox.google.com, DNS:*.c.lh3-dc.googleusercontent.com, DNS:*.c.lh3-dc.photos2.sandbox.google.com, DNS:*.c.lh3-dd.googleusercontent.com, DNS:*.c.lh3-dd.photos3.sandbox.google.com, DNS:*.c.lh3-de.googleusercontent.com, DNS:*.c.lh3-de.photos4.sandbox.google.com, DNS:*.c.lh3-df.googleusercontent.com, DNS:*.c.lh3-df.photos5.sandbox.google.com, DNS:*.c.lh3-dg.googleusercontent.com, DNS:*.c.lh3-dg.photos6.sandbox.google.com, DNS:*.c.lh3-dz.googleusercontent.com, DNS:*.c.lh3-dz.photos-autopush.sandbox.google.com, DNS:*.c.lh3.googleusercontent.com, DNS:*.c.lh3.photos.google.com, DNS:*.c.mail.google.com, DNS:*.c.offline.maps.google.com, DNS:*.c.pack.google.com, DNS:*.c.play.google.com, DNS:*.c.video.google.com, DNS:*.c.youtube.com, DNS:*.cache1.c.docs.google.com, DNS:*.cache1.c.play.google.com, DNS:*.cache1.c.video.google.com, DNS:*.cache1.c.youtube.com, DNS:*.cache2.c.docs.google.com, DNS:*.cache2.c.play.google.com, DNS:*.cache2.c.video.google.com, DNS:*.cache2.c.youtube.com, DNS:*.cache3.c.docs.google.com, DNS:*.cache3.c.play.google.com, DNS:*.cache3.c.video.google.com, DNS:*.cache3.c.youtube.com, DNS:*.cache4.c.docs.google.com, DNS:*.cache4.c.play.google.com, DNS:*.cache4.c.video.google.com, DNS:*.cache4.c.youtube.com, DNS:*.cache5.c.docs.google.com, DNS:*.cache5.c.play.google.com, DNS:*.cache5.c.video.google.com, DNS:*.cache5.c.youtube.com, DNS:*.cache6.c.docs.google.com, DNS:*.cache6.c.play.google.com, DNS:*.cache6.c.video.google.com, DNS:*.cache6.c.youtube.com, DNS:*.cache7.c.docs.google.com, DNS:*.cache7.c.play.google.com, DNS:*.cache7.c.video.google.com, DNS:*.cache7.c.youtube.com, DNS:*.cache8.c.docs.google.com, DNS:*.cache8.c.play.google.com, DNS:*.cache8.c.video.google.com, DNS:*.cache8.c.youtube.com, DNS:*.dai.googlevideo.com, DNS:*.gcpcdn.gvt1.com, DNS:*.googlevideo.com, DNS:*.googlezip.net, DNS:*.gvt1.com, DNS:*.offline-maps.gvt1.com, DNS:*.snap.gvt1.com, DNS:*.xn--ngstr-lra8j.com, DNS:xn--ngstr-lra8j.com
    at /Users/van/Library/Application Support/picgo/node_modules/@octokit/request/dist-node/index.js:107:11
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Octo.upload (/Users/van/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus/dist/lib/octokit.js:114:19)
    at async Object.handle (/Users/van/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus/dist/index.js:142:5)
    at async Lifecycle.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:70:9)
    at async Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:21:13)
    at async PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:145:21)
-------Error Stack End-------
`

---

**Comment by Molunerfinn** [comment]
建议你谷歌或者百度DNS用来干嘛的…

**Comment by Molunerfinn** [comment]
这里不负责解决网络问题
