### ISSUE TITLE
Mac 上传图片出错

### ISSUE THREAD

**Issue by kenx-max** [Molunerfinn/PicGo#407]
rror
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/uploader/smms.js:42:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------
2020-02-11 14:05:28 [PicGo ERROR] Error
------Error Stack Begin------
Error
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/plugins/uploader/smms.js:42:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/74214842-fc232f80-4cd9-11ea-894d-08bb2410523b.png)
