### ISSUE TITLE
有时候github图床上传失败

### ISSUE THREAD

**Issue by am-abudu** [Molunerfinn/PicGo#413]
## 问题类型

BUG

## PicGo的相关信息

Windows,Picgo2.2.2

## 问题重现

------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
![image](https://user-images.githubusercontent.com/51912589/75106557-e9edad80-5658-11ea-83ec-58b443271b71.png)

**Comment by Molunerfinn** [comment]
网络问题。

**Comment by 6xiaoDi** [comment]
有没有解决办法啊？

**Comment by Molunerfinn** [comment]
> 有没有解决办法啊？

挂代理，换gitee，或者花钱用阿里云，方法多得是。
