### ISSUE TITLE
网络环境正常，但出现 Error: socket hang up

### ISSUE THREAD

**Issue by TianZonglin** [Molunerfinn/PicGo#417]
## 问题类型

Bug Report 
我已经查阅了几个相关的issue，我看是有可能由于网络引起的，但是，我并不存在网络问题，Github使用一切正常（人不在国内），还是出现了这个问题，不理解这是什么网络问题。

新增：

试了下我家里的电脑，也上传失败了，昨天晚上还正常使用的，现在绝对不可能是网络环境的问题了。

## PicGo的相关信息

Windows 10

## 问题重现

```
PS C:\Program Files\PicGo>
 [PicGo INFO]: [PicGo Server] is listening at 36678
Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at TLSSocket.socketOnEnd (_http_client.js:436:23)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'ECONNRESET',
  config: {
    url: 'https://cdn.jsdelivr.net/gh/Molunerfinn/PicGo@latest/package.json',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.0'
    },
    transformRequest: [ [Function] ],
    transformResponse: [ [Function] ],
    timeout: 0,
    adapter: [Function],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function],
      error: [Function]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/gh/Molunerfinn/PicGo@latest/package.json',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      auth: undefined,
      hostname: 'cdn.jsdelivr.net',
      port: null,
      nativeProtocols: [Object],
      pathname: '/gh/Molunerfinn/PicGo@latest/package.json'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /gh/Molunerfinn/PicGo@latest/package.json HTTP/1.1\r' +
        '\nAccept: application/json, text/plain, */*\r' +
        '\nUser-Agent: axios/0.19.0\r' +
        '\nHost: cdn.jsdelivr.net\r' +
        '\nConnection: close\r' +
        '\n\r' +
        '\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/gh/Molunerfinn/PicGo@latest/package.json',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Circular],
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object: null prototype]
    },
    _currentUrl: 'https://cdn.jsdelivr.net/gh/Molunerfinn/PicGo@latest/package.json'
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}
(node:109768) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at ct (C:\Program Files\PicGo\resources\app.asar\background.js:16:38801)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:109768) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at ct (C:\Program Files\PicGo\resources\app.asar\background.js:16:38801)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:109768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:109768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:109768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:109768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## 功能请求

---

**Comment by Molunerfinn** [comment]
这个就是网络问题。能访问GitHub不代表访问它的api地址就一定没问题。最近我也会遇到这个问题，是GitHub服务端的问题。

简单来说就是GitHub服务端断开了连接，但是没有通知到PicGo客户端，PicGo再上传的时候会以之前的连接上传，但是会被GitHub服务端拒绝。

间歇性的问题，不是持续的，重新上传就行。

**Comment by TianZonglin** [comment]
好的
