### ISSUE TITLE
上传同名图片报错

### ISSUE THREAD

**Issue by soxio** [Molunerfinn/PicGo#418]
## 问题类型

Bug Report
## PicGo的相关信息

Windows
## 问题重现
上传同名文件就会报错，即使是两张不同的图片

![](https://raw.githubusercontent.com/soxio/imglib/master/img/springboot/20200227115417.png)
```
2020-02-27 11:49:20 [PicGo INFO] Before transform
2020-02-27 11:49:20 [PicGo INFO] Transforming...
2020-02-27 11:49:20 [PicGo INFO] Before upload
2020-02-27 11:49:20 [PicGo INFO] Uploading...
2020-02-27 11:49:22 [PicGo WARN] failed
2020-02-27 11:49:22 [PicGo ERROR] StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
    at new StatusCodeError (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------
```
## 功能请求

---

**Comment by Molunerfinn** [comment]
github图床目前不支持上传同名文件。因为要上传同名文件，github的接口不一样。

**Comment by soxio** [comment]
> github图床目前不支持上传同名文件。因为要上传同名文件，github的接口不一样。

好的，谢谢

**Comment by taizilongxu** [comment]
同样问题, 但是我在 github 删除老图片后, 上传新的同名图片, 最终还是变成老的图片

**Comment by Molunerfinn** [comment]
> 同样问题, 但是我在 github 删除老图片后, 上传新的同名图片, 最终还是变成老的图片

你觉得删除了其实只是一个commit而已，下次再上传同名的会被认为是复原了

**Comment by Molunerfinn** [comment]
如果要用GitHub图床就不要使用同名文件。
