### ISSUE TITLE
Github图床上传失败

### ISSUE THREAD

**Issue by XIEJD** [Molunerfinn/PicGo#419]
## 问题类型

Maybe Bug Report

## PicGo的相关信息

Mac 10.15.2
PicGo 2.2.2

## 问题重现

Github图床，试过开VPN和不开VPN，都是同样的错误

本地Chrome访问Github正常

错误日志，报了404

```shell
2020-02-29 00:41:04 [PicGo INFO] [PicGo Server] is listening at 36677
2020-02-29 00:43:32 [PicGo INFO] Before transform
2020-02-29 00:43:32 [PicGo INFO] Transforming...
2020-02-29 00:43:32 [PicGo INFO] Before upload
2020-02-29 00:43:32 [PicGo WARN] failed
2020-02-29 00:54:10 [PicGo INFO] Before transform
2020-02-29 00:54:10 [PicGo INFO] Before upload
2020-02-29 00:54:10 [PicGo INFO] Uploading...
2020-02-29 00:54:17 [PicGo WARN] failed
2020-02-29 00:54:26 [PicGo INFO] Before transform
2020-02-29 00:54:26 [PicGo INFO] Transforming...
2020-02-29 00:54:26 [PicGo INFO] Before upload
2020-02-29 00:54:26 [PicGo INFO] Uploading...
2020-02-29 00:54:30 [PicGo WARN] failed
2020-02-29 00:54:58 [PicGo INFO] Before transform
2020-02-29 00:54:58 [PicGo INFO] Transforming...
2020-02-29 00:54:58 [PicGo INFO] Before upload
2020-02-29 00:54:58 [PicGo INFO] Uploading...
2020-02-29 00:55:07 [PicGo WARN] failed
2020-02-29 00:55:07 [PicGo ERROR] StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------
2020-02-29 00:55:32 [PicGo INFO] Before transform
2020-02-29 00:55:32 [PicGo INFO] Before upload
2020-02-29 00:55:32 [PicGo WARN] failed
2020-02-29 00:55:32 [PicGo ERROR] RequestError: Error: connect ECONNREFUSED 13.250.168.23:443
------Error Stack Begin------
RequestError: Error: connect ECONNREFUSED 13.250.168.23:443
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
配置没配对，这个问题已经很多人问过了，请你好好看看文档。

**Comment by XIEJD** [comment]
我的锅，之前看了一遍文档，没看仔细

```
{
  "repo": "", // 仓库名，格式是username/reponame
  "token": "", // github token
  "path": "", // 自定义存储路径，比如img/
  "customUrl": "", // 自定义域名，注意要加http://或者https://
  "branch": "" // 分支名，默认是master
}
```

Repo名我理所当然的理解为reponame了，因为之前用marktext时，图床的配置username和reponame是分开的，还纳闷了一下为啥不用配username

感谢回复，建议可以分开配置，没看文档的可能误解😂

**Comment by XIEJD** [comment]
感谢回复，我的锅，repo的配置应该是`username/reponame`

**Comment by chengyi818** [comment]
我今天也碰到了一样的问题,也是repo的配置没对;
我是因为在`username/reponame`后面多了个空格.
这个可以加个类似strip的操作吗?提高下容错
