### ISSUE TITLE
github图床  用一会就出现问题

### ISSUE THREAD

**Issue by zelentre** [Molunerfinn/PicGo#425]
```
[PicGo ERROR] RequestError: Error: read ECONNRESET
````

**Comment by zelentre** [comment]
```
2020-03-04 14:56:39 [PicGo ERROR] RequestError: Error: read ECONNRESET
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
github服务端问题，跟频率有关
