### ISSUE TITLE
GITHUB图床 阶段性上传失败

### ISSUE THREAD

**Issue by GrandArth** [Molunerfinn/PicGo#434]
## 问题类型

GITHUB图床经常性的上传失败.
首先会报错
上传失败: 服务器端错误

之后会第二次报错
上传失败:检查配置文件和上传文件

## PicGo的相关信息

Windows Latest Release (20200311)

## 问题重现
```
2020-03-11 08:56:52 [PicGo INFO] Before transform
2020-03-11 08:56:52 [PicGo INFO] Transforming...
2020-03-11 08:56:52 [PicGo INFO] Before upload
2020-03-11 08:56:52 [PicGo INFO] Uploading...
2020-03-11 08:56:53 [PicGo WARN] failed
2020-03-11 08:56:53 [PicGo ERROR] RequestError: Error: read ECONNRESET
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (H:\Picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (H:\Picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (H:\Picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (H:\Picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (H:\Picgo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
2020-03-11 08:56:53 [PicGo ERROR] RequestError: Error: read ECONNRESET
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (H:\Picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (H:\Picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (H:\Picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (H:\Picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (H:\Picgo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
GitHub服务端问题。应该是使用的人多了触发了频率限制。跟PicGo这边无关

**Comment by GrandArth** [comment]
Gitee可作为国内代替品


| |
Risiamu
|
|
|
签名由网易邮箱大师定制
在2020年3月11日 09:45，PiEgg<notifications@github.com> 写道：

Closed #434.

**Comment by wss434631143** [comment]
我也遇到这个问题了，不知道怎么解决。

**Comment by Molunerfinn** [comment]
> 我也遇到这个问题了，不知道怎么解决。

过一会再上传就好了...应该是用的人太多，GitHub那边有频率限制
