### ISSUE TITLE
github图床上传图片有时成功有时失败

### ISSUE THREAD

**Issue by StoicLD** [Molunerfinn/PicGo#442]
## 问题类型
Bug Report

## PicGo的相关信息
2.2.2
Windows 10

## 问题重现
正常启动picgo，图床是github，无论是直接上传，剪贴板上传都有几率上传失败。
通常来说第一次打开picgo的时候都是上传成功的。随后就有可能上传失败。而且失败之后会
不断地重复消息提示上传，上传失败，请检测配置等等。

```
2020-03-19 15:12:54 [PicGo INFO] [PicGo Server] shutdown
2020-03-19 15:13:09 [PicGo INFO] [PicGo Server] is listening at 36678
2020-03-19 15:15:29 [PicGo INFO] Before transform
2020-03-19 15:15:30 [PicGo INFO] Transforming...
2020-03-19 15:15:30 [PicGo INFO] Before upload
2020-03-19 15:15:30 [PicGo INFO] Uploading...
2020-03-19 15:15:30 [PicGo WARN] failed
2020-03-19 15:15:30 [PicGo ERROR] RequestError: Error: read ECONNRESET
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (D:\software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\software\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
```
## 功能请求

---

**Comment by Molunerfinn** [comment]
服务端问题。这个没办法，只能间隔来传。如果受不了可以买阿里云等产品，也不贵...

**Comment by CarsonLam** [comment]
我也遇到了，用了其他软件可以上传了。连续上传也可以。

**Comment by StoicLD** [comment]
感谢作者大大回复，我换了云端存储现在OK了，看来国内github还是有点不稳定。

> 服务端问题。这个没办法，只能间隔来传。如果受不了可以买阿里云等产品，也不贵...
