### ISSUE TITLE
上传失败，请检查配置上上传文件格式

### ISSUE THREAD

**Issue by zhouzhou84** [Molunerfinn/PicGo#446]
## 问题类型
Bug Report

## PicGo的相关信息
 picgo-2.2.2 ，Windows10 

## 问题重现
按如图设置好github图床，然后拖拽上传或者点击上传，都会出现上传失败，然后又弹出“请检查配置和上传的文件是否符合要求”
抱歉截图我准备放上来，但是上传失败，一上传github就说“something went really wrong, and we can't process that file”

现在是不能上传了么？我问一个博主，
我就是跟他的教程学习hexo以及使用picgo+jsdelivr设置图床的，他也说现在上传不了

**Comment by Molunerfinn** [comment]
把错误日志放上来才知道为啥。日志可以在PicGo设置里找到。另外如果是你连GitHub这里自带的都传不了，应该是你网络问题了。

**Comment by Hitmi** [comment]
> 把错误日志放上来才知道为啥。日志可以在PicGo设置里找到。另外如果是你连GitHub这里自带的都传不了，应该是你网络问题了。
2020-05-10 11:54:20 [PicGo INFO] Before transform
2020-05-10 11:54:20 [PicGo INFO] Transforming...
2020-05-10 11:54:20 [PicGo INFO] Before upload
2020-05-10 11:54:20 [PicGo INFO] Uploading...
2020-05-10 11:54:21 [PicGo WARN] failed
2020-05-10 11:54:21 [PicGo ERROR] TypeError: Cannot read property 'body' of undefined
------Error Stack Begin------
TypeError: Cannot read property 'body' of undefined
    at Object.handle (F:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\qiniu.js:65:51)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2020-05-10 11:54:21 [PicGo ERROR] TypeError: Cannot read property 'body' of undefined
------Error Stack Begin------
TypeError: Cannot read property 'body' of undefined
    at Object.handle (F:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\qiniu.js:65:51)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2020-05-10 12:25:10 [PicGo ERROR] Error: image not found in clipboard
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (F:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:132:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2020-05-10 12:25:35 [PicGo INFO] Before transform
2020-05-10 12:25:35 [PicGo INFO] Transforming...
2020-05-10 12:25:35 [PicGo INFO] Before upload
2020-05-10 12:25:35 [PicGo INFO] Uploading...
2020-05-10 12:25:36 [PicGo ERROR] TypeError: Cannot read property 'body' of undefined
------Error Stack Begin------
TypeError: Cannot read property 'body' of undefined
    at Object.handle (F:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\qiniu.js:65:51)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2020-05-10 12:25:36 [PicGo WARN] failed
2020-05-10 12:29:54 [PicGo INFO] [PicGo Server] shutdown
2020-05-10 12:29:54 [PicGo INFO] [PicGo Server] is listening at 36677
2020-05-10 12:31:43 [PicGo INFO] [PicGo Server] is listening at 36677
2020-05-10 12:33:18 [PicGo INFO] Before transform
2020-05-10 12:33:18 [PicGo INFO] Transforming...
2020-05-10 12:33:18 [PicGo INFO] Before upload
2020-05-10 12:33:18 [PicGo INFO] Uploading...
2020-05-10 12:33:19 [PicGo WARN] failed
2020-05-10 12:33:19 [PicGo ERROR] TypeError: Cannot read property 'body' of undefined
------Error Stack Begin------
TypeError: Cannot read property 'body' of undefined
    at Object.handle (F:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\qiniu.js:65:51)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
大致这是今天上传失败的日志，出现的是和上面那个兄弟一样的问题

**Comment by jszgz** [comment]
我看了日志是DDoS protection，这该怎么办呢。。
