### ISSUE TITLE
typora上传报错 uploader duplicate id: gitee!

### ISSUE THREAD

**Issue by LeonG7** [Molunerfinn/PicGo#456]
## 问题类型
Bug Report
## PicGo的相关信息
2.2.2 windows版本
## 问题重现
单独上传没问题，用typora上传就报错，日志贴在下面
![](https://gitee.com/leonG7/blogImage/raw/master/img/20200404184336.png)
## 日志错误
2020-04-03 20:06:15 [PicGo INFO] [PicGo Server] shutdown
2020-04-04 16:08:25 [PicGo ERROR] TypeError: uploader duplicate id: gitee!
------Error Stack Begin------
TypeError: uploader duplicate id: gitee!
    at LifecyclePlugins.register (E:\新建文件夹\resources\app.asar\node_modules\picgo\dist\src\lib\LifecyclePlugins.js:15:19)
    at Object.register (C:\Users\qxm\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js:261:29)
    at PluginLoader.registerPlugin (E:\新建文件夹\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:62:38)
    at PluginLoader.load (E:\新建文件夹\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:54:18)
    at PicGo.init (E:\新建文件夹\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:71:31)
    at new PicGo (E:\新建文件夹\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:39:14)
    at Module.<anonymous> (E:\新建文件夹\resources\app.asar\background.js:16:35295)
    at n (E:\新建文件夹\resources\app.asar\background.js:1:110)
    at Object.<anonymous> (E:\新建文件夹\resources\app.asar\background.js:1:123163)
    at n (E:\新建文件夹\resources\app.asar\background.js:1:110)
-------Error Stack End-------
2020-04-04 16:08:27 [PicGo INFO] [PicGo Server] is listening at 36677
2020-04-04 16:08:28 [PicGo INFO] Before transform
2020-04-04 16:08:28 [PicGo INFO] Transforming...
2020-04-04 16:08:28 [PicGo INFO] Before upload
2020-04-04 16:08:28 [PicGo INFO] Uploading...
2020-04-04 16:08:28 [PicGo INFO] undefined
2020-04-04 16:08:28 [PicGo INFO] {"method":"POST","url":"https://getee.com/api/v5/repos/timelessmiss/rubbish/contents/img/20200404160828.png","headers":{"contentType":"application/json;charset=UTF-8","User-Agent":"PicGo"},"formData":{"access_token":"e2c2be1d157ee0784b584f96830c491b","content":"iVBORw0NMlFDUUpQAAASUVORK5CYII=","message":0}}
2020-04-04 16:09:09 [PicGo INFO] {"name":"RequestError","message":"Error: read ECONNRESET","cause":{"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"error":{"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"options":{"jar":{"_jar":{"version":"tough-cookie@2.4.3","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"cookies":[]}},"method":"POST","url":"https://getee.com/api/v5/repos/timelessmiss/rubbish/contents/img/20200404160828.png","headers":{"contentType":"application/json;charset=UTF-8","User-Agent":"PicGo"},"formData":{"access_token":"e2c2be1d157ee0784b584f96830c491b","content":"iVBK5CYII=","message":0},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
2020-04-04 16:09:09 [PicGo SUCCESS] 
undefined
undefined

**Comment by Molunerfinn** [comment]
duplicate id: gitee 说明你安装了两个跟gitee有关的插件，插件id冲突了导致的。但是这个不会影响最终上传结果。卸载掉其中一个就行。

这里的上传失败的原因是
![image](https://user-images.githubusercontent.com/12621342/78430477-73a48800-76a7-11ea-9b2a-e1bdb047bed7.png)

请找插件开发者，这个跟picgo无关。另外，PicGo可以单独上传说明跟PicGo本身功能无关。

**Comment by LeonG7** [comment]
好的，谢了

**Comment by Lrx20011230** [comment]
TypeError: uploader duplicate id: gitee!
    at LifecyclePlugins.register (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\LifecyclePlugins.js:17:19)
    at Object.register (C:\Users\LRX\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js:261:29)
    at PluginLoader.registerPlugin (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:78:42)
    at PluginLoader.load (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:61:18)
    at PicGo.init (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:97:32)
    at new PicGo (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:64:14)
    at Module.<anonymous> (D:\PicGo\resources\app.asar\background.js:36:27506)
    at r (D:\PicGo\resources\app.asar\background.js:1:110)
    at Object.<anonymous> (D:\PicGo\resources\app.asar\background.js:15:19041)
    at r (D:\PicGo\resources\app.asar\background.js:1:110)
<img width="760" alt="屏幕截图 2022-09-03 012604" src="https://user-images.githubusercontent.com/112327905/188206589-eaa2eba1-71ba-4d9f-9156-568757886d18.png">
picgo版本2.3.0
单独上传没问题，用picgo就会出现报错
下面是typora设置截图
<img width="599" alt="屏幕截图 2022-09-03 012801" src="https://user-images.githubusercontent.com/112327905/188206890-e9ec5a1a-a189-492d-8feb-0daefdc6e86b.png">

**Comment by Molunerfinn** [comment]
你装了两个gitee插件。卸载其中一个就行

**Comment by Lrx20011230** [comment]
<img width="585" alt="屏幕截图 2022-09-03 165559" src="https://user-images.githubusercontent.com/112327905/188263605-fcdd0c39-927e-4179-8214-87453310c9f0.png">
<img width="777" alt="屏幕截图 2022-09-03 165541" src="https://user-images.githubusercontent.com/112327905/188263607-06973f46-38fc-44a7-9515-4eeb8a24a6f9.png">
一开始显示这个报错。
RequestError: Error: connect ETIMEDOUT 8.7.198.46:443
    at new RequestError (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
插件就一个，之后上午查了报错显示是electron出问题，这个搞好之后显示这个报错
RequestError: Error: read ECONNRESET
    at new RequestError (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)

**Comment by Lrx20011230** [comment]
> 你装了两个gitee插件。卸载其中一个就行

可是我重装了，就报后来贴的错误
