### ISSUE TITLE
2.2.2版本mac版和win版bug 回退2.2.1正常

### ISSUE THREAD

**Issue by coders-47** [Molunerfinn/PicGo#459]
## 问题类型

2.2.2版本bug
## PicGo的相关信息

Mac OS 10.5.3 && Windows 10
## 问题重现

同事win10版安装2.2.2直接宕机
mac版无论是否使用代理图片均会上传失败

日志内容如下：
```
2020-04-10 17:23:25 [PicGo ERROR] RequestError: Error: tunneling socket could not be established, cause=Parse Error
------Error Stack Begin------
RequestError: Error: tunneling socket could not be established, cause=Parse Error
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at ClientRequest.onError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
-------Error Stack End-------
```

## 补充
mac版回退至2.2.1 可正常使用

**Comment by Molunerfinn** [comment]
无法复现。2.2.2在win10安装使用正常。
2.2.2对比2.2.1只修复了PicGo Server的的bug，没有修改底层上传相关的内容。

**Comment by Molunerfinn** [comment]
如果在自己的机器上确实版本影响了使用，那么就先用2.2.1吧

**Comment by coders-47** [comment]
mac os版本号写错了，是10.15.3，使用GitHub图床报上述错误，其他图床未测试。
win10是下载的[PicGo-Setup-2.2.2.exe](https://github.com/Molunerfinn/PicGo/releases/download/v2.2.2/PicGo-Setup-2.2.2.exe)安装包，在安装完后 点击finish自动启动，整个系统变灰，系统中所有正在运行的软件变为未响应状态，重启资源管理器也不行，只能强制关机

**Comment by Molunerfinn** [comment]
windows的问题不太了解，没有遇到过类似的情况...，PicGo有至少1w多的windows10用户，如果有问题应该issue区会炸。可能正好安装阶段有遇到什么系统问题才会导致这样的吧。如果再次安装还是这样就不建议继续安装了，这种情况我也不知道如何解决。
GitHub图床是不太稳定的，最近这段时间GitHub服务器应该有限频操作，所以会有上传失败的现象，这个是服务器问题，跟PicGo客户端没关系。想要稳定的话还是推荐用阿里云、腾讯云等付费服务。

**Comment by coders-47** [comment]
用之前的版本没有问题，因为限频有成功有失败，但是在今天下午两点更新了2.2.2版本后，多次尝试上传图片均失败，我以为是在github上的图床仓库出什么问题了，又新建了一个仓库，结果还是不行，最后回退到上个版本之后，问题解决。

回头再用我的机器使用2.2.2测试下阿里云的看看怎么样，到底是我机器的问题还是客户端的问题，有问题再在这里发吧。。。

**Comment by lzq1126** [comment]
2.2.2版本mac版 开了一下server 以后就无法正常提交。

**Comment by Molunerfinn** [comment]
> 2.2.2版本mac版 开了一下server 以后就无法正常提交。

server跟上传流程无关。
