### ISSUE TITLE
Upload failed sometimes.

### ISSUE THREAD

**Issue by liuhao326** [Molunerfinn/PicGo#460]
## Bug Report

This is the log：

2020-04-11 14:13:10 [PicGo INFO] Before transform
2020-04-11 14:13:10 [PicGo INFO] Transforming...
2020-04-11 14:13:10 [PicGo INFO] Before upload
2020-04-11 14:13:10 [PicGo INFO] Uploading...
2020-04-11 14:13:11 [PicGo WARN] failed
2020-04-11 14:13:11 [PicGo ERROR] RequestError: Error: read ECONNRESET
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

## PicGo的相关信息

Windows，PicGo-2.2.2

## 问题重现

It works well at the beginning，and can't upload surddenlly.
Actually，it's the second time this occur，and it suddenlly recovered last time.
My network works well.
Thanks.

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/452
https://github.com/Molunerfinn/PicGo/issues/442
