### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by guhailong18** [Molunerfinn/PicGo#468]
之前上传都是好好的，不知为何今天就不行了，求解决，而且以前上传时也经常会出现界面消失的情况，但是鼠标依然可以点击，有时候等一下就好了，但感觉上传多个图片时软件容易崩溃，顺便求一个复制多个图片自定义链接的功能，拜托啦！

## 问题类型

Bug Report

## PicGo的相关信息

Windows

## 问题重现

以下为部分日志，看不懂原因未知

---
-------Error Stack End-------
2020-04-20 23:11:36 [PicGo INFO] Before transform
2020-04-20 23:11:36 [PicGo INFO] Transforming...
2020-04-20 23:11:36 [PicGo INFO] Before upload
2020-04-20 23:11:46 [PicGo WARN] failed
2020-04-20 23:11:46 [PicGo ERROR] Error: super-prefix conflict
------Error Stack Begin------
Error: super-prefix conflict
    at Object.handle (C:\Users\神秘者\AppData\Roaming\picgo\node_modules\picgo-plugin-super-prefix\dist\index.js:45:27)
    at async D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:96:13
    at async Promise.all (index 0)
    at async Lifecycle.handlePlugins (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:95:9)
    at async Lifecycle.beforeUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:58:9)
    at async Lifecycle.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:20:13)
    at async PicGo.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------
2020-04-20 23:16:15 [PicGo INFO] Before transform
2020-04-20 23:16:15 [PicGo INFO] Transforming...
2020-04-20 23:16:15 [PicGo INFO] Before upload
2020-04-20 23:16:25 [PicGo WARN] failed
2020-04-20 23:16:25 [PicGo ERROR] Error: super-prefix conflict
------Error Stack Begin------
Error: super-prefix conflict
    at Object.handle (C:\Users\神秘者\AppData\Roaming\picgo\node_modules\picgo-plugin-super-prefix\dist\index.js:45:27)
    at async D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:96:13
    at async Promise.all (index 0)
    at async Lifecycle.handlePlugins (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:95:9)
    at async Lifecycle.beforeUpload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:58:9)
    at async Lifecycle.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:20:13)
    at async PicGo.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------

**Comment by guhailong18** [comment]
忽然发现是有个前缀插件冲突的问题，已自行解决！！
