### ISSUE TITLE
上传失败，服务端配置错误

### ISSUE THREAD

**Issue by zhouzhou84** [Molunerfinn/PicGo#483]
## 问题类型
bug report

## PicGo的相关信息
Window10 
PicGo2.2.2
github图床
![image](https://user-images.githubusercontent.com/33458022/80864970-cb3f0f00-8cb8-11ea-8697-9d8ec8839b1e.png)

## 问题重现
拖拽上传图片发送上传失败，服务端配置失败。

![image](https://user-images.githubusercontent.com/33458022/80864906-6d122c00-8cb8-11ea-90fe-96bcc92a71bd.png)

日志：
-------Error Stack End-------
2020-05-02 20:58:48 [PicGo INFO] Before transform
2020-05-02 20:58:48 [PicGo INFO] Transforming...
2020-05-02 20:58:48 [PicGo INFO] Before upload
2020-05-02 20:58:48 [PicGo INFO] Uploading...
2020-05-02 20:59:10 [PicGo WARN] failed
2020-05-02 20:59:10 [PicGo ERROR] RequestError: Error: connect ETIMEDOUT 203.208.39.104:443
------Error Stack Begin------
RequestError: Error: connect ETIMEDOUT 203.208.39.104:443
    at new RequestError (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

真的很想用这个软件，为什么我这里总是有问题，挂着T子上传也不行，不挂也不行。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/80865245-9fbd2400-8cba-11ea-85a4-05e6739fa308.png)
网络问题无能为力。

**Comment by Molunerfinn** [comment]
换gitee或者用腾讯云、阿里云之类的吧，付费的存储也不贵...

**Comment by Molunerfinn** [comment]
有梯子可以试试配置一下PicGo的代理，设置里有，不过只支持HTTP代理

**Comment by zhouzhou84** [comment]
感谢

**Comment by li-guohao** [comment]
> ![image](https://user-images.githubusercontent.com/12621342/80865245-9fbd2400-8cba-11ea-85a4-05e6739fa308.png) 网络问题无能为力。

<br><br>

我这边也有这个问题，检查了好多遍配置都没用，是tmd的被该死长城宽带域名劫持了。

报错截图：
![image](https://user-images.githubusercontent.com/46225881/192944183-7aad26b6-7d68-4fd5-8057-ce795d7b1489.png)

去TMD的长城宽带
![image](https://user-images.githubusercontent.com/46225881/192944302-b694dd38-7a35-4fe2-ba58-ddd270995c16.png)
