### ISSUE TITLE
The OSS Access Key Id you provided does not exist in our records

### ISSUE THREAD

**Issue by ShenZhenzly** [Molunerfinn/PicGo#488]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

mac2.2.2和2.3.0

## 问题重现

上传时提示上传失败，请检查配置和上传文件是否符合要求，我使用的是阿里云的OSS,该套配置在windows下的picgo2.2.2能使用，在iPic MAC版也能够使用，日志报错信息如下：
2020-05-04 20:13:55 [PicGo INFO] Before transform
2020-05-04 20:13:55 [PicGo INFO] Transforming...
2020-05-04 20:13:55 [PicGo INFO] Before upload
2020-05-04 20:13:57 [PicGo INFO] Uploading...
2020-05-04 20:13:57 [PicGo WARN] failed
2020-05-04 20:13:57 [PicGo ERROR] StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  <Code>InvalidAccessKeyId</Code>\n  <Message>The OSS Access Key Id you provided does not exist in our records.</Message>\n  <RequestId>5EB007079214783733C13E56</RequestId>\n  <HostId>wznote.oss-cn-shenzhen.aliyuncs.com</HostId>\n  <OSSAccessKeyId>1</OSSAccessKeyId>\n</Error>\n"
------Error Stack Begin------
StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  <Code>InvalidAccessKeyId</Code>\n  <Message>The OSS Access Key Id you provided does not exist in our records.</Message>\n  <RequestId>5EB007079214783733C13E56</RequestId>\n  <HostId>wznote.oss-cn-shenzhen.aliyuncs.com</HostId>\n  <OSSAccessKeyId>1</OSSAccessKeyId>\n</Error>\n"
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------
2020-05-04 20:17:39 [PicGo ERROR] Error: image not found in clipboard
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:132:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------

## 功能请求

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/80967797-8a2a3480-8e49-11ea-9dc1-efae1c9c5877.png)
配置问题，再检查一下吧。看看是不是有什么空格之类的。这个是你配置出错导致阿里云身份认证过不去，跟picgo没关系
