### ISSUE TITLE
服务端出错 GitHub图床

### ISSUE THREAD

**Issue by Innei** [Molunerfinn/PicGo#493]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report
## PicGo 的相关信息
Mac 2.2

## 问题重现
无法直接上传GitHub图床，无法使用http代理，无法使用socket5代理，上传出错如图所示。

![image](https://user-images.githubusercontent.com/41265413/81658518-6d09ed00-946b-11ea-9a18-bd67eba20758.png)

![image](https://user-images.githubusercontent.com/41265413/81658641-89a62500-946b-11ea-81af-080758596b99.png)

确保代理正常，并且通过 proxiflter 全局代理可以正常上传，关闭后无法上传，一直提示错误。

```
------Error Stack Begin------
RequestError: Error: connect ECONNREFUSED 13.250.168.23:443
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
```
![image](https://user-images.githubusercontent.com/41265413/81659089-f7525100-946b-11ea-9e64-c99a899d1334.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
FAQ 第7条
