### ISSUE TITLE
阿里云oss 配置了无作用,一直提示配置问题

### ISSUE THREAD

**Issue by mkdir700** [Molunerfinn/PicGo#498]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

Linux

## 问题重现
```
2020-05-15 22:42:11 [PicGo ERROR] RequestError: Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established
------Error Stack Begin------
RequestError: Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established
    at new RequestError (/tmp/.mount_PicGo-8hJpkN/resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/tmp/.mount_PicGo-8hJpkN/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/tmp/.mount_PicGo-8hJpkN/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/tmp/.mount_PicGo-8hJpkN/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/tmp/.mount_PicGo-8hJpkN/resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at ClientRequest.onError (/tmp/.mount_PicGo-8hJpkN/resources/app.asar/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
-------Error Stack End-------
```
上传文件,提示配置有误
![image](https://user-images.githubusercontent.com/56359329/82062734-203d4500-96fd-11ea-9c54-1e73c6ce9f37.png)

**Comment by mkdir700** [comment]
挂了梯子,系统代理的原因
PicGo设置下代理就好了
