### ISSUE TITLE
RequestError: Error: read ECONNRESET

### ISSUE THREAD

**Issue by RoddeHope** [Molunerfinn/PicGo#502]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

![image](https://user-images.githubusercontent.com/18653905/82388313-e907c480-9a6b-11ea-8b93-7095fe03e555.png)

windows平台

## 问题重现

不定时出现上传图片失败，图床为github图床

## 错误信息

------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (D:\software\assist\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\software\assist\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\software\assist\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\software\assist\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\software\assist\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

---

**Comment by Molunerfinn** [comment]
你真的看过FAQ么
