### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by skywater** [Molunerfinn/PicGo#504]
## 问题类型
Bug Report 

## PicGo 的相关信息
版本：2.3.0-beta.0
平台：windows

## 问题重现
我在issue搜到一样的问题是阿里云的报错，但我的是github做图床！！！
picGo图床我本地试过七牛云、腾讯云都没问题，但是github做图床有问题。
无论是否科学上网，都报错如下：
2020-05-20 19:55:52 [PicGo INFO] Uploading...
2020-05-20 19:55:53 [PicGo WARN] failed
2020-05-20 19:55:53 [PicGo ERROR] RequestError: Error: unable to verify the first certificate
------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (D:\root\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\root\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\root\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\root\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\root\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
![image](https://user-images.githubusercontent.com/20358885/82445405-53098380-9ad7-11ea-8400-17b492e225ed.png)

**Comment by Molunerfinn** [comment]
无解，网络问题
