### ISSUE TITLE
图片上传失败，报RequestError: Error: read ECONNRESET

### ISSUE THREAD

**Issue by zhangboyi** [Molunerfinn/PicGo#506]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
PicGo 的版本（2.3.0-beta-0)、所在平台（ Windows）

## 问题重现
<--每次上传图片就会报一下错误，图片上传失败-->
`2020-05-16 23:49:14 [PicGo INFO] Before transform
2020-05-16 23:49:14 [PicGo INFO] Transforming...
2020-05-16 23:49:14 [PicGo INFO] Before upload
2020-05-16 23:49:14 [PicGo INFO] Uploading...
2020-05-16 23:49:15 [PicGo WARN] failed
2020-05-16 23:49:15 [PicGo ERROR] RequestError: Error: read ECONNRESET
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (D:\工具\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\工具\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\工具\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\工具\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\工具\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)`

**Comment by Molunerfinn** [comment]
你真的看过FAQ吗

**Comment by STFQ** [comment]
> **声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**
> 
> ## 问题类型
> Bug Report
> 
> ## PicGo 的相关信息
> PicGo 的版本（2.3.0-beta-0)、所在平台（ Windows）
> 
> ## 问题重现
> <--每次上传图片就会报一下错误，图片上传失败-->
> `2020-05-16 23:49:14 [PicGo INFO] Before transform 2020-05-16 23:49:14 [PicGo INFO] Transforming... 2020-05-16 23:49:14 [PicGo INFO] Before upload 2020-05-16 23:49:14 [PicGo INFO] Uploading... 2020-05-16 23:49:15 [PicGo WARN] failed 2020-05-16 23:49:15 [PicGo ERROR] RequestError: Error: read ECONNRESET ------Error Stack Begin------ RequestError: Error: read ECONNRESET at new RequestError (D:\工具\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15) at Request.plumbing.callback (D:\工具\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29) at Request.RP$callback [as _callback] (D:\工具\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31) at self.callback (D:\工具\PicGo\resources\app.asar\node_modules\request\request.js:185:22) at Request.emit (events.js:200:13) at Request.onRequestError (D:\工具\PicGo\resources\app.asar\node_modules\request\request.js:881:8) at ClientRequest.emit (events.js:200:13) at TLSSocket.socketErrorListener (_http_client.js:402:9) at TLSSocket.emit (events.js:200:13) at emitErrorNT (internal/streams/destroy.js:91:8)`

我也跟你遇到了一样的问题，这个可能是因为上传的文件名重复了。我的解决办法是，进入设置然后打开时间戳重名。在FAQ已经说明过问题了
