### ISSUE TITLE
剪切版图片功能无响应

### ISSUE THREAD

**Issue by zhuhaifeng** [Molunerfinn/PicGo#512]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

 Bug Report 

## PicGo 的相关信息
2.3.0-beta.0 、window10 
 

## 问题重现

剪切版图片无法上传，信息如下：  
- 操作截图

![](https://markdown-sunfish.oss-cn-beijing.aliyuncs.com/picgo/pc/20200528191216.jpg)
- 软件没反应，日志如下：
------Error Stack Begin------
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\utils\getClipboardImage.js:45:41
    at new Promise (<anonymous>)
    at Object.getClipboardImage [as default] (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\utils\getClipboardImage.js:29:12)
    at PicGo.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:130:83)
    at Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:16:26256)
    at St (D:\Program Files\PicGo\resources\app.asar\background.js:16:34117)
    at EventEmitter.<anonymous> (D:\Program Files\PicGo\resources\app.asar\background.js:16:39367)
    at EventEmitter.emit (events.js:200:13)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
权限问题，安装的时候给管理员权限
