### ISSUE TITLE
mac2.3.0-beta.0下的两个bug: 1 剪切板上传URL图片失败 2 批量上传的问题

### ISSUE THREAD

**Issue by Simon921** [Molunerfinn/PicGo#522]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息
Version: 2.3.0-beta.0
Mac catalina 10.15.5
smms图床 token正确
## 问题重现
其他功能都可以正常使用，除了下面这两个
 ### 1 快捷键上传图片url失败
**描述**
剪切版中有图片URL，用快捷键上传会报错：
**上传失败 请检查配置和上传的文件是否符合要求**
eg.
剪切板中此时链接为
https://www.butnono.com/wp-content/uploads/2019/11/572e25c8ly1g8d15lk5gzj20rs0fmqf91-930x562.jpg
可在图形界面拖拽上传，但不能用快捷键上传
**日志内容**：
2020-06-09 11:19:41 [PicGo ERROR] Error: image not found in clipboard
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:132:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
**Debug内容**
[PicGo ERROR]: Error: image not found in clipboard
(node:6383) UnhandledPromiseRejectionWarning: Error: image not found in clipboard
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:132:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:6383) UnhandledPromiseRejectionWarning: Error: image not found in clipboard
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:132:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:6383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6383) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6383) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 2 批量上传URL失败

eg.
此时剪切板中为“|”分隔的两个URL
https://static.runoob.com/images/dashang/wechat.jpg|https://static.runoob.com/images/dashang/alipay.jpg

**快捷键上传报错日志同1**
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:132:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------

图形界面粘贴URL上传，显示正在上传，然后就没有然后了

**日志如下**
2020-06-09 11:49:42 [PicGo INFO] Before transform
2020-06-09 11:49:42 [PicGo INFO] Transforming...
2020-06-09 11:49:42 [PicGo INFO] Before upload
2020-06-09 11:49:42 [PicGo INFO] Uploading...
2020-06-09 11:49:42 [PicGo ERROR] request https://static.runoob.com/images/dashang/wechat.jpg|https://static.runoob.com/images/dashang/alipay.jpg error

有劳排查
再次感谢制作如此优秀的工具软件
---

**Comment by Molunerfinn** [comment]
1. 剪贴板必须有图片才能用剪贴板图片上传。剪贴板里是URL本来就不能用剪贴板上传的。你需要用URL上传。
2. URL上传只支持上传一个URL，从来没有说支持分隔符啊

**Comment by Simon921** [comment]
呃 那能不能直接转到 new feature request……

**Comment by Molunerfinn** [comment]
会考虑，不过最近没时间

**Comment by Simon921** [comment]
好的。期待。已打星。
