### ISSUE TITLE
archlinux下使用picgo上传图片会卡住很长时间

### ISSUE THREAD

**Issue by sunerpy** [Molunerfinn/PicGo#524]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

aur/picgo-appimage 2.2.2-1 (+3 0.13) (Installed)

archlinux 5.7.2-arch1-1

## 问题重现
archlinux桌面KDE，使用的是yay工具从aur仓库下载的picgo-appimage 2.2.2-1
当使用picgo的GUI工具上传图片时，拖拽上传表现正常，时间很快，如下文

```
2020-06-21 01:12:30 [PicGo INFO] Before transform
2020-06-21 01:12:30 [PicGo INFO] Before upload
2020-06-21 01:12:30 [PicGo INFO] Uploading...
2020-06-21 01:12:30 [PicGo SUCCESS] 

```
但是在使用剪贴板上传时，经常会出现报错，需要重复选择上传才能成功，而且最要命的问题是在使用剪贴板上传时，整个KDE界面会卡住，此时无法切换到其他程序进行工作，表现为界面异常卡顿无法进行其他操作，直至二三十秒后才能上传成功，此时界面的卡顿也随之消失，系统运行恢复正常，网络没有问题，通过上面的拖拽上传可以发现速度是很快的，300M带宽，使用的阿里云OSS做的图床，只有剪贴板上传有此现象，日志如下：

```
2020-06-21 00:52:20 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at /tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:20:28
    at async Promise.all (index 0)
    at async Object.handle (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:11:5)
    at async Lifecycle.doTransform (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:51:9)
    at async Lifecycle.start (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:19:13)
    at async PicGo.upload (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:145:21)
-------Error Stack End-------
2020-06-21 00:52:26 [PicGo INFO] Before transform
2020-06-21 00:52:26 [PicGo INFO] Transforming...
2020-06-21 00:52:26 [PicGo WARN] failed
2020-06-21 00:52:26 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at /tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:20:28
    at async Promise.all (index 0)
    at async Object.handle (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:11:5)
    at async Lifecycle.doTransform (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:51:9)
    at async Lifecycle.start (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:19:13)
    at async PicGo.upload (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:145:21)
-------Error Stack End-------
2020-06-21 00:52:26 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at /tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:20:28
    at async Promise.all (index 0)
    at async Object.handle (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:11:5)
    at async Lifecycle.doTransform (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:51:9)
    at async Lifecycle.start (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:19:13)
    at async PicGo.upload (/tmp/.mount_picgo.OFearz/resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:145:21)
-------Error Stack End-------
2020-06-21 00:52:35 [PicGo INFO] Before transform
2020-06-21 00:52:35 [PicGo INFO] Transforming...
2020-06-21 00:52:35 [PicGo INFO] Before upload
2020-06-21 00:52:35 [PicGo INFO] Uploading...
2020-06-21 00:53:00 [PicGo SUCCESS] 

```

## 功能请求

---

**Comment by Tuladingpro** [comment]
从最后的记录可以看到上传开始到结束用了25S时间，我反复实验不同图片、同一图片，包括使用wifi和以太网，都是同样的问题（剪贴板上传）

**Comment by Molunerfinn** [comment]
没遇到过是啥原因。等之后2.3.0更新，至少上面报错日志的情况不会再出现了

**Comment by Roc826** [comment]
遇到了同样的问题 manjaro-kde

**Comment by GuangDai** [comment]
问题+1 Manjaro KDE

**Comment by Molunerfinn** [comment]
用picgo-core会出现这个问题么，感觉是linux截图脚本的问题

**Comment by Empathy117** [comment]
感觉是kde桌面的问题
相同的环境我换成dwm没有这个问题 ( 截图工具用的都是flameshot, picgo版本(甚至还换了一次版本尝试) 截图内容相同, 配置信息相同, 各种环境变量也都相同)
我感觉会不会是knotify
因为我在dwm用的是dunst

**Comment by Empathy117** [comment]
> 用picgo-core会出现这个问题么，感觉是linux截图脚本的问题

应该不是, 因为不上传截图而上传图片也会有这个问题, 而且如果不用kde桌面也不会有这个问题

**Comment by guangsizhongbin** [comment]
在archlinux-ked用coc-picgo不会出现卡顿问题

**Comment by FleyX** [comment]
同样kde桌面存在这个问题，换了各种picgo版本都不好使

**Comment by chen462488588** [comment]
+1 Manjaro KDE使用AppImage包存在这个问题，桌面会卡好久，typora中使用的PIcgoCORE不存在这个问题。

**Comment by dodriveroing** [comment]
+1 很可惜KDE用户无法使用如此好用的软件（ps：已经仔细看过文档和搜索过已经关闭的issues）

**Comment by Molunerfinn** [comment]
> 

卡住的问题，剪贴板上传会遇到还是拖拽文件上传也会遇到？

**Comment by ChenSino** [comment]
> > 
> 
> 卡住的问题，剪贴板上传会遇到还是拖拽文件上传也会遇到？

我的直接粘贴的

**Comment by Molunerfinn** [comment]
> 感觉是kde桌面的问题 相同的环境我换成dwm没有这个问题 ( 截图工具用的都是flameshot, picgo版本(甚至还换了一次版本尝试) 截图内容相同, 配置信息相同, 各种环境变量也都相同) 我感觉会不会是knotify 因为我在dwm用的是dunst

看起来跟notification有点关系。后续给个配置，可以关掉notification，看看是否还会出现卡顿问题

**Comment by dodriveroing** [comment]
> > 
> 
> 卡住的问题，剪贴板上传会遇到还是拖拽文件上传也会遇到？

只有剪切板上传会卡住啦（卡10～20秒），卡完之后正常上传。（同样是试了不同网络、不同版本、不同剪切板软件）

**Comment by Molunerfinn** [comment]
可以更新最新的beta3版本

**Comment by GuangDai** [comment]
确认是KDE的问题，这个可能是长期的一个QT的bug

https://bugs.kde.org/show_bug.cgi?id=446581
