### ISSUE TITLE
切换插件不生效

### ISSUE THREAD

**Issue by tanoak10** [Molunerfinn/PicGo#550]
picGO 版本是2.2.2
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

使用gitee 的插件，设置上传， 但是看报错日志应该没有切换成功

## 问题重现

Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/plugins/uploader/smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:70:9)
    at async Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:21:13)
    at async PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:145:21)
-------Error Stack End-------
## 功能请求

---

<img width="546" alt="iShot2020-08-07下午02 43 48" src="https://user-images.githubusercontent.com/37281126/89617243-71a03f00-d8bc-11ea-8eaa-1d957f176541.png">

**Comment by tanoak10** [comment]
我试了自带的GitHub插件是可以上传并切换OK的，是不是对下载的插件上传切换有点问题

**Comment by Molunerfinn** [comment]
2.3.0-beta3已修复。
