### ISSUE TITLE
macOS 10.15 上传报错 github图床

### ISSUE THREAD

**Issue by qianmianyao** [Molunerfinn/PicGo#551]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by qianmianyao** [comment]
-------Error Stack End------- 
2020-08-10 16:18:18 [PicGo INFO] Before transform 
2020-08-10 16:18:18 [PicGo INFO] Transforming... 
2020-08-10 16:18:18 [PicGo INFO] Before upload 
2020-08-10 16:18:18 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-08-10 16:18:18 [PicGo INFO] Uploading... 
2020-08-10 16:18:22 [PicGo WARN] failed 
2020-08-10 16:18:22 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 422 - {"message":"path cannot start with a slash","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by qianmianyao** [comment]
报错，请检查配置和上传文件是否符合要求

**Comment by Molunerfinn** [comment]
请检查你自己的配置，4XX都是你自己配置错了。

**Comment by qianmianyao** [comment]
我是按照教程配置的呀
![Snipaste_2020-08-10_18-47-29.png](https://i.loli.net/2020/08/10/ywc7rSjUI41shtV.png)

**Comment by XPoet** [comment]
事实上，我也遇到同样问题，macOS，GitHub图床无法上传，配置无误，不知道原因

**Comment by Molunerfinn** [comment]
@qianmianyao 存储路径是 `img/` 不是 `/img`。

**Comment by XPoet** [comment]
@Molunerfinn 
我使用了 GitHub 图床，配置项确认无误，图片上传成功了，但并不是上传到 GitHub 的仓库里面，如下图。
![image](https://user-images.githubusercontent.com/24516169/89781119-52681280-db45-11ea-927c-5d635a1092eb.png)
![image](https://user-images.githubusercontent.com/24516169/89781143-5d22a780-db45-11ea-85fd-4df1d90de3d5.png)
![image](https://user-images.githubusercontent.com/24516169/89781155-63188880-db45-11ea-9446-10ff8baeeb03.png)
![image](https://user-images.githubusercontent.com/24516169/89781271-98bd7180-db45-11ea-8e80-d40349c199ea.png)
![image](https://user-images.githubusercontent.com/24516169/89781295-a3780680-db45-11ea-8119-f4f33e50ad7b.png)

**Comment by Molunerfinn** [comment]
更新beta3版本可以修复选中的图床无效的问题，你这个是上传到了默认的smms中去了。更新版本之后重新选择切换一下默认图床应该就OK了

**Comment by XPoet** [comment]
我使用的版本是 2.3.0-beta.3 ，刚刚按您说的重新切换了一下默认图床，默认图床为 GitHub，但还是上传不了
![image](https://user-images.githubusercontent.com/24516169/89854878-9ac81480-dbc7-11ea-8601-8589d985fcb2.png)

**Comment by Okiii-lh** [comment]
最终有解决吗？

**Comment by XPoet** [comment]
@Okiii-lh 

试试这个 https://github.com/XPoet/picx

**Comment by Molunerfinn** [comment]
上传报错建议看看报错日志...大部分问题日志里都有显示
