### ISSUE TITLE
相册里的照片删除不了，越删越多，重装升级都不起作用

### ISSUE THREAD

**Issue by Felixchen1024** [Molunerfinn/PicGo#552]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Felixchen1024** [comment]
2020-08-11 14:59:30 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"404 File Not Found"}
    at new StatusCodeError (D:\Felix\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\Felix\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\Felix\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\Felix\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\Felix\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\Felix\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
这个报错跟删除照片没有什么关系。

请说明一下你用的picgo版本，然后所谓的「删除不了，越删越多」，请提供截图或者动图说明一下？我都不知道你说的是什么意思，删了一张冒出两张么？

另外确认一下有没有用什么插件

**Comment by Felixchen1024** [comment]
卸载软件，删除文件夹：C:\Users\xxx\AppData\Roaming\picgo\
重启后重装解决。

**Comment by Felixchen1024** [comment]
> 这个报错跟删除照片没有什么关系。
> 
> 请说明一下你用的picgo版本，然后所谓的「删除不了，越删越多」，请提供截图或者动图说明一下？我都不知道你说的是什么意思，删了一张冒出两张么？
> 
> 另外确认一下有没有用什么插件

是的，删除一张，又冒出一张。。无限循环
