### ISSUE TITLE
上传图片出现错误  "message":"404 Project Not Found"

### ISSUE THREAD

**Issue by malicklin** [Molunerfinn/PicGo#556]
搜索过已经关闭的 后依然没有找到答案，所以才发了一个新的 issue。

 Bug Report

PicGo 的版本:  2.3.0 beta3  ，第三方GITEE插件
Mac  版本

想配合typora + picgo + gitee 图床， 出现以下问题，请大佬看下什么问题，谢谢！

-----Error Stack Begin------
StatusCodeError: 404 - {"message":"404 Project Not Found"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2020-08-20 22:06:39 [PicGo SUCCESS]

**Comment by Molunerfinn** [comment]
配置错了，找插件仓库提问
