### ISSUE TITLE
七牛云上传出错：token expired 25201 seconds ago（之前 OK的，没有修改配置）

### ISSUE THREAD

**Issue by zhangxiann** [Molunerfinn/PicGo#563]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

PicGo 的版本 2.2.2，所在平台 Windows

## 问题重现
我用了几个月了，七牛云，之前好好的。
我没有修改配置，今天就突然上传不了，所以不是我的配置问题。
```
2020-09-07 03:13:59 [PicGo INFO] Before transform
2020-09-07 03:13:59 [PicGo INFO] Transforming...
2020-09-07 03:13:59 [PicGo INFO] Before upload
2020-09-07 03:14:00 [PicGo INFO] Uploading...
2020-09-07 03:14:01 [PicGo WARN] failed
2020-09-07 03:14:01 [PicGo ERROR] StatusCodeError: 401 - "{\"error\":\"token expired 25201 seconds ago\"}"
------Error Stack Begin------
StatusCodeError: 401 - "{\"error\":\"token expired 25201 seconds ago\"}"
    at new StatusCodeError (D:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\Software\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\Software\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------
```

**Comment by zhangxiann** [comment]
我在 gitter 里，提了这个问题，这个需要关掉吗？

**Comment by Molunerfinn** [comment]
这个说的是你的token过期了，看看是不是七牛云更新了token规则，或者你重新申请一个token就行。

**Comment by Molunerfinn** [comment]
401的错误都是服务商认证问题，跟PicGo没关系

**Comment by zhangxiann** [comment]
> 这个说的是你的token过期了，看看是不是七牛云更新了token规则，或者你重新申请一个token就行。

谢谢你！
但是 七牛云不用什么 token 的。它用的是 Access Key 和 SecretKey
所以我有点疑惑，您说 token 是指什么？picGo 也不用配置 token，只要配置 Access Key 和 SecretKey。

**Comment by Molunerfinn** [comment]
对就是这个，重新申请一对试试

**Comment by zhangxiann** [comment]
> 对就是这个，重新申请一对试试

非常感谢您的回复！
