### ISSUE TITLE
github上传图片异常

### ISSUE THREAD

**Issue by sheungxin** [Molunerfinn/PicGo#569]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

github上传图片异常

## PicGo 的相关信息

2.3.0-beta.3 win7

## 问题重现

之前一直可用，这几天突然不好使了，看日志貌似是github要求上传文件时必须提供参数sha
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (C:\Users\user\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\user\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\user\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\user\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Users\user\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Users\user\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)

## 功能请求

---

**Comment by Molunerfinn** [comment]
说明你上传了一个同名的文件。PicGo目前不支持在github上上传同名文件，因为流程不一样，同名文件覆盖的操作比较复杂。所以建议你开启时间戳命名文件，这样就不会重名了。

**Comment by ZonuyCode** [comment]
![image](https://user-images.githubusercontent.com/57613482/97725999-c2b17f00-1b09-11eb-9e18-f8142f259ca9.png)
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'D:\Program Files (x86)\PicGo\https:\cdn.jsdelivr.net\gh\ZonuyCode\myhexo\img\安装1.png'
-------Error Stack End-------
2020-10-30 20:14:32 [PicGo INFO] [PicGo Server] shutdown
2020-10-30 20:15:17 [PicGo INFO] [PicGo Server] is listening at 36677
2020-10-30 20:28:00 [PicGo INFO] [PicGo Server] shutdown
2020-10-30 20:31:24 [PicGo INFO] [PicGo Server] is listening at 36677
2020-10-30 20:32:10 [PicGo INFO] [PicGo Server] shutdown
2020-10-30 21:32:53 [PicGo INFO] [PicGo Server] is listening at 36677
这是什么问题呀？有谁可以帮忙看一下吗？
