### ISSUE TITLE
PicGo 有时无法上传 Github 图床

### ISSUE THREAD

**Issue by LittleBirdWiki** [Molunerfinn/PicGo#570]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

Windows 10 
PicGo - 2.3.0-beta.3

## 问题重现

![image](https://user-images.githubusercontent.com/68726706/94784858-5b68b800-0401-11eb-8d6e-22c5957f040c.png)

```
2020-09-30 23:29:22 [PicGo INFO] Before transform 
2020-09-30 23:29:22 [PicGo INFO] Transforming... 
2020-09-30 23:29:22 [PicGo INFO] Before upload 
2020-09-30 23:29:22 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-09-30 23:29:22 [PicGo INFO] Uploading... 
2020-09-30 23:29:24 [PicGo WARN] failed 
2020-09-30 23:29:24 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\Xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\Xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Users\Xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
```

github token 权限 : 
![image](https://user-images.githubusercontent.com/68726706/94785193-d205b580-0401-11eb-81c3-072f7add18f2.png)

补充 : 我人在东莞，有开 V2Ray

## 功能请求

---

**Comment by Molunerfinn** [comment]
这是github服务器的问题跟picgo无关
