### ISSUE TITLE
通过typora验证图片上传,图片上传突然不行了

### ISSUE THREAD

**Issue by zjylilin** [Molunerfinn/PicGo#573]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题重现

![image](https://user-images.githubusercontent.com/22616886/96358019-3f6d5200-1135-11eb-86e4-c47157f09ab1.png)

2020-10-18 11:22:26 [PicGo INFO] Before transform 
2020-10-18 11:22:26 [PicGo INFO] Transforming... 
2020-10-18 11:22:26 [PicGo INFO] Before upload 
2020-10-18 11:22:26 [PicGo INFO] beforeUploadPlugins: watermark running 
2020-10-18 11:22:26 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-10-18 11:22:26 [PicGo INFO] {"left":673,"top":933} 
2020-10-18 11:22:26 [PicGo INFO] {"left":161,"top":421} 
2020-10-18 11:22:27 [PicGo INFO] Uploading... 
2020-10-18 11:22:33 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Invalid request.

"sha" wasn't supplied.
    at C:\Users\Administrator\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Octo.upload (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\lib\octokit.js:114:19)
    at async Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:142:5)
    at async Lifecycle.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:72:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:22:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:160:13)
-------Error Stack End------- 
2020-10-18 11:22:35 [PicGo ERROR] 
------Error Stack Begin------
HttpError: Invalid request.

"sha" wasn't supplied.
    at C:\Users\Administrator\AppData\Roaming\picgo\node_modules\@octokit\request\dist-node\index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Octo.upload (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\lib\octokit.js:114:19)
    at async Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\index.js:142:5)
    at async Lifecycle.doUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:72:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:22:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:160:13)
-------Error Stack End------- 
2020-10-18 11:22:35 [PicGo SUCCESS]

**Comment by Molunerfinn** [comment]
GitHub图床不能上传同名文件。

**Comment by zjylilin** [comment]
error中看不出这个提示

**Comment by Molunerfinn** [comment]
上传同名文件，GitHub会报这个错
![image](https://user-images.githubusercontent.com/12621342/96358398-5ca41f80-1139-11eb-9e2a-b546523c8ecf.png)

**Comment by Molunerfinn** [comment]
FAQ里已经说明了，GitHub上传同名文件会有报错的。如果用GitHub图床又不想报错的，建议开启时间戳重命名

**Comment by zjylilin** [comment]
ok
