### ISSUE TITLE
腾讯云配置求助，已看过完整配置手册

### ISSUE THREAD

**Issue by lionheart2133** [Molunerfinn/PicGo#576]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report 

## PicGo 的相关信息

windows版 2.3.0 beta3 
## 问题重现

配置完成后一直提示上传失败，相同的配置在腾讯云自带的COS客户端就可以成功使用，已多次确认复制后有无空格
![pic.JPG](https://i.loli.net/2020/10/28/dJlaTb32FoKQMyn.jpg)

附日志：
2020-10-28 11:12:10 [PicGo INFO] [PicGo Server] is listening at 36677 
2020-10-28 11:13:04 [PicGo INFO] Before transform 
2020-10-28 11:13:04 [PicGo INFO] Transforming... 
2020-10-28 11:13:04 [PicGo INFO] Before upload 
2020-10-28 11:13:04 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-10-28 11:13:04 [PicGo INFO] Uploading... 
2020-10-28 11:13:04 [PicGo WARN] failed 
2020-10-28 11:13:04 [PicGo ERROR] 
------Error Stack Begin------
Error: Upload failed
    at Object.handle (xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:114:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:72:9)
    at async Lifecycle.start (xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:22:13)
    at async PicGo.upload (xxx\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:160:13)

**Comment by Molunerfinn** [comment]
看了一下COS这边的报错日志，需要做一下修改才能更清晰。
https://github.com/PicGo/PicGo-Core/blob/dev/src/plugins/uploader/tcyun.ts#L141-L146

目前上传失败了之后，会有个系统弹窗，你可以点击windows右下角的系统通知按钮查看所有的系统通知，里面应该有比较详细的错误信息：
![image](https://user-images.githubusercontent.com/12621342/97392010-96d0a680-191b-11eb-96b2-705dcb3b0998.png)

把那个错误信息截图上传看看

**Comment by lionheart2133** [comment]
点击以后通知直接消失，没有出现任何窗口

**Comment by Molunerfinn** [comment]
不是点通知本身，是windows系统最右下角有个按钮点了能出现历史通知列表，可以看看里面有个通知能显示错误信息。

**Comment by lionheart2133** [comment]
只出现了两个通知
![pic2](https://user-images.githubusercontent.com/27777034/97400329-e4541000-1929-11eb-85fb-051a1e8fede6.png)

**Comment by Molunerfinn** [comment]
那就不知道了，没有遇到过。等下个版本更新吧

**Comment by lionheart2133** [comment]
噢，真是让人迷茫。。。多谢

**Comment by xldeng-chn** [comment]
> 噢，真是让人迷茫。。。多谢

我也遇到这个问题，之后去用Picgo-core就ok了，有可能是Picgo没配置上

**Comment by lionheart2133** [comment]
> > 噢，真是让人迷茫。。。多谢
> 
> 我也遇到这个问题，之后去用Picgo-core就ok了，有可能是Picgo没配置上

多谢，电脑上没装node.js
我后来发现自己博客主题附带的主题插件，在配置后可以在写文章时自动将图片上传至服务器和腾讯云，前台解析图片地址也是直接指向腾讯云的，更方便，于是就不再使用这个了
