### ISSUE TITLE
上传到 github 图床经常失败，报错为 connect ECONNREFUSED

### ISSUE THREAD

**Issue by deagon** [Molunerfinn/PicGo#582]
## 问题类型

Bug Report

## PicGo 的相关信息

Version: 2.3.0-beta.0
OS: macos 10.14.2

## 问题重现

第一次上传图片是成功的，然后继续上传就会失败，过一会儿（10分钟或半小时）再上传就又成功了。

这个不知道是 github 服务器的限制还是客户端 BUG？（几个月前还可以正常使用无此问题）

---

日志如下：

---

```
2020-11-05 15:00:52 [PicGo INFO] Before transform
2020-11-05 15:00:52 [PicGo INFO] Transforming...
2020-11-05 15:00:52 [PicGo INFO] Before upload
2020-11-05 15:00:55 [PicGo SUCCESS] 
https://raw.githubusercontent.com/deagon/img/master/2020/20201105150052.png
2020-11-05 15:16:34 [PicGo INFO] Before transform
2020-11-05 15:16:34 [PicGo INFO] Before upload
2020-11-05 15:16:34 [PicGo INFO] Uploading...
2020-11-05 15:16:34 [PicGo WARN] failed
2020-11-05 15:16:34 [PicGo ERROR] RequestError: Error: connect ECONNREFUSED 13.250.168.23:443
------Error Stack Begin------
RequestError: Error: connect ECONNREFUSED 13.250.168.23:443
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
```

---

**Comment by Molunerfinn** [comment]
FAQ里已经说了，这是GitHub的网络问题，PicGo无法解决。
