### ISSUE TITLE
设置github为默认图床 报错

### ISSUE THREAD

**Issue by dream-approaching** [Molunerfinn/PicGo#585]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息

PicGo版本：2.3.0-beta.3
所在平台：windows 10

## 问题重现

刚下载安装包是可以使用的，但默认会上传的图片地址是`https://i.loli.net/`，查看了其他issues，看到是因为默认图床为SM.MS的问题

然后我把默认图床改为github，这时候就传不上去了，配置信息：
![image](https://user-images.githubusercontent.com/22695534/98892607-a6cfb500-24db-11eb-85c1-3d2afb36ea8c.png)

日志信息：
```
2020-11-12 11:30:50 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
    at new StatusCodeError (D:\picGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\picGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\picGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\picGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
```

## 期望效果
希望github图床能上传成功，并且图片显示在github仓库中（以前mac上是可以的，但是换电脑了，忘记配置了，也不记得用的哪个版本了）

**Comment by Molunerfinn** [comment]
好好看看文档吧，你仓库名就是设置错的。

**Comment by dream-approaching** [comment]
> 好好看看文档吧，你仓库名就是设置错的。

尴尬，打扰了。仓库名填错了
贴个文档吧，自勉，[GitHub图床](https://picgo.github.io/PicGo-Doc/zh/guide/config.html#github%E5%9B%BE%E5%BA%8A)
```js
{
  "repo": "", // 仓库名，格式是username/reponame
  "token": "", // github token
  "path": "", // 自定义存储路径，比如img/
  "customUrl": "", // 自定义域名，注意要加http://或者https://
  "branch": "" // 分支名，默认是master
}
```
同时感谢大佬回复 @Molunerfinn

**Comment by huangchaof** [comment]
设置repo，如果是直接复制下面这个，**实际填入的repo名会有空格**，打开picgo配置文件可以看到
![image](https://user-images.githubusercontent.com/42507015/99641696-95f7e400-2a85-11eb-8d1c-cf3750f785d0.png)
![image](https://user-images.githubusercontent.com/42507015/99641988-f0914000-2a85-11eb-8744-7f758a8aa799.png)
日志报错如下：
![image](https://user-images.githubusercontent.com/42507015/99642657-b4aaaa80-2a86-11eb-94b2-2702fa69e47e.png)


重新填入无空格的repo，点击“确定”就修改好了。

**Comment by wwwjun** [comment]
注意分支 以前默认是master 现在GitHub默认是main 分支，修改成main就行了
