### ISSUE TITLE
关于picgo的新问题

### ISSUE THREAD

**Issue by lebron-bo** [Molunerfinn/PicGo#605]
提问之前请注意你看过 FAQ、配置手册以及那些被关闭的 issues。

## PicGo 的相关信息
PicGo 的版本2.3.0-beta1、Windows 10

## 问题重现
2020-12-31 18:14:35 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:150:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2020-12-31 18:14:36 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:150:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2020-12-31 18:25:22 [PicGo INFO] Before transform 
2020-12-31 18:25:22 [PicGo INFO] Transforming... 
2020-12-31 18:25:22 [PicGo INFO] Before upload 
2020-12-31 18:25:22 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-12-31 18:25:22 [PicGo INFO] Uploading... 
2020-12-31 18:25:24 [PicGo WARN] failed 
2020-12-31 18:25:24 [PicGo ERROR] 
不知道哪里出现了 问题 找不到

 -->

**Comment by Molunerfinn** [comment]
image not found in clipboard
剪贴板里没图片啊...

**Comment by lebron-bo** [comment]
> 无法在剪贴板
> 里里没图片上找到图片...

谢谢版主 我是纯小白给你添加麻烦了 
又出现了新问题  错误404这是配置错误吗
以下是日志
--Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (E:\picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (E:\picgo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (E:\picgo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by lebron-bo** [comment]
![QQ截图20210102091100](https://user-images.githubusercontent.com/76761554/103448878-a92fdd80-4cda-11eb-8364-5d1d0b464eac.png)
![QQ截图20210102091158](https://user-images.githubusercontent.com/76761554/103448880-aaf9a100-4cda-11eb-8dbe-a651a8301187.png)

**Comment by Molunerfinn** [comment]
指定存储路径后面要加个/

**Comment by lebron-bo** [comment]
依旧还是同样错误 我以前是有的  删了添上都不可以

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/103449241-8ef8fe00-4ce0-11eb-9872-e9eaa38649a6.png)
你就没有这个仓库啊。如果你创建的是私有仓库，picgo就算上传了你也无法将其用作图床，因为别人看不到。

所以请创建一个共有仓库来做存储。如果不想上传的图片列表被别人看到，请使用收费的云存储。

**Comment by lebron-bo** [comment]
已经创建数据库
![image](https://user-images.githubusercontent.com/76761554/103449482-cd43ec80-4ce3-11eb-8469-f3340a02311b.png)
picgo图床设置也换了
![QQ截图20210102101649](https://user-images.githubusercontent.com/76761554/103449495-e2208000-4ce3-11eb-98c2-7a24211152d0.png)
日志还是刚才的问题
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (E:\picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (E:\picgo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (E:\picgo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
你的名字是lebron不是leborn吧兄弟...

**Comment by lebron-bo** [comment]
真是大马虎  晦气
真心谢谢大佬的耐心   可以了 很感谢我搞了3天 真的谢谢

**Comment by little-haifeng** [comment]
![image](https://user-images.githubusercontent.com/75007778/140322706-e718b387-d239-48aa-8b3c-463a6add51a8.png)
换了新电脑就不行了
