### ISSUE TITLE
为什么设置都是好的一直报这个错·······

### ISSUE THREAD

**Issue by duolawag** [Molunerfinn/PicGo#606]
2021-01-12 00:10:01 [PicGo INFO] Before transform
2021-01-12 00:10:01 [PicGo INFO] Transforming...
2021-01-12 00:10:01 [PicGo INFO] Before upload
2021-01-12 00:10:01 [PicGo INFO] Uploading...
2021-01-12 00:10:04 [PicGo WARN] failed
2021-01-12 00:10:04 [PicGo ERROR] StatusCodeError: 404 - {"message":"Branch master not found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Branch master not found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (D:\soft\picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\soft\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\soft\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\soft\picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\soft\picgo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\soft\picgo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by duolawag** [comment]
![image](https://user-images.githubusercontent.com/69342654/104209424-a7011800-546c-11eb-859e-072684c951a4.png)

**Comment by duolawag** [comment]
点击code下面的main，在输入框里输入  master  ，就行了······（蠢了蠢了）
