### ISSUE TITLE
配置github图床报错：branch master not found

### ISSUE THREAD

**Issue by linuxcpp** [Molunerfinn/PicGo#608]
声明：我已经仔细看过 文档、FAQ、和搜索过已经关闭的 issues 后依然没有找到答案，所以才发了一个新的 issue。

在没有配置gitee图床的情况下，个人首先应用了 github图床。配置也照着网上千篇一律的设置。但是测试就是不成功。
github配置信息如下：
    "github": {
      "branch": "master",
      "customUrl": "https://cdn.jsdelivr.net/gh/linuxcpp/images",
      "path": "2021/",
      "repo": "linuxcpp/images",
      "token": "3……c"
    },
上述配置中token隐去，总是报错找不到仓库，仓库设置是public 没有问题的。
问题类型
2021-01-13 15:05:06 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-01-13 15:11:36 [PicGo INFO] Before transform 
2021-01-13 15:11:36 [PicGo INFO] Transforming... 
2021-01-13 15:11:36 [PicGo INFO] Before upload 
2021-01-13 15:11:36 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 15:11:36 [PicGo INFO] Uploading... 
2021-01-13 15:11:44 [PicGo WARN] failed 
2021-01-13 15:11:44 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Branch master not found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (D:\programs\picGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\programs\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\programs\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\programs\picGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\programs\picGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\programs\picGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 

PicGo 的相关信息
PicGo 的版本：2.3.0-b4
所在平台: Windows7 64位

**Comment by Molunerfinn** [comment]
你仔细看看文档吧。现在github没有master分支了，只有main分支- -

**Comment by linuxcpp** [comment]
> 你仔细看看文档吧。现在github没有master分支了，只有main分支- -

收到，看到网上好多教程都是master，关键程序默认提示也是master

**Comment by Molunerfinn** [comment]
> > 你仔细看看文档吧。现在github没有master分支了，只有main分支- -
> 
> 收到，看到网上好多教程都是master，关键程序默认提示也是master

输入框中的placeholder里的master会在下个版本里改为main，感谢提醒
