### ISSUE TITLE
相册中无效图片无法删除

### ISSUE THREAD

**Issue by whjysh** [Molunerfinn/PicGo#609]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题重现

**相册中无效的图片无法正常删除，越删越多**

![image](https://user-images.githubusercontent.com/40263315/104543105-bf855400-565f-11eb-9cb4-55903a896448.png)

![image](https://user-images.githubusercontent.com/40263315/104543015-8fd64c00-565f-11eb-88d5-d064f466d5b1.png)

![image](https://user-images.githubusercontent.com/40263315/104543049-a41a4900-565f-11eb-9e5d-ea0cabde8f8f.png)

**日志文件**
```
2021-01-13 23:23:53 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-01-13 23:24:46 [PicGo SUCCESS] 插件安装成功 
2021-01-13 23:26:08 [PicGo INFO] Before transform 
2021-01-13 23:26:08 [PicGo INFO] Transforming... 
2021-01-13 23:26:08 [PicGo INFO] Before upload 
2021-01-13 23:26:08 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:26:15 [PicGo INFO] Uploading... 
2021-01-13 23:26:15 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found Project"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-13 23:26:15 [PicGo SUCCESS] 
 
2021-01-13 23:26:38 [PicGo INFO] Before transform 
2021-01-13 23:26:38 [PicGo INFO] Transforming... 
2021-01-13 23:26:38 [PicGo INFO] Before upload 
2021-01-13 23:26:38 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:26:40 [PicGo INFO] Uploading... 
2021-01-13 23:26:40 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found Project"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-13 23:26:40 [PicGo SUCCESS] 
 
2021-01-13 23:26:48 [PicGo INFO] Before transform 
2021-01-13 23:26:48 [PicGo INFO] Transforming... 
2021-01-13 23:26:48 [PicGo INFO] Before upload 
2021-01-13 23:26:48 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:26:50 [PicGo INFO] Uploading... 
2021-01-13 23:26:50 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found Project"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-13 23:26:50 [PicGo SUCCESS] 
 
2021-01-13 23:27:14 [PicGo INFO] Before transform 
2021-01-13 23:27:14 [PicGo INFO] Transforming... 
2021-01-13 23:27:14 [PicGo INFO] Before upload 
2021-01-13 23:27:14 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:27:15 [PicGo INFO] Uploading... 
2021-01-13 23:27:16 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found Project"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-13 23:27:16 [PicGo SUCCESS] 
 
2021-01-13 23:28:19 [PicGo INFO] [PicGo Server] shutdown 
2021-01-13 23:28:24 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:150:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2021-01-13 23:28:25 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:150:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2021-01-13 23:28:31 [PicGo INFO] Before transform 
2021-01-13 23:28:31 [PicGo INFO] Transforming... 
2021-01-13 23:28:31 [PicGo INFO] Before upload 
2021-01-13 23:28:31 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:28:32 [PicGo INFO] Uploading... 
2021-01-13 23:28:32 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found Project"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-13 23:28:32 [PicGo SUCCESS] 
 
2021-01-13 23:29:55 [PicGo INFO] Before transform 
2021-01-13 23:29:55 [PicGo INFO] Transforming... 
2021-01-13 23:29:56 [PicGo INFO] Before upload 
2021-01-13 23:29:56 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:29:57 [PicGo INFO] Uploading... 
2021-01-13 23:29:57 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found Project"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-13 23:29:57 [PicGo SUCCESS] 
 
2021-01-13 23:30:42 [PicGo INFO] Before transform 
2021-01-13 23:30:42 [PicGo INFO] Transforming... 
2021-01-13 23:30:42 [PicGo INFO] Before upload 
2021-01-13 23:30:42 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:30:44 [PicGo INFO] Uploading... 
2021-01-13 23:30:44 [PicGo SUCCESS] 
https://gitee.com/ushai/yunhaiblog/raw/master/img/20210113233042.png 
2021-01-13 23:31:17 [PicGo INFO] Before transform 
2021-01-13 23:31:17 [PicGo INFO] Transforming... 
2021-01-13 23:31:17 [PicGo INFO] Before upload 
2021-01-13 23:31:17 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:31:18 [PicGo INFO] Uploading... 
2021-01-13 23:31:18 [PicGo SUCCESS] 
https://gitee.com/ushai/yunhaiblog/raw/master/blog/20210113233117.png 
2021-01-13 23:36:29 [PicGo INFO] Before transform 
2021-01-13 23:36:29 [PicGo INFO] Transforming... 
2021-01-13 23:36:29 [PicGo INFO] Before upload 
2021-01-13 23:36:29 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:36:31 [PicGo INFO] Uploading... 
2021-01-13 23:36:31 [PicGo SUCCESS] 
https://gitee.com/ushai/yunhaiblog/raw/master/hibiu/host/20210113233629.png 
2021-01-13 23:38:12 [PicGo INFO] Before transform 
2021-01-13 23:38:12 [PicGo INFO] Transforming... 
2021-01-13 23:38:12 [PicGo INFO] Before upload 
2021-01-13 23:38:12 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-13 23:38:14 [PicGo INFO] Uploading... 
2021-01-13 23:38:14 [PicGo SUCCESS] 
https://gitee.com/ushai/yunhaiblog/raw/master/jiaocheng/20210113233812.png 
2021-01-14 11:26:46 [PicGo INFO] [PicGo Server] shutdown 
2021-01-14 11:26:46 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-01-14 11:26:49 [PicGo INFO] Before transform 
2021-01-14 11:26:49 [PicGo INFO] Transforming... 
2021-01-14 11:26:49 [PicGo INFO] Before upload 
2021-01-14 11:26:49 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-14 11:26:57 [PicGo INFO] Uploading... 
2021-01-14 11:26:58 [PicGo SUCCESS] 
https://gitee.com/ushai/yunhaiblog/raw/master/host/swapidc/20210114112649.png
https://gitee.com/ushai/yunhaiblog/raw/master/host/swapidc/20210114112650.png 
2021-01-14 11:32:57 [PicGo INFO] Before transform 
2021-01-14 11:32:57 [PicGo INFO] Transforming... 
2021-01-14 11:32:57 [PicGo INFO] Before upload 
2021-01-14 11:32:57 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-14 11:33:05 [PicGo INFO] Uploading... 
2021-01-14 11:33:06 [PicGo SUCCESS] 
https://gitee.com/ushai/yunhaiblog/raw/master/host/swapidc/20210114113257.png 
2021-01-14 11:33:19 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:33:23 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:33:26 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:33:34 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:34:02 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:34:12 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:34:12 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:34:12 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:34:49 [PicGo INFO] [PicGo Server] shutdown 
2021-01-14 11:34:52 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-01-14 11:36:24 [PicGo SUCCESS] 插件安装成功 
2021-01-14 11:37:39 [PicGo INFO] Before transform 
2021-01-14 11:37:39 [PicGo INFO] Transforming... 
2021-01-14 11:37:39 [PicGo INFO] Before upload 
2021-01-14 11:37:39 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-14 11:37:39 [PicGo INFO] beforeUploadPlugins: watermark running 
2021-01-14 11:37:39 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot read property 'split' of undefined
    at Object.exports.getCoordinateByPosition (C:\Users\shai\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\util.js:18:34)
    at C:\Users\shai\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\output.js:18:35
    at async Promise.all (index 0)
    at async Object.exports.outputGen (C:\Users\shai\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\output.js:13:20)
    at async Object.handle (C:\Users\shai\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\index.js:40:22)
    at async C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:103:17
    at async Promise.all (index 1)
    at async Lifecycle.handlePlugins (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:100:9)
    at async Lifecycle.beforeUpload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:60:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
-------Error Stack End------- 
2021-01-14 11:37:39 [PicGo ERROR] beforeUploadPlugins: watermark error 
2021-01-14 11:37:39 [PicGo WARN] failed 
2021-01-14 11:37:39 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (C:\Users\shai\AppData\Roaming\picgo\node_modules\picgo-plugin-watermark\lib\index.js:55:15)
-------Error Stack End------- 
2021-01-14 11:38:13 [PicGo SUCCESS] 插件更新成功 
2021-01-14 11:38:18 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-01-14 11:43:01 [PicGo INFO] Before transform 
2021-01-14 11:43:01 [PicGo INFO] Transforming... 
2021-01-14 11:43:01 [PicGo INFO] Before upload 
2021-01-14 11:43:01 [PicGo INFO] beforeUploadPlugins: watermark running 
2021-01-14 11:43:01 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-01-14 11:43:01 [PicGo INFO] {"left":240,"top":146} 
2021-01-14 11:43:04 [PicGo INFO] Uploading... 
2021-01-14 11:43:04 [PicGo SUCCESS] 
https://gitee.com/ushai/yunhaiblog/raw/master/host/study/20210114114300.png 
2021-01-14 11:43:32 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:43:48 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:43:50 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:43:52 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-01-14 11:43:58 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"File"}
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 

```

## 功能请求

---

**Comment by Molunerfinn** [comment]
找gitee插件去

**Comment by whjysh** [comment]
> 找gitee插件去
用的就是gitee图床插件，比如上传成功可以自行删除，但当切换路径后或者云端自主删除，picgo中的图片就失效了，便无法删除相册中无效图片

**Comment by Molunerfinn** [comment]
我的意思是删除不成功是gitee插件的问题
找他提issue

**Comment by whjysh** [comment]
> 我的意思是删除不成功是gitee插件的问题
> 找他提issue

好的，多谢。

**Comment by hotspring-zwb** [comment]
1. 遇到了同样的问题，gitee 重新配置无效，卸载插件无效，重新安装 picgo 还是无效，感觉应该是picgo 的问题，插件都卸载了，删除还是越删越多，最后 找了个方法处理， 删词 picgo 在windows 下的缓存目录可以了
2. picgo 每次拉取图片是从新远端拉取吗？图片太多了，会做分页吗

**Comment by Molunerfinn** [comment]
> 1. 遇到了同样的问题，gitee 重新配置无效，卸载插件无效，重新安装 picgo 还是无效，感觉应该是picgo 的问题，插件都卸载了，删除还是越删越多，最后 找了个方法处理， 删词 picgo 在windows 下 C:\Users\Administrator\AppData\Roaming\picgo 缓存目录重装 picgo 可以了
> 2. picgo 每次拉取图片是从新远端拉取吗？图片太多了，会做分页吗

gitee插件做了删除的监听，并会对删除失败的图片做处理，但是处理得不对导致相册会删除的越来越多。

https://github.com/zhanghuid/picgo-plugin-gitee/blob/master/src/index.js#L108-L110

每次拉取图片都是从本地存储的配置文件data.json中读取的。

未来相册列表会和配置文件分开成两个文件。插件只能获取相册列表但是无法对相册列表操作，这样能避免相册被插件误删、误加等情况。
