### ISSUE TITLE
腾讯云COS上传出错

### ISSUE THREAD

**Issue by jonecns** [Molunerfinn/PicGo#638]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
上传失败遇到403 SignatureDoesNotMatch错误

## PicGo 的相关信息
Version 2.3.0-beta.4

OS: Windows10
## 问题重现
```
2021-03-07 18:33:13 [PicGo INFO] [PicGo Server] shutdown 
2021-03-07 18:33:34 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-03-07 18:34:17 [PicGo INFO] Before transform 
2021-03-07 18:34:17 [PicGo INFO] Transforming... 
2021-03-07 18:34:17 [PicGo INFO] Before upload 
2021-03-07 18:34:17 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-03-07 18:34:17 [PicGo INFO] Uploading... 
2021-03-07 18:34:17 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 403 - "<?xml version='1.0' encoding='utf-8' ?>\n<Error>\n\t<Code>SignatureDoesNotMatch</Code>\n\t<Message>The Signature you specified is invalid.</Message>\n\t<StringToSign>sha1\n1615113257;1615199657\nc7503b92a8581b3f3f68c8f7f64a8917b03a1a95\n</StringToSign>\n\t<FormatString>put\n/imagesresume-zh en_页面_1.png\n\nhost=o2-1258123310.cos.ap-beijing.myqcloud.com\n</FormatString>\n\t<Resource>o2-00000000.cos.ap-beijing.myqcloud.com/imagesresume-zh+en_页面_1.png</Resource>\n\t<RequestId>NjA0NGFjMmFfZTViOTJhMDlfMjA0NDlfNzU0MzM4NQ==</RequestId>\n\t<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNzgzOTgwNzViNjMzYmIzOWU0OGIzNDBiMjIxNTkwZTk=</TraceId>\n</Error>\n\n"
    at new StatusCodeError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
```

## 功能请求

---

**Comment by Molunerfinn** [comment]
403是你配置错了

**Comment by GoodEnoughL** [comment]
我在阿里云上遇到同样的错误，参考文章https://www.manongdao.com/article-2006237.html
发现是密码复制的时候多出了空格，重新复制后解决了错误
