### ISSUE TITLE
七牛云,无法上传图片 

### ISSUE THREAD

**Issue by fe1w0** [Molunerfinn/PicGo#643]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report 
七牛云,无法上传图片 
## PicGo 的相关信息
环境如下:
Windows,clash(确定关闭)
## 问题重现
日志中的报错信息
```
2021-03-26 19:11:07 [PicGo INFO] Before transform 
2021-03-26 19:11:07 [PicGo INFO] Transforming... 
2021-03-26 19:11:07 [PicGo INFO] Before upload 
2021-03-26 19:11:07 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-03-26 19:11:07 [PicGo INFO] Uploading... 
2021-03-26 19:11:07 [PicGo WARN] failed 
2021-03-26 19:11:07 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: Invalid protocol: 127.0.0.1:
    at new RequestError (F:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (F:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (F:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (F:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.init (F:\PicGo\resources\app.asar\node_modules\request\request.js:458:17)
    at Request.RP$initInterceptor [as init] (F:\PicGo\resources\app.asar\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (F:\PicGo\resources\app.asar\node_modules\request\request.js:127:8)
    at request (F:\PicGo\resources\app.asar\node_modules\request\index.js:53:10)
    at Request.request (F:\PicGo\resources\app.asar\node_modules\request\index.js:100:12)
-------Error Stack End------- 
```

**Comment by Molunerfinn** [comment]
picgo里的代理设置设置错了吧？

**Comment by Molunerfinn** [comment]
重新设置一下代理设置（清空也行），然后确定完重启一下picgo

**Comment by fe1w0** [comment]
我重启电脑后,picgo才可以使用配置的代理。但确实是代理问题,谢谢作者
