### ISSUE TITLE
安装完watermark插件，PICGO时间戳功能就用不了

### ISSUE THREAD

**Issue by CODESSHELL** [Molunerfinn/PicGo#651]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

PicGo 的版本 2.3.0 beta5、所在平台（Windows）

## 问题重现

安装完插件后，时间戳重命名失效，导致上传图片报错，因为文件名相同。

2021-04-11 04:13:44 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-04-11 04:13:49 [PicGo INFO] Before transform 
2021-04-11 04:13:49 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 04:13:49 [PicGo INFO] Before upload 
2021-04-11 04:13:49 [PicGo INFO] beforeUploadPlugins: watermark running 
2021-04-11 04:13:49 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 04:13:49 [PicGo INFO] {"left":1036,"top":668} 
2021-04-11 04:13:49 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 04:13:50 [PicGo WARN] failed 
2021-04-11 04:13:50 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (C:\Users\Google\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\Google\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\Google\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\Google\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Users\Google\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Users\Google\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 

## 功能请求

---

**Comment by Molunerfinn** [comment]
https://github.com/fhyoga/picgo-plugin-watermark/issues/19

是watermark处理的问题，它会重新根据文件路径覆写fileName，导致rename（重命名）失效。

这个是插件问题，去那边跟进。
