### ISSUE TITLE
UPLOAD FAILED

### ISSUE THREAD

**Issue by istek** [Molunerfinn/PicGo#652]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

Windows 10
PicGo v2.3.0-beta5

## 问题重现

使用github作为图床，上传失败，下面是失败日志

```
2021-04-11 15:20:27 [PicGo INFO] Before transform 
2021-04-11 15:20:27 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 15:20:27 [PicGo INFO] Before upload 
2021-04-11 15:20:27 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 15:20:27 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 15:20:27 [PicGo WARN] failed 
2021-04-11 15:20:27 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
2021-04-11 15:23:01 [PicGo INFO] Before transform 
2021-04-11 15:23:01 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 15:23:01 [PicGo INFO] Before upload 
2021-04-11 15:23:01 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 15:23:01 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 15:23:01 [PicGo WARN] failed 
2021-04-11 15:23:01 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
2021-04-11 15:23:13 [PicGo INFO] Before transform 
2021-04-11 15:23:13 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 15:23:13 [PicGo INFO] Before upload 
2021-04-11 15:23:13 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 15:23:13 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 15:23:14 [PicGo WARN] failed 
2021-04-11 15:23:14 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
2021-04-11 15:23:46 [PicGo INFO] Before transform 
2021-04-11 15:23:46 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 15:23:46 [PicGo INFO] Before upload 
2021-04-11 15:23:46 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 15:23:46 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 15:23:46 [PicGo WARN] failed 
2021-04-11 15:23:46 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
2021-04-11 15:28:14 [PicGo INFO] Before transform 
2021-04-11 15:28:14 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 15:28:14 [PicGo INFO] Before upload 
2021-04-11 15:28:14 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 15:28:14 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 15:28:15 [PicGo WARN] failed 
2021-04-11 15:28:15 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
2021-04-11 15:28:23 [PicGo INFO] [PicGo Server] shutdown 
2021-04-11 15:28:28 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-04-11 15:28:32 [PicGo INFO] Before transform 
2021-04-11 15:28:32 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 15:28:32 [PicGo INFO] Before upload 
2021-04-11 15:28:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 15:28:32 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 15:28:33 [PicGo WARN] failed 
2021-04-11 15:28:33 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
2021-04-11 15:29:13 [PicGo INFO] Before transform 
2021-04-11 15:29:13 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-11 15:29:13 [PicGo INFO] Before upload 
2021-04-11 15:29:13 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-11 15:29:13 [PicGo INFO] Uploading... Current uploader is [github] 
2021-04-11 15:29:14 [PicGo WARN] failed 
2021-04-11 15:29:14 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketOnEnd (_http_client.js:436:9)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
-------Error Stack End------- 
```

**Comment by Molunerfinn** [comment]
FAQ里有说 `RequestError: Error: socket hang up` ，这跟你的网络有关系，请检查是否有代理等设置。
