### ISSUE TITLE
作者你好呀！我想请教一下关于图片上传的报错：uploader duplicate id: gitee!

### ISSUE THREAD

**Issue by lin-xibin** [Molunerfinn/PicGo#655]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**  
## 问题类型  
 
图片上传报错  
## PicGo 的相关信息  

 * Windows10 
 * PicGo-2.2.2 
 * 图床-Gitee 
 * 使用插件-`gitee 2.0.3` picgo uploader for gitee (zhanghuid)   
 
 ## 问题重现  
  
 
 
![1](https://gitee.com/lin-xibin/image-repository/raw/master/img/1.jpg) 
> Typora验证上传图片  

![2](https://gitee.com/lin-xibin/image-repository/raw/master/img/2.jpg) 
> PicGo图床设置 

 如上，图床设置没有任何问题，因为两天前就已经使用过PicGo上传了10来张图片到Gitee，昨天突然就失灵了。 
查看日志文件，系统报错id重复——可是我的图片命名也没有出现重复
> 2021-04-20 12:04:44 [PicGo ERROR] TypeError: uploader duplicate id: gitee! 
------Error Stack Begin------ 
2021-04-20 12:04:44 [PicGo ERROR] TypeError: uploader duplicate id: gitee!
------Error Stack Begin------
> TypeError: uploader duplicate id: gitee!
    at LifecyclePlugins.register (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\LifecyclePlugins.js:15:19)
    at Object.register (C:\Users\santi\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js:261:29)
    at PluginLoader.registerPlugin (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:62:38)
    at PluginLoader.load (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:54:18)
    at PicGo.init (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:71:31)
    at new PicGo (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:39:14)
    at Module.<anonymous> (D:\PicGo\resources\app.asar\background.js:16:35295)
    at n (D:\PicGo\resources\app.asar\background.js:1:110)
    at Object.<anonymous> (D:\PicGo\resources\app.asar\background.js:1:123163)
    at n (D:\PicGo\resources\app.asar\background.js:1:110)
-------Error Stack End-------

## 最后
期待你的答复：）

**Comment by Molunerfinn** [comment]
插件设置里，看看是不是装了两个gitee相关的插件，卸载其中一个

**Comment by lin-xibin** [comment]
> 插件设置里，看看是不是装了两个gitee相关的插件，卸载其中一个

并没有，只安装了一个，我知道两个会有冲突的。

**Comment by Molunerfinn** [comment]
这个问题只有在两个插件同时注册了同样的叫做gitee id的uploader才会出现

**Comment by lin-xibin** [comment]
我之前因为无法上传图片，看网上教程后重新安装了另一个gitee插件，然而没作用，所以我又把它删除了，只留下这个2.0.3的，难道是另一个插件删除得不彻底（配置还存在）？

**Comment by Molunerfinn** [comment]
> 我之前因为无法上传图片，看网上教程后重新安装了另一个gitee插件，然而没作用，所以我又把它删除了，只留下这个2.0.3的，难道是另一个插件删除得不彻底（配置还存在）？

嗯是的，picgo是读取package.json里的dependencies来加载插件的。2.2.2我记得比较早了，可能有些逻辑有bug，建议更新到最新的beta版。现在删掉后应该是不会再有重复id问题了

**Comment by Molunerfinn** [comment]
删除了之后，完全退出picgo再开才能生效。

**Comment by lin-xibin** [comment]
下载了最新版后终于恢复正常了，多谢你的帮助

**Comment by lin-xibin** [comment]
![1](https://i.loli.net/2021/04/21/KX1mFZBYeCAolHV.png)
但为什么新版默认图床为SM.MS，无法设置为Gitee，那个设置按钮无法触发

**Comment by Molunerfinn** [comment]
切换一下别的图床为默认图床，然后再切回gitee就行了

**Comment by lin-xibin** [comment]
> 切换一下别的图床为默认图床，然后再切回gitee就行了

切回gitee之后，图片又没法上传了，不知道是什么问题——没任何弹窗提示，日志文件也没报错。可以保证gitee图床设置是准确的，难道是Bug?

**Comment by lin-xibin** [comment]
图片上传时有进度条显示，并且进度条是蓝色的，然后当它走到末尾时就结束了，也没什么反应

**Comment by lin-xibin** [comment]
![](https://gitee.com/lin-xibin/image-repository/raw/master/img/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202021-04-21%20200950.jpg)

**Comment by Molunerfinn** [comment]
> ![](https://gitee.com/lin-xibin/image-repository/raw/master/img/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202021-04-21%20200950.jpg)

日志贴一下

**Comment by lin-xibin** [comment]
> 2021-04-21 12:10:12 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-04-21 12:11:12 [PicGo SUCCESS] 插件安装成功 
2021-04-21 12:12:07 [PicGo INFO] Before transform 
2021-04-21 12:12:07 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-21 12:12:07 [PicGo INFO] Before upload 
2021-04-21 12:12:07 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-21 12:12:07 [PicGo INFO] Uploading... Current uploader is [smms] 
2021-04-21 12:12:09 [PicGo SUCCESS] 
https://i.loli.net/2021/04/21/5Y3QFmG8kE6nKTh.png 
2021-04-21 12:14:53 [PicGo INFO] Before transform 
2021-04-21 12:14:53 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-21 12:14:53 [PicGo INFO] Before upload 
2021-04-21 12:14:53 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-21 12:14:53 [PicGo INFO] Uploading... Current uploader is [smms] 
2021-04-21 12:14:56 [PicGo SUCCESS] 
https://i.loli.net/2021/04/21/BWYUrxA8q2Kdbme.jpg 
2021-04-21 12:30:59 [PicGo INFO] Before transform 
2021-04-21 12:30:59 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-21 12:31:00 [PicGo INFO] Before upload 
2021-04-21 12:31:00 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-21 12:31:00 [PicGo INFO] Uploading... Current uploader is [smms] 
2021-04-21 12:31:01 [PicGo SUCCESS] 
https://i.loli.net/2021/04/21/KX1mFZBYeCAolHV.png 
2021-04-21 12:43:11 [PicGo INFO] [PicGo Server] shutdown

**Comment by Molunerfinn** [comment]
> > 2021-04-21 12:10:12 [PicGo INFO] [PicGo Server] is listening at 36677 
> 
> 2021-04-21 12:11:12 [PicGo SUCCESS] 插件安装成功 
> 
> 2021-04-21 12:12:07 [PicGo INFO] Before transform 
> 
> 2021-04-21 12:12:07 [PicGo INFO] Transforming... Current transformer is [path] 
> 
> 2021-04-21 12:12:07 [PicGo INFO] Before upload 
> 
> 2021-04-21 12:12:07 [PicGo INFO] beforeUploadPlugins: renameFn running 
> 
> 2021-04-21 12:12:07 [PicGo INFO] Uploading... Current uploader is [smms] 
> 
> 2021-04-21 12:12:09 [PicGo SUCCESS] 
> 
> https://i.loli.net/2021/04/21/5Y3QFmG8kE6nKTh.png 
> 
> 2021-04-21 12:14:53 [PicGo INFO] Before transform 
> 
> 2021-04-21 12:14:53 [PicGo INFO] Transforming... Current transformer is [path] 
> 
> 2021-04-21 12:14:53 [PicGo INFO] Before upload 
> 
> 2021-04-21 12:14:53 [PicGo INFO] beforeUploadPlugins: renameFn running 
> 
> 2021-04-21 12:14:53 [PicGo INFO] Uploading... Current uploader is [smms] 
> 
> 2021-04-21 12:14:56 [PicGo SUCCESS] 
> 
> https://i.loli.net/2021/04/21/BWYUrxA8q2Kdbme.jpg 
> 
> 2021-04-21 12:30:59 [PicGo INFO] Before transform 
> 
> 2021-04-21 12:30:59 [PicGo INFO] Transforming... Current transformer is [path] 
> 
> 2021-04-21 12:31:00 [PicGo INFO] Before upload 
> 
> 2021-04-21 12:31:00 [PicGo INFO] beforeUploadPlugins: renameFn running 
> 
> 2021-04-21 12:31:00 [PicGo INFO] Uploading... Current uploader is [smms] 
> 
> 2021-04-21 12:31:01 [PicGo SUCCESS] 
> 
> https://i.loli.net/2021/04/21/KX1mFZBYeCAolHV.png 
> 
> 2021-04-21 12:43:11 [PicGo INFO] [PicGo Server] shutdown 
> 
> 
> 
> 

你这日志还是走的smms啊

**Comment by lin-xibin** [comment]
你说得没错，问题就在这里，这是之前使用smms上传成功产生的日志，但是为什么现在我用Gitee上传没成功，日志里啥都没有记录

**Comment by lin-xibin** [comment]
dns间接性抽风，github一直访问不上，好想哭。。

**Comment by Molunerfinn** [comment]
如果你一直用记事本开着日志文件，是不会有更新的。关了日志文件，然后重新上传，然后再打开日志文件就能看到日志了。

我装了gitee插件，随便配置了一下（我没有填真实的token等信息），然后我发现表现跟你的一样，蓝条走到底结束了没反应。

但是我的日志如下：

```
2021-04-21 22:37:01 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-04-21 22:37:12 [PicGo INFO] Before transform 
2021-04-21 22:37:12 [PicGo INFO] Transforming... Current transformer is [path] 
2021-04-21 22:37:12 [PicGo INFO] Before upload 
2021-04-21 22:37:12 [PicGo INFO] beforeUploadPlugins: watermark running 
2021-04-21 22:37:12 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-21 22:37:12 [PicGo INFO] {"left":172,"top":131} 
2021-04-21 22:37:12 [PicGo INFO] Uploading... Current uploader is [gitee] 
2021-04-21 22:37:14 [PicGo INFO] {"name":"StatusCodeError","statusCode":401,"message":"401 - \"{\\\"message\\\":\\\"401 Unauthorized: Access token does not exist\\\"}\"","error":"{\"message\":\"401 Unauthorized: Access token does not exist\"}","options":
....
```

这里面的日志说明我的配置是有问题的，我的确配的有问题。


只有为啥一道蓝条走到底，是因为picgo是根据插件回传的信息来判断是否上传成功。这个gitee插件没有回传错误信息，所以picgo认为上传成功并结束了。

**Comment by lin-xibin** [comment]
我日志本没有打开，直到我上传没有反应之后才打开查看，可惜依然没留下记录

**Comment by lin-xibin** [comment]
我把PicGO以及所有相关配置文件夹都删除后，重新下载-安装gitee插件-重新更换gitee的令牌，用默认的sm.ms能够顺利上传，切回Gitee后问题依然存在，暂时先放弃了

**Comment by Molunerfinn** [comment]
> 我把PicGO以及所有相关配置文件夹都删除后，重新下载-安装gitee插件-重新更换gitee的令牌，用默认的sm.ms能够顺利上传，切回Gitee后问题依然存在，暂时先放弃了

切回gitee后，依然没有留下日志？

**Comment by lin-xibin** [comment]
不过有趣的是，当我切换到Github图床的时候，图片可以顺利上传

**Comment by lin-xibin** [comment]
有可能是码云的问题？

**Comment by Molunerfinn** [comment]
不确定，没有日志的话无法排查，我也没用过码云

**Comment by Molunerfinn** [comment]
其实如果你把东西全删了，恢复到以前的状态的话，我估计装回2.2.2可能就能用了- -...

虽然不知道2.3的日志为什么在你那边不见了。

**Comment by lin-xibin** [comment]
我怀疑是我账号出了问题，于是找了朋友的账号来做一下实验哈，结果还是一样。我切回自己的账号后又上传了一次，再看日志，有东西了
> 2021-04-21 23:42:01 [PicGo SUCCESS] 
undefined

**Comment by lin-xibin** [comment]
你设置的PicGO判断成功的条件是什么

**Comment by lin-xibin** [comment]
undefine我不知道何来此说，我配置都上了，也按了确定并设置为默认图床

**Comment by lin-xibin** [comment]
不说了，我换了另一个插件后可以上传图片到码云了！看来这个插件gitee 2.0.3 picgo uploader for gitee (zhanghuid)可能存在Bug

**Comment by lin-xibin** [comment]
![](https://gitee.com/lin-xibin/image-repository/raw/master/img/20210421235347.png)
这个好

**Comment by oucliut** [comment]
> 在picgo设置里打开配置文件，然后在配置文件所在的目录下，有个package.json。贴一下这个package.json里面的内容
为什么无法打开配置文件？
![image](https://user-images.githubusercontent.com/24987167/128520844-5a4a0d1a-ece9-4174-8a16-17e2825f2c8e.png)

**Comment by oucliut** [comment]
> 我换了另一个插件后可以上传图片到码云了！


请问一下您，目前用的gitee插件是哪个？我离线导入插件也不成功，感觉这个插件有问题啊，一直上传不成功
