### ISSUE TITLE
关于github上传失败问题，已确定不是网络问题

### ISSUE THREAD

**Issue by wanghangcheng** [Molunerfinn/PicGo#662]
版本:2.3-bate.6
以前是可以上传的，这次更新后突然不行，git图床也重新配置过了

日志信息：
2020-09-16 21:50:50 [PicGo INFO] [PicGo Server] is listening at 36677 
2020-09-16 21:52:05 [PicGo SUCCESS] 插件安装成功 
2020-09-16 22:04:09 [PicGo INFO] Before transform 
2020-09-16 22:04:09 [PicGo INFO] Transforming... 
2020-09-16 22:04:09 [PicGo INFO] Before upload 
2020-09-16 22:04:09 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-09-16 22:04:17 [PicGo INFO] Uploading... 
2020-09-16 22:04:25 [PicGo SUCCESS] 
https://i.loli.net/2020/09/16/6F9Bbmk4cTwrqiQ.jpg 
2020-09-16 22:07:58 [PicGo INFO] Before transform 
2020-09-16 22:07:58 [PicGo INFO] Transforming... 
2020-09-16 22:07:58 [PicGo INFO] Before upload 
2020-09-16 22:07:58 [PicGo INFO] beforeUploadPlugins: renameFn running 
2020-09-16 22:08:04 [PicGo INFO] Uploading... 
2020-09-16 22:08:05 [PicGo SUCCESS] 
https://gitee.com/wanghangcheng/Image/raw/master/img/%E6%B5%8B%E8%AF%952.jpg 
2020-09-16 22:16:05 [PicGo INFO] [PicGo Server] shutdown 
2021-04-26 10:15:25 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-04-26 10:25:28 [PicGo INFO] Before transform 
2021-04-26 10:25:28 [PicGo INFO] Transforming... 
2021-04-26 10:25:28 [PicGo INFO] Before upload 
2021-04-26 10:25:28 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-04-26 10:26:22 [PicGo INFO] Uploading... 
2021-04-26 10:26:23 [PicGo WARN] failed 
2021-04-26 10:26:23 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (D:\PicGO\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\PicGO\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\PicGO\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\PicGO\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\PicGO\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\PicGO\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by wanghangcheng** [comment]
git图床配置没动过
![image](https://user-images.githubusercontent.com/43712864/116026472-6cbb2f80-a685-11eb-88ae-b8a59414958c.png)

**Comment by Molunerfinn** [comment]
仔细看看你的仓库名对不对吧![image](https://user-images.githubusercontent.com/12621342/116027349-3383bf00-a687-11eb-9aac-eff22299cff1.png)
