### ISSUE TITLE
上传失败,报错Error: Error in repo name

### ISSUE THREAD

**Issue by whereisthewind** [Molunerfinn/PicGo#665]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

无法上传图片

## PicGo 的相关信息

Windows10，PicGo 2.2.2

## 问题重现
日志记录：
2021-05-02 22:59:01 [PicGo INFO] Before transform
2021-05-02 22:59:01 [PicGo INFO] Transforming...
2021-05-02 22:59:01 [PicGo INFO] Before upload
2021-05-02 22:59:01 [PicGo INFO] Uploading...
2021-05-02 22:59:01 [PicGo WARN] failed
2021-05-02 22:59:01 [PicGo ERROR] Error: Error in repo name
------Error Stack Begin------
Error: Error in repo name
    at new Octo (C:\Users\WYG\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\lib\octokit.js:40:19)
    at Object.getIns (C:\Users\WYG\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\lib\octokit.js:230:11)
    at initOcto (C:\Users\WYG\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js:11:27)
    at Object.handle (C:\Users\WYG\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js:110:21)
    at Lifecycle.doUpload (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:24)
    at Lifecycle.start (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:24)
    at async PicGo.upload (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------

## 功能请求

---

**Comment by Molunerfinn** [comment]
请去picgo-plugin-gitee-uploader插件仓库提问。另外这个不是很明显你的配置有问题么。
