### ISSUE TITLE
上传至github图床失败

### ISSUE THREAD

**Issue by schrodingercatss** [Molunerfinn/PicGo#683]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息
Picgo版本：2.3.0-beta.6 版本
平台：Win10

## 问题重现

上传图片至github图床失败。

错误信息：
```
2021-06-18 19:37:47 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
```

**Comment by Molunerfinn** [comment]
网络问题，FAQ已经说了。
![image](https://user-images.githubusercontent.com/12621342/122555674-2d013a80-d06d-11eb-819d-9aa9ba6561fd.png)
