### ISSUE TITLE
作者您好，token过期，regenerate new token后就发生了上传失败的问题

### ISSUE THREAD

**Issue by Wei-i** [Molunerfinn/PicGo#684]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report 图片上传至github repo(public) 失败

## PicGo 的相关信息

PigGo -2.3.0-beta.6 Windows 10操作系统
## 问题重现

![image](https://user-images.githubusercontent.com/47490392/122932974-c77cb900-d3a0-11eb-94c6-55716adabef2.png)

## 功能请求
2021-06-22 21:29:21 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Software\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2021-06-22 21:29:21 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/683

**Comment by Wei-i** [comment]
作者您好，不好意思打扰您， 是这样的，昨天github邮箱提示了我 token要outdated，然后给了我一个regenerate new token的link。结果昨天貌似还好好的（我的repo显示 昨天又commit） 但是今天我就无法上传了
我更改了好几次githb setting的token以及对应的picgo上填写的github 图传的token，甚至我还重装了 但就是不行

**Comment by Molunerfinn** [comment]
所以跟picgo没有关系，这个是github的服务器的问题

**Comment by Wei-i** [comment]
谢谢您及时的回复！
我看到你给的#683 issue中说到了是网络的问题？
我有开vpn 也可以上github呀 
请问这有啥办法吗？ 还是说只能等？ 不是我设置或者操作的问题？

**Comment by Molunerfinn** [comment]
检查一下有没有配置代理呢？如果有的话，取消代理，或者更换代理试试。这个是网络问题，不是picgo能解决的

**Comment by Wei-i** [comment]
我刚刚把vpn关闭了 就可以了......

**Comment by Wei-i** [comment]
我吐了 但我刚刚关闭了登录github就上不去了T T  难道是我的VPN出问题了
