### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by daochen23** [Molunerfinn/PicGo#687]
# 版本
2.3.0-beta.6
# 图床
GitHub图床
# 文件格式
jpg png 都试了
# 报错信息
````
2021-06-27 23:55:09 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (E:\software\piogo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\software\piogo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\software\piogo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\software\piogo\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\software\piogo\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2021-06-27 23:55:09 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (E:\software\piogo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\software\piogo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\software\piogo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\software\piogo\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\software\piogo\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
````

**Comment by Molunerfinn** [comment]
请提issue前，先把之前的issue和FAQ好好看看。

**Comment by daochen23** [comment]
> 请提issue前，先把之前的issue和FAQ好好看看。

开了FAQ后发现是GitHub图床问题,更换又拍云后已经可以正常提交图片,谢谢
