### ISSUE TITLE
archlinux上无法上传图片

### ISSUE THREAD

**Issue by wanghuibin0** [Molunerfinn/PicGo#693]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

2.3.0-beta.6 appimage
archlinux (两台archlinux电脑都出现了同样的错误)

## 问题重现

![image](https://user-images.githubusercontent.com/14231615/124370433-55fb0f80-dcaa-11eb-80c8-219c5073e9ae.png)
![image](https://user-images.githubusercontent.com/14231615/124370443-71feb100-dcaa-11eb-94dc-a5ff8a9cd901.png)
第一张图那里点击确定，命令行里就出现 failed to connect to proxy
上传图片自然也是没成功

日志：
2021-07-03 19:29:31 [PicGo INFO] [PicGo Server] is listening at 36677
2021-07-03 19:30:03 [PicGo INFO] Before transform
2021-07-03 19:30:03 [PicGo INFO] Transforming...
2021-07-03 19:30:03 [PicGo WARN] failed
2021-07-03 19:30:03 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at /usr/share/picgo/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:20:28
    at async Promise.all (index 0)
    at async Object.handle (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:11:5)
    at async Lifecycle.doTransform (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:51:9)
    at async Lifecycle.start (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:19:13)
    at async PicGo.upload (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/PicGo.js:156:13)
-------Error Stack End-------
2021-07-03 19:30:14 [PicGo INFO] [PicGo Server] shutdown
2021-07-03 19:30:20 [PicGo INFO] [PicGo Server] is listening at 36677
2021-07-03 19:34:50 [PicGo INFO] [PicGo Server] shutdown
2021-07-03 19:43:33 [PicGo INFO] [PicGo Server] is listening at 36677
2021-07-03 19:43:42 [PicGo INFO] Before transform
2021-07-03 19:43:42 [PicGo INFO] Transforming...
2021-07-03 19:43:42 [PicGo INFO] Before upload
2021-07-03 19:43:42 [PicGo INFO] Uploading...
2021-07-03 19:43:44 [PicGo WARN] failed
2021-07-03 19:43:44 [PicGo ERROR] RequestError: Error: read ECONNRESET
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/share/picgo/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/usr/share/picgo/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
-------Error Stack End-------
2021-07-03 19:43:58 [PicGo INFO] [PicGo Server] shutdown
2021-07-03 19:45:10 [PicGo INFO] [PicGo Server] is listening at 36677
2021-07-03 19:46:04 [PicGo INFO] Before transform
2021-07-03 19:46:04 [PicGo INFO] Transforming...
2021-07-03 19:46:04 [PicGo INFO] Before upload
2021-07-03 19:46:04 [PicGo INFO] Uploading...
2021-07-03 19:46:07 [PicGo WARN] failed
2021-07-03 19:46:07 [PicGo ERROR] RequestError: Error: socket hang up
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/share/picgo/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/usr/share/picgo/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketOnEnd (_http_client.js:440:9)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
-------Error Stack End-------
2021-07-03 19:47:36 [PicGo INFO] Before transform
2021-07-03 19:47:36 [PicGo INFO] Transforming...
2021-07-03 19:47:36 [PicGo WARN] failed
2021-07-03 19:47:36 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at /usr/share/picgo/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:20:28
    at async Promise.all (index 0)
    at async Object.handle (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:11:5)
    at async Lifecycle.doTransform (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:51:9)
    at async Lifecycle.start (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:19:13)
    at async PicGo.upload (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/PicGo.js:156:13)
-------Error Stack End-------
2021-07-03 19:47:42 [PicGo INFO] Before transform
2021-07-03 19:47:42 [PicGo INFO] Transforming...
2021-07-03 19:47:42 [PicGo WARN] failed
2021-07-03 19:47:42 [PicGo ERROR] TypeError: Cannot read property 'width' of null
------Error Stack Begin------
TypeError: Cannot read property 'width' of null
    at /usr/share/picgo/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:20:28
    at async Promise.all (index 0)
    at async Object.handle (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/plugins/transformer/path.js:11:5)
    at async Lifecycle.doTransform (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:51:9)
    at async Lifecycle.start (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:19:13)
    at async PicGo.upload (/usr/share/picgo/app.asar/node_modules/picgo/dist/src/core/PicGo.js:156:13)
-------Error Stack End-------
2021-07-03 19:47:50 [PicGo INFO] [PicGo Server] shutdown
2021-07-03 19:47:57 [PicGo INFO] [PicGo Server] is listening at 36677
2021-07-03 19:48:05 [PicGo INFO] Before transform
2021-07-03 19:48:05 [PicGo INFO] Transforming...
2021-07-03 19:48:05 [PicGo INFO] Before upload
2021-07-03 19:48:05 [PicGo INFO] Uploading...
2021-07-03 19:48:07 [PicGo WARN] failed
2021-07-03 19:48:07 [PicGo ERROR] RequestError: Error: socket hang up
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/share/picgo/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/share/picgo/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/usr/share/picgo/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketOnEnd (_http_client.js:440:9)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
-------Error Stack End-------
2021-07-03 19:53:43 [PicGo INFO] [PicGo Server] shutdown
2021-07-04 08:59:14 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-07-04 08:59:24 [PicGo INFO] [PicGo Server] shutdown 
2021-07-04 09:01:13 [PicGo INFO] [PicGo Server] is listening at 36677 

## 功能请求

---

**Comment by Molunerfinn** [comment]
看你的日志不像是beta.6版本的。
我这有份beta.6的日志，你看看有啥区别：（标明了tranformer和uploader）
![image](https://user-images.githubusercontent.com/12621342/124370652-8c398e80-dcac-11eb-9293-3a24fc7501b1.png)

这里，你上传失败，日志里写得挺清楚了，应该是你本机或者picgo设置了代理，但是代理有问题导致的。

检查两个地方：

1. picgo的代理设置： picgo设置 - 设置代理和镜像地址 - 上传代理（只支持http代理）
![image](https://user-images.githubusercontent.com/12621342/124370675-d3c01a80-dcac-11eb-95ca-c99039275b55.png)

2. 系统的全局代理

3. 看图片，你并没有选择smms为默认上传图床，只是点了确定而已。图床上传区域这里是不是还是别的上传图床？
![image](https://user-images.githubusercontent.com/12621342/124370693-ff430500-dcac-11eb-9dd5-5f5b1e17c633.png)

点完确定之后，需要点击设为默认图床，才能在上传时候生效。

![image](https://user-images.githubusercontent.com/12621342/124370700-1255d500-dcad-11eb-9eec-1f1b7beae6aa.png)

**Comment by wanghuibin0** [comment]
谢谢回复。

是这样的
1. 家里的网络是透明代理，按理说对picgo应该是不可见的，我在运行archlinux的主机上没设置代理
2. 我又看了一下日志时间，大概是这样，我picgo先是昨晚通过aur装的，先后装了aur/picgo 2.2.2-3 (+2 0.98)，aur/picgo-appimage-beta 2.3.0-4 (+2 0.01)，是同样的错误。今天早上直接在github release这里下了最新版的appimage，还是一样。日志的话大概是卸载重装软件后日志还保留着

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/124371077-dae92780-dcb0-11eb-88b9-bb4d69a23bce.png)
如果报错是这个网络问题，picgo层面没法解决，需要自行看一下了

**Comment by wanghuibin0** [comment]
补充：
1. 刚才又试了一下，设置默认图床也没用，上传图片还是没成功
2. 检查了我的代理设置，是空的
![image](https://user-images.githubusercontent.com/14231615/124371110-35828380-dcb1-11eb-9d60-608be56a0220.png)
3. 又检查了日志文件，发现最新的地方并没有报错信息，只有 server is listening

**Comment by wanghuibin0** [comment]
补充：
1. 最新版picgo，上传不成功，除了命令行的failed to connect to proxy 外，日志没有任何报错信息 
2. 切换网络为手机开的热点，问题依旧
3. 换到win10上，一切正常

**Comment by Molunerfinn** [comment]
> 补充：
> 
> 1. 最新版picgo，上传不成功，除了命令行的failed to connect to proxy 外，日志没有任何报错信息
> 2. 切换网络为手机开的热点，问题依旧
> 3. 换到win10上，一切正常

上传的时候，没有别的日志么？有上传失败的弹窗但是没有上传失败的日志？

**Comment by wanghuibin0** [comment]
既没有弹窗，日志也没有相关错误信息，只有命令行会跳出三行 failed to connect to proxy

**Comment by Molunerfinn** [comment]
> 既没有弹窗，日志也没有相关错误信息，只有命令行会跳出三行 failed to connect to proxy

命令行的可以忽略- -...

你上传是用剪贴板上传还是拖拽文件上传

**Comment by Molunerfinn** [comment]
另外检查一下你的终端是不是有export http_proxy 或者 https_proxy之类的吧。linux我记得直接双击运行appimage就行了？

**Comment by Molunerfinn** [comment]
感觉你遇到的是这个问题：
https://github.com/Molunerfinn/PicGo/issues/524

**Comment by wanghuibin0** [comment]
> > 既没有弹窗，日志也没有相关错误信息，只有命令行会跳出三行 failed to connect to proxy
> 
> 命令行的可以忽略- -...
> 
> 你上传是用剪贴板上传还是拖拽文件上传

剪贴板上传

**Comment by wanghuibin0** [comment]
> 另外检查一下你的终端是不是有export http_proxy 或者 https_proxy之类的吧。linux我记得直接双击运行appimage就行了？

http_proxy
https_proxy
all_proxy
我都检查过了，都是空的，没设置

**Comment by wanghuibin0** [comment]
> > 既没有弹窗，日志也没有相关错误信息，只有命令行会跳出三行 failed to connect to proxy
> 
> 命令行的可以忽略- -...
> 
> 你上传是用剪贴板上传还是拖拽文件上传

用文件上传居然成功了

**Comment by wanghuibin0** [comment]
> > > 既没有弹窗，日志也没有相关错误信息，只有命令行会跳出三行 failed to connect to proxy
> > 
> > 
> > 命令行的可以忽略- -...
> > 你上传是用剪贴板上传还是拖拽文件上传
> 
> 用文件上传居然成功了，虽然终端上还是有那几行信息

所以是剪贴板的问题吗？我应该怎么处理

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/124373616-5c978000-dcc6-11eb-81b3-4b8d04e14818.png)

**Comment by wanghuibin0** [comment]
你这个#524并没有解决方案嘛
