### ISSUE TITLE
mac下无法上传问题

### ISSUE THREAD

**Issue by xpp1109** [Molunerfinn/PicGo#696]
总是提示上传失败，
![image](https://user-images.githubusercontent.com/51978706/125772437-3272f500-8967-4266-acdd-6c7f1968587d.png)
os : mac os big sur

2021-07-15 18:32:32 [PicGo INFO] Before transform 
2021-07-15 18:32:32 [PicGo INFO] Transforming... Current transformer is [path] 
2021-07-15 18:32:32 [PicGo INFO] Before upload 
2021-07-15 18:32:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-07-15 18:32:32 [PicGo INFO] Uploading... Current uploader is [github] 
2021-07-15 18:32:33 [PicGo WARN] failed 
2021-07-15 18:32:33 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: write EPIPE
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
-------Error Stack End------- 
2021-07-15 18:32:33 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: write EPIPE
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
网络问题。
