### ISSUE TITLE
不能上传图片

### ISSUE THREAD

**Issue by jxmyh99** [Molunerfinn/PicGo#703]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
图片上传不成功

## PicGo 的相关信息
2.2.2 mac

## 功能请求

---

2021-07-23 23:05:07 [PicGo INFO] Before transform
2021-07-23 23:05:07 [PicGo INFO] Transforming...
2021-07-23 23:05:07 [PicGo INFO] Before upload
2021-07-23 23:05:07 [PicGo INFO] Uploading...
2021-07-23 23:05:07 [PicGo ERROR] StatusCodeError: 401 - "{\"msg\":\"signature error\",\"code\":40100005,\"id\":\"9685391e8d6cab6bbf21e2debd61ebc2\"}"
------Error Stack Begin------
StatusCodeError: 401 - "{\"msg\":\"signature error\",\"code\":40100005,\"id\":\"9685391e8d6cab6bbf21e2debd61ebc2\"}"
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------
2021-07-23 23:05:07 [PicGo WARN] failed

**Comment by Molunerfinn** [comment]
请仔细检查自己的配置。报错显示你的配置有问题导致检验不过。
