### ISSUE TITLE
ssl验证未使用系统根目录证书导致报错

### ISSUE THREAD

**Issue by leafmoes** [Molunerfinn/PicGo#725]
请问怎么改成系统根目录证书啊，附报错代码

------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (C:\Users\Leafmoes\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Leafmoes\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Leafmoes\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\Leafmoes\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Users\Leafmoes\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
一般跟你的代理设置有关，检查自己电脑的代理设置。
