### ISSUE TITLE
Mac版本上传图片失败

### ISSUE THREAD

**Issue by zheyuye** [Molunerfinn/PicGo#741]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

上传图片失败

## PicGo 的相关信息

平台环境: Mac M1 Big Sur
PicGo: 2.3.0-beta.8

## 问题重现
> ------Error Stack Begin------
Error
    at Object.handle (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/plugins/uploader/tcyun.js:115:27)
    at async Lifecycle.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:80:9)
    at async Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:26:13)
    at async PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:205:32)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:28656)
    at async Rt (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:31093)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/132613570-4d609eb4-48d2-471c-ad73-f063e738ac94.png)
400报错请检查自己的配置。

**Comment by zheyuye** [comment]
通过添加pac规则解决了这个问题 , 十分感谢

**Comment by GYunZhi** [comment]
我这里也出现了相同的问题，配置对了好几遍了，没问题。用官方的 COSBrowser 是可以的。
