### ISSUE TITLE
上传图片到腾讯云错误

### ISSUE THREAD

**Issue by Alickx** [Molunerfinn/PicGo#744]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

PicGo 2.3.0 window端
## 问题重现

2021-09-16 11:59:36 [PicGo INFO] Before transform 
2021-09-16 11:59:36 [PicGo INFO] Transforming... Current transformer is [path] 
2021-09-16 11:59:36 [PicGo INFO] Before upload 
2021-09-16 11:59:36 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-09-16 11:59:36 [PicGo INFO] Uploading... Current uploader is [tcyun] 
2021-09-16 11:59:36 [PicGo ERROR] 
------Error Stack Begin------
RequestError: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new RequestError (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:205:15)
    at Request.start (E:\PicGo\resources\app.asar\node_modules\request\request.js:753:10)
    at Request.write (E:\PicGo\resources\app.asar\node_modules\request\request.js:1491:10)
    at FormData.ondata (internal/streams/legacy.js:17:31)
    at FormData.emit (events.js:200:13)
    at FormData.CombinedStream.write (E:\PicGo\resources\app.asar\node_modules\combined-stream\lib\combined_stream.js:138:8)
-------Error Stack End------- 
2021-09-16 11:59:36 [PicGo WARN] failed 
2021-09-16 11:59:36 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (E:\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (E:\PicGo\resources\app.asar\background.js:36:31625)
-------Error Stack End------- 
2021-09-16 11:59:36 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (E:\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (E:\PicGo\resources\app.asar\background.js:36:31625)
-------Error Stack End------- 

## 功能请求

---

**Comment by Molunerfinn** [comment]
你传的图片本地路径和图片名是什么，是不是带有中文

**Comment by Alickx** [comment]
> 你传的图片本地路径和图片名是什么，是不是带有中文

本地路径：C:\Users\Alickx\OneDrive\桌面\记录\图片
图片名：命令错误.PNG

是带有中文的。

**Comment by Molunerfinn** [comment]
腾讯云的路径配置有中文吗

**Comment by Alickx** [comment]
> 腾讯云的路径配置有中文吗

腾讯云的路径为: img/ 
没有中文
现在上传带不带中文都会出现此错误，但是之前一直使用正常。

**Comment by Molunerfinn** [comment]
这边试了一下无法复现

**Comment by Molunerfinn** [comment]
配置截个图
![image](https://user-images.githubusercontent.com/12621342/133550787-04c28706-1f28-4463-8899-11690ce4b08f.png)

**Comment by Alickx** [comment]
> 配置截个图
> ![image](https://user-images.githubusercontent.com/12621342/133550787-04c28706-1f28-4463-8899-11690ce4b08f.png)
![配置](https://user-images.githubusercontent.com/55425385/133551058-fefc89f4-b55a-425c-8488-d8dc6ca71e3a.PNG)

**Comment by Alickx** [comment]
![window](https://user-images.githubusercontent.com/55425385/133551670-795b2eb0-14fc-4498-809d-1dcdb7f2354e.PNG)
电脑系统信息

**Comment by Alickx** [comment]
解决了，确认是配置问题，存储空间名和存储区域改成v5版本的格式就行了，昨天还在正常使用，今天就变了，奇怪。。。。
