### ISSUE TITLE
【Bug】Typora 上传所有本地图片失败

### ISSUE THREAD

**Issue by alfoil** [Molunerfinn/PicGo#745]
## Bug 说明

我在 Typora 图像的设置里，选择了将图片统一“复制到当前文件夹”：

![](https://lyf-image-hosting.oss-cn-hangzhou.aliyuncs.com/img/202109162343315.png)

然后想利用 Typora 中的“上传所有本地图片”（下图）功能实现批量上传 md 内的所有图片。

![](https://lyf-image-hosting.oss-cn-hangzhou.aliyuncs.com/img/202109162344382.png)

但是Typora 打开 md 文件，粘贴图片自动复制到当前文件夹后，**如果当前文件夹有中文路径，选择上传所有图片就会失败；没有中文路径的情况能正常上传。**

## PicGo 的相关信息

- OS：Windows 11 22000.184
- PicGo：2.3.0
- Typora：0.11.8

## 问题重现

同样的 2 张图片粘贴到 Typora 打开的 md 文件里，
- 如果 md 文件所在路径有中文，上传所有图片会失败，日志文件如下：
```
2021-09-16 22:51:45 [PicGo INFO] [PicGo Server] get the request {"list":["D:\\Files\\Desktop\\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\\202109162231838.png","D:\\Files\\Desktop\\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\\202109162235721.png"]}
2021-09-16 22:51:45 [PicGo INFO] [PicGo Server] upload files in list
2021-09-16 22:51:45 [PicGo INFO] Before transform
2021-09-16 22:51:45 [PicGo INFO] Transforming... Current transformer is [path]
2021-09-16 22:51:45 [PicGo WARN] failed
2021-09-16 22:51:45 [PicGo ERROR]
------Error Stack Begin------
Error: read file D:\Files\Desktop\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\202109162231838.png error
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:25:19
    at async Promise.all (index 0)
    at async Object.handle (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:6:5)
    at async Lifecycle.doTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:59:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:24:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (C:\Program Files\PicGo\resources\app.asar\background.js:36:31625)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End-------
2021-09-16 22:51:45 [PicGo ERROR]
------Error Stack Begin------
Error: read file D:\Files\Desktop\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\202109162231838.png error
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:25:19
    at async Promise.all (index 0)
    at async Object.handle (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:6:5)
    at async Lifecycle.doTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:59:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:24:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (C:\Program Files\PicGo\resources\app.asar\background.js:36:31625)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End-------
2021-09-16 22:51:45 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑
2021-09-16 23:11:07 [PicGo INFO] [PicGo Server] get the request {"list":["D:\\Files\\Desktop\\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\\202109162231838.png","D:\\Files\\Desktop\\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\\202109162235721.png"]}
2021-09-16 23:11:07 [PicGo INFO] [PicGo Server] upload files in list
2021-09-16 23:11:07 [PicGo INFO] Before transform
2021-09-16 23:11:07 [PicGo INFO] Transforming... Current transformer is [path]
2021-09-16 23:11:07 [PicGo WARN] failed
2021-09-16 23:11:07 [PicGo ERROR]
------Error Stack Begin------
Error: read file D:\Files\Desktop\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\202109162231838.png error
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:25:19
    at async Promise.all (index 0)
    at async Object.handle (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:6:5)
    at async Lifecycle.doTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:59:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:24:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (C:\Program Files\PicGo\resources\app.asar\background.js:36:31625)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End-------
2021-09-16 23:11:07 [PicGo ERROR]
------Error Stack Begin------
Error: read file D:\Files\Desktop\%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9\202109162231838.png error
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:25:19
    at async Promise.all (index 0)
    at async Object.handle (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:6:5)
    at async Lifecycle.doTransform (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:59:9)
    at async Lifecycle.start (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:24:13)
    at async PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (C:\Program Files\PicGo\resources\app.asar\background.js:36:31625)
    at async C:\Program Files\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End-------
2021-09-16 23:11:07 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑
```

- 如果 md 文件所在没有中文路径，则能成功上传，日志如下：
```
2021-09-16 23:22:41 [PicGo INFO] [PicGo Server] get the request {"list":["D:\\Files\\Desktop\\new\\202109162231838.png","D:\\Files\\Desktop\\new\\202109162235721.png"]} 
2021-09-16 23:22:41 [PicGo INFO] [PicGo Server] upload files in list 
2021-09-16 23:22:41 [PicGo INFO] Before transform 
2021-09-16 23:22:41 [PicGo INFO] Transforming... Current transformer is [path] 
2021-09-16 23:22:41 [PicGo INFO] Before upload 
2021-09-16 23:22:41 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-09-16 23:22:41 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2021-09-16 23:22:42 [PicGo SUCCESS] 
https://lyf-image-hosting.oss-cn-hangzhou.aliyuncs.com/img/202109162322739.png
https://lyf-image-hosting.oss-cn-hangzhou.aliyuncs.com/img/202109162322740.png 
```

**Comment by Molunerfinn** [comment]
这是typora上传的时候转义了路径导致的。请去typora仓库提交issue

**Comment by Kiku-CN** [comment]
Typora 0.11.13 已经修复该 Bug，亲测
