### ISSUE TITLE
报错 certificate has expired

### ISSUE THREAD

**Issue by SongshGeo** [Molunerfinn/PicGo#749]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

一直能用，今天忽然不能用了，报错是证书过期的问题。我知道这大概率不是PicGo本身的问题，但我做了以下尝试仍不知道如何解决，只好来这里开Issue了：
- 百度+google，没有搜到相似的问题。
- 查看了closed issue中certificate相关的问题，没有相似的报错。
- 更换GitHub、Gitee，更换目标仓库。
- 更新Token令牌。
- 确认SSH可以访问仓库。

对任何可能解决问题的提示表示感激！

## PicGo 的相关信息
PicGo 2.3.0, MacOS

### PicGo日志
2021-10-02 12:52:40 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)

-------Error Stack End-------

**Comment by Molunerfinn** [comment]
证书过期了，请检查你的代理或者系统证书设置

**Comment by wejack639** [comment]
> 证书过期了，请检查你的代理或者系统证书设置

我这也是突然不能用了，原来一直正常用的，请问有没有具体一点的系统证书设置的文档之类的，我找了很长时间，但是一头雾水。的是Mac，感谢

**Comment by che77a38** [comment]
> 我将compress插件更新到1.3.5，再启用插件，也正常了

帮大忙了
