### ISSUE TITLE
You do not have permission to get URL '/files/v2/1254100264/blog-1254100264/avatar.jpeg' from this server

### ISSUE THREAD

**Issue by mafeifan** [Molunerfinn/PicGo#751]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

无法上传图片，日志里提示没有权限

## PicGo 的相关信息

Mac 
PicGo 2.3.0

## 问题重现

使用腾讯云上传图片，无法上传成功
尝试了重启电脑和安装之前运行 sudo spctl --master-disable，依然无效

```
2021-10-03 20:58:55 [PicGo INFO] Before transform 
2021-10-03 20:58:55 [PicGo INFO] Transforming... Current transformer is [path] 
2021-10-03 20:58:55 [PicGo INFO] Before upload 
2021-10-03 20:58:55 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-10-03 20:58:55 [PicGo INFO] Uploading... Current uploader is [tcyun] 
2021-10-03 20:58:55 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 403 - "You do not have permission to get URL '/files/v2/1254100264/blog-1254100264/avatar.jpeg' from this server."
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2021-10-03 20:58:55 [PicGo WARN] failed 
2021-10-03 20:58:55 [PicGo ERROR] 
```

**Comment by Molunerfinn** [comment]
这不是写得很清楚了吗，是你的配置问题导致权限不足啊

**Comment by li-zheng-hao** [comment]
同样遇到这个问题？请问哪里配置有问题？

**Comment by li-zheng-hao** [comment]
![image](https://user-images.githubusercontent.com/22129824/151787567-9e71aa39-1983-4e21-b000-15bb464b3dc8.png)

**Comment by li-zheng-hao** [comment]
找到原因了，picgo右键管理员运行就好了，我还以为是腾讯云上的访问权限有问题
