### ISSUE TITLE
腾讯COS上传报错

### ISSUE THREAD

**Issue by lixingwu** [Molunerfinn/PicGo#757]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息

PicGo 的版本：2.3.0
所在平台：Windows10

## 问题重现

腾讯COS图床上传报错，突然就报错了，也没修改过什么，重新安装的新版本也这样
下面是报错日志：

```log
2021-10-10 20:54:18 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
```

**Comment by lixingwu** [comment]
卸载不会删除用户文件夹下的 \AppData\Roaming\picgo，手动删除一下，重新安装就好了
