### ISSUE TITLE
Deepin v20 无法安装插件

### ISSUE THREAD

**Issue by disburden** [Molunerfinn/PicGo#774]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
Deepin(linux) v20
PicGo:2.3.0

## 问题重现
安装插件的时候总是提示请安装nodejs
![2021-11-03_01-10](https://user-images.githubusercontent.com/1391188/139915878-647bd20d-0f8c-44bb-ab64-df50a034a758.png)

但是我node,nvm,npm都装好了

![2021-11-03_01-09](https://user-images.githubusercontent.com/1391188/139916220-04432277-9c09-4d88-beff-886f62d930c0.png)

![2021-11-03_01-18](https://user-images.githubusercontent.com/1391188/139916237-18b05403-2795-45a6-9d99-cc0b0dc88953.png)
![2021-11-03_01-31](https://user-images.githubusercontent.com/1391188/139916251-cc5c6881-caa9-4eeb-b6e8-ff09d3662bab.png)

## 错误日志:
2021-11-03 00:38:03 [PicGo ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
-------Error Stack End------- 
2021-11-03 00:38:03 [PicGo ERROR] NPM is not installed 
2021-11-03 00:38:03 [PicGo ERROR] 插件安装失败，失败码为-2，错误日志为 
2021-11-03 00:42:05 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-11-03 00:42:05 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: Cannot read property 'status' of undefined
    at be (/tmp/.mount_PicGo-HN2bvX/resources/app.asar/background.js:36:50456)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2021-11-03 00:42:24 [PicGo ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
-------Error Stack End------- 
2021-11-03 00:42:24 [PicGo ERROR] NPM is not installed 
2021-11-03 00:42:24 [PicGo ERROR] 插件安装失败，失败码为-2，错误日志为 
2021-11-03 00:43:39 [PicGo ERROR] 
------Error Stack Begin------

是不是要设置什么固定名称的环境变量?

**Comment by Molunerfinn** [comment]
最简单的是重启电脑再安装插件就行，理论上只是找不到npm这个命令而已

**Comment by disburden** [comment]
重启了很多次了,没用

**Comment by disburden** [comment]
我在任何目录下都能运行npm命令,或者你们不是直接调用npm命令,是不是通过什么环境变量找npm目录的路径再调用?

**Comment by Molunerfinn** [comment]
直接调用的npm命令。可以看看是不是sh环境没有npm命令（bash、sh、zsh等都可以试一下）

**Comment by disburden** [comment]
```shell
# /etc/shells: valid login shells
/bin/sh
/bin/bash
/usr/bin/bash
/bin/rbash
/usr/bin/rbash
/bin/dash
/usr/bin/dash
```

我这就这么几个shell,每个我都试了,都能正常执行npm命令

或者你给我一个手动安装gitee插件的教程,我主要就是想装这个插件试试

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/140011947-b8fd8a1a-c774-4673-801f-feed7fc11e6c.png)

手动安装只需要进入picgo配置文件所在的文件夹，然后输入 `npm install picgo-plugin-xxx`，安装完重启picgo即可

**Comment by disburden** [comment]
手动安装成功了,谢谢!

**Comment by Molunerfinn** [comment]
应该是electron内部spawn进程的时候没有读取到正确的PATH值导致的

**Comment by Molunerfinn** [comment]
参考：
- https://github.com/electron/electron/issues/3627
- https://stackoverflow.com/questions/51992220/issue-running-a-child-process-from-an-electron-app-using-spawn-method

看起来简单的解决方式是调用的时候传入一个 env：ELECTRON_RUN_AS_NODE

**Comment by Molunerfinn** [comment]
下个beta版本可以尝试一下是否安装插件正常了

**Comment by joezhouchenye** [comment]
Ubuntu22.04还是有这个问题，另外补充一下snap安装的配置文件在`~/snap/picgo/current/.config/picgo/data.json`

**Comment by FallingSakura** [comment]
> Ubuntu22.04还是有这个问题，另外补充一下snap安装的配置文件在`~/snap/picgo/current/.config/picgo/data.json`

感谢
