### ISSUE TITLE
[BUG]windows平台的picgo相册突然不显示上传记录，求大佬帮忙看下

### ISSUE THREAD

**Issue by maozuxiao** [Molunerfinn/PicGo#781]
> PicGo version: 2.3.0
> 操作系统平台: Windows10 ×64

## 问题重现
昨天在使用picgo时发现相册处之前的上传记录全部消失了。
> 如下是我的操作
![test](https://user-images.githubusercontent.com/48650555/142551832-ad5f4609-63ff-4381-92ff-0adc4bed23b4.gif)

## 如上操作的相关log
> 2021-11-19 09:56:35 [PicGo INFO] Before transform 
> 2021-11-19 09:56:35 [PicGo INFO] Transforming... Current transformer is [path] 
> 2021-11-19 09:56:35 [PicGo INFO] Before upload 
> 2021-11-19 09:56:35 [PicGo INFO] beforeUploadPlugins: super-prefix running 
> 2021-11-19 09:56:35 [PicGo INFO] beforeUploadPlugins: renameFn running 
> 2021-11-19 09:56:35 [PicGo INFO] Uploading... Current uploader is [github] 
> 2021-11-19 09:56:37 [PicGo SUCCESS] 
> https://cdn.jsdelivr.net/gh/maozuxiao/Image-shack/20211119095635.png `

**Comment by Molunerfinn** [comment]
可能是存储相册的db文件有损坏导致无法读写

另外相册里先不用开启图床过滤，看看是否有数据：

![image](https://user-images.githubusercontent.com/12621342/142554992-82d3ca71-06a4-49f8-a6f7-df8e49a3f89c.png)

然后检查以下步骤：

1. 上传图片之后，剪贴板是否包含了上传的图片链接
2. 日志里是否有error日志
3. 打开picgo的日志所在目录，应该能找到一个 `config-bak.json` 的文件，这个文件是升级到2.3.0之前的配置文件备份，里面应该包含着之前的相册信息。
	1. 首先备份一下同目录下的 `picgo.db` 这个是目前所使用相册文件，可以发给我（marksz@teamsz.xyz）看看是否有损坏
	2. 删除 `picgo.db`，备份一下 `config-bak.json`，删除当前的配置文件 `data.json` 然后重命名 `config-bak.json` -> `data.json`（这一步是还原旧的picgo配置文件，注意已经配置好的配置项处理好不要丢了） ，然后重启picgo，picgo会自动迁移旧的配置文件里的相册信息到 `picgo.db` 中。

**Comment by Molunerfinn** [comment]
之前有遇到过类似配置文件读写失败的问题，相册文件这里估计也是类似的情况

**Comment by Molunerfinn** [comment]
未来会推出同步插件来做配置、相册同步，可以尽可能减少独立配置文件挂掉这件事

**Comment by maozuxiao** [comment]
> 可能是存储相册的db文件有损坏导致无法读写
> 
> 另外相册里先不用开启图床过滤，看看是否有数据：
> 
> ![image](https://user-images.githubusercontent.com/12621342/142554992-82d3ca71-06a4-49f8-a6f7-df8e49a3f89c.png)
> 
> 然后检查以下步骤：
> 
> 1. 上传图片之后，剪贴板是否包含了上传的图片链接
//上传图片之后，剪贴板包含图片链接

> 2. 日志里是否有error日志
//上传文件到结束的时间段内没有error日志

> 3. 打开picgo的日志所在目录，应该能找到一个 `config-bak.json` 的文件，这个文件是升级到2.3.0之前的配置文件备份，里面应该包含着之前的相册信息。
//这里我没有找到`config-bak.json`只看到`date-bak.json`
>    
>    1. 首先备份一下同目录下的 `picgo.db` 这个是目前所使用相册文件，可以发给我（[marksz@teamsz.xyz](mailto:marksz@teamsz.xyz)）看看是否有损坏
//已经发送给你啦

>    2. 删除 `picgo.db`，备份一下 `config-bak.json`，删除当前的配置文件 `data.json` 然后重命名 `config-bak.json` -> `data.json`（这一步是还原旧的picgo配置文件，注意已经配置好的配置项处理好不要丢了） ，然后重启picgo，picgo会自动迁移旧的配置文件里的相册信息到 `picgo.db` 中。
//这里我没有找到`config-bak.json`只看到`date-bak.json`，其他按你的指导操作后，问题解决，可以看到新上传的图片了
![](https://cdn.jsdelivr.net/gh/maozuxiao/Image-shack/20211119170319.png)


#

**Comment by Jeffrey28** [comment]
macos m1下PicGo-2.3.1-beta.2出现类似问题，是七牛图床，url已经设置了前缀，然后不过macos下的picgo.db的文件应该在哪里呢？剪贴板包含图片链接，上传文件到结束的时间段内没有error日志。从安装后一直相册都没有出现已经上传成功的图片。

**Comment by Molunerfinn** [comment]
> 

跟日志文件在同级目录。另外，上传有成功日志么

**Comment by Jeffrey28** [comment]
2022-01-08 15:55:48 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-08 15:55:48 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-08 15:57:35 [PicGo INFO] Before transform 
2022-01-08 15:57:35 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-08 15:57:35 [PicGo INFO] Before upload 
2022-01-08 15:57:35 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-08 15:57:35 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-01-08 15:57:37 [PicGo SUCCESS] 
https://cdn.drxlchan.com/202201081557718.png 
2022-01-08 15:57:45 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:180:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:530747)
    at async xe (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:532499)
-------Error Stack End------- 
2022-01-08 15:57:55 [PicGo ERROR] 
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:180:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:530747)
    at async xe (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:532499)
-------Error Stack End------- 
2022-01-08 15:58:00 [PicGo INFO] Before transform 
2022-01-08 15:58:00 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-08 15:58:00 [PicGo INFO] Before upload 
2022-01-08 15:58:00 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-08 15:58:00 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-01-08 15:58:10 [PicGo SUCCESS] 
https://cdn.drxlchan.com/202201081558685.png 
2022-01-08 16:04:21 [PicGo INFO] Before transform 
2022-01-08 16:04:21 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-08 16:04:21 [PicGo INFO] Before upload 
2022-01-08 16:04:21 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-08 16:04:21 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-01-08 16:04:23 [PicGo SUCCESS] 
cdn.drxlchan.com/202201081604499.png 
2022-01-08 16:11:47 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-08 16:11:47 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-08 23:36:24 [PicGo INFO] Before transform 
2022-01-08 23:36:24 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-08 23:36:24 [PicGo INFO] Before upload 
2022-01-08 23:36:24 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-08 23:36:24 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-01-08 23:36:25 [PicGo SUCCESS] 
https://cdn.drxlchan.com/202201082336489.png 
2022-01-08 23:51:36 [PicGo INFO] Before transform 
2022-01-08 23:51:36 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-08 23:51:36 [PicGo INFO] Before upload 
2022-01-08 23:51:36 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-08 23:51:36 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-01-08 23:51:38 [PicGo SUCCESS] 
https://cdn.drxlchan.com/202201082351818.png 
2022-01-09 10:41:52 [PicGo INFO] [PicGo Server] shutdown 
2022-01-09 10:50:47 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-09 10:50:47 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-09 10:54:26 [PicGo INFO] Before transform 
2022-01-09 10:54:26 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-09 10:54:26 [PicGo INFO] Before upload 
2022-01-09 10:54:26 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-09 10:54:26 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-01-09 10:54:30 [PicGo SUCCESS] 
https://cdn.drxlchan.com/202201091054937.png 
2022-01-09 11:29:55 [PicGo INFO] Before transform 
2022-01-09 11:29:55 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-09 11:29:55 [PicGo INFO] Before upload 
2022-01-09 11:29:55 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-09 11:29:55 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-01-09 11:30:02 [PicGo SUCCESS] 
https://cdn.drxlchan.com/202201091129367.png 
2022-01-09 12:14:29 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-09 12:14:29 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------

**Comment by Jeffrey28** [comment]
macos下我可以打开日志文件，但是不知道该怎么找到这个文件所在的位置，我用spotlight search找不到

**Comment by Molunerfinn** [comment]
> macos下我可以打开日志文件，但是不知道该怎么找到这个文件所在的位置，我用spotlight search找不到

注意看文档...文档有说到配置文件所在的路径。picgo.db的话是在配置文件同级目录下。看了一下报错确实是picgo.db文件损坏了。找到这个文件发给我，然后你可以直接删掉这个文件，重启picgo即可。

![image](https://user-images.githubusercontent.com/12621342/148674774-9c80b356-4392-47f0-a7bb-0255912f318d.png)


https://picgo.github.io/PicGo-Doc/zh/guide/config.html

![image](https://user-images.githubusercontent.com/12621342/148674752-1cd0ade4-013d-4c03-81f8-b0d739701c96.png)

**Comment by Jeffrey28** [comment]
我现在找到了，我删除picgo.db后，重启应用就好了，感谢。

**Comment by Molunerfinn** [comment]
> 我现在找到了，我删除picgo.db后，重启应用就好了，感谢。

这边看了一下你的picgo.db确实发生了文件损坏。后续主要有两个方面来处理

1. 文件损坏之后，无法使用，picgo会给出一个提示，重新创建一个新的db文件
2. 会推出官方的配置同步插件用于同步配置、相册数据

**Comment by darkThanBlack** [comment]
#### 简介
新用户，遇到相同问题，做个记录

#### 环境
MacBook Pro(13-inch, M1, 2020)
mac OS Big Sur 11.5.1

#### 处理过程
* 从 Github 下载 .dmg 文件，安装时提示"文件已损坏"；
* 执行 ``sudo spctl  --master-disable``，无效；
* 执行 ``sudo spctl  --master-disable ${AppName}``，此处``${AppName}``指``/Applications/PicGo.app``，可以启动应用，但出现
  * 问题1：启动后，应用出现在状态栏上，但左键菜单整体全部变黑（无"已上传"等 UI），右键无反应；
* 打开活动监视器，强制结束和``PicGo``相关的所有进程（ 5 个左右），重新启动应用；
* 应用成功启动，并可以展示相应菜单，配置图床后，图片可以成功上传，但出现
  * 问题2：拖拽上传后页面无反应，'已上传'内无记录，URL 未复制至剪切板；相册区配置后无反应，且重启应用后配置丢失；查看日志文件，URL 成功输出；查看仓库文件，图片已上传成功；尝试访问对应外链，访问成功。
* 找到 ``/Library/Application\ Support/picgo/picgo.db`` 文件并删除，重启应用。
* 问题解决。

**Comment by beermedlar** [comment]
> #### 简介
> 新用户，遇到相同问题，做个记录
> 
> #### 环境
> MacBook Pro(13-inch, M1, 2020) mac OS Big Sur 11.5.1
> 
> #### 处理过程
> * 从 Github 下载 .dmg 文件，安装时提示"文件已损坏"；
> * 执行 `sudo spctl  --master-disable`，无效；
> * 执行 `sudo spctl  --master-disable ${AppName}`，此处`${AppName}`指`/Applications/PicGo.app`，可以启动应用，但出现
>   
>   * 问题1：启动后，应用出现在状态栏上，但左键菜单整体全部变黑（无"已上传"等 UI），右键无反应；
> * 打开活动监视器，强制结束和`PicGo`相关的所有进程（ 5 个左右），重新启动应用；
> * 应用成功启动，并可以展示相应菜单，配置图床后，图片可以成功上传，但出现
>   
>   * 问题2：拖拽上传后页面无反应，'已上传'内无记录，URL 未复制至剪切板；相册区配置后无反应，且重启应用后配置丢失；查看日志文件，URL 成功输出；查看仓库文件，图片已上传成功；尝试访问对应外链，访问成功。
> * 找到 `/Library/Application\ Support/picgo/picgo.db` 文件并删除，重启应用。
> * 问题解决。

相同的流程，同样的解决方法解决好了

**Comment by QY-Sheila** [comment]
请教各位，我也是m1 mac，如何找到 /Library/Application\ Support/picgo/picgo.db文件呢？我一直找不到，所以上传成功后，也看不到图片。

**Comment by AskaJohnny** [comment]
very nice  我也是 m1 mac 一开始 七牛云 一直无法上传,最后删了/Library/Application\ Support/picgo/picgo.db 和 data.json 重启 重新配置 就好了

**Comment by Molunerfinn** [comment]
beta.4应该已经修复相册文件写入失败造成的相册丢失或者相册文件损坏的问题了。可以更新体验。
