### ISSUE TITLE
[BUG] 上传腾讯云COS失败

### ISSUE THREAD

**Issue by czy0538** [Molunerfinn/PicGo#788]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

2021.12.1通过picgo上传腾讯云失败，之前一直可以正常上传。使用SM.MS上传正常。已经排除COS过期或者账号权限错误问题。

## PicGo 的相关信息

PicGo 的版本：2.3.0
所在平台： windows10 21H2

## 问题重现

```c
2021-12-01 10:07:32 [PicGo INFO] Before transform 
2021-12-01 10:07:32 [PicGo INFO] Transforming... Current transformer is [path] 
2021-12-01 10:07:32 [PicGo INFO] Before upload 
2021-12-01 10:07:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-12-01 10:07:32 [PicGo INFO] Uploading... Current uploader is [tcyun] 
2021-12-01 10:07:34 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: connect ECONNREFUSED 127.0.0.1:80
    at new RequestError (D:\software date\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\software date\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\software date\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\software date\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\software date\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2021-12-01 10:07:34 [PicGo WARN] failed 
2021-12-01 10:07:34 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\software date\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\software date\PicGo\resources\app.asar\background.js:36:31625)
-------Error Stack End------- 
2021-12-01 10:07:34 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (D:\software date\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\software date\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\software date\PicGo\resources\app.asar\background.js:36:31625)
-------Error Stack End------- 
```c
---

<!-- 
  最后，喜欢 PicGo 的话不妨给它点个 star~
  如果可以的话，请我喝杯咖啡？首页有赞助二维码，谢谢你的支持！ 
 -->

**Comment by Molunerfinn** [comment]
检查你的代理配置，把picgo的代理配置清空再上传

**Comment by czy0538** [comment]
> 检查你的代理配置，把picgo的代理配置清空再上传

感谢您的回复，我从未设置过picgo代理，相关代理配置一直保持为空。图床中COS出现此问题，SM.MS可以正常上传。
![](https://i.loli.net/2021/12/01/QJRHLEdiKweVkY5.png)

**Comment by Molunerfinn** [comment]
我这边上传是正常的。可以查一下类似的报错，这个是你电脑那边的网络和代理相关的问题

**Comment by jllobvemy** [comment]
其实很有可能是空格的原因，把每个参数后面都注意一下不要留有空格，我是这么解决的
