### ISSUE TITLE
deepin20没法使用

### ISSUE THREAD

**Issue by JeffDing99** [Molunerfinn/PicGo#790]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
2.3 Linux

## 问题重现
``` txt
2021-12-05 19:03:41 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2021-12-05 19:03:41 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/tmp/.mount_PicGo-5wNeI2/resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 

```

用的是github图床，window下没问题，linux版本一直上传失败。sm.ms图床也没问题

**Comment by Molunerfinn** [comment]
网络问题请自行搜索解决办法
