### ISSUE TITLE
M1 出现上传服务器出错

### ISSUE THREAD

**Issue by duochizhacai** [Molunerfinn/PicGo#794]
------Error Stack Begin------
Error: Object has been destroyed
    at WebContents.send (/Applications/PicGo.app/Contents/Resources/electron.asar/browser/api/web-contents.js:103:17)
    at PicGo.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:28289)
    at PicGo.emit (events.js:200:13)
    at Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:32:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2021-12-10 09:38:44 [PicGo WARN] failed 
2021-12-10 09:38:44 [PicGo ERROR] 
------Error Stack Begin------
Error: Object has been destroyed
    at WebContents.send (/Applications/PicGo.app/Contents/Resources/electron.asar/browser/api/web-contents.js:103:17)
    at PicGo.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:28289)
    at PicGo.emit (events.js:200:13)
    at Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:32:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 

请求大佬解决一下 帮帮忙🥺
之前一直用的没问题 突然就不行了 仓库也是public

**Comment by Molunerfinn** [comment]
你这是用什么方式上传的，剪贴板还是命令行调用？

**Comment by Molunerfinn** [comment]
退出重启应用试试呢

**Comment by duochizhacai** [comment]
> 退出重启应用试试呢

哈哈哈我试过了重启应用和重装应用 还有重装客户端都不可以哈。是不是跟翻墙有关呀😣

**Comment by duochizhacai** [comment]
> 退出重启应用试试呢

我试过重启应用和重装应用都不可以诶 重启电脑也不🉑️以  是不是跟翻墙有关呢😣

**Comment by Molunerfinn** [comment]
看这报错跟electron窗口销毁有点关系，还没进上传逻辑。

你直接在主窗口拖动上传图片，然后把报错日志发上来看看

**Comment by duochizhacai** [comment]
2021-12-10 15:11:53 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ETIMEDOUT
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
> 2021-12-10 15:11:53 [PicGo ERROR] ------Error Stack Begin------ RequestError: Error: read ETIMEDOUT at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22) at Request.emit (events.js:200:13) at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8) at ClientRequest.emit (events.js:200:13) at TLSSocket.socketErrorListener (_http_client.js:402:9) at TLSSocket.emit (events.js:200:13) at emitErrorNT (internal/streams/destroy.js:91:8) -------Error Stack End-------

这个报错是网络问题，可以看一下代理设置

**Comment by duochizhacai** [comment]
我用的shadowsocks 全局模式
