### ISSUE TITLE
[bug] ubuntu18下无法安装插件

### ISSUE THREAD

**Issue by CommradeStarLight** [Molunerfinn/PicGo#797]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息

 ubuntu18.04

## 问题重现
 **_ubuntu18.04下无法下载gitee的任何插件 但在ubuntu16下可以正常下载_**

2021-12-17 22:37:38 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-12-17 22:38:23 [PicGo ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
-------Error Stack End------- 
2021-12-17 22:38:23 [PicGo ERROR] NPM is not installed 
2021-12-17 22:38:23 [PicGo ERROR] 插件安装失败，失败码为-2，错误日志为 
2021-12-17 22:38:31 [PicGo ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
-------Error Stack End------- 
2021-12-17 22:38:31 [PicGo ERROR] NPM is not installed 
2021-12-17 22:38:31 [PicGo ERROR] 插件安装失败，失败码为-2，错误日志为 
2021-12-17 22:42:47 [PicGo ERROR] 插件安装失败，失败码为1，错误日志为[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m npm does not support Node.js v8.10.0
[0m[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m You should probably upgrade to a newer version of node as we
[0m[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m can't make any promises that npm will work with this version.
[0m[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m You can find the latest version at https://nodejs.org/
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m URL is not defined
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /home/commrade_starlight/.npm/_logs/2021-12-17T14_42_47_321Z-debug.log
[0m 
**2021-12-17 22:42:52 [PicGo ERROR] 插件安装失败，失败码为1，错误日志为[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m npm does not support Node.js v8.10.0
[0m[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m You should probably upgrade to a newer version of node as we
[0m[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m can't make any promises that npm will work with this version.
[0m[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mnpm[0m You can find the latest version at https://nodejs.org/
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m URL is not defined
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /home/commrade_starlight/.npm/_logs/2021-12-17T14_42_52_985Z-debug.log**

---

**Comment by CommradeStarLight** [comment]
PICTURE:/home/commrade_starlight/.config/tencent-qq/1055271080/image/origin/B45471B3A21042AE2DFA4467B8D1807A.jpg

**Comment by CommradeStarLight** [comment]
加粗的为下载时弹出的错误提示，重启、更改软件版本都没有效果

**Comment by Molunerfinn** [comment]
Linux的环境变量问题，已知

安装一下Node.js（最好版本在12及以上）

然后可以打开PicGo的配置文件所在路径，手动安装插件: `npm install picgo-plugin-xxx` xxx为插件名。

**Comment by Molunerfinn** [comment]
重复issue，放到这里一起处理：https://github.com/Molunerfinn/PicGo/issues/774

**Comment by CommradeStarLight** [comment]
> 重复issue，放到这里一起处理：#774

感谢，当时看环境不同以为是不同问题，麻烦了
