### ISSUE TITLE
[bug] 2.3.0版本，使用GitHub图床上传错误：unable to verify the first certificate

### ISSUE THREAD

**Issue by Mask37** [Molunerfinn/PicGo#804]
根据[配置手册#github图床](https://picgo.github.io/PicGo-Doc/zh/guide/config.html#github%E5%9B%BE%E5%BA%8A)进行配置，上传图片错误，错误日志：
```
2021-12-23 15:15:33 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-12-23 15:18:34 [PicGo INFO] Before transform 
2021-12-23 15:18:34 [PicGo INFO] Transforming... Current transformer is [path] 
2021-12-23 15:18:34 [PicGo INFO] Before upload 
2021-12-23 15:18:34 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-12-23 15:18:34 [PicGo INFO] Uploading... Current uploader is [github] 
2021-12-23 15:18:34 [PicGo WARN] failed 
2021-12-23 15:18:34 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2021-12-23 15:18:34 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
```

**Comment by Molunerfinn** [comment]
这种情况一般是你的代理配置的问题，是网络相关的。

可以去picgo的代理配置里配置你对应的http代理。
