### ISSUE TITLE
gitee图床提交无端404失败 #bug

### ISSUE THREAD

**Issue by Tracker647** [Molunerfinn/PicGo#813]
一两个月前一直能正常转化图片链接到gitee，最近再上传图片就报404错误了，试着重装gitee-loader，重装picgo都无法解决问题，看了下令牌文件的修改日期在最后一次上传图片之后排除了令牌被修改的问题，由报错文件看起来像Picgo内部的问题或者是gitee-loader的问题，具体未知

## 问题类型

BUG

## PicGo 的相关信息

Windows 10, Picgo2.3.0

## 问题重现

```
------Error Stack Begin------
StatusCodeError: 404 - {"status":"404","error":"Not Found"}
    at new StatusCodeError (C:\Users\hw\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\hw\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\hw\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\hw\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\Users\hw\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\Users\hw\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
```

**Comment by Molunerfinn** [comment]
去gitee插件仓库提问

**Comment by zjj0723** [comment]
我安装了gitee插件，上传图片时，一直报tunneling socket could not be established, cause=socket hang up，是网络问题吗？该如何解决。
2022-01-29 14:35:04 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: tunneling socket could not be established, cause=socket hang up
    at new RequestError (D:\tools\picGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\tools\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\tools\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\tools\picGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\tools\picGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at ClientRequest.onError (D:\tools\picGo\resources\app.asar\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
-------Error Stack End-------
