### ISSUE TITLE
http请求无响应，但图片上传了

### ISSUE THREAD

**Issue by supermanc88** [Molunerfinn/PicGo#816]
使用版本：2.3.1-beta.2 arm64版本
机器：m1 pro

![image](https://user-images.githubusercontent.com/8957358/148724052-715f96e5-60d0-41a8-8fff-318db3a739ef.png)

![image](https://user-images.githubusercontent.com/8957358/148724109-0df367df-3601-4e66-af38-7e2f5bed36ab.png)

和 https://github.com/Molunerfinn/PicGo/issues/627 问题类似

**Comment by Molunerfinn** [comment]
这边用beta2-x64的版本没有问题。回头找一台arm64的看一下... 你的M1用beta2-x64的版本的话会出现这个问题么

**Comment by supermanc88** [comment]
> 

我用x64的版本也是这个情况，不知道是不是我机器的原因，系统是 Monterey 12.1

**Comment by Molunerfinn** [comment]
我的系统也是12.1

不过理论上能接到响应的情况下，返回消息没有报错应该是正常的才对

**Comment by supermanc88** [comment]
这个有意思了，失败的时候有返回，成功却没有
我给了一个错误的图片路径，有错误返回
<img width="873" alt="image" src="https://user-images.githubusercontent.com/8957358/148747212-e15d91a5-31ba-460b-8d78-613b65cd7a4e.png">

**Comment by supermanc88** [comment]
我共测试了2.3.1-beta版本和2.3.0正式版，这两个版本均不返回响应，退到2.2.2版本可正常使用

**Comment by Molunerfinn** [comment]
> 我共测试了2.3.1-beta版本和2.3.0正式版，这两个版本均不返回响应，退到2.2.2版本可正常使用

看起来跟picgo.db有点关系。

可以装回2.3.x版本，然后看看上传成功后能否在相册里看到结果？如果不行应该跟这个issue的情况是一样的：https://github.com/Molunerfinn/PicGo/issues/817

可以找到配置文件所在路径的 `picgo.db`，发到我的邮箱，然后删掉这个文件再重启picgo应该就好了

**Comment by Molunerfinn** [comment]
另外可以看看日志里有没有类似这样的报错：
------Error Stack Begin------
Error: unexpected end of file
at Zlib.zlibOnError [as onerror]

**Comment by supermanc88** [comment]
确实有上面的报错，2.3.x版本上传成功情况下，相册中并不能看到结果。删除picgo.db重启后，出现其它错误：
```
2022-01-11 10:23:36 [PicGo INFO] Before transform
2022-01-11 10:23:36 [PicGo INFO] Transforming... Current transformer is [path]
2022-01-11 10:23:36 [PicGo INFO] Before upload
2022-01-11 10:23:36 [PicGo INFO] beforeUploadPlugins: renameFn running
2022-01-11 10:23:36 [PicGo INFO] Uploading... Current uploader is [github]
2022-01-11 10:23:38 [PicGo WARN] failed
2022-01-11 10:23:38 [PicGo ERROR]
------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
-------Error Stack End-------
2022-01-11 10:23:38 [PicGo ERROR]
------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
-------Error Stack End-------
2022-01-11 10:23:38 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑
```

<img width="860" alt="image" src="https://user-images.githubusercontent.com/8957358/148870418-9eb75f2b-e0ae-4d4f-84b0-5a0d8b01f313.png">

**Comment by supermanc88** [comment]
db文件已发你邮箱

**Comment by Molunerfinn** [comment]
> 确实有上面的报错，2.3.x版本上传成功情况下，相册中并不能看到结果。删除picgo.db重启后，出现其它错误：
> 
> ```
> 2022-01-11 10:23:36 [PicGo INFO] Before transform
> 2022-01-11 10:23:36 [PicGo INFO] Transforming... Current transformer is [path]
> 2022-01-11 10:23:36 [PicGo INFO] Before upload
> 2022-01-11 10:23:36 [PicGo INFO] beforeUploadPlugins: renameFn running
> 2022-01-11 10:23:36 [PicGo INFO] Uploading... Current uploader is [github]
> 2022-01-11 10:23:38 [PicGo WARN] failed
> 2022-01-11 10:23:38 [PicGo ERROR]
> ------Error Stack Begin------
> StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
>     at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
>     at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
>     at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
>     at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
>     at Request.emit (node:events:394:28)
>     at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
>     at Request.emit (node:events:394:28)
>     at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (node:events:513:28)
>     at IncomingMessage.emit (node:events:406:35)
> -------Error Stack End-------
> 2022-01-11 10:23:38 [PicGo ERROR]
> ------Error Stack Begin------
> StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
>     at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
>     at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
>     at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
>     at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
>     at Request.emit (node:events:394:28)
>     at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
>     at Request.emit (node:events:394:28)
>     at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (node:events:513:28)
>     at IncomingMessage.emit (node:events:406:35)
> -------Error Stack End-------
> 2022-01-11 10:23:38 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑
> ```
> 
> <img alt="image" width="860" src="https://user-images.githubusercontent.com/8957358/148870418-9eb75f2b-e0ae-4d4f-84b0-5a0d8b01f313.png">

422这个错误码是github图床不能上传同名文件导致的报错。现在看起来正常了

**Comment by Molunerfinn** [comment]
没收到db文件...
不过应该大概率是db文件损坏导致的。目前看来有好几例了，后续会做一个功能处理一下损坏文件自动修复。

**Comment by supermanc88** [comment]
给你发的marksz@teamsz.xyz 这个邮箱

**Comment by qingmo** [comment]
今天我也遇到了相同的问题，根据大神们的讨论的确也能解决问题。
**原因**
picgo.db损坏

**日志**
```
2022-04-15 10:22:45 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-04-15 10:22:46 [PicGo ERROR] process error begin
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------

```

**临时解决办法**
关闭应用
cd ~/Library/Application\ Support/picgo && rm picgo.db
重开应用

**环境**
PicGo版本：2.3.1-beta.3

**Comment by wuranxu** [comment]
也遇到了，gs的渣渣电脑，正好在图片上传的时候重启了，直接导致picgo图片上传接口没响应了，是要删除下db文件对吧？

**Comment by Molunerfinn** [comment]
> 也遇到了，gs的渣渣电脑，正好在图片上传的时候重启了，直接导致picgo图片上传接口没响应了，是要删除下db文件对吧？

对，这是因为突然断电或者重启导致db文件写失败的问题。
