### ISSUE TITLE
macOS Monterey 下上传图片之后未复制链接，相册中也无图片的信息

### ISSUE THREAD

**Issue by DingJunyao** [Molunerfinn/PicGo#823]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report：

macOS Monterey 下，在 开启上传提示 已打开的情况下，上传图片之后，未复制链接至剪贴板。相册中也无图片的信息。

## PicGo 的相关信息

版本：2.3.1-beta.2

平台：macOS Monterey

## 问题重现

开启上传提示 已打开。

相册中无图片的信息：

<img width="802" alt="相册中无图片的信息" src="https://user-images.githubusercontent.com/11372753/149651254-485c9db4-af2e-4bc5-884d-eebc2d55bd64.png">

日志如下：

```
2022-01-16 14:36:03 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 14:36:03 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-16 14:42:04 [PicGo INFO] Before transform 
2022-01-16 14:42:04 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:42:04 [PicGo INFO] Before upload 
2022-01-16 14:42:04 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:42:04 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:42:05 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161442539.png/imageslim 
2022-01-16 14:42:58 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 14:42:58 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-16 14:43:07 [PicGo INFO] Before transform 
2022-01-16 14:43:07 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:43:07 [PicGo INFO] Before upload 
2022-01-16 14:43:07 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:43:07 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:43:07 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161443062.png/imageslim 
2022-01-16 14:44:45 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:44:46 [PicGo INFO] Before transform 
2022-01-16 14:44:46 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:44:46 [PicGo INFO] Before upload 
2022-01-16 14:44:46 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:44:46 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:44:47 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161444468.png/imageslim 
2022-01-16 14:45:27 [PicGo INFO] [PicGo Server] shutdown 
2022-01-16 14:48:24 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 14:48:24 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-16 14:48:52 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:48:52 [PicGo INFO] Before transform 
2022-01-16 14:48:52 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:48:52 [PicGo INFO] Before upload 
2022-01-16 14:48:52 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:48:57 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:48:59 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161448777.png/imageslim 
2022-01-16 14:49:04 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:49:11 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:49:11 [PicGo INFO] Before transform 
2022-01-16 14:49:11 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:49:11 [PicGo INFO] Before upload 
2022-01-16 14:49:11 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:49:11 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:49:12 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161449831.png/imageslim 
2022-01-16 14:50:55 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:50:56 [PicGo INFO] Before transform 
2022-01-16 14:50:56 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:50:56 [PicGo INFO] Before upload 
2022-01-16 14:50:56 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:50:56 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:50:57 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161450502.png/imageslim 
2022-01-16 14:52:10 [PicGo INFO] Before transform 
2022-01-16 14:52:10 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:52:10 [PicGo INFO] Before upload 
2022-01-16 14:52:10 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:52:10 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:52:11 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161452724.png/imageslim 
2022-01-16 14:53:09 [PicGo INFO] Before transform 
2022-01-16 14:53:09 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:53:09 [PicGo INFO] Before upload 
2022-01-16 14:53:09 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:53:09 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:53:10 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161453594.png/imageslim 
2022-01-16 14:53:52 [PicGo INFO] Before transform 
2022-01-16 14:53:52 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:53:52 [PicGo INFO] Before upload 
2022-01-16 14:53:52 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:53:52 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:53:53 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161453459.png/imageslim 
2022-01-16 14:55:25 [PicGo INFO] [PicGo Server] shutdown 
2022-01-16 14:55:30 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 14:55:30 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-16 14:55:34 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:55:35 [PicGo INFO] Before transform 
2022-01-16 14:55:35 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:55:35 [PicGo INFO] Before upload 
2022-01-16 14:55:35 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:55:35 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:55:38 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161455344.png/imageslim 
2022-01-16 14:56:28 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:56:29 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 14:56:29 [PicGo INFO] Before transform 
2022-01-16 14:56:29 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 14:56:29 [PicGo INFO] Before upload 
2022-01-16 14:56:29 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 14:56:29 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 14:56:31 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161456627.png/imageslim 
2022-01-16 15:02:56 [PicGo INFO] Before transform 
2022-01-16 15:02:56 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:02:56 [PicGo INFO] Before upload 
2022-01-16 15:02:56 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:02:56 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:02:58 [PicGo SUCCESS] 
https://4ading.oss-cn-shanghai.aliyuncs.com/img/2022/202201161502223.png/imageslim 
2022-01-16 15:06:18 [PicGo INFO] [PicGo Server] shutdown 
2022-01-16 15:07:44 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 15:07:44 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17)
-------Error Stack End-------
2022-01-16 15:08:25 [PicGo INFO] Before transform 
2022-01-16 15:08:25 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:08:25 [PicGo INFO] Before upload 
2022-01-16 15:08:25 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:08:25 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:08:26 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161508928.png/imageslim 
2022-01-16 15:09:12 [PicGo INFO] [PicGo Server] shutdown 
2022-01-16 15:10:14 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 15:10:14 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17)
-------Error Stack End-------
2022-01-16 15:10:18 [PicGo INFO] [PicGo Server] shutdown 
2022-01-16 15:10:36 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 15:10:36 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17)
-------Error Stack End-------
2022-01-16 15:11:05 [PicGo INFO] Before transform 
2022-01-16 15:11:05 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:11:05 [PicGo INFO] Before upload 
2022-01-16 15:11:05 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:11:05 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:11:07 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161511887.png/imageslim 
2022-01-16 15:11:29 [PicGo INFO] Before transform 
2022-01-16 15:11:29 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:11:29 [PicGo INFO] Before upload 
2022-01-16 15:11:29 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:11:29 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:11:34 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161511557.png/imageslim 
2022-01-16 15:11:50 [PicGo INFO] Before transform 
2022-01-16 15:11:50 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:11:50 [PicGo INFO] Before upload 
2022-01-16 15:11:50 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:11:50 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:11:55 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161511934.png/imageslim 
2022-01-16 15:12:02 [PicGo INFO] Before transform 
2022-01-16 15:12:02 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:12:02 [PicGo INFO] Before upload 
2022-01-16 15:12:02 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:12:02 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:12:04 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161512691.png/imageslim 
2022-01-16 15:12:18 [PicGo INFO] Before transform 
2022-01-16 15:12:18 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:12:18 [PicGo INFO] Before upload 
2022-01-16 15:12:18 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:12:18 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:12:22 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161512195.png/imageslim 
2022-01-16 15:12:55 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 15:12:55 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17)
-------Error Stack End-------
2022-01-16 15:13:32 [PicGo INFO] [PicGo Server] shutdown 
2022-01-16 15:13:45 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 15:13:45 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-16 15:13:50 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 15:13:50 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 15:13:51 [PicGo INFO] Before transform 
2022-01-16 15:13:51 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:13:51 [PicGo INFO] Before upload 
2022-01-16 15:13:51 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:13:51 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:14:51 [PicGo WARN] failed 
2022-01-16 15:14:51 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: Client network socket disconnected before secure TLS connection was established
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
-------Error Stack End------- 
2022-01-16 15:14:51 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: Client network socket disconnected before secure TLS connection was established
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
-------Error Stack End------- 
2022-01-16 15:15:00 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 15:15:01 [PicGo INFO] Before transform 
2022-01-16 15:15:01 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:15:01 [PicGo INFO] Before upload 
2022-01-16 15:15:01 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:15:01 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:15:31 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161515115.png/imageslim 
2022-01-16 15:16:26 [PicGo INFO] Before transform 
2022-01-16 15:16:26 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:16:26 [PicGo INFO] Before upload 
2022-01-16 15:16:26 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:16:26 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:16:30 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161516838.png/imageslim 
2022-01-16 15:17:34 [PicGo INFO] Before transform 
2022-01-16 15:17:34 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:17:34 [PicGo INFO] Before upload 
2022-01-16 15:17:34 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:17:34 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:17:36 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161517445.png/imageslim 
2022-01-16 15:18:14 [PicGo INFO] Before transform 
2022-01-16 15:18:14 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:18:14 [PicGo INFO] Before upload 
2022-01-16 15:18:14 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:18:14 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:18:18 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161518025.png/imageslim 
2022-01-16 15:25:33 [PicGo INFO] [PicGo Server] shutdown 
2022-01-16 15:25:45 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-01-16 15:25:45 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
-------Error Stack End-------
2022-01-16 15:25:58 [PicGo INFO] Before transform 
2022-01-16 15:25:58 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:25:58 [PicGo INFO] Before upload 
2022-01-16 15:25:58 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:25:58 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:25:59 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161525200.png/imageslim 
2022-01-16 15:26:14 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 15:26:14 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: h.systemPreferences.isDarkMode is not a function
    at Object.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:561003)
    at Object.emit (node:events:394:28)
-------Error Stack End-------
2022-01-16 15:26:15 [PicGo INFO] Before transform 
2022-01-16 15:26:15 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:26:15 [PicGo INFO] Before upload 
2022-01-16 15:26:15 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:26:15 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2022-01-16 15:26:16 [PicGo SUCCESS] 
https://static.a4ding.com/img/2022/202201161526135.png/imageslim 
2022-01-16 15:26:30 [PicGo INFO] Before transform 
2022-01-16 15:26:30 [PicGo INFO] Transforming... Current transformer is [path] 
2022-01-16 15:26:30 [PicGo INFO] Before upload 
2022-01-16 15:26:30 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-01-16 15:26:30 [PicGo INFO] Uploading... Current uploader is [aliyun] 
```

这几次上传均未复制链接到剪贴板，但上传成功之后，日志中会有图片链接，能够正常访问。

**Comment by Molunerfinn** [comment]
删掉配置文件所在目录的picgo.db文件，重启picgo即可

**Comment by CZT0** [comment]
> 删掉配置文件所在目录的picgo.db文件，重启picgo即可

遇到相同的问题，这个方式有效
