### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by Nesxc** [Molunerfinn/PicGo#833]
Error: Cannot find module 'C:\Users\Hr082\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Function.Module._resolveFilename (G:\picgo\resources\electron.asar\common\reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (G:\picgo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:125:24)
    at PluginLoader.registerPlugin (G:\picgo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:78:26)
    at G:\picgo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginHandler.js:40:43
-------Error Stack End-------

**Comment by wstZeng09** [comment]
想问下后来解决了吗，我也遇到这个问题，现实安装成功(github-plus/gitee)，无法正常开启插件

2022-02-09 15:22:45 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module '/Users/zyc/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus'
Require stack:
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js
- /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/index.js
- /Applications/PicGo.app/Contents/Resources/app.asar/background.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Applications/PicGo.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:125:24)
    at PluginLoader.registerPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginLoader.js:78:26)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginHandler.js:40:43
    at Array.forEach (<anonymous>)
    at PluginHandler.install (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/lib/PluginHandler.js:39:29)
-------Error Stack End------- 
2022-02-09 15:22:45 [PicGo SUCCESS] 插件安装成功

**Comment by fengxiuyang** [comment]
我也遇到了这个问题，在最新的正式版和beta版软件中
