### ISSUE TITLE
Mac 系统 SmMs 图床，填写 Token 后依然无法上传，手动上传时边框栏呈红色。

### ISSUE THREAD

**Issue by ccc592** [Molunerfinn/PicGo#842]
## 问题类型

 Bug Report 

## PicGo 的相关信息

 Mac

## 问题重现

Mac 系统 SmMs 图床，填写 Token 后依然无法上传，手动上传时边框栏呈红色。

![image](https://user-images.githubusercontent.com/63574264/154619324-4ebe74c2-093b-4432-a12f-a6395efcf931.png)

-------Error Stack End------- 
2022-02-18 12:43:44 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
检查网络设置是否开启了代理等
