### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Yrc030** [Molunerfinn/PicGo#858]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
- Bug Report

## PicGo 的相关信息

- 版本：2.3.0-brta.4
- 平台：windows 

## 问题重现
使用 picgo + chevereto 进行图床搭建，上传失败，错误如下：

~~~markdown
------Error Stack Begin------
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handle (C:\Users\joker\AppData\Roaming\picgo\node_modules\picgo-plugin-chevereto\src\index.js:34:21)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (D:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:72:9)
    at async Lifecycle.start (D:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:22:13)
    at async PicGo.upload (D:\Program Files\picgo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:176:13)
-------Error Stack End------- 
~~~

使用网页端上传图片可以成功。

使用 Postman 向上传图片的 RestAPI 发送请求，响应为 HTML 页面，如下图：

![image](https://user-images.githubusercontent.com/82157706/160094150-9ac9dbed-ea14-455f-a755-77b41dcb1fd4.png)

请问大佬应该如何解决，谢谢！

---

**Comment by Molunerfinn** [comment]
配置有问题，json不合法导致解析错误。

请去对应插件仓库提问

**Comment by Yrc030** [comment]
> 合法导致解

好的，谢谢大佬
