### ISSUE TITLE
七牛云中上传域名少个p，导致华东-浙江2无法上传

### ISSUE THREAD

**Issue by q314872695** [Molunerfinn/PicGo#863]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report
## PicGo 的相关信息

Windows 2.3.0
## 问题重现

七牛云创建了个华东-浙江2的对象存储，图片一直上传失败，调试后发现日志中的上传网址是`upload-cn-east-2.qiniu.com`，而七牛云文档中的是`http(s)://upload-cn-east-2.qiniup.com`，在qiniu的后面少了个p，后来测试其它区域的上传网址少了p可以，但华东-浙江2就不行，官方文档中都是`qiniup.com`，不知道为啥软件中是`qiniu.com`
[七牛云存储区域](https://developer.qiniu.com/kodo/1671/region-endpoint-fq)
![image](https://user-images.githubusercontent.com/41626157/160740706-660c4098-3e1d-4639-a9a2-a9e072b87afd.png)

------Error Stack Begin------
RequestError: Error: getaddrinfo ENOTFOUND upload-cn-east-2.qiniu.com
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------
## 功能请求

---

**Comment by Molunerfinn** [comment]
因为一开始七牛的上传域名只有qiniu.com。

后续会给七牛补充一个选项，用于手动指定加速上传的地址

**Comment by Molunerfinn** [comment]
更新最新beta3即可

**Comment by penzed** [comment]
我也发现来了这个问题，上传失败
环境：windos 11 21H2,picog-2.3.1-beta.3,七牛云，地区:华南

报错日志：
2022-05-16 01:24:05 [PicGo WARN] failed 
2022-05-16 01:24:05 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: getaddrinfo ENOTFOUND xn--upload--qp2ltc.qiniup.com
    at new RequestError (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
-------Error Stack End------- 
2022-05-16 01:24:05 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: getaddrinfo ENOTFOUND xn--upload--qp2ltc.qiniup.com
    at new RequestError (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (D:\Users\pinux\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
-------Error Stack End-------
