### ISSUE TITLE
又拍云上传报错

### ISSUE THREAD

**Issue by 99165655** [Molunerfinn/PicGo#866]
-------Error Stack End------- 
2022-04-01 00:28:55 [PicGo INFO] Before transform 
2022-04-01 00:28:55 [PicGo INFO] Transforming... Current transformer is [path] 
2022-04-01 00:28:55 [PicGo INFO] Before upload 
2022-04-01 00:28:55 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-04-01 00:28:56 [PicGo INFO] Uploading... Current uploader is [upyun] 
2022-04-01 00:29:03 [PicGo WARN] failed 
2022-04-01 00:29:03 [PicGo ERROR] 
------Error Stack Begin------
SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handle (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\upyun.js:72:31)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
2022-04-01 00:29:03 [PicGo ERROR] 
------Error Stack Begin------
SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handle (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\upyun.js:72:31)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 

![image](https://user-images.githubusercontent.com/44029594/161106840-154bd059-faca-4743-acb1-c1354940666a.png)

**Comment by Molunerfinn** [comment]
配置有问题，又拍云那边上传没过
