### ISSUE TITLE
[Bug]: 本地上传图标一直提示 Error: You must be logged in to use.

### ISSUE THREAD

**Issue by Meik0o** [Molunerfinn/PicGo#871]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.2.2

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用的gitee结合picgo  在进行图片上传的时候提示You must be logged in to use 
gitee配置检查无问题
网上找过教程以及参考文档 未能解决问题
麻烦看下 辛苦了

### 相关日志 | Logs

2022-04-05 18:07:07 [PicGo INFO] Before transform
2022-04-05 18:07:07 [PicGo INFO] Transforming...
2022-04-05 18:07:07 [PicGo INFO] Before upload
2022-04-05 18:07:07 [PicGo INFO] Uploading...
2022-04-05 18:07:07 [PicGo WARN] failed
2022-04-05 18:07:07 [PicGo ERROR] Error: You must be logged in to use.
------Error Stack Begin------
Error: You must be logged in to use.
    at Object.handle (D:\picgo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\smms.js:47:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (D:\picgo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:70:9)
    at async Lifecycle.start (D:\picgo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:21:13)
    at async PicGo.upload (D:\picgo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:156:13)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
gitee问题请在gitee插件仓库提问
