### ISSUE TITLE
[Bug]: 知乎图片无法上传

### ISSUE THREAD

**Issue by RuJingTingShan** [Molunerfinn/PicGo#876]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

说一下我的软件：Typora+picgo+github

我从网络上剪藏文档，其中的图片自动上传。
大部分图片都好用，但今天发现知乎图片出错了，日志显示的是“ xxx is not image”

然后我把下面的图片地址放进地址栏，发现它自动下载了，而非自动显示在浏览器里
https://pic1.zhimg.com/v2-3fc60125ad231e09ccd8ad739ca890dc_r.jpg
这里可能有什么我不清楚的机制在里面，我对着地址栏思考半天，删掉了最后的_r
https://pic1.zhimg.com/v2-3fc60125ad231e09ccd8ad739ca890dc.jpg
结果可以正常使用了。

但是并不是每个带_r的图片都不能自动上传，有的可以有的不可以，目前尚不清楚机制。
而且手动改地址很累。

### 相关日志 | Logs

2022-04-16 13:38:42 [PicGo ERROR] 
------Error Stack Begin------
Error: https://pic1.zhimg.com/v2-3fc60125ad231e09ccd8ad739ca890dc_r.jpg is not image
    at D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:25:19
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
    at async Object.handle (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:6:5)
    at async Lifecycle.doTransform (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:59:9)
    at async Lifecycle.start (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:24:13)
    at async PicGo.upload (D:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\Program Files\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\Program Files\PicGo\resources\app.asar\background.js:36:31625)
    at async D:\Program Files\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End------- 
2022-04-16 13:38:42 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by RuJingTingShan** [comment]
又遇到一个
https://pic1.zhimg.com/v2-6dc2bb29d64102e1f58375364f26e3a7.jpg

这次图片本身就不带_r，一样会自动下载，我只好改域名
https://pic2.zhimg.com/v2-6dc2bb29d64102e1f58375364f26e3a7.jpg
就可以了
深层次的原因究竟是什么呢？

**Comment by Molunerfinn** [comment]
typora调用的picgo只能上传系统路径的图片，其余的图片（比如url之类的）不保证能上传。

这个是typora的问题，不是picgo的
