### ISSUE TITLE
[Bug]: 再上传些较大文件（< 100）至 Github 仓库时报错

### ISSUE THREAD

**Issue by zkitefly** [Molunerfinn/PicGo#880]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

有时候会利用 Github 来分发些大于 50 mb 小于 100 mb 的文件，使用 PicGo 上传（无代理），结果报错

不太清楚是否是我 [仓库](https://github.com/zkitefly/myphoto) 的问题？（如果是，请问是何种原因，是不是仓库太大了？）

https://docs.github.com/cn/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits

日志摘取（仅摘取 Error 部分）：
```
-------Error Stack End------- 
2022-04-17 10:33:05 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:01:04 [PicGo INFO] Before transform 
2022-04-17 11:01:04 [PicGo INFO] Transforming... Current transformer is [path] 
2022-04-17 11:01:06 [PicGo WARN] can't get /home/zkitefly/UNDERVERSE-0.6.zip's image size 
2022-04-17 11:01:06 [PicGo WARN] fallback to 200 * 200 
2022-04-17 11:01:06 [PicGo INFO] Before upload 
2022-04-17 11:01:06 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-04-17 11:01:14 [PicGo INFO] Uploading... Current uploader is [github] 
2022-04-17 11:02:15 [PicGo WARN] failed 
2022-04-17 11:02:15 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:02:15 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:03:06 [PicGo INFO] [PicGo Server] shutdown 
2022-04-17 11:03:12 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-04-17 11:03:36 [PicGo INFO] Before transform 
2022-04-17 11:03:36 [PicGo INFO] Transforming... Current transformer is [path] 
2022-04-17 11:03:38 [PicGo WARN] can't get /home/zkitefly/UNDERVERSE-0.6.mp4's image size 
2022-04-17 11:03:38 [PicGo WARN] fallback to 200 * 200 
2022-04-17 11:03:38 [PicGo INFO] Before upload 
2022-04-17 11:03:38 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-04-17 11:03:41 [PicGo INFO] Uploading... Current uploader is [github] 
2022-04-17 11:04:51 [PicGo WARN] failed 
2022-04-17 11:04:51 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:04:51 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
```

data.json ：
```
{
  "picBed": {
    "current": "github",
    "uploader": "github",
    "smms": {
      "token": ""
    },
    "list": [
      {
        "name": "SM.MS图床",
        "type": "smms",
        "visible": false
      },
      {
        "name": "腾讯云COS",
        "type": "tcyun",
        "visible": false
      },
      {
        "name": "GitHub图床",
        "type": "github",
        "visible": true
      },
      {
        "name": "七牛图床",
        "type": "qiniu",
        "visible": false
      },
      {
        "name": "Imgur图床",
        "type": "imgur",
        "visible": false
      },
      {
        "name": "阿里云OSS",
        "type": "aliyun",
        "visible": false
      },
      {
        "name": "又拍云图床",
        "type": "upyun",
        "visible": false
      }
    ],
    "github": {
      "branch": "main",
      "customUrl": "https://cdn.jsdelivr.net/gh/zkitefly/myphoto",
      "path": "2022/",
      "repo": "zkitefly/myphoto",
      "token": "ghp_EvfFr9s8hJ72GTR6ty0RoIhmYh**********"
    }
  },
  "settings": {
    "shortKey": {
      "picgo:upload": {
        "enable": true,
        "key": "CommandOrControl+Shift+P",
        "name": "upload",
        "label": "快捷上传"
      }
    },
    "server": {
      "port": 36677,
      "host": "127.0.0.1",
      "enable": true
    },
    "privacyEnsure": true,
    "showUpdateTip": true,
    "pasteStyle": "markdown",
    "autoStart": true,
    "miniWindowOntop": false,
    "uploadNotification": true,
    "autoRename": false,
    "rename": true,
    "checkBetaUpdate": false,
    "logLevel": [
      "error"
    ]
  },
  "picgoPlugins": {},
  "debug": true,
  "PICGO_ENV": "GUI",
  "needReload": false
}
```

### 相关日志 | Logs

```
-------Error Stack End------- 
2022-04-17 10:33:05 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:01:04 [PicGo INFO] Before transform 
2022-04-17 11:01:04 [PicGo INFO] Transforming... Current transformer is [path] 
2022-04-17 11:01:06 [PicGo WARN] can't get /home/zkitefly/UNDERVERSE-0.6.zip's image size 
2022-04-17 11:01:06 [PicGo WARN] fallback to 200 * 200 
2022-04-17 11:01:06 [PicGo INFO] Before upload 
2022-04-17 11:01:06 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-04-17 11:01:14 [PicGo INFO] Uploading... Current uploader is [github] 
2022-04-17 11:02:15 [PicGo WARN] failed 
2022-04-17 11:02:15 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:02:15 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.AFVMTIk/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:03:06 [PicGo INFO] [PicGo Server] shutdown 
2022-04-17 11:03:12 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-04-17 11:03:36 [PicGo INFO] Before transform 
2022-04-17 11:03:36 [PicGo INFO] Transforming... Current transformer is [path] 
2022-04-17 11:03:38 [PicGo WARN] can't get /home/zkitefly/UNDERVERSE-0.6.mp4's image size 
2022-04-17 11:03:38 [PicGo WARN] fallback to 200 * 200 
2022-04-17 11:03:38 [PicGo INFO] Before upload 
2022-04-17 11:03:38 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-04-17 11:03:41 [PicGo INFO] Uploading... Current uploader is [github] 
2022-04-17 11:04:51 [PicGo WARN] failed 
2022-04-17 11:04:51 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-04-17 11:04:51 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 502 - {"message":"Server Error"}
    at new StatusCodeError (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/tmp/.mount_base.Ajhu2Si/resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
```

**Comment by Molunerfinn** [comment]
github限制 服务端问题。另外不要把github当网盘
