### ISSUE TITLE
[Bug]: typora上传图片，默认上传两次，第二次报错，导致typora不能拿到url

### ISSUE THREAD

**Issue by sdd1989** [Molunerfinn/PicGo#881]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

在mac上，typora上传图片必现

### 相关日志 | Logs

2022-04-18 16:44:46 [PicGo INFO] [PicGo Server] get the request {"list":["\/Users\/guomeiling\/Library\/Application Support\/typora-user-images\/image-20220418164446288.png"]}
2022-04-18 16:44:46 [PicGo INFO] [PicGo Server] upload files in list
2022-04-18 16:44:46 [PicGo INFO] Before transform
2022-04-18 16:44:46 [PicGo INFO] Transforming... Current transformer is [path]
2022-04-18 16:44:46 [PicGo INFO] Before upload
2022-04-18 16:44:46 [PicGo INFO] beforeUploadPlugins: renameFn running
2022-04-18 16:44:46 [PicGo INFO] Uploading... Current uploader is [githubPlus]

2022-04-18 16:44:49 [PicGo SUCCESS]
https://gitee.com/qiuliang_2015/picture/raw/master/typora/image-20220418164446288.png

2022-04-18 16:45:52 [PicGo INFO] [PicGo Server] get the request {"list":["\/Users\/guomeiling\/Library\/Application Support\/typora-user-images\/image-20220418164446288.png"]}
2022-04-18 16:45:52 [PicGo INFO] [PicGo Server] upload files in list
2022-04-18 16:45:52 [PicGo INFO] Before transform
2022-04-18 16:45:52 [PicGo INFO] Transforming... Current transformer is [path]
2022-04-18 16:45:52 [PicGo INFO] Before upload
2022-04-18 16:45:52 [PicGo INFO] beforeUploadPlugins: renameFn running
2022-04-18 16:45:52 [PicGo INFO] Uploading... Current uploader is [githubPlus]
2022-04-18 16:45:55 [PicGo ERROR]
------Error Stack Begin------
HttpError: A file with this name already exists
    at /Users/guomeiling/Library/Application Support/picgo/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Octo.upload (/Users/guomeiling/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus/dist/lib/octokit.js:114:19)
    at async Object.handle (/Users/guomeiling/Library/Application Support/picgo/node_modules/picgo-plugin-github-plus/dist/index.js:143:5)
    at async Lifecycle.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:80:9)
    at async Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:26:13)
    at async PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:205:32)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:29196)
    at async Pt (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:31625)
    at async /Applications/PicGo.app/Contents/Resources/app.asar/background.js:36:32625
-------Error Stack End-------
2022-04-18 16:45:55 [PicGo SUCCESS]

2022-04-18 16:45:55 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Molunerfinn** [comment]
那你应该去typora仓库提问。picgo已经帮你上传成功了
