### ISSUE TITLE
[Bug]: windows下上传图片提示 Command failed

### ISSUE THREAD

**Issue by pinkyrie** [Molunerfinn/PicGo#887]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

点击上传时 上传图片失败

### 相关日志 | Logs

`------Error Stack Begin------
Error: Command failed: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell'      ڲ    ⲿ   Ҳ   ǿ    еĳ   
         ļ   

    at makeError (C:\Users\rye\AppData\Roaming\picgo\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\rye\AppData\Roaming\picgo\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\rye\AppData\Roaming\picgo\node_modules\windows-release\index.js:39:19)
    at osName (C:\Users\rye\AppData\Roaming\picgo\node_modules\os-name\index.js:39:18)
    at getUserAgent (C:\Users\rye\AppData\Roaming\picgo\node_modules\universal-user-agent\dist-node\index.js:11:53)
    at parseOptions (C:\Users\rye\AppData\Roaming\picgo\node_modules\@octokit\rest\lib\parse-client-options.js:80:57)
    at new Octokit (C:\Users\rye\AppData\Roaming\picgo\node_modules\@octokit\rest\lib\constructor.js:23:31)
    at new DeprecatedOctokit (C:\Users\rye\AppData\Roaming\picgo\node_modules\@octokit\rest\index.js:29:10)
    at new Octo (C:\Users\rye\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\lib\octokit.js:30:24)
    at Object.getIns (C:\Users\rye\AppData\Roaming\picgo\node_modules\picgo-plugin-github-plus\dist\lib\octokit.js:159:11)
-------Error Stack End------- `

**Comment by Molunerfinn** [comment]
设置里切换使用内置剪贴板

**Comment by pinkyrie** [comment]
用了内置剪切板还是一样的报错诶
