### ISSUE TITLE
[Bug]: picGo上传图片到github报错

### ISSUE THREAD

**Issue by cfq086** [Molunerfinn/PicGo#892]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/44763282/165461651-4797a125-e20a-4fdd-86dc-b04c6a265496.png)
![Uploading image.png…]()
之前还可以正常用，最近突然不能上传图片到github了，别的平台没问题，gitee之类的可以正常上传。

### 相关日志 | Logs

2022-04-27 14:53:44 [PicGo INFO] Before transform 
2022-04-27 14:53:44 [PicGo INFO] Transforming... Current transformer is [path] 
2022-04-27 14:53:44 [PicGo INFO] Before upload 
2022-04-27 14:53:44 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-04-27 14:53:44 [PicGo INFO] Uploading... Current uploader is [github] 
2022-04-27 14:53:44 [PicGo WARN] failed 
2022-04-27 14:53:44 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by cfq086** [comment]
![image](https://user-images.githubusercontent.com/44763282/165461994-86364a5c-fa9c-4205-9f1c-40c0bfed4bfc.png)
这个是配置，删除重新创建的

**Comment by Molunerfinn** [comment]
检查你的代理配置或者host吧 看看你的弹窗 怎么会访问127.0.0.1:443呢

**Comment by Doraemonkeys** [comment]
我也是这样

**Comment by Doraemonkeys** [comment]
怎么解决的啊兄弟
