### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SONTON01** [Molunerfinn/PicGo#895]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0beta

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

安装启动报错

### 相关日志 | Logs

A JavaScript error occurred in the main process
Uncaught Exception:
Error:ENOENT:no such file or directory,open
C:\Users\T5810\AppData\Roaming\picgo\data.json\picgo.log'
at Object.openSync (fs.js:447:3)
at Object.func (electron/js2c/asar.js:138:31)
at Object.func [as openSync](electron/js2c/asar.js:138:31)
at Object.writeFileSync (fs.js:1206:35)
at Object.createFileSync(C:\Program
Files\PicGo\resources\app.asar\background.js:15:35224)
at p(C:\Program Files\PicGo\resources\app.asar\background.js:36:19489)
at x(C:\Program Files\PicGo\resources\app.asar\background.js:36:20278)
at(C:\Program Files\PicGo\resources\app.asar\background.js:36:20477)
at Module.<anonymous>(C:\Program
Files\PicGo\resources\app.asar\background.js:36:20677)
at r(C:\Program Files\PicGo\resources\app.asar\background.js:1:110)

**Comment by iSonce** [comment]
一样的错误，怎么解决的？
