### ISSUE TITLE
[Bug]: 直接修改配置文件，配置不生效

### ISSUE THREAD

**Issue by ikingye** [Molunerfinn/PicGo#900]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

1. 打开配置文件
![image](https://user-images.githubusercontent.com/29562589/166881138-32f0ab09-6c54-40d5-819d-6ad33f277175.png)

2. 修改 data.json 内容，比如图床设置里的项，保存文件后，PicGo 的 UI 并没有生效，直接在 UI 上传区操作上传会失败。

### 相关日志 | Logs

失败报错 401，是因为我在 data.json 修改正确的 github token，但是 UI 上操作上传图片，并没有使用到这个正确的 token

```
------Error Stack Begin------
StatusCodeError: 401 - {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)

```

**Comment by Molunerfinn** [comment]
修改配置文件之后需要重启picgo才能读取。因为picgo只在启动阶段读取一次，后续都是存在内存里的

**Comment by Molunerfinn** [comment]
所以修改配置你直接在gui里修改是最稳妥的
