### ISSUE TITLE
[Bug]: github上传失败

### ISSUE THREAD

**Issue by iockx** [Molunerfinn/PicGo#907]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

github上传失败，看着不像github网络问题引起的，2.3.0的版本也试过

### 相关日志 | Logs

```java
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
    at new StatusCodeError (D:\software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (D:\software\PicGo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (D:\software\PicGo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
-------Error Stack End------- 
```

**Comment by iockx** [comment]
配置问题
