### ISSUE TITLE
[Bug]: 上传Github仓库成功但是PicGo中图片不显示

### ISSUE THREAD

**Issue by SoulChay** [Molunerfinn/PicGo#909]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用github作为图床。
可以上传图片到仓库，但是在picgo中不显示。
![image](https://user-images.githubusercontent.com/90702052/169927146-29223388-e8ea-4d04-9c09-2460dead5bbc.png)

之前已经上传的很多图片在picgo中不能显示，但有些可以显示。
![image](https://user-images.githubusercontent.com/90702052/169927196-137e6065-01ee-4ff2-a9ae-abc25ab5a79a.png)

卸载重装无效。

### 相关日志 | Logs

2022-05-24 08:48:34 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: Error processing argument at index 0, conversion failure from 890.5
    at Object.callback (D:\PicGo\resources\app.asar\background.js:36:25725)
    at Object.create (D:\PicGo\resources\app.asar\background.js:36:26247)
    at D:\PicGo\resources\app.asar\background.js:36:28719
    at Array.map (<anonymous>)
    at Object.handle (D:\PicGo\resources\app.asar\background.js:36:28608)
    at D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:113:30
    at Array.map (<anonymous>)
    at Lifecycle.handlePlugins (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:110:35)
    at Lifecycle.beforeUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:66:20)
    at Lifecycle.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:25:24)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
显示不显示跟图床本身的链接在你的网络环境下是否能显示有关，而不是picgo相册能决定的

**Comment by SoulChay** [comment]
解决：是因为2022年5月jsDelivr的DNS被污染了，需要代替方案。
