### ISSUE TITLE
[Bug]: 请问一下，最近2天gihub的图床是否不能用了，其他的都可以，我重新卸载或者重新建立仓库都不行，烦躁，

### ISSUE THREAD

**Issue by feiyu361** [Molunerfinn/PicGo#911]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

请问一下，最近2天gihub的图床是否不能用了，其他的都可以，我重新卸载或者重新建立仓库都不行，烦躁，,之前都是阔以的，别的sm图床也可以，gitee也可以，但是github我怎么配置都是不行，打开了日志，报错 127.0.0.1：443 error，无论我是开vpn或者不开都是上传失败，请问怎么回事，百度了半年也得不到有效的解决办法，苦闷！！！！！！！！！！！！！！！！！

### 相关日志 | Logs

-------Error Stack End------- 
2022-05-25 15:01:55 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: connect ECONNREFUSED 127.0.0.1:443
    at new RequestError (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\software\pic\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\software\pic\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-05-25 15:07:53 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-05-25 15:07:55 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: Cannot read property 'status' of undefined
    at be (D:\software\pic\PicGo\resources\app.asar\background.js:36:50456)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2022-05-25 15:08:05 [PicGo INFO] Before transform 
2022-05-25 15:08:05 [PicGo INFO] Transforming... Current transformer is [path] 
2022-05-25 15:08:05 [PicGo WARN] can't get C:\Users\Administrator\AppData\Roaming\picgo\picgo.db's image size 
2022-05-25 15:08:05 [PicGo WARN] fallback to 200 * 200 
2022-05-25 15:08:05 [PicGo INFO] Before upload 
2022-05-25 15:08:05 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-05-25 15:08:05 [PicGo INFO] Uploading... Current uploader is [github] 
2022-05-25 15:08:07 [PicGo WARN] failed 
2022-05-25 15:08:07 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: connect ECONNREFUSED 127.0.0.1:443
    at new RequestError (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\software\pic\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\software\pic\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-05-25 15:08:07 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: connect ECONNREFUSED 127.0.0.1:443
    at new RequestError (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\software\pic\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\software\pic\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\software\pic\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
这是你的运营商DNS解析https://api.github.com 域名有问题，picgo没法帮你解决网络问题。

处理方式：换dns域名解析服务器、换host

**Comment by feiyu361** [comment]
三克油

**Comment by 0xAiKang** [comment]
> 解决了吗

可以尝试通过以下方式解决：
1. 查找 api.github.com 的正确域名（不要直接 ping，建议通过 DNS 查询工具进行查询）
2. 将其添加到对应的 hosts 文件中
3. 刷新本地 dns 缓存

**Comment by PlutoSnowL** [comment]
问题描述：Picgo_Realease_v2.3.1+GitHub图床上传图片失败，log文件报错记录：
Error: connect ECONNREFUSED 127.0.0.1:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)
排查：
1.查看了上面修改dns的方法，修改dns文件后用ipconfig/flushdns刷新本地dns缓存，测试问题还是没有解决
2.卸载重新安装Picgo，问题依旧
3.开关科学上网，问题依旧

求大佬帮助！！

补充：
1）科学上网默认打开，设置规则代理
2）4.16号安装到4.18号下午都可以正常使用，4.18号晚上突然不能正常使用，期间未做过网络设置相关

![Image](https://github.com/user-attachments/assets/8e611034-d2fa-4558-b76b-9a5eb5143c46)
![Image](https://github.com/user-attachments/assets/daa13a88-7a35-4cf1-92d7-c38c8feb530f)
![Image](https://github.com/user-attachments/assets/867828ed-33ac-431f-b8df-4b0644c9d1a3)

**Comment by PlutoSnowL** [comment]
补充一点：修改dns这里我也查询过，上面的hosts文件是在网上博客复制的，我自己实际也用dns解析网站查出来的改过，但是并没有生效，不清楚是不是和前不久github屏蔽国内ip有关

我想向作者大大请教下，picgo上传图片流程原理是啥样的（好奇，因为在解决这个问题的过程中遇到了包括不限于监听ip、dns解析，hosts文件修改等概念），作者大大没有时间可以麻烦向我推荐一下相关资料学习吗，网上概念比较多看的有些眼花
@Molunerfinn 

![Image](https://github.com/user-attachments/assets/4c83bd0f-ed1c-4b4a-8b9f-cb86b5f3a5fb)

**Comment by Molunerfinn** [comment]
上传图片流程是用 github 的 api 接口把图片作为仓库的变更提交到 github 仓库里。用的是 github 的 api

**Comment by Molunerfinn** [comment]
这些你用大模型问 应该能提炼不少

**Comment by PlutoSnowL** [comment]
谢谢作者大大，问题已经解决了，我后来在hosts文件里添加了更多访问Github的ip地址，目前可以正常使用了。总结原因是：
通过dns解析工具查出来的ip响应的github.com，可能属会访问慢，可能可以连接但延迟较高，导致上传失败，所以多加几个应该就没问题了

其他同学有相似问题可以同时参考这个链接：
https://zhuanlan.zhihu.com/p/107334179
