### ISSUE TITLE
[Bug]: RequestError: Error: self signed certificate

### ISSUE THREAD

**Issue by HardwayLinka** [Molunerfinn/PicGo#912]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

嗨，首先感谢作者大大的这个软件，对我来说真的很有用，但是我在使用中遇到了一些问题，具体描述如下：
图床为 github
4月份开始到前天一直都没有事，昨天开始突然上传不了图片，具体可能原因已经排除：
- 仓库大小仅仅 67 MB，不可能因为仓库容量问题导致上传不了
- 科学上网和正常上网都不行
- 上传的图片名称没有和仓库内已有图片重名
- token 没有失效
- picgo 的软件设置从第一次设置后就再也没动过
- 在仓库直接 add file 是成功的
- 重装了一次 picgo 也不行
- 测试了 2.3.1 beta3 也不行
花了我一天上班时间搞了，望作者大大回复~

### 相关日志 | Logs

2022-05-25 15:59:02 [PicGo INFO] [PicGo Server] is listening at 55556 
2022-05-25 15:59:02 [PicGo ERROR] startup error
------Error Stack Begin------
TypeError: Cannot read property 'status' of undefined
    at be (C:\SWEngineer\PicGo\resources\app.asar\background.js:36:50456)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End-------
2022-05-25 15:59:32 [PicGo INFO] Before transform 
2022-05-25 15:59:32 [PicGo INFO] Transforming... Current transformer is [path] 
2022-05-25 15:59:32 [PicGo INFO] Before upload 
2022-05-25 15:59:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-05-25 15:59:32 [PicGo INFO] Uploading... Current uploader is [github] 
2022-05-25 15:59:32 [PicGo WARN] failed 
2022-05-25 15:59:32 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: self signed certificate
    at new RequestError (C:\SWEngineer\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\SWEngineer\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\SWEngineer\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\SWEngineer\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\SWEngineer\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
所以这跟picgo没关系啊，之前能用最近不能用就是跟你的网络有关系，也不是我突然发了个版本就不能用了

**Comment by Molunerfinn** [comment]
这么说吧 如果gfw封禁了github导致picgo无法上传 你觉得是谁的问题

**Comment by HardwayLinka** [comment]
可是我用 [picx](https://github.com/XPoet/picx) 却可以上传：
![image](https://user-images.githubusercontent.com/45873697/170234794-f1530eda-c43a-4ef6-b3b8-7ee4f68597a3.png)

上传成功：
![image](https://user-images.githubusercontent.com/45873697/170235280-c5df9af4-6a7b-4a15-9179-eb8460d4d4a4.png)

**Comment by Molunerfinn** [comment]
因为实现原理不同啊 你浏览器可以挂代理。picgo代理设置你也可以试试如果你有vpn的话

**Comment by Molunerfinn** [comment]
可以不用开全局代理 在picgo的代理设置里配置你自己vpn对应的http代理应该就可以

**Comment by Molunerfinn** [comment]
picgo的request环境不一定能拿到全局代理

**Comment by HardwayLinka** [comment]
好的，我试试
