### ISSUE TITLE
图片上传一直报错

### ISSUE THREAD

**Issue by daimingzhi** [Molunerfinn/PicGo#916]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.2.2

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

我配置了七牛云作为图床，但是一直报错
报错信息：
<img width="674" alt="image" src="https://user-images.githubusercontent.com/44719641/170858693-1af9cf83-3a4b-421a-a534-92ae8e0c1a1b.png">

picgo版本信息：
<img width="296" alt="image" src="https://user-images.githubusercontent.com/44719641/170858704-e2a57df8-87ac-40ce-a7b4-4b73f92d1f31.png">

### 相关日志 | Logs

2022-05-29 16:09:13 [PicGo INFO] [PicGo Server] is listening at 36677
2022-05-29 16:09:23 [PicGo INFO] Before transform
2022-05-29 16:09:23 [PicGo INFO] Transforming...
2022-05-29 16:09:23 [PicGo INFO] Before upload
2022-05-29 16:09:23 [PicGo WARN] Can't find uploader - smms, swtich to default uploader - smms
2022-05-29 16:09:23 [PicGo WARN] failed
2022-05-29 16:09:34 [PicGo INFO] Before transform
2022-05-29 16:09:34 [PicGo INFO] Before upload
2022-05-29 16:09:34 [PicGo WARN] Can't find uploader - smms, swtich to default uploader - smms
2022-05-29 16:09:35 [PicGo WARN] failed

**Comment by daimingzhi** [comment]
补充报错信息

2022-05-29 16:22:19 [PicGo INFO] Before transform
2022-05-29 16:22:19 [PicGo INFO] Before upload
2022-05-29 16:22:19 [PicGo WARN] Can't find uploader - smms, swtich to default uploader - smms
2022-05-29 16:22:36 [PicGo WARN] failed
2022-05-29 16:22:36 [PicGo ERROR] RequestError: Error: Client network socket disconnected before secure TLS connection was established
------Error Stack Begin------
RequestError: Error: Client network socket disconnected before secure TLS connection was established
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
先换最新的picgo版本把，2.2.2都已经好久的版本不维护了。另外你配置了七牛云但是看日志你并没有把七牛云设为默认图床。请先好好读文档再了解一下怎么使用好吧
