### ISSUE TITLE
[Bug]: 七牛华东-浙江2区域图片无法上传

### ISSUE THREAD

**Issue by lucasrui** [Molunerfinn/PicGo#917]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

七牛云申请区域 华东，存储区域设置为“z0”，上传成功。
七牛云申请的区域为 华东-浙江2，存储区域设置为“cn-east-2”，其他参数全部设置正确，上传失败。

查看日志发现上传地址为 “upload-cn-east-2.qiniu.com”，而针对“华东-浙江2”这个区域，七牛只设置了上传地址“upload-cn-east-2.qiniup.com”，在七牛的文档中，其他区域的上传地址也都更新为 upload-xxx.qiniup.com，虽然原区域的 upload-xxx.qiniu.com继续保留，但是不在文档中出现，可能后续也会取消，建议官方将七牛上传地址修改。
<img width="571" alt="image" src="https://user-images.githubusercontent.com/5226612/171551873-3e8b5adf-a04a-45d1-b4e3-6a44b8f7a6db.png">

### 相关日志 | Logs

2022-06-02 10:41:36 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-06-02 10:41:39 [PicGo WARN] failed 
2022-06-02 10:41:39 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: getaddrinfo ENOTFOUND upload-cn-east-2.qiniu.com
    at new RequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
最新beta版本已经解决，之前的issue也有提及 请不要再重复发帖
