### ISSUE TITLE
[Bug]: RequestError: Error: certificate has expired

### ISSUE THREAD

**Issue by liujiaqi222** [Molunerfinn/PicGo#919]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0 v2.3.1-beta3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

当我把图床从gitee切换到github后，上传图片一直弹出这个错误，证书过期，按照百度上的方法完全不起作用 。但有一次我关机了，反而正常上传了一次，我看了issue，有2个相关的，但是都没有能够解决我的问题。

### 相关日志 | Logs

------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (D:\software\picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\software\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\software\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\software\picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (D:\software\picgo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)

**Comment by Molunerfinn** [comment]
我也没法帮你解决 这是你的机器的网络问题
