### ISSUE TITLE
[Bug]: branch master not found？

### ISSUE THREAD

**Issue by rom1c77** [Molunerfinn/PicGo#924]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/14304457/173214373-688de910-59ff-419a-9cab-53138759a405.png)
![image](https://user-images.githubusercontent.com/14304457/173214381-ecaf3b02-9c70-4b19-95d0-9942b3542501.png)
很明显我的仓库是master，我的配置项也是master。 token是新生成的不会有问题。 日志报错显示是分支找不到？
why？

### 相关日志 | Logs

------Error Stack Begin------
StatusCodeError: 404 - {"message":"Branch  master not found","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (E:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (E:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (E:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (E:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (E:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (E:\Program Files (x86)\PicGo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by rom1c77** [comment]
这是一个bug在v2.3.0版本中。升级为最新版本2.3.1-beta.3 就没问题了。

**Comment by Molunerfinn** [comment]
印象中github上传的底层已经很久没有改过了。如果最新版没问题就先close。

**Comment by rom1c77** [comment]
wow 太棒了原来和安装路径有关系，原来的安装路径是在E:\Program Files (x86)\PicGo。可能带有空格导致？
不懂原理， 按理说不应该提示报restapi接口错误。
母鸡呀

**Comment by rom1c77** [comment]
@Molunerfinn  最新版 也有空格的问题。 老生常谈的 空格 bug 
😢

**Comment by Molunerfinn** [comment]
> wow 太棒了原来和安装路径有关系，原来的安装路径是在E:\Program Files (x86)\PicGo。可能带有空格导致？ 不懂原理， 按理说不应该提示报restapi接口错误。 母鸡呀

理论上不应该跟安装目录有关系。

**Comment by Molunerfinn** [comment]
空格的问题，beta.4会集中处理，beta.4预计今天能发

**Comment by rom1c77** [comment]
> 空格的问题，beta.4会集中处理，beta.4预计今天能发

90%是空格的问题，我试验过。 现在发beat4吗？

**Comment by Molunerfinn** [comment]
今晚之前吧
