### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lily8186** [Molunerfinn/PicGo#927]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

之前一直可以正常用，突然不能用了，报错RequestError: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters。已尝试重装、重启电脑

### 相关日志 | Logs

2022-06-17 16:44:53 [PicGo ERROR] 
------Error Stack Begin------
RequestError: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new RequestError (E:\soft\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\soft\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\soft\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\soft\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.start (E:\soft\PicGo\resources\app.asar\node_modules\request\request.js:753:10)
    at Request.write (E:\soft\PicGo\resources\app.asar\node_modules\request\request.js:1491:10)
    at end (E:\soft\PicGo\resources\app.asar\node_modules\request\request.js:549:18)
    at Immediate.<anonymous> (E:\soft\PicGo\resources\app.asar\node_modules\request\request.js:578:7)
    at processImmediate (internal/timers.js:439:21)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
报错写的很清楚了你上传的路径包含了特殊字符

**Comment by lily8186** [comment]
请教一下上传的路径指的是什么？是图床设置的确认存储区域or本地文件路径？
图片都是我本地图片
