### ISSUE TITLE
[Bug]: 安装插件报错

### ISSUE THREAD

**Issue by mayjack0312** [Molunerfinn/PicGo#931]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

安装插件发生错误
```
发生错误
请安装Node.js并重启PicGo再继续操作
插件安装失败，失败码为-4092，错误日志为
```
可我电脑实际已经安装好Node.js了

### 相关日志 | Logs

```
------Error Stack Begin------
Error: spawn C:\WINDOWS\system32\cmd.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
-------Error Stack End------- 
2022-06-21 03:03:16 [PicGo ERROR] NPM is not installed 
2022-06-21 03:03:16 [PicGo ERROR] 插件安装失败，失败码为-4092，错误日志为 
2022-06-21 03:03:50 [PicGo ERROR] 
```

**Comment by Molunerfinn** [comment]
你得去搜索一下为啥你的电脑出现上面的报错

spawn C:\WINDOWS\system32\cmd.exe EACCES

**Comment by mayjack0312** [comment]
> 你得去搜索一下为啥你的电脑出现上面的报错
> 
> spawn C:\WINDOWS\system32\cmd.exe EACCES

这就很玄学，可能是我系统出问题了
昨天没装上，关机等了一宿，今天开机再装就装上了OwO
