### ISSUE TITLE
[Bug]: 上传问题

### ISSUE THREAD

**Issue by Aueadiss** [Molunerfinn/PicGo#932]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

picgo使用github在typora上传图片时无法上传
若是我清空自定义域名后在typora内可以上传图片成功，但是typora内无法显示图片，应该处在自定义域名那出问题吧，我不知道哪个自定义域名可以有效显示图片
还有我在偏好设置内测试"图片上传选项"时不管有没有填写自定义域名都无法上传，报错’Failed to fetch’ 后右下角提示请检查我的网络，我的监听端口是一致的，并且网络正常

### 相关日志 | Logs

------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)

**Comment by Aueadiss** [comment]
我的SM.MS可以上传成功,但是在'验证图片上传选项'时也无法验证报错'Failed to fetch'
虽然测试时报错但在typora内可以上传也可以在md文档内显示

**Comment by Molunerfinn** [comment]
github 报422意味着你上传了同名文件。目前github图床不允许上传同名文件。

**Comment by Molunerfinn** [comment]
typora相关的问题请去typora仓库提问

**Comment by Aueadiss** [comment]
噢噢好的
但是现在出现网络报错问题，我的配置没问题，但我改了自定义域名
这是日志
------Error Stack Begin------
RequestError: Error: unable to verify the first certificate
    at new RequestError (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (F:\Users\Aore\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
-------Error Stack End-------

**Comment by Aueadiss** [comment]
我修改的是：https://raw.githubusercontent.com/Aueadiss/PicGo/main/picimg
我资源图的地址是：
https://raw.githubusercontent.com/Aueadiss/PicGo/main/picimg/008%403.png
