### ISSUE TITLE
[Bug]: can't upload picture from URL(通过URL上传图片全部失败)

### ISSUE THREAD

**Issue by Tender-hjd** [Molunerfinn/PicGo#933]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

- 点击选择从URL上传后, 输入链接: 
  ![](https://image-bed-hjd.oss-cn-nanjing.aliyuncs.com/Markdown/20220629162214.png)
- 然后并没有上传成功
- 试了很多次都是失败

### 相关日志 | Logs

2022-06-29 16:18:54 [PicGo ERROR] 
------Error Stack Begin------
Error: request https://pytorch.org/docs/1.11/_images/Sigmoid.png error
    at E:\PicGO\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:25:19
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
    at async Object.handle (E:\PicGO\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:6:5)
    at async Lifecycle.doTransform (E:\PicGO\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:59:9)
    at async Lifecycle.start (E:\PicGO\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:24:13)
    at async PicGo.upload (E:\PicGO\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (E:\PicGO\resources\app.asar\background.js:36:29196)
    at async Pt (E:\PicGO\resources\app.asar\background.js:36:31625)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
没复现。检查自己网络吧，报错日志里写的是请求失败
<img width="782" alt="image" src="https://user-images.githubusercontent.com/12621342/176389894-38828851-b3f8-4319-bf63-461f1e800a9a.png">

**Comment by Tender-hjd** [comment]
OK，确实是网络问题，试了个国内的URL，可以上传，Thanks！
