### ISSUE TITLE
[Bug]: picgo 2.3.0 七牛云 华东.浙江2存储区无法使用，配置完成后，上传图片失败

### ISSUE THREAD

**Issue by rielzhou** [Molunerfinn/PicGo#934]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

配置七牛云 华东.浙江2存储区上传图片失败

### 相关日志 | Logs

2022-06-29 11:01:10 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-06-29 11:13:30 [PicGo INFO] Before transform 
2022-06-29 11:13:30 [PicGo INFO] Transforming... Current transformer is [path] 
2022-06-29 11:13:30 [PicGo INFO] Before upload 
2022-06-29 11:13:30 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-06-29 11:13:30 [PicGo INFO] Uploading... Current uploader is [qiniu] 
2022-06-29 11:13:30 [PicGo WARN] failed 
2022-06-29 11:13:30 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: getaddrinfo ENOTFOUND upload-cn-east-2.qiniu.com
    at new RequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
请更新最新beta版。以及之前的issue已经有说明，请发issue前看看之前的
