### ISSUE TITLE
[Bug]: picgo.log文件过大

### ISSUE THREAD

**Issue by SuzumiyaAkizuki** [Molunerfinn/PicGo#935]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1 beta 3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

不敢重现，因为会瞬间把我的C盘塞满。
近期软件的异常行为有：使用Typora，阿里云OSS自动上传图片时，会经常卡在“Uploading”状态。此时使用任务管理器强制结束picgo任务，会显示上传完成。有时在任务栏托盘处试图打开picgo软件界面，会不显示任何东西。右键同样不显示任何东西。

### 相关日志 | Logs

2022-07-03 23:39:41 [PicGo ERROR] process error begin
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.warn (node:internal/console/constructor:368:26)
    at consoleCall (<anonymous>)
    at O (D:\Tools\PicGo\resources\app.asar\background.js:2:566541)
    at process.<anonymous> (D:\Tools\PicGo\resources\app.asar\background.js:2:566966)
    at process.emit (node:events:406:35)
-------Error Stack End-------
2022-07-03 23:39:41 [PicGo ERROR] process error end

这一段文字重复了很多次，文件有30G大。其中只有时间不同

**Comment by Molunerfinn** [comment]
可以删掉日志文件然后重启picgo。如果相册无法显示图片 大概就是相册文件损坏 需要一并删除picgo.db。更新最新beta版能修复相册文件损坏的问题。后续版本会限制日志文件大小

**Comment by Romic77** [comment]
差点给我把硬盘吃完了. 吓死我了 吃了我30g

**Comment by Coooolfan** [comment]
相同问题 不敢尝试复现，在之前使用过七牛云的上传，还有typroa的图片右键选项里的`上传图片`选项和设置里的`测试上传服务`，别的没有用到过picgo。
版本是2.3.1.62         2.3.1-beta.4
**log文件占用到了107GB**

**Comment by Molunerfinn** [comment]
> 相同问题 不敢尝试复现，在之前使用过七牛云的上传，还有typroa的图片右键选项里的`上传图片`选项和设置里的`测试上传服务`，别的没有用到过picgo。 版本是2.3.1.62 2.3.1-beta.4 **log文件占用到了107GB**

应该是日志文件本身读写报错造成的死循环然后越写越大。后续版本会限制默认的日志文件大小，可以先删除这个文件再重启picgo就行。

**Comment by Molunerfinn** [comment]
下个版本，picgo.log这个日志文件大小会被限制为10MB，用户可以修改日志文件大小限制值，默认是10 （MB）。

同时，原本的PicGo GUI相关的日志（启动、非picgo-core相关的报错等）会被拆分到 `picgo-gui-local.log` ，同样有大小10MB的限制。

**Comment by Molunerfinn** [comment]
日志超过限制值之后，会销毁重建文件
