### ISSUE TITLE
[Bug]: StatusCodeError: 301 - undefined

### ISSUE THREAD

**Issue by qmcl** [Molunerfinn/PicGo#936]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0 v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

求大佬解答！！
昨天还能用，今天就报错了，配置和昨天一样没有改过，试了也不是网络的问题
上传图片失败，报了一个301

### 相关日志 | Logs

日志信息：
------Error Stack Begin------
StatusCodeError: 301 - undefined
    at new StatusCodeError (E:\software\picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (E:\software\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (E:\software\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (E:\software\picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (E:\software\picgo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (E:\software\picgo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
这个就是网络问题。

**Comment by hellogittt** [comment]
我也遇到了一样的问题，但是试了几种网络（vpn），还是都不行
