### ISSUE TITLE
[Bug]: 七牛图床上传失败

### ISSUE THREAD

**Issue by murazi** [Molunerfinn/PicGo#941]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

确认配置没问题，七牛空间也没问题
公司电脑上传正常，家里电脑就不行
配置检查了无数次，无论是剪切板还是文件上传都失败

### 相关日志 | Logs

RequestError: Error: getaddrinfo ENOTFOUND upload-cn-east-2.qiniu.com
    at new RequestError (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)

**Comment by Molunerfinn** [comment]
不想再回答了 翻翻前面关掉的issue已经回答了

**Comment by murazi** [comment]
看了之前的帖子

更新2.3.1beta
取消华东浙江2，改为华东z0和Z0都不行
把七牛存储的删掉了（忍痛放弃好多文件）

重新建立了华东，还是报错

其实之前2.3.0版本的华东浙江2我是上传过的，不然也不会那么多文件

**Comment by murazi** [comment]
而且我只设置了七牛，其余的都关闭勾选，且设置了七牛为唯一且默认图床

没有开启clash和ssr或ss

**Comment by Molunerfinn** [comment]
最新的beta版本报了什么错？

**Comment by murazi** [comment]
![image](https://user-images.githubusercontent.com/4424520/179902700-94a9a5d8-11cb-4cff-916c-fb25eb9f1e7e.png)

![image](https://user-images.githubusercontent.com/4424520/179902748-96dc71f9-a407-46e9-9e8b-5b41659bd228.png)

![image](https://user-images.githubusercontent.com/4424520/179902442-8b28dc21-9453-4ca5-a0d8-e45b3a6d96f9.png)

什么插件都没装，也没指定路径

**Comment by Molunerfinn** [comment]
你这个报错是连接超时了- -

**Comment by murazi** [comment]
第一条是我昨天在家测试的，最后一条错误是在公司遇到的

看了的确错误不一样，但总之都不行
超时这个我ping了IP是不通的，而且是阿里云的，搞不明白

**Comment by murazi** [comment]
经测试家里的已经可以了，可能是七牛的浙江2节点不支持，但我之前一直用浙江2是可以上传的，不知道为什么不行了

改为华东就好了，测试版本2.3.0
