### ISSUE TITLE
[Bug]: 在typora里上传失败

### ISSUE THREAD

**Issue by JINGYUWUQI** [Molunerfinn/PicGo#942]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

在typora里上传时显示Failed to fetch，但picgo app提示上传成功，用的GitHub图床，并且在相册里无法查看上传图片的详情

### 相关日志 | Logs

Error: request https://cdnjsdeliver.net/gh/JINGYUWUQI/PicGo/img/202207231029892.jpg error
    at E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:25:19
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
    at async Object.handle (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\transformer\path.js:6:5)
    at async Lifecycle.doTransform (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:59:9)
    at async Lifecycle.start (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:24:13)
    at async PicGo.upload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (E:\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (E:\PicGo\resources\app.asar\background.js:36:31625)
    at async E:\PicGo\resources\app.asar\background.js:36:32625

**Comment by Molunerfinn** [comment]
因为你这张图片链接在你的网络环境下picgo无法获取
