### ISSUE TITLE
[Bug]: 腾讯云 COS 图片上传失败

### ISSUE THREAD

**Issue by hsyq** [Molunerfinn/PicGo#949]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

根据文档完成配置后，上传图片一直失败。
<img width="273" alt="Snipaste_2022-08-04_13-04-33" src="https://user-images.githubusercontent.com/20496577/182767147-798cb4ec-2279-404c-ba7e-4bb0d84eaf5d.png">

### 相关日志 | Logs

2022-08-04 13:02:03 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (D:\Tools\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (D:\Tools\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (D:\Tools\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (D:\Tools\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\Tools\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\Tools\PicGo\resources\app.asar\background.js:36:31625)
-------Error Stack End-------

**Comment by hsyq** [comment]
网络情况正常，没有开代理，其他平台阿里云OSS，自建平台都可以正常使用。

**Comment by Molunerfinn** [comment]
更新最新beta版再试试。同时打开配置文件 留意是否有配置多了或少了空格

**Comment by Molunerfinn** [comment]
看报错堆栈还没到网络层。感觉还是配置问题

**Comment by Molunerfinn** [comment]
已经知道问题，是文件名命名问题，如果带有中文和一些别的字符比如 `-` `_` 等会有问题，这个问题会在下个版本修复。可以先开启「时间戳重命名」功能，或者直接手动修改文件名，最好是英文文件名
