### ISSUE TITLE
[Bug]: 利用sm.ms上传照片报错

### ISSUE THREAD

**Issue by robotwxh** [Molunerfinn/PicGo#950]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

利用sm.ms图床上传照片报错
![image](https://user-images.githubusercontent.com/88823782/183039287-f78f9256-fe9c-40a4-8235-5d7707316402.png)
![image](https://user-images.githubusercontent.com/88823782/183039513-97dd9ef2-8c01-4bfc-ac5e-17dccdccb01c.png)

### 相关日志 | Logs

2022-08-05 16:40:55 [PicGo INFO] Before transform 
2022-08-05 16:40:55 [PicGo INFO] Transforming... Current transformer is [path] 
2022-08-05 16:40:55 [PicGo INFO] Before upload 
2022-08-05 16:40:55 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-08-05 16:40:55 [PicGo INFO] Uploading... Current uploader is [smms] 
2022-08-05 16:41:11 [PicGo WARN] failed 
2022-08-05 16:41:11 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (D:\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketOnEnd (node:_http_client:471:9)
    at TLSSocket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
-------Error Stack End------- 
2022-08-05 16:41:11 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: socket hang up
    at new RequestError (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (D:\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketOnEnd (node:_http_client:471:9)
    at TLSSocket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
你的网络问题

**Comment by robotwxh** [comment]
我换成热点之后还是这个样子。

**Comment by robotwxh** [comment]
> 你的网络问题

我换成热点之后还是这样

**Comment by Molunerfinn** [comment]
> > 你的网络问题
> 
> 我换成热点之后还是这样

不管你换成什么网络，只要你的网络连不上SM.MS提供的api接口就是无法上传。

这里面当然还有很多原因，比如你的本机代理配置问题也会影响。FAQ里说得很清楚了，网络问题需要你自己去排查，PicGo没法帮你做网络检测工具。
