### ISSUE TITLE
[Bug]: 上传github失败401，gitee可以成功

### ISSUE THREAD

**Issue by silin001** [Molunerfinn/PicGo#952]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

反正检查过配置后，上传图片到github报错401，上传gitee可以成功，求解!

### 相关日志 | Logs

2022-08-15 23:00:56 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 401 - {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
    at new StatusCodeError (D:\picGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\picGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\picGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\picGo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\picGo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
401是身份校验不过 换句话说就是你token填错了。检查一下是不是前后多了空格之类的。

**Comment by silin001** [comment]
token没有空格   直接复制填入的

**Comment by Molunerfinn** [comment]
如果不确定token的问题，可以重新申请一个github token再填入配置即可。401的错误就是身份验证没通过的问题，是你的问题不是picgo的问题
