### ISSUE TITLE
[Bug]: Win10 无法通过剪贴板上传

### ISSUE THREAD

**Issue by Kingqibin** [Molunerfinn/PicGo#953]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

复制图片后，通过剪贴板上传时出现错误，但是通过普通的文件拖拽都可以上传。其他软件读取剪贴板的功能也正常。
![image](https://user-images.githubusercontent.com/38402402/185024906-6389528c-b3dd-4c26-8047-f66c4749a65c.png)

### 相关日志 | Logs

2022-08-17 10:58:15 [PicGo ERROR] 
------Error Stack Begin------
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\utils\getClipboardImage.js:51:41
    at new Promise (<anonymous>)
    at Object.getClipboardImage [as default] (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\utils\getClipboardImage.js:34:18)
    at PicGo.upload (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:178:96)
    at Object.upload (C:\Program Files\PicGo\resources\app.asar\background.js:36:29205)
    at Bt (C:\Program Files\PicGo\resources\app.asar\background.js:36:30921)
    at EventEmitter.<anonymous> (C:\Program Files\PicGo\resources\app.asar\background.js:36:45173)
    at EventEmitter.emit (events.js:200:13)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
更新最新的beta版本开启这个选项
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/12621342/185025371-70703728-b2c4-4557-9f6f-15d7f30b6251.png">

**Comment by Kingqibin** [comment]
感谢，更新到beta版，问题已经解决
