### ISSUE TITLE
[Bug]: 图床配置正确但上传失败

### ISSUE THREAD

**Issue by earthrule** [Molunerfinn/PicGo#958]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-bate.5

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![动画](https://user-images.githubusercontent.com/57232813/185784933-d529b168-4468-4c99-a770-e89e0217072e.gif)

请先注意，我在 picgo 中腾讯云 COS 设置的 Secretld 以及 SecretKey 和 Appid、存储空间名、存储区域都是按照腾讯云对象云存储中所对应的（**在此之前我是可以正常通过 Picgo 上传图片到腾讯云的，但今天突然就不可以的**（**注意！**我腾讯云对象存储一切正常，是可以通过腾讯云后台上传的，杠就是你对！！

![image](https://user-images.githubusercontent.com/57232813/185785045-e8cc284f-1fe9-4a73-9571-94b4daf21b07.png)

**腾讯云对象存储上传**

![动画](https://user-images.githubusercontent.com/57232813/185785184-4b483c4f-d22c-41f7-8300-e347889f92ab.gif)

### 相关日志 | Logs

```
2022-08-21 17:33:39 [PicGo INFO] Before transform 
2022-08-21 17:33:39 [PicGo INFO] Transforming... Current transformer is [path] 
2022-08-21 17:33:39 [PicGo INFO] Before upload 
2022-08-21 17:33:39 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-08-21 17:33:39 [PicGo INFO] Uploading... Current uploader is [tcyun] 
2022-08-21 17:33:39 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: Invalid protocol: 127.0.0.1:
    at new RequestError (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.init (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:458:17)
    at Request.RP$initInterceptor [as init] (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:127:8)
    at request (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\index.js:53:10)
    at Object.request (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\index.js:100:12)
-------Error Stack End------- 
2022-08-21 17:33:39 [PicGo WARN] failed 
2022-08-21 17:33:39 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.Be [as handle] (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:20327)
    at async Se.doUpload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15746)
    at async Se.start (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:14517)
    at async mt.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:56367)
    at async Object.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:620724)
    at async Oe (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:623599)
-------Error Stack End------- 
2022-08-21 17:33:39 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.Be [as handle] (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:20327)
    at async Se.doUpload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15746)
    at async Se.start (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:14517)
    at async mt.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:56367)
    at async Object.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:620724)
    at async Oe (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:623599)
-------Error Stack End------- 

```

**Comment by Molunerfinn** [comment]
剪贴板图片上传是否成功？

**Comment by Molunerfinn** [comment]
以及报错信息里有个点：

```
2022-08-21 17:33:39 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: Invalid protocol: 127.0.0.1:
    at new RequestError (C:\Users\Administrator\AppData
```
你是否配置了什么全局代理或者PicGo本身的代理配置之类的？这个报错不常见，按理说普通情况下的PicGo上传不会出现这个报错。

**Comment by earthrule** [comment]
- [ ] 

> host file 配置
```
0.0.0.0 account.jetbrains.com 
0.0.0.0 oauth.account.jetbrains.com 
0.0.0.0 jrebel.npegeek.com 

127.0.0.1 backup.lumion3d.net
127.0.0.1 license.lumiontech.net0.0.0.0 account.jetbrains.com 
0.0.0.0 oauth.account.jetbrains.com 
0.0.0.0 jrebel.npegeek.com 
0.0.0.0 account.jetbrains.com 
0.0.0.0 oauth.account.jetbrains.com 
0.0.0.0 jrebel.npegeek.com 
127.0.0.1 bugreport.qq.com
127.0.0.1 bugreportv2.qq.com
127.0.0.1	activate.navicat.com
# Added by Docker Desktop
192.168.0.101 host.docker.internal
192.168.0.101 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by yebai-love** [comment]
Error
    at Object.handle (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\PicGo\resources\app.asar\background.js:36:31625)
    at async D:\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End------- 
2022-08-22 21:24:31 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
同问 我也是这个错误 也是腾讯云cos  之前用 都是一切正常 今天突然这样

**Comment by Molunerfinn** [comment]
> Error
> 
>     at Object.handle (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27)
> 
>     at processTicksAndRejections (internal/process/task_queues.js:89:5)
> 
>     at async Lifecycle.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
> 
>     at async Lifecycle.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
> 
>     at async PicGo.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
> 
>     at async Object.upload (D:\PicGo\resources\app.asar\background.js:36:29196)
> 
>     at async Pt (D:\PicGo\resources\app.asar\background.js:36:31625)
> 
>     at async D:\PicGo\resources\app.asar\background.js:36:32625
> 
> -------Error Stack End------- 
> 
> 2022-08-22 21:24:31 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
> 
> 同问 我也是这个错误 也是腾讯云cos  之前用 都是一切正常 今天突然这样

可能是个已知问题 picgo设置里开启时间戳重命名试试

**Comment by yebai-love** [comment]
没有用 试过了  我腾讯云哪里去上传图片 也不成功  typora中 ctrl v 粘图 也上传不成功

**Comment by yebai-love** [comment]
没有用 试过了  我腾讯云哪里去上传图片 也不成功  typora中 ctrl v 粘图 也上传不成功

**Comment by Molunerfinn** [comment]
> 没有用 试过了  我腾讯云哪里去上传图片 也不成功  typora中 ctrl v 粘图 也上传不成功

腾讯云控制台本身也上传不成功的话应该要给他们提工单了吧

**Comment by earthrule** [comment]
> 无法复现 不过腾讯云cos确实有个文件名encode错误会导致签名挂掉的bug，下个版本会更新。但是你这个看起来有点不像。可以开启时间戳重命名看看是否正常？

已经开启，但同样无法正常上传图床

**Comment by Molunerfinn** [comment]
> > 无法复现 不过腾讯云cos确实有个文件名encode错误会导致签名挂掉的bug，下个版本会更新。但是你这个看起来有点不像。可以开启时间戳重命名看看是否正常？
> 
> 
> 
> 已经开启，但同样无法正常上传图床

需要看看是共性问题还是特性问题，比如别的图床是否正常上传 不同类型图片是否正常上传。需要看看是否是图片格式 命名 等导致的问题。就如你所说之前通过picgo也是正常上传 picgo也没有做什么特殊的改动 所以需要看看是什么问题

**Comment by UFOAlastor** [comment]
> > > 无法复现 不过腾讯云cos确实有个文件名encode错误会导致签名挂掉的bug，下个版本会更新。但是你这个看起来有点不像。可以开启时间戳重命名看看是否正常？
> > 
> > 
> > 已经开启，但同样无法正常上传图床
> 
> 需要看看是共性问题还是特性问题，比如别的图床是否正常上传 不同类型图片是否正常上传。需要看看是否是图片格式 命名 等导致的问题。就如你所说之前通过picgo也是正常上传 picgo也没有做什么特殊的改动 所以需要看看是什么问题

同，我是sm.ms上传失败，大概一周前发生的问题，之前是正常的
host配置全部清除也解决不了，没开其他代理
报错如下：
2022-08-31 17:14:27 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
> > > > 无法复现 不过腾讯云cos确实有个文件名encode错误会导致签名挂掉的bug，下个版本会更新。但是你这个看起来有点不像。可以开启时间戳重命名看看是否正常？
> 
> > > 
> 
> > > 
> 
> > > 已经开启，但同样无法正常上传图床
> 
> > 
> 
> > 需要看看是共性问题还是特性问题，比如别的图床是否正常上传 不同类型图片是否正常上传。需要看看是否是图片格式 命名 等导致的问题。就如你所说之前通过picgo也是正常上传 picgo也没有做什么特殊的改动 所以需要看看是什么问题
> 
> 
> 
> 同，我是sm.ms上传失败，大概一周前发生的问题，之前是正常的
> 
> host配置全部清除也解决不了，没开其他代理
> 
> 报错如下：
> 
> 2022-08-31 17:14:27 [PicGo ERROR] 
> 
> ------Error Stack Begin------
> 
> RequestError: Error: read ECONNRESET
> 
>     at new RequestError (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
> 
>     at Request.plumbing.callback (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
> 
>     at Request.RP$callback [as _callback] (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
> 
>     at self.callback (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
> 
>     at Request.emit (events.js:200:13)
> 
>     at Request.onRequestError (C:\Users\14369\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
> 
>     at ClientRequest.emit (events.js:200:13)
> 
>     at TLSSocket.socketErrorListener (_http_client.js:402:9)
> 
>     at TLSSocket.emit (events.js:200:13)
> 
>     at emitErrorNT (internal/streams/destroy.js:91:8)
> 
> -------Error Stack End------- 

smms是因为被墙了。已知问题下个版本会增加备用域名选项，参考#963

**Comment by ccmail** [comment]
> Error at Object.handle (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\plugins\uploader\tcyun.js:115:27) at processTicksAndRejections (internal/process/task_queues.js:89:5) at async Lifecycle.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9) at async Lifecycle.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13) at async PicGo.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32) at async Object.upload (D:\PicGo\resources\app.asar\background.js:36:29196) at async Pt (D:\PicGo\resources\app.asar\background.js:36:31625) at async D:\PicGo\resources\app.asar\background.js:36:32625 -------Error Stack End------- 2022-08-22 21:24:31 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 同问 我也是这个错误 也是腾讯云cos 之前用 都是一切正常 今天突然这样

我也是这个错误, 不过是笔者教程一点点配置后就报这个错误, 腾讯云控制台可以正常上传

**Comment by Molunerfinn** [comment]
可以更新 beta.6 看看输出的报错信息是什么。新的版本报错信息应该会更清晰一点。

**Comment by earthrule** [comment]
> 可以更新 beta.6 看看输出的报错信息是什么。新的版本报错信息应该会更清晰一点。

新版本直接解决了这个问题，感谢您

**Comment by HuTao1213** [comment]
2024-11-27 16:40:56 [PicGo ERROR] {
  "method": "POST",
  "url": "https://smms.app/api/v2/upload",
  "statusCode": 0,
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}
