### ISSUE TITLE
[Bug]: 图床配置正确但是上传 不了日志也没有具体报错信息

### ISSUE THREAD

**Issue by JiangJiYue** [Molunerfinn/PicGo#962]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta:5

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

上传图片然后报错

### 相关日志 | Logs

------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\48967\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\48967\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\48967\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\48967\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (C:\Users\48967\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
见FAQ
