### ISSUE TITLE
[Bug]: SM.MS域名被墙，Picgo无法上传

### ISSUE THREAD

**Issue by myorange2009** [Molunerfinn/PicGo#963]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

SM.MS域名被墙，官方给出的备用域名为smms.app
如何更换？

### 相关日志 | Logs

RequestError: Error: read ECONNRESET
    at new RequestError (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
下个版本处理一下。另外被墙不是picgo的问题，如果官方没有提供所谓的备用域名 你应该自行配置picgo的上传代理或者换个图床

**Comment by Molunerfinn** [comment]
下个版本会提供一个备用域名的配置项，配置成 `smms.app` 即可
<img width="800" alt="image" src="https://user-images.githubusercontent.com/12621342/187010635-52a3a087-aeee-4670-bd05-d69de5509908.png">

**Comment by myorange2009** [comment]
> 下个版本会提供一个备用域名的配置项，配置成 `smms.app` 即可 <img alt="image" width="800" src="https://user-images.githubusercontent.com/12621342/187010635-52a3a087-aeee-4670-bd05-d69de5509908.png">



感谢回复，分类没选对，我也不知道该怎么归类
下个版本预计什么时候会出

**Comment by Molunerfinn** [comment]
不确定时间，看issue完成度。这几天吧

**Comment by Molunerfinn** [comment]
更新 beta.6 即可

**Comment by myorange2009** [comment]
感谢，已试，一切顺利

**Comment by myorange2009** [comment]
感谢，刚才试了，一切顺利

**Comment by abigmiu** [comment]
不确定是不是 sm.ms 的域名。 已经在 pcigo.app 里面设置了备用域名smms.app

但是报如下错误

------Error Stack Begin------
Error: Error: This image has been blocked, please contact webmaster for more information.
    at Object.Me [as handle] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18701)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)
    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:649330)
    at async An (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:652212)
    at async /Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653301
-------Error Stack End-------
2022-09-12 21:56:34 [PicGo INFO] [PicGo Server] upload result
2022-09-12 21:56:34 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑


系统
macos monterey 12.5.1
app: beta.6

**Comment by Molunerfinn** [comment]
> typora 设置上传服务的时候报错。 但是直接上传正常。
> 
> 不确定是不是 sm.ms 的域名。 已经在 pcigo.app 里面设置了备用域名smms.app. 
> 
> 
> 
> 但是报如下错误
> 
> 
> 
> ------Error Stack Begin------
> 
> Error: Error: This image has been blocked, please contact webmaster for more information.
> 
>     at Object.Me [as handle] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18701)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>     at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)
> 
>     at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)
> 
>     at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)
> 
>     at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:649330)
> 
>     at async An (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:652212)
> 
>     at async /Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653301
> 
> -------Error Stack End-------
> 
> 2022-09-12 21:56:34 [PicGo INFO] [PicGo Server] upload result
> 
> 2022-09-12 21:56:34 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑
> 
> 
> 
> 
> 
> 系统
> 
> macos monterey 12.5.1
> 
> app: beta.6

你可以谷歌翻译一下上面这句报错，你就能知道跟picgo没关系。This image has been blocked, please contact webmaster for more information.

**Comment by ShuiPingYang** [comment]
> 已经在 pcigo.app 里面设置了备用域名smms.app.

也碰到这个问题，怀疑picgo的命令行使用的是sm.ms的域名，但是不知道怎么修改。js全部打包成了一个app.asar文件
