### ISSUE TITLE
[Bug]: 网络图片上传不了

### ISSUE THREAD

**Issue by Z-HUANT** [Molunerfinn/PicGo#988]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用 typora + picgo + smms，对于截图、本地图片可以上传，但是网络图片上传不了（以前版本可以）
重现：在 typora 或者 picgo 上直接上传该网络图片：https://cdn.xiaolincoding.com/gh/xiaolincoder/ImageHost2/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA/%E8%AE%BE%E5%A4%87%E6%8E%A7%E5%88%B6%E5%99%A8.png

备注：windows 版本，上面的系统选择不了...

### 相关日志 | Logs

2022-10-09 19:53:40 [PicGo INFO] Before transform 
2022-10-09 19:53:40 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-09 19:53:40 [PicGo WARN] can't get https://cdn.xiaolincoding.com/gh/xiaolincoder/ImageHost2/操作系统/输入输出/设备控制器.png's image size 
2022-10-09 19:53:40 [PicGo WARN] fallback to 200 * 200 
2022-10-09 19:53:40 [PicGo INFO] Before upload 
2022-10-09 19:53:40 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-09 19:53:40 [PicGo INFO] Uploading... Current uploader is [smms-user] 
2022-10-09 19:53:42 [PicGo WARN] failed 
2022-10-09 19:53:42 [PicGo ERROR] 
------Error Stack Begin------
Error: Can't get target upload source info
    at Object.handle (C:\Users\ZPT\AppData\Roaming\picgo\node_modules\picgo-plugin-smms-user\src\index.js:55:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17169)
    at async $e.start (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15940)
    at async yt.upload (D:\Software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:67044)
    at async Object.upload (D:\Software\PicGo\resources\app.asar\background.js:2:649330)
    at async An (D:\Software\PicGo\resources\app.asar\background.js:2:652212)
-------Error Stack End------- 
2022-10-09 19:53:42 [PicGo ERROR]

**Comment by Molunerfinn** [comment]
已知问题，已经修复，会在下个beta版本带出去

**Comment by Z-HUANT** [comment]
好的，谢谢作者大佬，蹲个新版本

**Comment by Molunerfinn** [comment]
> smms的地址好像被墙了，有没有不打包直接换地址的配置呀

麻烦看看更新日志
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/12621342/195298284-8547f44e-abae-420a-969d-b85671caa763.png">

**Comment by wellmoonloft** [comment]
> > smms的地址好像被墙了，有没有不打包直接换地址的配置呀
> 
> 麻烦看看更新日志 <img alt="image" width="1021" src="https://user-images.githubusercontent.com/12621342/195298284-8547f44e-abae-420a-969d-b85671caa763.png">

抱歉抱歉，已经搞定了

**Comment by YGXB-net** [comment]
我这几天也遇到了相似的问题，版本是：v2.3.1-beta.6，虽然显示是上传图片成功，但实际上并没有上传上去

```
2022-10-21 11:20:39 [PicGo INFO] Before transform 
2022-10-21 11:20:39 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-21 11:20:40 [PicGo WARN] can't get https://s.cn.bing.net/th?id=OHR.GeorgiaCypress_ZH-CN3705257154_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&qlt=50's image size 
2022-10-21 11:20:40 [PicGo WARN] fallback to 200 * 200 
2022-10-21 11:20:40 [PicGo INFO] Before upload 
2022-10-21 11:20:40 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-21 11:20:40 [PicGo INFO] Uploading... Current uploader is [lankong] 
2022-10-21 11:20:42 [PicGo SUCCESS] 
```

希望作者大大可以快点修复，谢谢了

**Comment by Molunerfinn** [comment]
beta.7已修复
