### ISSUE TITLE
[Bug]: picgo-gui-local.log文件过大

### ISSUE THREAD

**Issue by Pil0tXia** [Molunerfinn/PicGo#995]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1beta6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/41445332/197377132-52fdf33c-a164-460c-9afe-a72dab45852d.png)
今日打开电脑发现picgo-gui-local.log文件巨大（如图12G），此时picgo并未在运行。在这一次电脑关机前，我对台式机在多天内进行了多次S3睡眠和S4休眠，其中picgo都在运行。
另外，通常从休眠唤醒后，使用typora上传图片时，picgo的gui会卡死，typora始终uploading。任务管理器结束picgo后，picgo自动重启，typora的图片才得以上传。此问题在我的台式机和笔记本上都有复现。
win11 22621.674

### 相关日志 | Logs

无法打开此巨大log文件。
picgo gui卡死期间，picgo.log无任何记录。

**Comment by Molunerfinn** [comment]
已知问题 已经修复 跟着下个版本带出去

**Comment by Pil0tXia** [comment]
好的谢谢

**Comment by Molunerfinn** [comment]
这个log文件能看到里面写了什么么？

**Comment by Pil0tXia** [comment]
> 这个log文件能看到里面写了什么么？

记事本打不开，vscode打开时会报错，所以放弃打开计划了。OneDrive正在上传，进度1/3，上传完毕后会把分享链接贴在此issue里

**Comment by Molunerfinn** [comment]
不需要，直接git bash终端里打开，输出最后一百行日志

```bash
tail -n 100 picgo-gui-local.log
```

**Comment by Pil0tXia** [comment]
```
at process.emit (node:events:406:35)
-------Error Stack End-------
2022-10-18 13:13:37 [PicGo ERROR]
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.log (node:internal/console/constructor:363:26)
    at consoleCall (<anonymous>)
    at C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:598359
    at Ct (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639585)
    at process.<anonymous> (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639635)
-------Error Stack End-------
2022-10-18 13:13:37 [PicGo ERROR]
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.warn (node:internal/console/constructor:368:26)
    at consoleCall (<anonymous>)
    at Ct (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639576)
    at process.<anonymous> (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639635)
    at process.emit (node:events:406:35)
-------Error Stack End-------
2022-10-18 13:13:37 [PicGo ERROR]
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.log (node:internal/console/constructor:363:26)
    at consoleCall (<anonymous>)
    at C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:598359
    at Ct (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639585)
    at process.<anonymous> (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639635)
-------Error Stack End-------
2022-10-18 13:13:37 [PicGo ERROR]
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.warn (node:internal/console/constructor:368:26)
    at consoleCall (<anonymous>)
    at Ct (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639576)
    at process.<anonymous> (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639635)
    at process.emit (node:events:406:35)
-------Error Stack End-------
2022-10-18 13:13:37 [PicGo ERROR]
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.log (node:internal/console/constructor:363:26)
    at consoleCall (<anonymous>)
    at C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:598359
    at Ct (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639585)
    at process.<anonymous> (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639635)
-------Error Stack End-------
2022-10-18 13:13:37 [PicGo ERROR]
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.warn (node:internal/console/constructor:368:26)
    at consoleCall (<anonymous>)
    at Ct (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639576)
    at process.<anonymous> (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639635)
    at process.emit (node:events:406:35)
-------Error Stack End-------
2022-10-18 13:13:37 [PicGo ERROR]
------Error Stack Begin------
Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:289:16)
    at console.log (node:internal/console/constructor:363:26)
    at consoleCall (<anonymous>)
    at C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:598359
    at Ct (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639585)
    at process.<anonymous> (C:\Users\18377\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:639635)
-------Error Stack End-------
```

**Comment by Molunerfinn** [comment]
嗯大概知道了，有个地方写日志如果遇到错误抛出会导致死循环。下个版本应该不会出现了

**Comment by Pil0tXia** [comment]
感谢
